// Decompiled with JetBrains decompiler
// Type: EllieMae.EMLite.ClientServer.Acl.AclFeatureTypes
// Assembly: ClientServer, Version=1.5.1.0, Culture=neutral, PublicKeyToken=d11ef57bba4acf91
// MVID: 301E11EA-0960-40C7-AC1B-26929E024B20
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\ClientServer.dll

#nullable disable
namespace EllieMae.EMLite.ClientServer.Acl
{
  public enum AclFeatureTypes
  {
    Access,
    AdditionalServices,
    AusTracking,
    BorrowerContacts,
    BusinessContacts,
    BusinessRules,
    ClosingDocs,
    PreClosingDocs,
    CompanyUserSetup,
    EFolderHistory,
    ConsumerConnect,
    Contacts,
    ContactSetup,
    Dashboard,
    DisclosureTracking,
    DocsSetup,
    Documents,
    DynamicDataManagement,
    EDisclosures,
    EFolderSetup,
    ExternalSettings,
    FileContacts,
    GseServices,
    Home,
    ItemizationFee,
    Loan,
    LoanSetup,
    PersonalSettings,
    PersonalTemplates,
    Pipeline,
    PipelineTasks,
    PostClosingConditions,
    PreliminaryConditions,
    Print,
    DeveloperConnect,
    ProtectedDocuments,
    PurchaseConditions,
    Reports,
    SecondarySetup,
    Settings,
    SmartClient,
    SystemAdministration,
    TablesAndFees,
    Tools,
    TpoCompanyDetails,
    TpoConnectSiteSettings,
    TpoContacts,
    TpoFees,
    TpoInformation,
    TpoOrganizationSettings,
    TqlServices,
    Trades,
    UnassignedFiles,
    UnderwritingConditions,
    UnprotectedDocuments,
    Obsolete,
    SellConditions,
    InvestorServices,
    LoConnectTasks,
    EncompassWebServices,
    UnderwritingCenter,
    EVaultPortal,
    InvestorConnectSetup,
    PipelineDefault,
    Aiq,
    MiCenter,
  }
}
