// Decompiled with JetBrains decompiler
// Type: EllieMae.EMLite.InputEngine.IncomeBonusForm
// Assembly: EMInput, Version=24.3.0.5, Culture=neutral, PublicKeyToken=null
// MVID: ED3FE5F8-B05D-4E0B-8366-E502FB568694
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\EMInput.dll

using EllieMae.EMLite.Common;
using EllieMae.EMLite.Common.UI.Controls;
using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.HelpAPI;
using EllieMae.EMLite.RemotingServices;
using EllieMae.EMLite.UI;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Resources;
using System.Windows.Forms;

#nullable disable
namespace EllieMae.EMLite.InputEngine
{
  public class IncomeBonusForm : Form, IOnlineHelpTarget, IHelp
  {
    private const string className = "IncomeBonusForm";
    private Sessions.Session session;
    private IHtmlInput inputData;
    private LoanData loan;
    private GenericFormInputHandler incomeFormInputHandler;
    private IContainer components;
    private GroupContainer groupContainer1;
    private TextBox txtOverCobAverage;
    private TextBox txtOverBorAverage;
    private TextBox txtOverBorY3;
    private TextBox txtOverCob3;
    private TextBox txtOverBorM3;
    private Label label10;
    private TextBox txtOverBor3;
    private Label label11;
    private TextBox txtOverBorY2;
    private TextBox txtOverCob2;
    private TextBox txtOverBorM2;
    private Label label9;
    private TextBox txtOverBor2;
    private TextBox txtOverCob1;
    private TextBox txtOverBorM1;
    private Label label8;
    private Label label7;
    private Label label6;
    private Label label4;
    private Label label3;
    private Label label2;
    private TextBox txtOverBor1;
    private Label label1;
    private GroupContainer groupContainer2;
    private TextBox txtBonusCobAverage;
    private TextBox txtBonusBorAverage;
    private TextBox txtBonusBorY3;
    private TextBox txtBonusCob3;
    private TextBox txtBonusBorM3;
    private Label label5;
    private TextBox txtBonusBor3;
    private Label label12;
    private TextBox txtBonusBorY2;
    private TextBox txtBonusCob2;
    private TextBox txtBonusBorM2;
    private Label label13;
    private TextBox txtBonusBor2;
    private TextBox txtBonusCob1;
    private TextBox txtBonusBorM1;
    private Label label14;
    private Label label15;
    private Label label16;
    private Label label17;
    private Label label18;
    private Label label19;
    private TextBox txtBonusBor1;
    private Label label20;
    private GroupContainer groupContainer3;
    private TextBox txtCommCobAverage;
    private TextBox txtCommBorAverage;
    private TextBox txtCommBorY2;
    private TextBox txtCommCob2;
    private TextBox txtCommBorM2;
    private Label label23;
    private TextBox txtCommBor2;
    private TextBox txtCommCob1;
    private TextBox txtCommBorM1;
    private Label label24;
    private Label label25;
    private Label label26;
    private Label label27;
    private Label label28;
    private Label label29;
    private TextBox txtCommBor1;
    private Label label30;
    private Button btnOK;
    private Button btnCancel;
    private EMHelpLink emHelpLink1;
    private PictureBox pboxDownArrow;
    private PictureBox pboxAsterisk;
    private ToolTip toolTipField;
    private TextBox txtOverCobY3;
    private TextBox txtOverCobM3;
    private Label label21;
    private TextBox txtOverCobY2;
    private TextBox txtOverCobM2;
    private Label label31;
    private TextBox txtOverCobM1;
    private Label label33;
    private TextBox txtBonusCobY3;
    private TextBox txtBonusCobM3;
    private Label label35;
    private TextBox txtBonusCobY2;
    private TextBox txtBonusCobM2;
    private Label label37;
    private TextBox txtBonusCobM1;
    private Label label39;
    private TextBox txtCommCobY2;
    private TextBox txtCommCobM2;
    private Label label43;
    private TextBox txtCommCobM1;
    private Label label45;
    private TextBox txtOverCobY1;
    private TextBox txtOverBorY1;
    private TextBox txtBonusBorY1;
    private TextBox txtBonusCobY1;
    private TextBox txtCommBorY1;
    private TextBox txtCommCobY1;
    private TextBox txtCommCobY3;
    private TextBox txtCommCobM3;
    private Label label22;
    private TextBox txtCommBorY3;
    private TextBox txtCommCob3;
    private TextBox txtCommBorM3;
    private Label label32;
    private TextBox txtCommBor3;
    private Label label34;

    public IncomeBonusForm(IHtmlInput inputData, Sessions.Session session)
    {
      this.session = session;
      this.inputData = inputData;
      if (this.inputData is LoanData)
        this.loan = (LoanData) this.inputData;
      this.InitializeComponent();
      this.incomeFormInputHandler = new GenericFormInputHandler(this.inputData, this.Controls, this.session);
      this.initForm();
    }

    private void initForm()
    {
      this.incomeFormInputHandler.SetFieldValuesToForm();
      this.incomeFormInputHandler.SetBusinessRules(new ResourceManager(typeof (IncomeOtherForm)));
      this.incomeFormInputHandler.SetFieldTip(this.toolTipField);
      for (int index = 0; index < this.incomeFormInputHandler.FieldControls.Count; ++index)
        this.incomeFormInputHandler.SetFieldEvents(this.incomeFormInputHandler.FieldControls[index]);
      this.incomeFormInputHandler.OnKeyUp += new EventHandler(this.calculateFields);
      this.incomeFormInputHandler.OnLeave += new EventHandler(this.textField_Leave);
    }

    private void textField_Leave(object sender, EventArgs e)
    {
      TextBox sender1 = (TextBox) sender;
      if ((sender1.Name.IndexOf("BorY") > -1 || sender1.Name.IndexOf("CobY") > -1) && sender1.Text != string.Empty)
      {
        int num1 = Utils.ParseInt((object) sender1.Text.Trim());
        if (num1 >= 1900 && num1 <= 2199)
          return;
        int num2 = (int) Utils.Dialog((IWin32Window) this, "Value '" + sender1.Text.Trim() + "' is out of range. Must be between 1900 and 2199.", MessageBoxButtons.OK, MessageBoxIcon.Hand);
        sender1.Text = string.Empty;
        this.calculateFields((object) sender1, (EventArgs) null);
        sender1.Focus();
      }
      else
      {
        if (sender1.Name.IndexOf("BorM") <= -1 && sender1.Name.IndexOf("CobM") <= -1 || !(sender1.Text != string.Empty))
          return;
        int num3 = Utils.ParseInt((object) sender1.Text.Trim());
        if (num3 >= 0 && num3 <= 12)
          return;
        int num4 = (int) Utils.Dialog((IWin32Window) this, "Value '" + sender1.Text.Trim() + "' is out of range. Must be between 1 and 12.", MessageBoxButtons.OK, MessageBoxIcon.Hand);
        sender1.Text = string.Empty;
        this.calculateFields((object) sender1, (EventArgs) null);
        sender1.Focus();
      }
    }

    private void calculateFields(object sender, EventArgs e)
    {
      this.calculateAverages(this.txtOverBorM1, this.txtOverBorM2, this.txtOverBorM3, this.txtOverBor1, this.txtOverBor2, this.txtOverBor3, this.txtOverBorAverage);
      this.calculateAverages(this.txtOverCobM1, this.txtOverCobM2, this.txtOverCobM3, this.txtOverCob1, this.txtOverCob2, this.txtOverCob3, this.txtOverCobAverage);
      this.calculateAverages(this.txtBonusBorM1, this.txtBonusBorM2, this.txtBonusBorM3, this.txtBonusBor1, this.txtBonusBor2, this.txtBonusBor3, this.txtBonusBorAverage);
      this.calculateAverages(this.txtBonusCobM1, this.txtBonusCobM2, this.txtBonusCobM3, this.txtBonusCob1, this.txtBonusCob2, this.txtBonusCob3, this.txtBonusCobAverage);
      this.calculateAverages(this.txtCommBorM1, this.txtCommBorM2, this.txtCommBorM3, this.txtCommBor1, this.txtCommBor2, this.txtCommBor3, this.txtCommBorAverage);
      this.calculateAverages(this.txtCommCobM1, this.txtCommCobM2, this.txtCommCobM3, this.txtCommCob1, this.txtCommCob2, this.txtCommCob3, this.txtCommCobAverage);
    }

    private void calculateAverages(
      TextBox boxMonth1,
      TextBox boxMonth2,
      TextBox boxMonth3,
      TextBox boxAmount1,
      TextBox boxAmount2,
      TextBox boxAmount3,
      TextBox boxAverage)
    {
      Decimal num1 = 0M;
      int num2 = 0;
      if (boxMonth1.Text.Trim() != string.Empty && boxAmount1.Text.Trim() != string.Empty)
      {
        num2 += Utils.ParseInt((object) boxMonth1.Text.Trim());
        num1 += Utils.ParseDecimal((object) boxAmount1.Text.Trim().Replace(",", ""));
      }
      if (boxMonth2.Text.Trim() != string.Empty && boxAmount2.Text.Trim() != string.Empty)
      {
        num2 += Utils.ParseInt((object) boxMonth2.Text.Trim());
        num1 += Utils.ParseDecimal((object) boxAmount2.Text.Trim().Replace(",", ""));
      }
      if (boxMonth3.Text.Trim() != string.Empty && boxAmount3.Text.Trim() != string.Empty)
      {
        num2 += Utils.ParseInt((object) boxMonth3.Text.Trim());
        num1 += Utils.ParseDecimal((object) boxAmount3.Text.Trim().Replace(",", ""));
      }
      Decimal num3 = num2 == 0 || num1 == 0M ? 0M : Utils.ArithmeticRounding(num1 / (Decimal) num2, 2);
      boxAverage.Text = num3 == 0M ? "" : num3.ToString("N2");
    }

    private void btnOK_Click(object sender, EventArgs e)
    {
      this.incomeFormInputHandler.SetFieldValuesToLoan();
      this.inputData.SetField("QM.X138", this.txtOverBorAverage.Text.Trim());
      this.inputData.SetField("QM.X139", this.txtBonusBorAverage.Text.Trim());
      this.inputData.SetField("QM.X140", this.txtCommBorAverage.Text.Trim());
      this.inputData.SetField("QM.X146", this.txtOverCobAverage.Text.Trim());
      this.inputData.SetField("QM.X147", this.txtBonusCobAverage.Text.Trim());
      this.inputData.SetField("QM.X148", this.txtCommCobAverage.Text.Trim());
      this.DialogResult = DialogResult.OK;
    }

    private void dialog_KeyPress(object sender, KeyPressEventArgs e)
    {
      if (e.KeyChar != '\u001B')
        return;
      this.DialogResult = DialogResult.Cancel;
    }

    public void ShowHelp()
    {
      JedHelp.ShowHelp((Control) this, SystemSettings.HelpFile, this.GetHelpTargetName());
    }

    public string GetHelpTargetName() => nameof (IncomeBonusForm);

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.components = (IContainer) new System.ComponentModel.Container();
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (IncomeBonusForm));
      this.groupContainer1 = new GroupContainer();
      this.txtOverCobY3 = new TextBox();
      this.txtOverCobM3 = new TextBox();
      this.label21 = new Label();
      this.txtOverCobY2 = new TextBox();
      this.txtOverCobM2 = new TextBox();
      this.label31 = new Label();
      this.txtOverCobM1 = new TextBox();
      this.label33 = new Label();
      this.txtOverCobAverage = new TextBox();
      this.txtOverBorAverage = new TextBox();
      this.txtOverBorY3 = new TextBox();
      this.txtOverCob3 = new TextBox();
      this.txtOverBorM3 = new TextBox();
      this.label10 = new Label();
      this.txtOverBor3 = new TextBox();
      this.label11 = new Label();
      this.txtOverBorY2 = new TextBox();
      this.txtOverCob2 = new TextBox();
      this.txtOverBorM2 = new TextBox();
      this.label9 = new Label();
      this.txtOverBor2 = new TextBox();
      this.txtOverCob1 = new TextBox();
      this.txtOverBorM1 = new TextBox();
      this.label8 = new Label();
      this.label7 = new Label();
      this.label6 = new Label();
      this.label4 = new Label();
      this.label3 = new Label();
      this.label2 = new Label();
      this.txtOverBor1 = new TextBox();
      this.label1 = new Label();
      this.groupContainer2 = new GroupContainer();
      this.txtBonusCobY3 = new TextBox();
      this.txtBonusCobM3 = new TextBox();
      this.label35 = new Label();
      this.txtBonusCobY2 = new TextBox();
      this.txtBonusCobM2 = new TextBox();
      this.label37 = new Label();
      this.txtBonusCobM1 = new TextBox();
      this.label39 = new Label();
      this.txtBonusCobAverage = new TextBox();
      this.txtBonusBorAverage = new TextBox();
      this.txtBonusBorY3 = new TextBox();
      this.txtBonusCob3 = new TextBox();
      this.txtBonusBorM3 = new TextBox();
      this.label5 = new Label();
      this.txtBonusBor3 = new TextBox();
      this.label12 = new Label();
      this.txtBonusBorY2 = new TextBox();
      this.txtBonusCob2 = new TextBox();
      this.txtBonusBorM2 = new TextBox();
      this.label13 = new Label();
      this.txtBonusBor2 = new TextBox();
      this.txtBonusCob1 = new TextBox();
      this.txtBonusBorM1 = new TextBox();
      this.label14 = new Label();
      this.label15 = new Label();
      this.label16 = new Label();
      this.label17 = new Label();
      this.label18 = new Label();
      this.label19 = new Label();
      this.txtBonusBor1 = new TextBox();
      this.label20 = new Label();
      this.groupContainer3 = new GroupContainer();
      this.txtCommCobY2 = new TextBox();
      this.txtCommCobM2 = new TextBox();
      this.label43 = new Label();
      this.txtCommCobM1 = new TextBox();
      this.label45 = new Label();
      this.txtCommCobAverage = new TextBox();
      this.txtCommBorAverage = new TextBox();
      this.txtCommBorY2 = new TextBox();
      this.txtCommCob2 = new TextBox();
      this.txtCommBorM2 = new TextBox();
      this.label23 = new Label();
      this.txtCommBor2 = new TextBox();
      this.txtCommCob1 = new TextBox();
      this.txtCommBorM1 = new TextBox();
      this.label24 = new Label();
      this.label25 = new Label();
      this.label26 = new Label();
      this.label27 = new Label();
      this.label28 = new Label();
      this.label29 = new Label();
      this.txtCommBor1 = new TextBox();
      this.label30 = new Label();
      this.btnOK = new Button();
      this.btnCancel = new Button();
      this.emHelpLink1 = new EMHelpLink();
      this.pboxDownArrow = new PictureBox();
      this.pboxAsterisk = new PictureBox();
      this.toolTipField = new ToolTip(this.components);
      this.txtOverBorY1 = new TextBox();
      this.txtOverCobY1 = new TextBox();
      this.txtBonusCobY1 = new TextBox();
      this.txtBonusBorY1 = new TextBox();
      this.txtCommCobY1 = new TextBox();
      this.txtCommBorY1 = new TextBox();
      this.txtCommCobY3 = new TextBox();
      this.txtCommCobM3 = new TextBox();
      this.label22 = new Label();
      this.txtCommBorY3 = new TextBox();
      this.txtCommCob3 = new TextBox();
      this.txtCommBorM3 = new TextBox();
      this.label32 = new Label();
      this.txtCommBor3 = new TextBox();
      this.label34 = new Label();
      this.groupContainer1.SuspendLayout();
      this.groupContainer2.SuspendLayout();
      this.groupContainer3.SuspendLayout();
      ((ISupportInitialize) this.pboxDownArrow).BeginInit();
      ((ISupportInitialize) this.pboxAsterisk).BeginInit();
      this.SuspendLayout();
      this.groupContainer1.BackColor = Color.White;
      this.groupContainer1.Controls.Add((Control) this.txtOverCobY1);
      this.groupContainer1.Controls.Add((Control) this.txtOverBorY1);
      this.groupContainer1.Controls.Add((Control) this.txtOverCobY3);
      this.groupContainer1.Controls.Add((Control) this.txtOverCobM3);
      this.groupContainer1.Controls.Add((Control) this.label21);
      this.groupContainer1.Controls.Add((Control) this.txtOverCobY2);
      this.groupContainer1.Controls.Add((Control) this.txtOverCobM2);
      this.groupContainer1.Controls.Add((Control) this.label31);
      this.groupContainer1.Controls.Add((Control) this.txtOverCobM1);
      this.groupContainer1.Controls.Add((Control) this.label33);
      this.groupContainer1.Controls.Add((Control) this.txtOverCobAverage);
      this.groupContainer1.Controls.Add((Control) this.txtOverBorAverage);
      this.groupContainer1.Controls.Add((Control) this.txtOverBorY3);
      this.groupContainer1.Controls.Add((Control) this.txtOverCob3);
      this.groupContainer1.Controls.Add((Control) this.txtOverBorM3);
      this.groupContainer1.Controls.Add((Control) this.label10);
      this.groupContainer1.Controls.Add((Control) this.txtOverBor3);
      this.groupContainer1.Controls.Add((Control) this.label11);
      this.groupContainer1.Controls.Add((Control) this.txtOverBorY2);
      this.groupContainer1.Controls.Add((Control) this.txtOverCob2);
      this.groupContainer1.Controls.Add((Control) this.txtOverBorM2);
      this.groupContainer1.Controls.Add((Control) this.label9);
      this.groupContainer1.Controls.Add((Control) this.txtOverBor2);
      this.groupContainer1.Controls.Add((Control) this.txtOverCob1);
      this.groupContainer1.Controls.Add((Control) this.txtOverBorM1);
      this.groupContainer1.Controls.Add((Control) this.label8);
      this.groupContainer1.Controls.Add((Control) this.label7);
      this.groupContainer1.Controls.Add((Control) this.label6);
      this.groupContainer1.Controls.Add((Control) this.label4);
      this.groupContainer1.Controls.Add((Control) this.label3);
      this.groupContainer1.Controls.Add((Control) this.label2);
      this.groupContainer1.Controls.Add((Control) this.txtOverBor1);
      this.groupContainer1.Controls.Add((Control) this.label1);
      this.groupContainer1.HeaderForeColor = SystemColors.ControlText;
      this.groupContainer1.Location = new Point(9, 12);
      this.groupContainer1.Name = "groupContainer1";
      this.groupContainer1.Size = new Size(501, 148);
      this.groupContainer1.TabIndex = 0;
      this.groupContainer1.Text = "Overtime Income";
      this.txtOverCobY3.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverCobY3.Location = new Point(296, 98);
      this.txtOverCobY3.MaxLength = 4;
      this.txtOverCobY3.Name = "txtOverCobY3";
      this.txtOverCobY3.Size = new Size(46, 20);
      this.txtOverCobY3.TabIndex = 16;
      this.txtOverCobY3.Tag = (object) "QM.X317";
      this.txtOverCobY3.TextAlign = HorizontalAlignment.Right;
      this.txtOverCobM3.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverCobM3.Location = new Point(348, 98);
      this.txtOverCobM3.MaxLength = 2;
      this.txtOverCobM3.Name = "txtOverCobM3";
      this.txtOverCobM3.Size = new Size(42, 20);
      this.txtOverCobM3.TabIndex = 17;
      this.txtOverCobM3.Tag = (object) "QM.X318";
      this.txtOverCobM3.TextAlign = HorizontalAlignment.Right;
      this.label21.AutoSize = true;
      this.label21.Location = new Point(390, 101);
      this.label21.Name = "label21";
      this.label21.Size = new Size(16, 13);
      this.label21.TabIndex = 29;
      this.label21.Text = "M";
      this.txtOverCobY2.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverCobY2.Location = new Point(296, 76);
      this.txtOverCobY2.MaxLength = 4;
      this.txtOverCobY2.Name = "txtOverCobY2";
      this.txtOverCobY2.Size = new Size(46, 20);
      this.txtOverCobY2.TabIndex = 10;
      this.txtOverCobY2.Tag = (object) "QM.X315";
      this.txtOverCobY2.TextAlign = HorizontalAlignment.Right;
      this.txtOverCobM2.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverCobM2.Location = new Point(348, 76);
      this.txtOverCobM2.MaxLength = 2;
      this.txtOverCobM2.Name = "txtOverCobM2";
      this.txtOverCobM2.Size = new Size(42, 20);
      this.txtOverCobM2.TabIndex = 11;
      this.txtOverCobM2.Tag = (object) "QM.X316";
      this.txtOverCobM2.TextAlign = HorizontalAlignment.Right;
      this.label31.AutoSize = true;
      this.label31.Location = new Point(390, 79);
      this.label31.Name = "label31";
      this.label31.Size = new Size(16, 13);
      this.label31.TabIndex = 27;
      this.label31.Text = "M";
      this.txtOverCobM1.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverCobM1.Location = new Point(348, 54);
      this.txtOverCobM1.MaxLength = 2;
      this.txtOverCobM1.Name = "txtOverCobM1";
      this.txtOverCobM1.Size = new Size(42, 20);
      this.txtOverCobM1.TabIndex = 5;
      this.txtOverCobM1.Tag = (object) "QM.X314";
      this.txtOverCobM1.TextAlign = HorizontalAlignment.Right;
      this.label33.AutoSize = true;
      this.label33.Location = new Point(390, 57);
      this.label33.Name = "label33";
      this.label33.Size = new Size(16, 13);
      this.label33.TabIndex = 23;
      this.label33.Text = "M";
      this.txtOverCobAverage.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverCobAverage.Location = new Point(410, 120);
      this.txtOverCobAverage.MaxLength = 10;
      this.txtOverCobAverage.Name = "txtOverCobAverage";
      this.txtOverCobAverage.ReadOnly = true;
      this.txtOverCobAverage.Size = new Size(81, 20);
      this.txtOverCobAverage.TabIndex = 20;
      this.txtOverCobAverage.TabStop = false;
      this.txtOverCobAverage.Tag = (object) "QM.X216";
      this.txtOverCobAverage.TextAlign = HorizontalAlignment.Right;
      this.txtOverBorAverage.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverBorAverage.Location = new Point(192, 120);
      this.txtOverBorAverage.MaxLength = 10;
      this.txtOverBorAverage.Name = "txtOverBorAverage";
      this.txtOverBorAverage.ReadOnly = true;
      this.txtOverBorAverage.Size = new Size(81, 20);
      this.txtOverBorAverage.TabIndex = 19;
      this.txtOverBorAverage.TabStop = false;
      this.txtOverBorAverage.Tag = (object) "QM.X215";
      this.txtOverBorAverage.TextAlign = HorizontalAlignment.Right;
      this.txtOverBorY3.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverBorY3.Location = new Point(76, 98);
      this.txtOverBorY3.MaxLength = 4;
      this.txtOverBorY3.Name = "txtOverBorY3";
      this.txtOverBorY3.Size = new Size(46, 20);
      this.txtOverBorY3.TabIndex = 13;
      this.txtOverBorY3.Tag = (object) "QM.X211";
      this.txtOverBorY3.TextAlign = HorizontalAlignment.Right;
      this.txtOverCob3.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverCob3.Location = new Point(410, 98);
      this.txtOverCob3.MaxLength = 10;
      this.txtOverCob3.Name = "txtOverCob3";
      this.txtOverCob3.Size = new Size(81, 20);
      this.txtOverCob3.TabIndex = 18;
      this.txtOverCob3.Tag = (object) "QM.X214";
      this.txtOverCob3.TextAlign = HorizontalAlignment.Right;
      this.txtOverBorM3.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverBorM3.Location = new Point(128, 98);
      this.txtOverBorM3.MaxLength = 2;
      this.txtOverBorM3.Name = "txtOverBorM3";
      this.txtOverBorM3.Size = new Size(42, 20);
      this.txtOverBorM3.TabIndex = 14;
      this.txtOverBorM3.Tag = (object) "QM.X212";
      this.txtOverBorM3.TextAlign = HorizontalAlignment.Right;
      this.label10.AutoSize = true;
      this.label10.Location = new Point(170, 101);
      this.label10.Name = "label10";
      this.label10.Size = new Size(16, 13);
      this.label10.TabIndex = 18;
      this.label10.Text = "M";
      this.txtOverBor3.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverBor3.Location = new Point(192, 98);
      this.txtOverBor3.MaxLength = 10;
      this.txtOverBor3.Name = "txtOverBor3";
      this.txtOverBor3.Size = new Size(81, 20);
      this.txtOverBor3.TabIndex = 15;
      this.txtOverBor3.Tag = (object) "QM.X213";
      this.txtOverBor3.TextAlign = HorizontalAlignment.Right;
      this.label11.AutoSize = true;
      this.label11.Location = new Point(6, 101);
      this.label11.Name = "label11";
      this.label11.Size = new Size(53, 13);
      this.label11.TabIndex = 16;
      this.label11.Text = "Prior Year";
      this.txtOverBorY2.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverBorY2.Location = new Point(76, 76);
      this.txtOverBorY2.MaxLength = 4;
      this.txtOverBorY2.Name = "txtOverBorY2";
      this.txtOverBorY2.Size = new Size(46, 20);
      this.txtOverBorY2.TabIndex = 7;
      this.txtOverBorY2.Tag = (object) "QM.X207";
      this.txtOverBorY2.TextAlign = HorizontalAlignment.Right;
      this.txtOverCob2.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverCob2.Location = new Point(410, 76);
      this.txtOverCob2.MaxLength = 10;
      this.txtOverCob2.Name = "txtOverCob2";
      this.txtOverCob2.Size = new Size(81, 20);
      this.txtOverCob2.TabIndex = 12;
      this.txtOverCob2.Tag = (object) "QM.X210";
      this.txtOverCob2.TextAlign = HorizontalAlignment.Right;
      this.txtOverBorM2.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverBorM2.Location = new Point(128, 76);
      this.txtOverBorM2.MaxLength = 2;
      this.txtOverBorM2.Name = "txtOverBorM2";
      this.txtOverBorM2.Size = new Size(42, 20);
      this.txtOverBorM2.TabIndex = 8;
      this.txtOverBorM2.Tag = (object) "QM.X208";
      this.txtOverBorM2.TextAlign = HorizontalAlignment.Right;
      this.label9.AutoSize = true;
      this.label9.Location = new Point(170, 79);
      this.label9.Name = "label9";
      this.label9.Size = new Size(16, 13);
      this.label9.TabIndex = 12;
      this.label9.Text = "M";
      this.txtOverBor2.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverBor2.Location = new Point(192, 76);
      this.txtOverBor2.MaxLength = 10;
      this.txtOverBor2.Name = "txtOverBor2";
      this.txtOverBor2.Size = new Size(81, 20);
      this.txtOverBor2.TabIndex = 9;
      this.txtOverBor2.Tag = (object) "QM.X209";
      this.txtOverBor2.TextAlign = HorizontalAlignment.Right;
      this.txtOverCob1.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverCob1.ForeColor = SystemColors.WindowText;
      this.txtOverCob1.Location = new Point(410, 54);
      this.txtOverCob1.MaxLength = 10;
      this.txtOverCob1.Name = "txtOverCob1";
      this.txtOverCob1.Size = new Size(81, 20);
      this.txtOverCob1.TabIndex = 6;
      this.txtOverCob1.Tag = (object) "QM.X206";
      this.txtOverCob1.TextAlign = HorizontalAlignment.Right;
      this.txtOverBorM1.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverBorM1.Location = new Point(128, 54);
      this.txtOverBorM1.MaxLength = 2;
      this.txtOverBorM1.Name = "txtOverBorM1";
      this.txtOverBorM1.Size = new Size(42, 20);
      this.txtOverBorM1.TabIndex = 2;
      this.txtOverBorM1.Tag = (object) "QM.X204";
      this.txtOverBorM1.TextAlign = HorizontalAlignment.Right;
      this.label8.AutoSize = true;
      this.label8.Location = new Point(6, 123);
      this.label8.Name = "label8";
      this.label8.Size = new Size(92, 13);
      this.label8.TabIndex = 8;
      this.label8.Text = "Average Overtime";
      this.label7.AutoSize = true;
      this.label7.Location = new Point(6, 79);
      this.label7.Name = "label7";
      this.label7.Size = new Size(52, 13);
      this.label7.TabIndex = 7;
      this.label7.Text = "Last Year";
      this.label6.AutoSize = true;
      this.label6.Location = new Point(170, 57);
      this.label6.Name = "label6";
      this.label6.Size = new Size(16, 13);
      this.label6.TabIndex = 6;
      this.label6.Text = "M";
      this.label4.AutoSize = true;
      this.label4.Location = new Point(6, 57);
      this.label4.Name = "label4";
      this.label4.Size = new Size(67, 13);
      this.label4.TabIndex = 4;
      this.label4.Text = "Year to Date";
      this.label3.AutoSize = true;
      this.label3.Location = new Point(345, 38);
      this.label3.Name = "label3";
      this.label3.Size = new Size(65, 13);
      this.label3.TabIndex = 3;
      this.label3.Text = "Co-Borrower";
      this.label2.AutoSize = true;
      this.label2.Location = new Point(125, 38);
      this.label2.Name = "label2";
      this.label2.Size = new Size(49, 13);
      this.label2.TabIndex = 2;
      this.label2.Text = "Borrower";
      this.txtOverBor1.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverBor1.Location = new Point(192, 54);
      this.txtOverBor1.MaxLength = 10;
      this.txtOverBor1.Name = "txtOverBor1";
      this.txtOverBor1.Size = new Size(81, 20);
      this.txtOverBor1.TabIndex = 3;
      this.txtOverBor1.Tag = (object) "QM.X205";
      this.txtOverBor1.TextAlign = HorizontalAlignment.Right;
      this.label1.AutoSize = true;
      this.label1.Location = new Point(6, 38);
      this.label1.Name = "label1";
      this.label1.Size = new Size(67, 13);
      this.label1.TabIndex = 0;
      this.label1.Text = "Overtime For";
      this.groupContainer2.BackColor = Color.White;
      this.groupContainer2.Controls.Add((Control) this.txtBonusBorY1);
      this.groupContainer2.Controls.Add((Control) this.txtBonusCobY1);
      this.groupContainer2.Controls.Add((Control) this.txtBonusCobY3);
      this.groupContainer2.Controls.Add((Control) this.txtBonusCobM3);
      this.groupContainer2.Controls.Add((Control) this.label35);
      this.groupContainer2.Controls.Add((Control) this.txtBonusCobY2);
      this.groupContainer2.Controls.Add((Control) this.txtBonusCobM2);
      this.groupContainer2.Controls.Add((Control) this.label37);
      this.groupContainer2.Controls.Add((Control) this.txtBonusCobM1);
      this.groupContainer2.Controls.Add((Control) this.label39);
      this.groupContainer2.Controls.Add((Control) this.txtBonusCobAverage);
      this.groupContainer2.Controls.Add((Control) this.txtBonusBorAverage);
      this.groupContainer2.Controls.Add((Control) this.txtBonusBorY3);
      this.groupContainer2.Controls.Add((Control) this.txtBonusCob3);
      this.groupContainer2.Controls.Add((Control) this.txtBonusBorM3);
      this.groupContainer2.Controls.Add((Control) this.label5);
      this.groupContainer2.Controls.Add((Control) this.txtBonusBor3);
      this.groupContainer2.Controls.Add((Control) this.label12);
      this.groupContainer2.Controls.Add((Control) this.txtBonusBorY2);
      this.groupContainer2.Controls.Add((Control) this.txtBonusCob2);
      this.groupContainer2.Controls.Add((Control) this.txtBonusBorM2);
      this.groupContainer2.Controls.Add((Control) this.label13);
      this.groupContainer2.Controls.Add((Control) this.txtBonusBor2);
      this.groupContainer2.Controls.Add((Control) this.txtBonusCob1);
      this.groupContainer2.Controls.Add((Control) this.txtBonusBorM1);
      this.groupContainer2.Controls.Add((Control) this.label14);
      this.groupContainer2.Controls.Add((Control) this.label15);
      this.groupContainer2.Controls.Add((Control) this.label16);
      this.groupContainer2.Controls.Add((Control) this.label17);
      this.groupContainer2.Controls.Add((Control) this.label18);
      this.groupContainer2.Controls.Add((Control) this.label19);
      this.groupContainer2.Controls.Add((Control) this.txtBonusBor1);
      this.groupContainer2.Controls.Add((Control) this.label20);
      this.groupContainer2.HeaderForeColor = SystemColors.ControlText;
      this.groupContainer2.Location = new Point(9, 166);
      this.groupContainer2.Name = "groupContainer2";
      this.groupContainer2.Size = new Size(501, 148);
      this.groupContainer2.TabIndex = 21;
      this.groupContainer2.Text = "Bonus Income";
      this.txtBonusCobY3.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusCobY3.Location = new Point(296, 98);
      this.txtBonusCobY3.MaxLength = 4;
      this.txtBonusCobY3.Name = "txtBonusCobY3";
      this.txtBonusCobY3.Size = new Size(46, 20);
      this.txtBonusCobY3.TabIndex = 37;
      this.txtBonusCobY3.Tag = (object) "QM.X322";
      this.txtBonusCobY3.TextAlign = HorizontalAlignment.Right;
      this.txtBonusCobM3.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusCobM3.Location = new Point(348, 98);
      this.txtBonusCobM3.MaxLength = 2;
      this.txtBonusCobM3.Name = "txtBonusCobM3";
      this.txtBonusCobM3.Size = new Size(42, 20);
      this.txtBonusCobM3.TabIndex = 38;
      this.txtBonusCobM3.Tag = (object) "QM.X323";
      this.txtBonusCobM3.TextAlign = HorizontalAlignment.Right;
      this.label35.AutoSize = true;
      this.label35.Location = new Point(390, 101);
      this.label35.Name = "label35";
      this.label35.Size = new Size(16, 13);
      this.label35.TabIndex = 40;
      this.label35.Text = "M";
      this.txtBonusCobY2.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusCobY2.Location = new Point(296, 76);
      this.txtBonusCobY2.MaxLength = 4;
      this.txtBonusCobY2.Name = "txtBonusCobY2";
      this.txtBonusCobY2.Size = new Size(46, 20);
      this.txtBonusCobY2.TabIndex = 31;
      this.txtBonusCobY2.Tag = (object) "QM.X320";
      this.txtBonusCobY2.TextAlign = HorizontalAlignment.Right;
      this.txtBonusCobM2.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusCobM2.Location = new Point(348, 76);
      this.txtBonusCobM2.MaxLength = 2;
      this.txtBonusCobM2.Name = "txtBonusCobM2";
      this.txtBonusCobM2.Size = new Size(42, 20);
      this.txtBonusCobM2.TabIndex = 32;
      this.txtBonusCobM2.Tag = (object) "QM.X321";
      this.txtBonusCobM2.TextAlign = HorizontalAlignment.Right;
      this.label37.AutoSize = true;
      this.label37.Location = new Point(390, 79);
      this.label37.Name = "label37";
      this.label37.Size = new Size(16, 13);
      this.label37.TabIndex = 38;
      this.label37.Text = "M";
      this.txtBonusCobM1.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusCobM1.Location = new Point(348, 54);
      this.txtBonusCobM1.MaxLength = 2;
      this.txtBonusCobM1.Name = "txtBonusCobM1";
      this.txtBonusCobM1.Size = new Size(42, 20);
      this.txtBonusCobM1.TabIndex = 26;
      this.txtBonusCobM1.Tag = (object) "QM.X319";
      this.txtBonusCobM1.TextAlign = HorizontalAlignment.Right;
      this.label39.AutoSize = true;
      this.label39.Location = new Point(390, 57);
      this.label39.Name = "label39";
      this.label39.Size = new Size(16, 13);
      this.label39.TabIndex = 34;
      this.label39.Text = "M";
      this.txtBonusCobAverage.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusCobAverage.Location = new Point(410, 120);
      this.txtBonusCobAverage.MaxLength = 10;
      this.txtBonusCobAverage.Name = "txtBonusCobAverage";
      this.txtBonusCobAverage.ReadOnly = true;
      this.txtBonusCobAverage.Size = new Size(81, 20);
      this.txtBonusCobAverage.TabIndex = 41;
      this.txtBonusCobAverage.TabStop = false;
      this.txtBonusCobAverage.Tag = (object) "QM.X229";
      this.txtBonusCobAverage.TextAlign = HorizontalAlignment.Right;
      this.txtBonusBorAverage.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusBorAverage.Location = new Point(192, 120);
      this.txtBonusBorAverage.MaxLength = 10;
      this.txtBonusBorAverage.Name = "txtBonusBorAverage";
      this.txtBonusBorAverage.ReadOnly = true;
      this.txtBonusBorAverage.Size = new Size(81, 20);
      this.txtBonusBorAverage.TabIndex = 40;
      this.txtBonusBorAverage.TabStop = false;
      this.txtBonusBorAverage.Tag = (object) "QM.X228";
      this.txtBonusBorAverage.TextAlign = HorizontalAlignment.Right;
      this.txtBonusBorY3.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusBorY3.Location = new Point(76, 98);
      this.txtBonusBorY3.MaxLength = 4;
      this.txtBonusBorY3.Name = "txtBonusBorY3";
      this.txtBonusBorY3.Size = new Size(46, 20);
      this.txtBonusBorY3.TabIndex = 34;
      this.txtBonusBorY3.Tag = (object) "QM.X224";
      this.txtBonusBorY3.TextAlign = HorizontalAlignment.Right;
      this.txtBonusCob3.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusCob3.Location = new Point(410, 98);
      this.txtBonusCob3.MaxLength = 10;
      this.txtBonusCob3.Name = "txtBonusCob3";
      this.txtBonusCob3.Size = new Size(81, 20);
      this.txtBonusCob3.TabIndex = 39;
      this.txtBonusCob3.Tag = (object) "QM.X227";
      this.txtBonusCob3.TextAlign = HorizontalAlignment.Right;
      this.txtBonusBorM3.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusBorM3.Location = new Point(128, 98);
      this.txtBonusBorM3.MaxLength = 2;
      this.txtBonusBorM3.Name = "txtBonusBorM3";
      this.txtBonusBorM3.Size = new Size(42, 20);
      this.txtBonusBorM3.TabIndex = 35;
      this.txtBonusBorM3.Tag = (object) "QM.X225";
      this.txtBonusBorM3.TextAlign = HorizontalAlignment.Right;
      this.label5.AutoSize = true;
      this.label5.Location = new Point(170, 101);
      this.label5.Name = "label5";
      this.label5.Size = new Size(16, 13);
      this.label5.TabIndex = 18;
      this.label5.Text = "M";
      this.txtBonusBor3.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusBor3.Location = new Point(192, 98);
      this.txtBonusBor3.MaxLength = 10;
      this.txtBonusBor3.Name = "txtBonusBor3";
      this.txtBonusBor3.Size = new Size(81, 20);
      this.txtBonusBor3.TabIndex = 36;
      this.txtBonusBor3.Tag = (object) "QM.X226";
      this.txtBonusBor3.TextAlign = HorizontalAlignment.Right;
      this.label12.AutoSize = true;
      this.label12.Location = new Point(6, 101);
      this.label12.Name = "label12";
      this.label12.Size = new Size(53, 13);
      this.label12.TabIndex = 16;
      this.label12.Text = "Prior Year";
      this.txtBonusBorY2.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusBorY2.Location = new Point(76, 76);
      this.txtBonusBorY2.MaxLength = 4;
      this.txtBonusBorY2.Name = "txtBonusBorY2";
      this.txtBonusBorY2.Size = new Size(46, 20);
      this.txtBonusBorY2.TabIndex = 28;
      this.txtBonusBorY2.Tag = (object) "QM.X220";
      this.txtBonusBorY2.TextAlign = HorizontalAlignment.Right;
      this.txtBonusCob2.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusCob2.Location = new Point(410, 76);
      this.txtBonusCob2.MaxLength = 10;
      this.txtBonusCob2.Name = "txtBonusCob2";
      this.txtBonusCob2.Size = new Size(81, 20);
      this.txtBonusCob2.TabIndex = 33;
      this.txtBonusCob2.Tag = (object) "QM.X223";
      this.txtBonusCob2.TextAlign = HorizontalAlignment.Right;
      this.txtBonusBorM2.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusBorM2.Location = new Point(128, 76);
      this.txtBonusBorM2.MaxLength = 2;
      this.txtBonusBorM2.Name = "txtBonusBorM2";
      this.txtBonusBorM2.Size = new Size(42, 20);
      this.txtBonusBorM2.TabIndex = 29;
      this.txtBonusBorM2.Tag = (object) "QM.X221";
      this.txtBonusBorM2.TextAlign = HorizontalAlignment.Right;
      this.label13.AutoSize = true;
      this.label13.Location = new Point(170, 79);
      this.label13.Name = "label13";
      this.label13.Size = new Size(16, 13);
      this.label13.TabIndex = 12;
      this.label13.Text = "M";
      this.txtBonusBor2.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusBor2.Location = new Point(192, 76);
      this.txtBonusBor2.MaxLength = 10;
      this.txtBonusBor2.Name = "txtBonusBor2";
      this.txtBonusBor2.Size = new Size(81, 20);
      this.txtBonusBor2.TabIndex = 30;
      this.txtBonusBor2.Tag = (object) "QM.X222";
      this.txtBonusBor2.TextAlign = HorizontalAlignment.Right;
      this.txtBonusCob1.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusCob1.Location = new Point(410, 54);
      this.txtBonusCob1.MaxLength = 10;
      this.txtBonusCob1.Name = "txtBonusCob1";
      this.txtBonusCob1.Size = new Size(81, 20);
      this.txtBonusCob1.TabIndex = 27;
      this.txtBonusCob1.Tag = (object) "QM.X219";
      this.txtBonusCob1.TextAlign = HorizontalAlignment.Right;
      this.txtBonusBorM1.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusBorM1.Location = new Point(128, 54);
      this.txtBonusBorM1.MaxLength = 2;
      this.txtBonusBorM1.Name = "txtBonusBorM1";
      this.txtBonusBorM1.Size = new Size(42, 20);
      this.txtBonusBorM1.TabIndex = 23;
      this.txtBonusBorM1.Tag = (object) "QM.X217";
      this.txtBonusBorM1.TextAlign = HorizontalAlignment.Right;
      this.label14.AutoSize = true;
      this.label14.Location = new Point(4, 123);
      this.label14.Name = "label14";
      this.label14.Size = new Size(80, 13);
      this.label14.TabIndex = 8;
      this.label14.Text = "Average Bonus";
      this.label15.AutoSize = true;
      this.label15.Location = new Point(6, 79);
      this.label15.Name = "label15";
      this.label15.Size = new Size(52, 13);
      this.label15.TabIndex = 7;
      this.label15.Text = "Last Year";
      this.label16.AutoSize = true;
      this.label16.Location = new Point(170, 57);
      this.label16.Name = "label16";
      this.label16.Size = new Size(16, 13);
      this.label16.TabIndex = 6;
      this.label16.Text = "M";
      this.label17.AutoSize = true;
      this.label17.Location = new Point(4, 57);
      this.label17.Name = "label17";
      this.label17.Size = new Size(67, 13);
      this.label17.TabIndex = 4;
      this.label17.Text = "Year to Date";
      this.label18.AutoSize = true;
      this.label18.Location = new Point(345, 38);
      this.label18.Name = "label18";
      this.label18.Size = new Size(65, 13);
      this.label18.TabIndex = 3;
      this.label18.Text = "Co-Borrower";
      this.label19.AutoSize = true;
      this.label19.Location = new Point(125, 38);
      this.label19.Name = "label19";
      this.label19.Size = new Size(49, 13);
      this.label19.TabIndex = 2;
      this.label19.Text = "Borrower";
      this.txtBonusBor1.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusBor1.Location = new Point(192, 54);
      this.txtBonusBor1.MaxLength = 10;
      this.txtBonusBor1.Name = "txtBonusBor1";
      this.txtBonusBor1.Size = new Size(81, 20);
      this.txtBonusBor1.TabIndex = 24;
      this.txtBonusBor1.Tag = (object) "QM.X218";
      this.txtBonusBor1.TextAlign = HorizontalAlignment.Right;
      this.label20.AutoSize = true;
      this.label20.Location = new Point(6, 38);
      this.label20.Name = "label20";
      this.label20.Size = new Size(55, 13);
      this.label20.TabIndex = 0;
      this.label20.Text = "Bonus For";
      this.groupContainer3.BackColor = Color.White;
      this.groupContainer3.Controls.Add((Control) this.txtCommCobY3);
      this.groupContainer3.Controls.Add((Control) this.txtCommCobM3);
      this.groupContainer3.Controls.Add((Control) this.label22);
      this.groupContainer3.Controls.Add((Control) this.txtCommBorY3);
      this.groupContainer3.Controls.Add((Control) this.txtCommCob3);
      this.groupContainer3.Controls.Add((Control) this.txtCommBorM3);
      this.groupContainer3.Controls.Add((Control) this.label32);
      this.groupContainer3.Controls.Add((Control) this.txtCommBor3);
      this.groupContainer3.Controls.Add((Control) this.label34);
      this.groupContainer3.Controls.Add((Control) this.txtCommBorY1);
      this.groupContainer3.Controls.Add((Control) this.txtCommCobY1);
      this.groupContainer3.Controls.Add((Control) this.txtCommCobY2);
      this.groupContainer3.Controls.Add((Control) this.txtCommCobM2);
      this.groupContainer3.Controls.Add((Control) this.label43);
      this.groupContainer3.Controls.Add((Control) this.txtCommCobM1);
      this.groupContainer3.Controls.Add((Control) this.label45);
      this.groupContainer3.Controls.Add((Control) this.txtCommCobAverage);
      this.groupContainer3.Controls.Add((Control) this.txtCommBorAverage);
      this.groupContainer3.Controls.Add((Control) this.txtCommBorY2);
      this.groupContainer3.Controls.Add((Control) this.txtCommCob2);
      this.groupContainer3.Controls.Add((Control) this.txtCommBorM2);
      this.groupContainer3.Controls.Add((Control) this.label23);
      this.groupContainer3.Controls.Add((Control) this.txtCommBor2);
      this.groupContainer3.Controls.Add((Control) this.txtCommCob1);
      this.groupContainer3.Controls.Add((Control) this.txtCommBorM1);
      this.groupContainer3.Controls.Add((Control) this.label24);
      this.groupContainer3.Controls.Add((Control) this.label25);
      this.groupContainer3.Controls.Add((Control) this.label26);
      this.groupContainer3.Controls.Add((Control) this.label27);
      this.groupContainer3.Controls.Add((Control) this.label28);
      this.groupContainer3.Controls.Add((Control) this.label29);
      this.groupContainer3.Controls.Add((Control) this.txtCommBor1);
      this.groupContainer3.Controls.Add((Control) this.label30);
      this.groupContainer3.HeaderForeColor = SystemColors.ControlText;
      this.groupContainer3.Location = new Point(9, 320);
      this.groupContainer3.Name = "groupContainer3";
      this.groupContainer3.Size = new Size(501, 148);
      this.groupContainer3.TabIndex = 34;
      this.groupContainer3.Text = "Commission Income";
      this.txtCommCobY2.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommCobY2.Location = new Point(296, 76);
      this.txtCommCobY2.MaxLength = 4;
      this.txtCommCobY2.Name = "txtCommCobY2";
      this.txtCommCobY2.Size = new Size(46, 20);
      this.txtCommCobY2.TabIndex = 51;
      this.txtCommCobY2.Tag = (object) "QM.X325";
      this.txtCommCobY2.TextAlign = HorizontalAlignment.Right;
      this.txtCommCobM2.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommCobM2.Location = new Point(348, 76);
      this.txtCommCobM2.MaxLength = 2;
      this.txtCommCobM2.Name = "txtCommCobM2";
      this.txtCommCobM2.Size = new Size(42, 20);
      this.txtCommCobM2.TabIndex = 52;
      this.txtCommCobM2.Tag = (object) "QM.X326";
      this.txtCommCobM2.TextAlign = HorizontalAlignment.Right;
      this.label43.AutoSize = true;
      this.label43.Location = new Point(390, 79);
      this.label43.Name = "label43";
      this.label43.Size = new Size(16, 13);
      this.label43.TabIndex = 49;
      this.label43.Text = "M";
      this.txtCommCobM1.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommCobM1.Location = new Point(348, 54);
      this.txtCommCobM1.MaxLength = 2;
      this.txtCommCobM1.Name = "txtCommCobM1";
      this.txtCommCobM1.Size = new Size(42, 20);
      this.txtCommCobM1.TabIndex = 46;
      this.txtCommCobM1.Tag = (object) "QM.X324";
      this.txtCommCobM1.TextAlign = HorizontalAlignment.Right;
      this.label45.AutoSize = true;
      this.label45.Location = new Point(390, 57);
      this.label45.Name = "label45";
      this.label45.Size = new Size(16, 13);
      this.label45.TabIndex = 45;
      this.label45.Text = "M";
      this.txtCommCobAverage.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommCobAverage.Location = new Point(410, 120);
      this.txtCommCobAverage.MaxLength = 10;
      this.txtCommCobAverage.Name = "txtCommCobAverage";
      this.txtCommCobAverage.ReadOnly = true;
      this.txtCommCobAverage.Size = new Size(81, 20);
      this.txtCommCobAverage.TabIndex = 61;
      this.txtCommCobAverage.TabStop = false;
      this.txtCommCobAverage.Tag = (object) "QM.X238";
      this.txtCommCobAverage.TextAlign = HorizontalAlignment.Right;
      this.txtCommBorAverage.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommBorAverage.Location = new Point(192, 120);
      this.txtCommBorAverage.MaxLength = 10;
      this.txtCommBorAverage.Name = "txtCommBorAverage";
      this.txtCommBorAverage.ReadOnly = true;
      this.txtCommBorAverage.Size = new Size(81, 20);
      this.txtCommBorAverage.TabIndex = 60;
      this.txtCommBorAverage.TabStop = false;
      this.txtCommBorAverage.Tag = (object) "QM.X237";
      this.txtCommBorAverage.TextAlign = HorizontalAlignment.Right;
      this.txtCommBorY2.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommBorY2.Location = new Point(76, 76);
      this.txtCommBorY2.MaxLength = 4;
      this.txtCommBorY2.Name = "txtCommBorY2";
      this.txtCommBorY2.Size = new Size(46, 20);
      this.txtCommBorY2.TabIndex = 48;
      this.txtCommBorY2.Tag = (object) "QM.X233";
      this.txtCommBorY2.TextAlign = HorizontalAlignment.Right;
      this.txtCommCob2.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommCob2.Location = new Point(410, 76);
      this.txtCommCob2.MaxLength = 10;
      this.txtCommCob2.Name = "txtCommCob2";
      this.txtCommCob2.Size = new Size(81, 20);
      this.txtCommCob2.TabIndex = 53;
      this.txtCommCob2.Tag = (object) "QM.X236";
      this.txtCommCob2.TextAlign = HorizontalAlignment.Right;
      this.txtCommBorM2.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommBorM2.Location = new Point(128, 76);
      this.txtCommBorM2.MaxLength = 2;
      this.txtCommBorM2.Name = "txtCommBorM2";
      this.txtCommBorM2.Size = new Size(42, 20);
      this.txtCommBorM2.TabIndex = 49;
      this.txtCommBorM2.Tag = (object) "QM.X234";
      this.txtCommBorM2.TextAlign = HorizontalAlignment.Right;
      this.label23.AutoSize = true;
      this.label23.Location = new Point(170, 79);
      this.label23.Name = "label23";
      this.label23.Size = new Size(16, 13);
      this.label23.TabIndex = 12;
      this.label23.Text = "M";
      this.txtCommBor2.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommBor2.Location = new Point(192, 76);
      this.txtCommBor2.MaxLength = 10;
      this.txtCommBor2.Name = "txtCommBor2";
      this.txtCommBor2.Size = new Size(81, 20);
      this.txtCommBor2.TabIndex = 50;
      this.txtCommBor2.Tag = (object) "QM.X235";
      this.txtCommBor2.TextAlign = HorizontalAlignment.Right;
      this.txtCommCob1.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommCob1.Location = new Point(410, 54);
      this.txtCommCob1.MaxLength = 10;
      this.txtCommCob1.Name = "txtCommCob1";
      this.txtCommCob1.Size = new Size(81, 20);
      this.txtCommCob1.TabIndex = 47;
      this.txtCommCob1.Tag = (object) "QM.X232";
      this.txtCommCob1.TextAlign = HorizontalAlignment.Right;
      this.txtCommBorM1.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommBorM1.Location = new Point(128, 54);
      this.txtCommBorM1.MaxLength = 2;
      this.txtCommBorM1.Name = "txtCommBorM1";
      this.txtCommBorM1.Size = new Size(42, 20);
      this.txtCommBorM1.TabIndex = 43;
      this.txtCommBorM1.Tag = (object) "QM.X230";
      this.txtCommBorM1.TextAlign = HorizontalAlignment.Right;
      this.label24.AutoSize = true;
      this.label24.Location = new Point(6, 123);
      this.label24.Name = "label24";
      this.label24.Size = new Size(105, 13);
      this.label24.TabIndex = 8;
      this.label24.Text = "Average Commission";
      this.label25.AutoSize = true;
      this.label25.Location = new Point(6, 79);
      this.label25.Name = "label25";
      this.label25.Size = new Size(52, 13);
      this.label25.TabIndex = 7;
      this.label25.Text = "Last Year";
      this.label26.AutoSize = true;
      this.label26.Location = new Point(170, 57);
      this.label26.Name = "label26";
      this.label26.Size = new Size(16, 13);
      this.label26.TabIndex = 6;
      this.label26.Text = "M";
      this.label27.AutoSize = true;
      this.label27.Location = new Point(6, 57);
      this.label27.Name = "label27";
      this.label27.Size = new Size(67, 13);
      this.label27.TabIndex = 4;
      this.label27.Text = "Year to Date";
      this.label28.AutoSize = true;
      this.label28.Location = new Point(345, 38);
      this.label28.Name = "label28";
      this.label28.Size = new Size(65, 13);
      this.label28.TabIndex = 3;
      this.label28.Text = "Co-Borrower";
      this.label29.AutoSize = true;
      this.label29.Location = new Point(125, 38);
      this.label29.Name = "label29";
      this.label29.Size = new Size(49, 13);
      this.label29.TabIndex = 2;
      this.label29.Text = "Borrower";
      this.txtCommBor1.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommBor1.Location = new Point(192, 54);
      this.txtCommBor1.MaxLength = 10;
      this.txtCommBor1.Name = "txtCommBor1";
      this.txtCommBor1.Size = new Size(81, 20);
      this.txtCommBor1.TabIndex = 44;
      this.txtCommBor1.Tag = (object) "QM.X231";
      this.txtCommBor1.TextAlign = HorizontalAlignment.Right;
      this.label30.AutoSize = true;
      this.label30.Location = new Point(6, 38);
      this.label30.Name = "label30";
      this.label30.Size = new Size(80, 13);
      this.label30.TabIndex = 0;
      this.label30.Text = "Commission For";
      this.btnOK.Location = new Point(354, 474);
      this.btnOK.Name = "btnOK";
      this.btnOK.Size = new Size(75, 23);
      this.btnOK.TabIndex = 62;
      this.btnOK.Text = "&OK";
      this.btnOK.UseVisualStyleBackColor = true;
      this.btnOK.Click += new EventHandler(this.btnOK_Click);
      this.btnCancel.DialogResult = DialogResult.Cancel;
      this.btnCancel.Location = new Point(435, 474);
      this.btnCancel.Name = "btnCancel";
      this.btnCancel.Size = new Size(75, 23);
      this.btnCancel.TabIndex = 63;
      this.btnCancel.Text = "&Cancel";
      this.btnCancel.UseVisualStyleBackColor = true;
      this.emHelpLink1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.emHelpLink1.BackColor = Color.Transparent;
      this.emHelpLink1.Cursor = Cursors.Hand;
      this.emHelpLink1.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.emHelpLink1.HelpTag = nameof (IncomeBonusForm);
      this.emHelpLink1.Location = new Point(9, 482);
      this.emHelpLink1.Name = "emHelpLink1";
      this.emHelpLink1.Size = new Size(90, 16);
      this.emHelpLink1.TabIndex = 70;
      this.pboxDownArrow.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.pboxDownArrow.Image = (Image) componentResourceManager.GetObject("pboxDownArrow.Image");
      this.pboxDownArrow.Location = new Point(191, 481);
      this.pboxDownArrow.Name = "pboxDownArrow";
      this.pboxDownArrow.Size = new Size(17, 17);
      this.pboxDownArrow.TabIndex = 71;
      this.pboxDownArrow.TabStop = false;
      this.pboxDownArrow.Visible = false;
      this.pboxAsterisk.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.pboxAsterisk.Image = (Image) componentResourceManager.GetObject("pboxAsterisk.Image");
      this.pboxAsterisk.Location = new Point(156, 483);
      this.pboxAsterisk.Name = "pboxAsterisk";
      this.pboxAsterisk.Size = new Size(24, 12);
      this.pboxAsterisk.TabIndex = 69;
      this.pboxAsterisk.TabStop = false;
      this.pboxAsterisk.Visible = false;
      this.txtOverBorY1.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverBorY1.Location = new Point(76, 54);
      this.txtOverBorY1.MaxLength = 4;
      this.txtOverBorY1.Name = "txtOverBorY1";
      this.txtOverBorY1.Size = new Size(46, 20);
      this.txtOverBorY1.TabIndex = 1;
      this.txtOverBorY1.Tag = (object) "QM.X352";
      this.txtOverBorY1.TextAlign = HorizontalAlignment.Right;
      this.txtOverCobY1.BorderStyle = BorderStyle.FixedSingle;
      this.txtOverCobY1.Location = new Point(296, 54);
      this.txtOverCobY1.MaxLength = 4;
      this.txtOverCobY1.Name = "txtOverCobY1";
      this.txtOverCobY1.Size = new Size(46, 20);
      this.txtOverCobY1.TabIndex = 4;
      this.txtOverCobY1.Tag = (object) "QM.X353";
      this.txtOverCobY1.TextAlign = HorizontalAlignment.Right;
      this.txtBonusCobY1.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusCobY1.Location = new Point(296, 54);
      this.txtBonusCobY1.MaxLength = 4;
      this.txtBonusCobY1.Name = "txtBonusCobY1";
      this.txtBonusCobY1.Size = new Size(46, 20);
      this.txtBonusCobY1.TabIndex = 25;
      this.txtBonusCobY1.Tag = (object) "QM.X355";
      this.txtBonusCobY1.TextAlign = HorizontalAlignment.Right;
      this.txtBonusBorY1.BorderStyle = BorderStyle.FixedSingle;
      this.txtBonusBorY1.Location = new Point(76, 54);
      this.txtBonusBorY1.MaxLength = 4;
      this.txtBonusBorY1.Name = "txtBonusBorY1";
      this.txtBonusBorY1.Size = new Size(46, 20);
      this.txtBonusBorY1.TabIndex = 22;
      this.txtBonusBorY1.Tag = (object) "QM.X354";
      this.txtBonusBorY1.TextAlign = HorizontalAlignment.Right;
      this.txtCommCobY1.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommCobY1.Location = new Point(296, 54);
      this.txtCommCobY1.MaxLength = 4;
      this.txtCommCobY1.Name = "txtCommCobY1";
      this.txtCommCobY1.Size = new Size(46, 20);
      this.txtCommCobY1.TabIndex = 45;
      this.txtCommCobY1.Tag = (object) "QM.X357";
      this.txtCommCobY1.TextAlign = HorizontalAlignment.Right;
      this.txtCommBorY1.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommBorY1.Location = new Point(76, 54);
      this.txtCommBorY1.MaxLength = 4;
      this.txtCommBorY1.Name = "txtCommBorY1";
      this.txtCommBorY1.Size = new Size(46, 20);
      this.txtCommBorY1.TabIndex = 42;
      this.txtCommBorY1.Tag = (object) "QM.X356";
      this.txtCommBorY1.TextAlign = HorizontalAlignment.Right;
      this.txtCommCobY3.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommCobY3.Location = new Point(296, 98);
      this.txtCommCobY3.MaxLength = 4;
      this.txtCommCobY3.Name = "txtCommCobY3";
      this.txtCommCobY3.Size = new Size(46, 20);
      this.txtCommCobY3.TabIndex = 57;
      this.txtCommCobY3.Tag = (object) "QM.X361";
      this.txtCommCobY3.TextAlign = HorizontalAlignment.Right;
      this.txtCommCobM3.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommCobM3.Location = new Point(348, 98);
      this.txtCommCobM3.MaxLength = 2;
      this.txtCommCobM3.Name = "txtCommCobM3";
      this.txtCommCobM3.Size = new Size(42, 20);
      this.txtCommCobM3.TabIndex = 58;
      this.txtCommCobM3.Tag = (object) "QM.X362";
      this.txtCommCobM3.TextAlign = HorizontalAlignment.Right;
      this.label22.AutoSize = true;
      this.label22.Location = new Point(390, 101);
      this.label22.Name = "label22";
      this.label22.Size = new Size(16, 13);
      this.label22.TabIndex = 60;
      this.label22.Text = "M";
      this.txtCommBorY3.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommBorY3.Location = new Point(76, 98);
      this.txtCommBorY3.MaxLength = 4;
      this.txtCommBorY3.Name = "txtCommBorY3";
      this.txtCommBorY3.Size = new Size(46, 20);
      this.txtCommBorY3.TabIndex = 54;
      this.txtCommBorY3.Tag = (object) "QM.X358";
      this.txtCommBorY3.TextAlign = HorizontalAlignment.Right;
      this.txtCommCob3.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommCob3.Location = new Point(410, 98);
      this.txtCommCob3.MaxLength = 10;
      this.txtCommCob3.Name = "txtCommCob3";
      this.txtCommCob3.Size = new Size(81, 20);
      this.txtCommCob3.TabIndex = 59;
      this.txtCommCob3.Tag = (object) "QM.X363";
      this.txtCommCob3.TextAlign = HorizontalAlignment.Right;
      this.txtCommBorM3.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommBorM3.Location = new Point(128, 98);
      this.txtCommBorM3.MaxLength = 2;
      this.txtCommBorM3.Name = "txtCommBorM3";
      this.txtCommBorM3.Size = new Size(42, 20);
      this.txtCommBorM3.TabIndex = 55;
      this.txtCommBorM3.Tag = (object) "QM.X359";
      this.txtCommBorM3.TextAlign = HorizontalAlignment.Right;
      this.label32.AutoSize = true;
      this.label32.Location = new Point(170, 101);
      this.label32.Name = "label32";
      this.label32.Size = new Size(16, 13);
      this.label32.TabIndex = 53;
      this.label32.Text = "M";
      this.txtCommBor3.BorderStyle = BorderStyle.FixedSingle;
      this.txtCommBor3.Location = new Point(192, 98);
      this.txtCommBor3.MaxLength = 10;
      this.txtCommBor3.Name = "txtCommBor3";
      this.txtCommBor3.Size = new Size(81, 20);
      this.txtCommBor3.TabIndex = 56;
      this.txtCommBor3.Tag = (object) "QM.X360";
      this.txtCommBor3.TextAlign = HorizontalAlignment.Right;
      this.label34.AutoSize = true;
      this.label34.Location = new Point(6, 101);
      this.label34.Name = "label34";
      this.label34.Size = new Size(53, 13);
      this.label34.TabIndex = 52;
      this.label34.Text = "Prior Year";
      this.AcceptButton = (IButtonControl) this.btnOK;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(519, 504);
      this.Controls.Add((Control) this.emHelpLink1);
      this.Controls.Add((Control) this.pboxDownArrow);
      this.Controls.Add((Control) this.pboxAsterisk);
      this.Controls.Add((Control) this.btnCancel);
      this.Controls.Add((Control) this.btnOK);
      this.Controls.Add((Control) this.groupContainer3);
      this.Controls.Add((Control) this.groupContainer2);
      this.Controls.Add((Control) this.groupContainer1);
      this.FormBorderStyle = FormBorderStyle.FixedDialog;
      this.KeyPreview = true;
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = nameof (IncomeBonusForm);
      this.ShowInTaskbar = false;
      this.StartPosition = FormStartPosition.CenterScreen;
      this.Text = "Calculate Overtime, Bonus or Commission Income";
      this.KeyPress += new KeyPressEventHandler(this.dialog_KeyPress);
      this.groupContainer1.ResumeLayout(false);
      this.groupContainer1.PerformLayout();
      this.groupContainer2.ResumeLayout(false);
      this.groupContainer2.PerformLayout();
      this.groupContainer3.ResumeLayout(false);
      this.groupContainer3.PerformLayout();
      ((ISupportInitialize) this.pboxDownArrow).EndInit();
      ((ISupportInitialize) this.pboxAsterisk).EndInit();
      this.ResumeLayout(false);
    }
  }
}
