// Decompiled with JetBrains decompiler
// Type: EllieMae.EMLite.InputEngine.IncomeDividendForm
// Assembly: EMInput, Version=24.3.0.5, Culture=neutral, PublicKeyToken=null
// MVID: ED3FE5F8-B05D-4E0B-8366-E502FB568694
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\EMInput.dll

using EllieMae.EMLite.Common;
using EllieMae.EMLite.Common.UI.Controls;
using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.HelpAPI;
using EllieMae.EMLite.RemotingServices;
using EllieMae.EMLite.UI;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Resources;
using System.Windows.Forms;

#nullable disable
namespace EllieMae.EMLite.InputEngine
{
  public class IncomeDividendForm : Form, IOnlineHelpTarget, IHelp
  {
    private const string className = "IncomeDividendForm";
    private Sessions.Session session;
    private IHtmlInput inputData;
    private LoanData loan;
    private GenericFormInputHandler incomeFormInputHandler;
    private IContainer components;
    private Button btnCancel;
    private Button btnOK;
    private GroupContainer groupContainer2;
    private TextBox txtIntCobAverage;
    private TextBox txtIntBorAverage;
    private TextBox txtIntBorY2;
    private TextBox txtIntCobCash;
    private TextBox txtIntBorCash;
    private Label label12;
    private TextBox txtIntBorY1;
    private TextBox txtIntCob2;
    private TextBox txtIntBorM2;
    private Label label13;
    private TextBox txtIntBor2;
    private TextBox txtIntCob1;
    private TextBox txtIntBorM1;
    private Label label14;
    private Label label15;
    private Label label16;
    private Label label18;
    private Label label19;
    private TextBox txtIntBor1;
    private Label label20;
    private GroupContainer groupContainer1;
    private TextBox txtDividendCobAverage;
    private TextBox txtDividendBorAverage;
    private TextBox txtDividendBorY2;
    private TextBox txtDividendCobCash;
    private TextBox txtDividendBorCash;
    private Label label11;
    private TextBox txtDividendBorY1;
    private TextBox txtDividendCob2;
    private TextBox txtDividendBorM2;
    private Label label9;
    private TextBox txtDividendBor2;
    private TextBox txtDividendCob1;
    private TextBox txtDividendBorM1;
    private Label label8;
    private Label label7;
    private Label label6;
    private Label label3;
    private Label label2;
    private TextBox txtDividendBor1;
    private Label label1;
    private Label label10;
    private Label label4;
    private Label label5;
    private Label label17;
    private EMHelpLink emHelpLink1;
    private PictureBox pboxDownArrow;
    private PictureBox pboxAsterisk;
    private ToolTip toolTipField;
    private TextBox txtDividendCobY2;
    private TextBox txtDividendCobY1;
    private TextBox txtDividendCobM2;
    private Label label22;
    private TextBox txtDividendCobM1;
    private Label label24;
    private TextBox txtIntCobY2;
    private TextBox txtIntCobY1;
    private TextBox txtIntCobM2;
    private Label label26;
    private TextBox txtIntCobM1;
    private Label label28;

    public IncomeDividendForm(IHtmlInput inputData, Sessions.Session session)
    {
      this.session = session;
      this.inputData = inputData;
      if (this.inputData is LoanData)
        this.loan = (LoanData) this.inputData;
      this.InitializeComponent();
      this.incomeFormInputHandler = new GenericFormInputHandler(this.inputData, this.Controls, this.session);
      this.initForm();
    }

    private void initForm()
    {
      this.incomeFormInputHandler.SetFieldValuesToForm();
      this.incomeFormInputHandler.SetBusinessRules(new ResourceManager(typeof (IncomeOtherForm)));
      this.incomeFormInputHandler.SetFieldTip(this.toolTipField);
      for (int index = 0; index < this.incomeFormInputHandler.FieldControls.Count; ++index)
        this.incomeFormInputHandler.SetFieldEvents(this.incomeFormInputHandler.FieldControls[index]);
      this.incomeFormInputHandler.OnKeyUp += new EventHandler(this.calculateFields);
      this.incomeFormInputHandler.OnLeave += new EventHandler(this.textField_Leave);
    }

    private void calculateFields(object sender, EventArgs e)
    {
      this.calculateAverages(this.txtDividendBorM1, this.txtDividendBorM2, this.txtDividendBor1, this.txtDividendBor2, this.txtDividendBorCash, this.txtDividendBorAverage);
      this.calculateAverages(this.txtDividendCobM1, this.txtDividendCobM2, this.txtDividendCob1, this.txtDividendCob2, this.txtDividendCobCash, this.txtDividendCobAverage);
      this.calculateAverages(this.txtIntBorM1, this.txtIntBorM2, this.txtIntBor1, this.txtIntBor2, this.txtIntBorCash, this.txtIntBorAverage);
      this.calculateAverages(this.txtIntCobM1, this.txtIntCobM2, this.txtIntCob1, this.txtIntCob2, this.txtIntCobCash, this.txtIntCobAverage);
    }

    private void calculateAverages(
      TextBox boxMonth1,
      TextBox boxMonth2,
      TextBox boxAmount1,
      TextBox boxAmount2,
      TextBox boxCash,
      TextBox boxAverage)
    {
      Decimal num1 = 0M;
      int num2 = 0;
      Decimal num3 = Utils.ParseDecimal((object) boxCash.Text.Trim().Replace(",", ""));
      if (boxMonth1.Text.Trim() != string.Empty && boxAmount1.Text.Trim() != string.Empty)
      {
        num2 += Utils.ParseInt((object) boxMonth1.Text.Trim());
        num1 += Utils.ParseDecimal((object) boxAmount1.Text.Trim().Replace(",", ""));
      }
      if (boxMonth2.Text.Trim() != string.Empty && boxAmount2.Text.Trim() != string.Empty)
      {
        num2 += Utils.ParseInt((object) boxMonth2.Text.Trim());
        num1 += Utils.ParseDecimal((object) boxAmount2.Text.Trim().Replace(",", ""));
      }
      Decimal num4 = num2 == 0 || num1 == 0M ? 0M : Utils.ArithmeticRounding((num1 - num3) / (Decimal) num2, 2);
      boxAverage.Text = num4 == 0M ? "" : num4.ToString("N2");
    }

    private void btnOK_Click(object sender, EventArgs e)
    {
      this.incomeFormInputHandler.SetFieldValuesToLoan();
      Decimal num1 = Utils.ParseDecimal((object) this.txtDividendBorAverage.Text.Trim()) + Utils.ParseDecimal((object) this.txtIntBorAverage.Text.Trim());
      this.inputData.SetField("QM.X141", num1 == 0M ? "" : num1.ToString("N2"));
      Decimal num2 = Utils.ParseDecimal((object) this.txtDividendCobAverage.Text.Trim()) + Utils.ParseDecimal((object) this.txtIntCobAverage.Text.Trim());
      this.inputData.SetField("QM.X149", num2 == 0M ? "" : num2.ToString("N2"));
      this.DialogResult = DialogResult.OK;
    }

    private void dialog_KeyPress(object sender, KeyPressEventArgs e)
    {
      if (e.KeyChar != '\u001B')
        return;
      this.DialogResult = DialogResult.Cancel;
    }

    private void textField_Leave(object sender, EventArgs e)
    {
      TextBox sender1 = (TextBox) sender;
      if ((sender1.Name.IndexOf("BorY") > -1 || sender1.Name.IndexOf("CobY") > -1) && sender1.Text != string.Empty)
      {
        int num1 = Utils.ParseInt((object) sender1.Text.Trim());
        if (num1 >= 1900 && num1 <= 2199)
          return;
        int num2 = (int) Utils.Dialog((IWin32Window) this, "Value '" + sender1.Text.Trim() + "' is out of range. Must be between 1900 and 2199.", MessageBoxButtons.OK, MessageBoxIcon.Hand);
        sender1.Text = string.Empty;
        this.calculateFields((object) sender1, (EventArgs) null);
        sender1.Focus();
      }
      else
      {
        if (sender1.Name.IndexOf("BorM") <= -1 && sender1.Name.IndexOf("CobM") <= -1 || !(sender1.Text != string.Empty))
          return;
        int num3 = Utils.ParseInt((object) sender1.Text.Trim());
        if (num3 >= 0 && num3 <= 12)
          return;
        int num4 = (int) Utils.Dialog((IWin32Window) this, "Value '" + sender1.Text.Trim() + "' is out of range. Must be between 1 and 12.", MessageBoxButtons.OK, MessageBoxIcon.Hand);
        sender1.Text = string.Empty;
        this.calculateFields((object) sender1, (EventArgs) null);
        sender1.Focus();
      }
    }

    public void ShowHelp()
    {
      JedHelp.ShowHelp((Control) this, SystemSettings.HelpFile, this.GetHelpTargetName());
    }

    public string GetHelpTargetName() => nameof (IncomeDividendForm);

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.components = (IContainer) new System.ComponentModel.Container();
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (IncomeDividendForm));
      this.btnCancel = new Button();
      this.btnOK = new Button();
      this.groupContainer2 = new GroupContainer();
      this.txtIntCobY2 = new TextBox();
      this.txtIntCobY1 = new TextBox();
      this.txtIntCobM2 = new TextBox();
      this.label26 = new Label();
      this.txtIntCobM1 = new TextBox();
      this.label28 = new Label();
      this.label5 = new Label();
      this.label17 = new Label();
      this.txtIntCobAverage = new TextBox();
      this.txtIntBorAverage = new TextBox();
      this.txtIntBorY2 = new TextBox();
      this.txtIntCobCash = new TextBox();
      this.txtIntBorCash = new TextBox();
      this.label12 = new Label();
      this.txtIntBorY1 = new TextBox();
      this.txtIntCob2 = new TextBox();
      this.txtIntBorM2 = new TextBox();
      this.label13 = new Label();
      this.txtIntBor2 = new TextBox();
      this.txtIntCob1 = new TextBox();
      this.txtIntBorM1 = new TextBox();
      this.label14 = new Label();
      this.label15 = new Label();
      this.label16 = new Label();
      this.label18 = new Label();
      this.label19 = new Label();
      this.txtIntBor1 = new TextBox();
      this.label20 = new Label();
      this.groupContainer1 = new GroupContainer();
      this.txtDividendCobY2 = new TextBox();
      this.txtDividendCobY1 = new TextBox();
      this.txtDividendCobM2 = new TextBox();
      this.label22 = new Label();
      this.txtDividendCobM1 = new TextBox();
      this.label24 = new Label();
      this.label10 = new Label();
      this.label4 = new Label();
      this.txtDividendCobAverage = new TextBox();
      this.txtDividendBorAverage = new TextBox();
      this.txtDividendBorY2 = new TextBox();
      this.txtDividendCobCash = new TextBox();
      this.txtDividendBorCash = new TextBox();
      this.label11 = new Label();
      this.txtDividendBorY1 = new TextBox();
      this.txtDividendCob2 = new TextBox();
      this.txtDividendBorM2 = new TextBox();
      this.label9 = new Label();
      this.txtDividendBor2 = new TextBox();
      this.txtDividendCob1 = new TextBox();
      this.txtDividendBorM1 = new TextBox();
      this.label8 = new Label();
      this.label7 = new Label();
      this.label6 = new Label();
      this.label3 = new Label();
      this.label2 = new Label();
      this.txtDividendBor1 = new TextBox();
      this.label1 = new Label();
      this.emHelpLink1 = new EMHelpLink();
      this.pboxDownArrow = new PictureBox();
      this.pboxAsterisk = new PictureBox();
      this.toolTipField = new ToolTip(this.components);
      this.groupContainer2.SuspendLayout();
      this.groupContainer1.SuspendLayout();
      ((ISupportInitialize) this.pboxDownArrow).BeginInit();
      ((ISupportInitialize) this.pboxAsterisk).BeginInit();
      this.SuspendLayout();
      this.btnCancel.DialogResult = DialogResult.Cancel;
      this.btnCancel.Location = new Point(435, 320);
      this.btnCancel.Name = "btnCancel";
      this.btnCancel.Size = new Size(75, 23);
      this.btnCancel.TabIndex = 31;
      this.btnCancel.Text = "&Cancel";
      this.btnCancel.UseVisualStyleBackColor = true;
      this.btnOK.Location = new Point(354, 320);
      this.btnOK.Name = "btnOK";
      this.btnOK.Size = new Size(75, 23);
      this.btnOK.TabIndex = 30;
      this.btnOK.Text = "&OK";
      this.btnOK.UseVisualStyleBackColor = true;
      this.btnOK.Click += new EventHandler(this.btnOK_Click);
      this.groupContainer2.BackColor = Color.White;
      this.groupContainer2.Controls.Add((Control) this.txtIntCobY2);
      this.groupContainer2.Controls.Add((Control) this.txtIntCobY1);
      this.groupContainer2.Controls.Add((Control) this.txtIntCobM2);
      this.groupContainer2.Controls.Add((Control) this.label26);
      this.groupContainer2.Controls.Add((Control) this.txtIntCobM1);
      this.groupContainer2.Controls.Add((Control) this.label28);
      this.groupContainer2.Controls.Add((Control) this.label5);
      this.groupContainer2.Controls.Add((Control) this.label17);
      this.groupContainer2.Controls.Add((Control) this.txtIntCobAverage);
      this.groupContainer2.Controls.Add((Control) this.txtIntBorAverage);
      this.groupContainer2.Controls.Add((Control) this.txtIntBorY2);
      this.groupContainer2.Controls.Add((Control) this.txtIntCobCash);
      this.groupContainer2.Controls.Add((Control) this.txtIntBorCash);
      this.groupContainer2.Controls.Add((Control) this.label12);
      this.groupContainer2.Controls.Add((Control) this.txtIntBorY1);
      this.groupContainer2.Controls.Add((Control) this.txtIntCob2);
      this.groupContainer2.Controls.Add((Control) this.txtIntBorM2);
      this.groupContainer2.Controls.Add((Control) this.label13);
      this.groupContainer2.Controls.Add((Control) this.txtIntBor2);
      this.groupContainer2.Controls.Add((Control) this.txtIntCob1);
      this.groupContainer2.Controls.Add((Control) this.txtIntBorM1);
      this.groupContainer2.Controls.Add((Control) this.label14);
      this.groupContainer2.Controls.Add((Control) this.label15);
      this.groupContainer2.Controls.Add((Control) this.label16);
      this.groupContainer2.Controls.Add((Control) this.label18);
      this.groupContainer2.Controls.Add((Control) this.label19);
      this.groupContainer2.Controls.Add((Control) this.txtIntBor1);
      this.groupContainer2.Controls.Add((Control) this.label20);
      this.groupContainer2.HeaderForeColor = SystemColors.ControlText;
      this.groupContainer2.Location = new Point(9, 166);
      this.groupContainer2.Name = "groupContainer2";
      this.groupContainer2.Size = new Size(501, 148);
      this.groupContainer2.TabIndex = 15;
      this.groupContainer2.Text = "Interest Income";
      this.txtIntCobY2.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntCobY2.Location = new Point(296, 76);
      this.txtIntCobY2.MaxLength = 4;
      this.txtIntCobY2.Name = "txtIntCobY2";
      this.txtIntCobY2.Size = new Size(46, 20);
      this.txtIntCobY2.TabIndex = 26;
      this.txtIntCobY2.Tag = (object) "QM.X333";
      this.txtIntCobY1.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntCobY1.Location = new Point(296, 54);
      this.txtIntCobY1.MaxLength = 4;
      this.txtIntCobY1.Name = "txtIntCobY1";
      this.txtIntCobY1.Size = new Size(46, 20);
      this.txtIntCobY1.TabIndex = 23;
      this.txtIntCobY1.Tag = (object) "QM.X331";
      this.txtIntCobM2.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntCobM2.Location = new Point(348, 76);
      this.txtIntCobM2.MaxLength = 2;
      this.txtIntCobM2.Name = "txtIntCobM2";
      this.txtIntCobM2.Size = new Size(42, 20);
      this.txtIntCobM2.TabIndex = 27;
      this.txtIntCobM2.Tag = (object) "QM.X334";
      this.txtIntCobM2.TextAlign = HorizontalAlignment.Right;
      this.label26.AutoSize = true;
      this.label26.Location = new Point(390, 79);
      this.label26.Name = "label26";
      this.label26.Size = new Size(16, 13);
      this.label26.TabIndex = 30;
      this.label26.Text = "M";
      this.txtIntCobM1.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntCobM1.Location = new Point(348, 54);
      this.txtIntCobM1.MaxLength = 2;
      this.txtIntCobM1.Name = "txtIntCobM1";
      this.txtIntCobM1.Size = new Size(42, 20);
      this.txtIntCobM1.TabIndex = 24;
      this.txtIntCobM1.Tag = (object) "QM.X332";
      this.txtIntCobM1.TextAlign = HorizontalAlignment.Right;
      this.label28.AutoSize = true;
      this.label28.Location = new Point(390, 57);
      this.label28.Name = "label28";
      this.label28.Size = new Size(16, 13);
      this.label28.TabIndex = 28;
      this.label28.Text = "M";
      this.label5.AutoSize = true;
      this.label5.Location = new Point(6, 108);
      this.label5.Name = "label5";
      this.label5.Size = new Size(74, 13);
      this.label5.TabIndex = 27;
      this.label5.Text = "for cash inv (-)";
      this.label17.AutoSize = true;
      this.label17.Location = new Point(6, 97);
      this.label17.Name = "label17";
      this.label17.Size = new Size(126, 13);
      this.label17.TabIndex = 26;
      this.label17.Text = "Interest Income Required";
      this.txtIntCobAverage.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntCobAverage.Location = new Point(410, 121);
      this.txtIntCobAverage.MaxLength = 10;
      this.txtIntCobAverage.Name = "txtIntCobAverage";
      this.txtIntCobAverage.ReadOnly = true;
      this.txtIntCobAverage.Size = new Size(81, 20);
      this.txtIntCobAverage.TabIndex = 25;
      this.txtIntCobAverage.TabStop = false;
      this.txtIntCobAverage.Tag = (object) "QM.X262";
      this.txtIntCobAverage.TextAlign = HorizontalAlignment.Right;
      this.txtIntBorAverage.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntBorAverage.Location = new Point(192, 120);
      this.txtIntBorAverage.MaxLength = 10;
      this.txtIntBorAverage.Name = "txtIntBorAverage";
      this.txtIntBorAverage.ReadOnly = true;
      this.txtIntBorAverage.Size = new Size(81, 20);
      this.txtIntBorAverage.TabIndex = 24;
      this.txtIntBorAverage.TabStop = false;
      this.txtIntBorAverage.Tag = (object) "QM.X261";
      this.txtIntBorAverage.TextAlign = HorizontalAlignment.Right;
      this.txtIntBorY2.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntBorY2.Location = new Point(76, 76);
      this.txtIntBorY2.MaxLength = 4;
      this.txtIntBorY2.Name = "txtIntBorY2";
      this.txtIntBorY2.Size = new Size(46, 20);
      this.txtIntBorY2.TabIndex = 19;
      this.txtIntBorY2.Tag = (object) "QM.X255";
      this.txtIntCobCash.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntCobCash.Location = new Point(410, 99);
      this.txtIntCobCash.MaxLength = 10;
      this.txtIntCobCash.Name = "txtIntCobCash";
      this.txtIntCobCash.Size = new Size(81, 20);
      this.txtIntCobCash.TabIndex = 29;
      this.txtIntCobCash.Tag = (object) "QM.X260";
      this.txtIntCobCash.TextAlign = HorizontalAlignment.Right;
      this.txtIntBorCash.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntBorCash.Location = new Point(192, 98);
      this.txtIntBorCash.MaxLength = 10;
      this.txtIntBorCash.Name = "txtIntBorCash";
      this.txtIntBorCash.Size = new Size(81, 20);
      this.txtIntBorCash.TabIndex = 22;
      this.txtIntBorCash.Tag = (object) "QM.X259";
      this.txtIntBorCash.TextAlign = HorizontalAlignment.Right;
      this.label12.AutoSize = true;
      this.label12.Location = new Point(6, 79);
      this.label12.Name = "label12";
      this.label12.Size = new Size(52, 13);
      this.label12.TabIndex = 16;
      this.label12.Text = "Last Year";
      this.txtIntBorY1.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntBorY1.Location = new Point(76, 54);
      this.txtIntBorY1.MaxLength = 4;
      this.txtIntBorY1.Name = "txtIntBorY1";
      this.txtIntBorY1.Size = new Size(46, 20);
      this.txtIntBorY1.TabIndex = 16;
      this.txtIntBorY1.Tag = (object) "QM.X251";
      this.txtIntCob2.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntCob2.Location = new Point(410, 77);
      this.txtIntCob2.MaxLength = 10;
      this.txtIntCob2.Name = "txtIntCob2";
      this.txtIntCob2.Size = new Size(81, 20);
      this.txtIntCob2.TabIndex = 28;
      this.txtIntCob2.Tag = (object) "QM.X258";
      this.txtIntCob2.TextAlign = HorizontalAlignment.Right;
      this.txtIntBorM2.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntBorM2.Location = new Point(128, 76);
      this.txtIntBorM2.MaxLength = 2;
      this.txtIntBorM2.Name = "txtIntBorM2";
      this.txtIntBorM2.Size = new Size(42, 20);
      this.txtIntBorM2.TabIndex = 20;
      this.txtIntBorM2.Tag = (object) "QM.X256";
      this.txtIntBorM2.TextAlign = HorizontalAlignment.Right;
      this.label13.AutoSize = true;
      this.label13.Location = new Point(170, 79);
      this.label13.Name = "label13";
      this.label13.Size = new Size(16, 13);
      this.label13.TabIndex = 12;
      this.label13.Text = "M";
      this.txtIntBor2.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntBor2.Location = new Point(192, 76);
      this.txtIntBor2.MaxLength = 10;
      this.txtIntBor2.Name = "txtIntBor2";
      this.txtIntBor2.Size = new Size(81, 20);
      this.txtIntBor2.TabIndex = 21;
      this.txtIntBor2.Tag = (object) "QM.X257";
      this.txtIntBor2.TextAlign = HorizontalAlignment.Right;
      this.txtIntCob1.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntCob1.Location = new Point(410, 55);
      this.txtIntCob1.MaxLength = 10;
      this.txtIntCob1.Name = "txtIntCob1";
      this.txtIntCob1.Size = new Size(81, 20);
      this.txtIntCob1.TabIndex = 25;
      this.txtIntCob1.Tag = (object) "QM.X254";
      this.txtIntCob1.TextAlign = HorizontalAlignment.Right;
      this.txtIntBorM1.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntBorM1.Location = new Point(128, 54);
      this.txtIntBorM1.MaxLength = 2;
      this.txtIntBorM1.Name = "txtIntBorM1";
      this.txtIntBorM1.Size = new Size(42, 20);
      this.txtIntBorM1.TabIndex = 17;
      this.txtIntBorM1.Tag = (object) "QM.X252";
      this.txtIntBorM1.TextAlign = HorizontalAlignment.Right;
      this.label14.AutoSize = true;
      this.label14.Location = new Point(6, 124);
      this.label14.Name = "label14";
      this.label14.Size = new Size(85, 13);
      this.label14.TabIndex = 8;
      this.label14.Text = "Average Interest";
      this.label15.AutoSize = true;
      this.label15.Location = new Point(6, 57);
      this.label15.Name = "label15";
      this.label15.Size = new Size(67, 13);
      this.label15.TabIndex = 7;
      this.label15.Text = "Year to Date";
      this.label16.AutoSize = true;
      this.label16.Location = new Point(170, 57);
      this.label16.Name = "label16";
      this.label16.Size = new Size(16, 13);
      this.label16.TabIndex = 6;
      this.label16.Text = "M";
      this.label18.AutoSize = true;
      this.label18.Location = new Point(345, 38);
      this.label18.Name = "label18";
      this.label18.Size = new Size(65, 13);
      this.label18.TabIndex = 3;
      this.label18.Text = "Co-Borrower";
      this.label19.AutoSize = true;
      this.label19.Location = new Point(134, 38);
      this.label19.Name = "label19";
      this.label19.Size = new Size(49, 13);
      this.label19.TabIndex = 2;
      this.label19.Text = "Borrower";
      this.txtIntBor1.BorderStyle = BorderStyle.FixedSingle;
      this.txtIntBor1.Location = new Point(192, 54);
      this.txtIntBor1.MaxLength = 10;
      this.txtIntBor1.Name = "txtIntBor1";
      this.txtIntBor1.Size = new Size(81, 20);
      this.txtIntBor1.TabIndex = 18;
      this.txtIntBor1.Tag = (object) "QM.X253";
      this.txtIntBor1.TextAlign = HorizontalAlignment.Right;
      this.label20.AutoSize = true;
      this.label20.Location = new Point(6, 38);
      this.label20.Name = "label20";
      this.label20.Size = new Size(60, 13);
      this.label20.TabIndex = 0;
      this.label20.Text = "Interest For";
      this.groupContainer1.BackColor = Color.White;
      this.groupContainer1.Controls.Add((Control) this.txtDividendCobY2);
      this.groupContainer1.Controls.Add((Control) this.txtDividendCobY1);
      this.groupContainer1.Controls.Add((Control) this.txtDividendCobM2);
      this.groupContainer1.Controls.Add((Control) this.label22);
      this.groupContainer1.Controls.Add((Control) this.txtDividendCobM1);
      this.groupContainer1.Controls.Add((Control) this.label24);
      this.groupContainer1.Controls.Add((Control) this.label10);
      this.groupContainer1.Controls.Add((Control) this.label4);
      this.groupContainer1.Controls.Add((Control) this.txtDividendCobAverage);
      this.groupContainer1.Controls.Add((Control) this.txtDividendBorAverage);
      this.groupContainer1.Controls.Add((Control) this.txtDividendBorY2);
      this.groupContainer1.Controls.Add((Control) this.txtDividendCobCash);
      this.groupContainer1.Controls.Add((Control) this.txtDividendBorCash);
      this.groupContainer1.Controls.Add((Control) this.label11);
      this.groupContainer1.Controls.Add((Control) this.txtDividendBorY1);
      this.groupContainer1.Controls.Add((Control) this.txtDividendCob2);
      this.groupContainer1.Controls.Add((Control) this.txtDividendBorM2);
      this.groupContainer1.Controls.Add((Control) this.label9);
      this.groupContainer1.Controls.Add((Control) this.txtDividendBor2);
      this.groupContainer1.Controls.Add((Control) this.txtDividendCob1);
      this.groupContainer1.Controls.Add((Control) this.txtDividendBorM1);
      this.groupContainer1.Controls.Add((Control) this.label8);
      this.groupContainer1.Controls.Add((Control) this.label7);
      this.groupContainer1.Controls.Add((Control) this.label6);
      this.groupContainer1.Controls.Add((Control) this.label3);
      this.groupContainer1.Controls.Add((Control) this.label2);
      this.groupContainer1.Controls.Add((Control) this.txtDividendBor1);
      this.groupContainer1.Controls.Add((Control) this.label1);
      this.groupContainer1.HeaderForeColor = SystemColors.ControlText;
      this.groupContainer1.Location = new Point(9, 12);
      this.groupContainer1.Name = "groupContainer1";
      this.groupContainer1.Size = new Size(501, 148);
      this.groupContainer1.TabIndex = 0;
      this.groupContainer1.Text = "Dividend Income";
      this.txtDividendCobY2.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendCobY2.Location = new Point(296, 76);
      this.txtDividendCobY2.MaxLength = 4;
      this.txtDividendCobY2.Name = "txtDividendCobY2";
      this.txtDividendCobY2.Size = new Size(46, 20);
      this.txtDividendCobY2.TabIndex = 11;
      this.txtDividendCobY2.Tag = (object) "QM.X329";
      this.txtDividendCobY1.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendCobY1.Location = new Point(296, 54);
      this.txtDividendCobY1.MaxLength = 4;
      this.txtDividendCobY1.Name = "txtDividendCobY1";
      this.txtDividendCobY1.Size = new Size(46, 20);
      this.txtDividendCobY1.TabIndex = 8;
      this.txtDividendCobY1.Tag = (object) "QM.X327";
      this.txtDividendCobM2.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendCobM2.Location = new Point(348, 76);
      this.txtDividendCobM2.MaxLength = 2;
      this.txtDividendCobM2.Name = "txtDividendCobM2";
      this.txtDividendCobM2.Size = new Size(42, 20);
      this.txtDividendCobM2.TabIndex = 12;
      this.txtDividendCobM2.Tag = (object) "QM.X330";
      this.txtDividendCobM2.TextAlign = HorizontalAlignment.Right;
      this.label22.AutoSize = true;
      this.label22.Location = new Point(390, 79);
      this.label22.Name = "label22";
      this.label22.Size = new Size(16, 13);
      this.label22.TabIndex = 32;
      this.label22.Text = "M";
      this.txtDividendCobM1.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendCobM1.Location = new Point(348, 54);
      this.txtDividendCobM1.MaxLength = 2;
      this.txtDividendCobM1.Name = "txtDividendCobM1";
      this.txtDividendCobM1.Size = new Size(42, 20);
      this.txtDividendCobM1.TabIndex = 9;
      this.txtDividendCobM1.Tag = (object) "QM.X328";
      this.txtDividendCobM1.TextAlign = HorizontalAlignment.Right;
      this.label24.AutoSize = true;
      this.label24.Location = new Point(390, 57);
      this.label24.Name = "label24";
      this.label24.Size = new Size(16, 13);
      this.label24.TabIndex = 30;
      this.label24.Text = "M";
      this.label10.AutoSize = true;
      this.label10.Location = new Point(6, 108);
      this.label10.Name = "label10";
      this.label10.Size = new Size(120, 13);
      this.label10.TabIndex = 25;
      this.label10.Text = "Required for cash inv (-)";
      this.label4.AutoSize = true;
      this.label4.Location = new Point(6, 97);
      this.label4.Name = "label4";
      this.label4.Size = new Size(87, 13);
      this.label4.TabIndex = 24;
      this.label4.Text = "Dividend Income";
      this.txtDividendCobAverage.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendCobAverage.Location = new Point(410, 120);
      this.txtDividendCobAverage.MaxLength = 10;
      this.txtDividendCobAverage.Name = "txtDividendCobAverage";
      this.txtDividendCobAverage.ReadOnly = true;
      this.txtDividendCobAverage.Size = new Size(81, 20);
      this.txtDividendCobAverage.TabIndex = 12;
      this.txtDividendCobAverage.TabStop = false;
      this.txtDividendCobAverage.Tag = (object) "QM.X250";
      this.txtDividendCobAverage.TextAlign = HorizontalAlignment.Right;
      this.txtDividendBorAverage.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendBorAverage.Location = new Point(192, 120);
      this.txtDividendBorAverage.MaxLength = 10;
      this.txtDividendBorAverage.Name = "txtDividendBorAverage";
      this.txtDividendBorAverage.ReadOnly = true;
      this.txtDividendBorAverage.Size = new Size(81, 20);
      this.txtDividendBorAverage.TabIndex = 11;
      this.txtDividendBorAverage.TabStop = false;
      this.txtDividendBorAverage.Tag = (object) "QM.X249";
      this.txtDividendBorAverage.TextAlign = HorizontalAlignment.Right;
      this.txtDividendBorY2.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendBorY2.Location = new Point(76, 76);
      this.txtDividendBorY2.MaxLength = 4;
      this.txtDividendBorY2.Name = "txtDividendBorY2";
      this.txtDividendBorY2.Size = new Size(46, 20);
      this.txtDividendBorY2.TabIndex = 4;
      this.txtDividendBorY2.Tag = (object) "QM.X243";
      this.txtDividendCobCash.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendCobCash.Location = new Point(410, 98);
      this.txtDividendCobCash.MaxLength = 10;
      this.txtDividendCobCash.Name = "txtDividendCobCash";
      this.txtDividendCobCash.Size = new Size(81, 20);
      this.txtDividendCobCash.TabIndex = 14;
      this.txtDividendCobCash.Tag = (object) "QM.X248";
      this.txtDividendCobCash.TextAlign = HorizontalAlignment.Right;
      this.txtDividendBorCash.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendBorCash.Location = new Point(192, 98);
      this.txtDividendBorCash.MaxLength = 10;
      this.txtDividendBorCash.Name = "txtDividendBorCash";
      this.txtDividendBorCash.Size = new Size(81, 20);
      this.txtDividendBorCash.TabIndex = 7;
      this.txtDividendBorCash.Tag = (object) "QM.X247";
      this.txtDividendBorCash.TextAlign = HorizontalAlignment.Right;
      this.label11.AutoSize = true;
      this.label11.Location = new Point(6, 79);
      this.label11.Name = "label11";
      this.label11.Size = new Size(52, 13);
      this.label11.TabIndex = 16;
      this.label11.Text = "Last Year";
      this.txtDividendBorY1.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendBorY1.Location = new Point(76, 54);
      this.txtDividendBorY1.MaxLength = 4;
      this.txtDividendBorY1.Name = "txtDividendBorY1";
      this.txtDividendBorY1.Size = new Size(46, 20);
      this.txtDividendBorY1.TabIndex = 1;
      this.txtDividendBorY1.Tag = (object) "QM.X239";
      this.txtDividendCob2.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendCob2.Location = new Point(410, 76);
      this.txtDividendCob2.MaxLength = 10;
      this.txtDividendCob2.Name = "txtDividendCob2";
      this.txtDividendCob2.Size = new Size(81, 20);
      this.txtDividendCob2.TabIndex = 13;
      this.txtDividendCob2.Tag = (object) "QM.X246";
      this.txtDividendCob2.TextAlign = HorizontalAlignment.Right;
      this.txtDividendBorM2.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendBorM2.Location = new Point(128, 76);
      this.txtDividendBorM2.MaxLength = 2;
      this.txtDividendBorM2.Name = "txtDividendBorM2";
      this.txtDividendBorM2.Size = new Size(42, 20);
      this.txtDividendBorM2.TabIndex = 5;
      this.txtDividendBorM2.Tag = (object) "QM.X244";
      this.txtDividendBorM2.TextAlign = HorizontalAlignment.Right;
      this.label9.AutoSize = true;
      this.label9.Location = new Point(170, 79);
      this.label9.Name = "label9";
      this.label9.Size = new Size(16, 13);
      this.label9.TabIndex = 12;
      this.label9.Text = "M";
      this.txtDividendBor2.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendBor2.Location = new Point(192, 76);
      this.txtDividendBor2.MaxLength = 10;
      this.txtDividendBor2.Name = "txtDividendBor2";
      this.txtDividendBor2.Size = new Size(81, 20);
      this.txtDividendBor2.TabIndex = 6;
      this.txtDividendBor2.Tag = (object) "QM.X245";
      this.txtDividendBor2.TextAlign = HorizontalAlignment.Right;
      this.txtDividendCob1.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendCob1.Location = new Point(410, 54);
      this.txtDividendCob1.MaxLength = 10;
      this.txtDividendCob1.Name = "txtDividendCob1";
      this.txtDividendCob1.Size = new Size(81, 20);
      this.txtDividendCob1.TabIndex = 10;
      this.txtDividendCob1.Tag = (object) "QM.X242";
      this.txtDividendCob1.TextAlign = HorizontalAlignment.Right;
      this.txtDividendBorM1.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendBorM1.Location = new Point(128, 54);
      this.txtDividendBorM1.MaxLength = 2;
      this.txtDividendBorM1.Name = "txtDividendBorM1";
      this.txtDividendBorM1.Size = new Size(42, 20);
      this.txtDividendBorM1.TabIndex = 2;
      this.txtDividendBorM1.Tag = (object) "QM.X240";
      this.txtDividendBorM1.TextAlign = HorizontalAlignment.Right;
      this.label8.AutoSize = true;
      this.label8.Location = new Point(6, 124);
      this.label8.Name = "label8";
      this.label8.Size = new Size(92, 13);
      this.label8.TabIndex = 8;
      this.label8.Text = "Average Dividend";
      this.label7.AutoSize = true;
      this.label7.Location = new Point(6, 57);
      this.label7.Name = "label7";
      this.label7.Size = new Size(67, 13);
      this.label7.TabIndex = 7;
      this.label7.Text = "Year to Date";
      this.label6.AutoSize = true;
      this.label6.Location = new Point(170, 57);
      this.label6.Name = "label6";
      this.label6.Size = new Size(16, 13);
      this.label6.TabIndex = 6;
      this.label6.Text = "M";
      this.label3.AutoSize = true;
      this.label3.Location = new Point(345, 38);
      this.label3.Name = "label3";
      this.label3.Size = new Size(65, 13);
      this.label3.TabIndex = 3;
      this.label3.Text = "Co-Borrower";
      this.label2.AutoSize = true;
      this.label2.Location = new Point(125, 38);
      this.label2.Name = "label2";
      this.label2.Size = new Size(49, 13);
      this.label2.TabIndex = 2;
      this.label2.Text = "Borrower";
      this.txtDividendBor1.BorderStyle = BorderStyle.FixedSingle;
      this.txtDividendBor1.Location = new Point(192, 54);
      this.txtDividendBor1.MaxLength = 10;
      this.txtDividendBor1.Name = "txtDividendBor1";
      this.txtDividendBor1.Size = new Size(81, 20);
      this.txtDividendBor1.TabIndex = 3;
      this.txtDividendBor1.Tag = (object) "QM.X241";
      this.txtDividendBor1.TextAlign = HorizontalAlignment.Right;
      this.label1.AutoSize = true;
      this.label1.Location = new Point(6, 38);
      this.label1.Name = "label1";
      this.label1.Size = new Size(67, 13);
      this.label1.TabIndex = 0;
      this.label1.Text = "Dividend For";
      this.emHelpLink1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.emHelpLink1.BackColor = Color.Transparent;
      this.emHelpLink1.Cursor = Cursors.Hand;
      this.emHelpLink1.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.emHelpLink1.HelpTag = nameof (IncomeDividendForm);
      this.emHelpLink1.Location = new Point(12, 326);
      this.emHelpLink1.Name = "emHelpLink1";
      this.emHelpLink1.Size = new Size(90, 16);
      this.emHelpLink1.TabIndex = 70;
      this.pboxDownArrow.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.pboxDownArrow.Image = (Image) componentResourceManager.GetObject("pboxDownArrow.Image");
      this.pboxDownArrow.Location = new Point(194, 325);
      this.pboxDownArrow.Name = "pboxDownArrow";
      this.pboxDownArrow.Size = new Size(17, 17);
      this.pboxDownArrow.TabIndex = 71;
      this.pboxDownArrow.TabStop = false;
      this.pboxDownArrow.Visible = false;
      this.pboxAsterisk.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
      this.pboxAsterisk.Image = (Image) componentResourceManager.GetObject("pboxAsterisk.Image");
      this.pboxAsterisk.Location = new Point(159, 327);
      this.pboxAsterisk.Name = "pboxAsterisk";
      this.pboxAsterisk.Size = new Size(24, 12);
      this.pboxAsterisk.TabIndex = 69;
      this.pboxAsterisk.TabStop = false;
      this.pboxAsterisk.Visible = false;
      this.AcceptButton = (IButtonControl) this.btnOK;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(519, 351);
      this.Controls.Add((Control) this.emHelpLink1);
      this.Controls.Add((Control) this.pboxDownArrow);
      this.Controls.Add((Control) this.pboxAsterisk);
      this.Controls.Add((Control) this.btnCancel);
      this.Controls.Add((Control) this.btnOK);
      this.Controls.Add((Control) this.groupContainer2);
      this.Controls.Add((Control) this.groupContainer1);
      this.FormBorderStyle = FormBorderStyle.FixedDialog;
      this.KeyPreview = true;
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = nameof (IncomeDividendForm);
      this.ShowInTaskbar = false;
      this.StartPosition = FormStartPosition.CenterScreen;
      this.Text = "Calculate Dividend and Interest Income";
      this.KeyPress += new KeyPressEventHandler(this.dialog_KeyPress);
      this.groupContainer2.ResumeLayout(false);
      this.groupContainer2.PerformLayout();
      this.groupContainer1.ResumeLayout(false);
      this.groupContainer1.PerformLayout();
      ((ISupportInitialize) this.pboxDownArrow).EndInit();
      ((ISupportInitialize) this.pboxAsterisk).EndInit();
      this.ResumeLayout(false);
    }
  }
}
