// Decompiled with JetBrains decompiler
// Type: EllieMae.EMLite.InputEngine.ServicingAnnualSummary
// Assembly: EMInput, Version=24.3.0.5, Culture=neutral, PublicKeyToken=null
// MVID: ED3FE5F8-B05D-4E0B-8366-E502FB568694
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\EMInput.dll

using EllieMae.EMLite.DataEngine.InterimServicing;
using EllieMae.EMLite.UI;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace EllieMae.EMLite.InputEngine
{
  public class ServicingAnnualSummary : Form
  {
    private ServicingSummaryViewModel vm;
    private int selectedYear = -1;
    private IContainer components;
    private GroupContainer groupContainer1;
    private Label label4;
    private Label label3;
    private ComboBox cboPaymentYear;
    private Label label29;
    private Button btnCancel;
    private Label label32;
    private Label label33;
    private TextBox txtBuydownSubsidyAmount;
    private TextBox txtPnI;
    private Label label20;
    private Label label21;
    private Label label22;
    private Label label23;
    private TextBox txtLateFee;
    private TextBox txtTotalFeeCollected;
    private Label label2;
    private Label label6;
    private TextBox txtPrincipal;
    private Label label9;
    private TextBox txtInterest;
    private Label label10;
    private TextBox txtEscrow;
    private Label label14;
    private TextBox txtMiscFee;
    private Label label15;
    private Label label18;
    private Label label16;
    private Label label34;
    private TextBox txtEscrowUsdaMonthlyPremium;
    private Label label35;
    private Label label30;
    private TextBox txtEscrowOther3;
    private Label label31;
    private Label label27;
    private TextBox txtEscrowOther2;
    private Label label28;
    private Label label25;
    private TextBox txtEscrowOther1;
    private Label label26;
    private Label label19;
    private TextBox txtEscrowCityPropertyTax;
    private Label label24;
    private Label label13;
    private TextBox txtEscrowFloodInsurance;
    private Label label17;
    private Label label11;
    private TextBox txtEscrowMortgageInsurance;
    private Label label12;
    private Label label7;
    private TextBox txtEscrowHazardInsurance;
    private Label label8;
    private Label label5;
    private TextBox txtEscrowTaxes;
    private Label label1;

    public ServicingAnnualSummary(ServicingSummaryViewModel vm)
    {
      this.InitializeComponent();
      this.vm = vm;
      this.initControl();
      this.initView();
    }

    private void initControl()
    {
      this.resetView();
      this.cboPaymentYear.Items.Clear();
      this.cboPaymentYear.Items.Add((object) "Select Year");
      if (this.vm.LastPaymentReceivedDate != DateTime.MinValue)
      {
        for (int index = 0; index < 3; ++index)
          this.cboPaymentYear.Items.Add((object) (this.vm.LastPaymentReceivedDate.Year - index));
      }
      if (this.cboPaymentYear.Items.Count <= 0)
        return;
      this.cboPaymentYear.SelectedIndex = 0;
    }

    private void resetView()
    {
      this.txtPrincipal.Text = "";
      this.txtInterest.Text = "";
      this.txtPnI.Text = "";
      this.txtEscrow.Text = "";
      this.txtEscrowTaxes.Text = "";
      this.txtEscrowHazardInsurance.Text = "";
      this.txtEscrowMortgageInsurance.Text = "";
      this.txtEscrowFloodInsurance.Text = "";
      this.txtEscrowCityPropertyTax.Text = "";
      this.txtEscrowOther1.Text = "";
      this.txtEscrowOther2.Text = "";
      this.txtEscrowOther3.Text = "";
      this.txtEscrowUsdaMonthlyPremium.Text = "";
      this.txtBuydownSubsidyAmount.Text = "";
      this.txtLateFee.Text = "";
      this.txtMiscFee.Text = "";
      this.txtTotalFeeCollected.Text = "";
    }

    private void initView()
    {
      this.selectedYear = -1;
      if (!int.TryParse(this.cboPaymentYear.SelectedItem.ToString(), out this.selectedYear))
        return;
      TextBox txtPrincipal = this.txtPrincipal;
      double num = this.vm.Principal + this.vm.AdditionalPrincipal;
      string str1 = num.ToString("N2");
      txtPrincipal.Text = str1;
      TextBox txtInterest = this.txtInterest;
      num = this.vm.Interest;
      string str2 = num.ToString("N2");
      txtInterest.Text = str2;
      TextBox txtPnI = this.txtPnI;
      num = this.vm.PnI;
      string str3 = num.ToString("N2");
      txtPnI.Text = str3;
      TextBox txtEscrow = this.txtEscrow;
      num = this.vm.Escrow.TotalEscrowPayment + this.vm.AdditionalEscrow;
      string str4 = num.ToString("N2");
      txtEscrow.Text = str4;
      TextBox txtEscrowTaxes = this.txtEscrowTaxes;
      num = this.vm.Escrow.Taxes;
      string str5 = num.ToString("N2");
      txtEscrowTaxes.Text = str5;
      TextBox escrowHazardInsurance = this.txtEscrowHazardInsurance;
      num = this.vm.Escrow.HazardInsurance;
      string str6 = num.ToString("N2");
      escrowHazardInsurance.Text = str6;
      TextBox mortgageInsurance = this.txtEscrowMortgageInsurance;
      num = this.vm.Escrow.MortgageInsurance;
      string str7 = num.ToString("N2");
      mortgageInsurance.Text = str7;
      TextBox escrowFloodInsurance = this.txtEscrowFloodInsurance;
      num = this.vm.Escrow.FloodInsurance;
      string str8 = num.ToString("N2");
      escrowFloodInsurance.Text = str8;
      TextBox escrowCityPropertyTax = this.txtEscrowCityPropertyTax;
      num = this.vm.Escrow.CityPropertyTax;
      string str9 = num.ToString("N2");
      escrowCityPropertyTax.Text = str9;
      TextBox txtEscrowOther1 = this.txtEscrowOther1;
      num = this.vm.Escrow.Other1;
      string str10 = num.ToString("N2");
      txtEscrowOther1.Text = str10;
      TextBox txtEscrowOther2 = this.txtEscrowOther2;
      num = this.vm.Escrow.Other2;
      string str11 = num.ToString("N2");
      txtEscrowOther2.Text = str11;
      TextBox txtEscrowOther3 = this.txtEscrowOther3;
      num = this.vm.Escrow.Other3;
      string str12 = num.ToString("N2");
      txtEscrowOther3.Text = str12;
      TextBox usdaMonthlyPremium = this.txtEscrowUsdaMonthlyPremium;
      num = this.vm.Escrow.UsdaMonthlyPremuim;
      string str13 = num.ToString("N2");
      usdaMonthlyPremium.Text = str13;
      TextBox buydownSubsidyAmount = this.txtBuydownSubsidyAmount;
      num = this.vm.BuydownSubsidyAmount;
      string str14 = num.ToString("N2");
      buydownSubsidyAmount.Text = str14;
      TextBox txtLateFee = this.txtLateFee;
      num = this.vm.LateFee;
      string str15 = num.ToString("N2");
      txtLateFee.Text = str15;
      TextBox txtMiscFee = this.txtMiscFee;
      num = this.vm.MiscFee;
      string str16 = num.ToString("N2");
      txtMiscFee.Text = str16;
      TextBox totalFeeCollected = this.txtTotalFeeCollected;
      num = this.vm.TotalFeeCollected;
      string str17 = num.ToString("N2");
      totalFeeCollected.Text = str17;
    }

    private void cboPaymentYear_SelectedIndexChanged(object sender, EventArgs e)
    {
      this.resetView();
      if (this.cboPaymentYear.SelectedItem == null || this.cboPaymentYear.SelectedIndex == 0)
        return;
      this.selectedYear = -1;
      if (!int.TryParse(this.cboPaymentYear.SelectedItem.ToString(), out this.selectedYear))
        this.initControl();
      this.vm.GenerateAnnualSummary(this.selectedYear);
      this.initView();
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.groupContainer1 = new GroupContainer();
      this.label4 = new Label();
      this.label3 = new Label();
      this.cboPaymentYear = new ComboBox();
      this.label29 = new Label();
      this.btnCancel = new Button();
      this.label32 = new Label();
      this.label33 = new Label();
      this.txtBuydownSubsidyAmount = new TextBox();
      this.txtPnI = new TextBox();
      this.label20 = new Label();
      this.label21 = new Label();
      this.label22 = new Label();
      this.label23 = new Label();
      this.txtLateFee = new TextBox();
      this.txtTotalFeeCollected = new TextBox();
      this.label2 = new Label();
      this.label6 = new Label();
      this.txtPrincipal = new TextBox();
      this.label9 = new Label();
      this.txtInterest = new TextBox();
      this.label10 = new Label();
      this.txtEscrow = new TextBox();
      this.label14 = new Label();
      this.txtMiscFee = new TextBox();
      this.label15 = new Label();
      this.label18 = new Label();
      this.label16 = new Label();
      this.label1 = new Label();
      this.txtEscrowTaxes = new TextBox();
      this.label5 = new Label();
      this.label7 = new Label();
      this.txtEscrowHazardInsurance = new TextBox();
      this.label8 = new Label();
      this.label11 = new Label();
      this.txtEscrowMortgageInsurance = new TextBox();
      this.label12 = new Label();
      this.label13 = new Label();
      this.txtEscrowFloodInsurance = new TextBox();
      this.label17 = new Label();
      this.label19 = new Label();
      this.txtEscrowCityPropertyTax = new TextBox();
      this.label24 = new Label();
      this.label25 = new Label();
      this.txtEscrowOther1 = new TextBox();
      this.label26 = new Label();
      this.label27 = new Label();
      this.txtEscrowOther2 = new TextBox();
      this.label28 = new Label();
      this.label30 = new Label();
      this.txtEscrowOther3 = new TextBox();
      this.label31 = new Label();
      this.label34 = new Label();
      this.txtEscrowUsdaMonthlyPremium = new TextBox();
      this.label35 = new Label();
      this.groupContainer1.SuspendLayout();
      this.SuspendLayout();
      this.groupContainer1.Controls.Add((Control) this.label34);
      this.groupContainer1.Controls.Add((Control) this.txtEscrowUsdaMonthlyPremium);
      this.groupContainer1.Controls.Add((Control) this.label35);
      this.groupContainer1.Controls.Add((Control) this.label30);
      this.groupContainer1.Controls.Add((Control) this.txtEscrowOther3);
      this.groupContainer1.Controls.Add((Control) this.label31);
      this.groupContainer1.Controls.Add((Control) this.label27);
      this.groupContainer1.Controls.Add((Control) this.txtEscrowOther2);
      this.groupContainer1.Controls.Add((Control) this.label28);
      this.groupContainer1.Controls.Add((Control) this.label25);
      this.groupContainer1.Controls.Add((Control) this.txtEscrowOther1);
      this.groupContainer1.Controls.Add((Control) this.label26);
      this.groupContainer1.Controls.Add((Control) this.label19);
      this.groupContainer1.Controls.Add((Control) this.txtEscrowCityPropertyTax);
      this.groupContainer1.Controls.Add((Control) this.label24);
      this.groupContainer1.Controls.Add((Control) this.label13);
      this.groupContainer1.Controls.Add((Control) this.txtEscrowFloodInsurance);
      this.groupContainer1.Controls.Add((Control) this.label17);
      this.groupContainer1.Controls.Add((Control) this.label11);
      this.groupContainer1.Controls.Add((Control) this.txtEscrowMortgageInsurance);
      this.groupContainer1.Controls.Add((Control) this.label12);
      this.groupContainer1.Controls.Add((Control) this.label7);
      this.groupContainer1.Controls.Add((Control) this.txtEscrowHazardInsurance);
      this.groupContainer1.Controls.Add((Control) this.label8);
      this.groupContainer1.Controls.Add((Control) this.label5);
      this.groupContainer1.Controls.Add((Control) this.txtEscrowTaxes);
      this.groupContainer1.Controls.Add((Control) this.label1);
      this.groupContainer1.Controls.Add((Control) this.label4);
      this.groupContainer1.Controls.Add((Control) this.label3);
      this.groupContainer1.Controls.Add((Control) this.cboPaymentYear);
      this.groupContainer1.Controls.Add((Control) this.label29);
      this.groupContainer1.Controls.Add((Control) this.btnCancel);
      this.groupContainer1.Controls.Add((Control) this.label32);
      this.groupContainer1.Controls.Add((Control) this.label33);
      this.groupContainer1.Controls.Add((Control) this.txtBuydownSubsidyAmount);
      this.groupContainer1.Controls.Add((Control) this.txtPnI);
      this.groupContainer1.Controls.Add((Control) this.label20);
      this.groupContainer1.Controls.Add((Control) this.label21);
      this.groupContainer1.Controls.Add((Control) this.label22);
      this.groupContainer1.Controls.Add((Control) this.label23);
      this.groupContainer1.Controls.Add((Control) this.txtLateFee);
      this.groupContainer1.Controls.Add((Control) this.txtTotalFeeCollected);
      this.groupContainer1.Controls.Add((Control) this.label2);
      this.groupContainer1.Controls.Add((Control) this.label6);
      this.groupContainer1.Controls.Add((Control) this.txtPrincipal);
      this.groupContainer1.Controls.Add((Control) this.label9);
      this.groupContainer1.Controls.Add((Control) this.txtInterest);
      this.groupContainer1.Controls.Add((Control) this.label10);
      this.groupContainer1.Controls.Add((Control) this.txtEscrow);
      this.groupContainer1.Controls.Add((Control) this.label14);
      this.groupContainer1.Controls.Add((Control) this.txtMiscFee);
      this.groupContainer1.Controls.Add((Control) this.label15);
      this.groupContainer1.Controls.Add((Control) this.label18);
      this.groupContainer1.Controls.Add((Control) this.label16);
      this.groupContainer1.Dock = DockStyle.Fill;
      this.groupContainer1.HeaderForeColor = SystemColors.ControlText;
      this.groupContainer1.Location = new Point(0, 0);
      this.groupContainer1.Name = "groupContainer1";
      this.groupContainer1.Size = new Size(310, 481);
      this.groupContainer1.TabIndex = 164;
      this.groupContainer1.Text = "Payment Summary By Year";
      this.label4.AutoSize = true;
      this.label4.Location = new Point(151, 104);
      this.label4.Name = "label4";
      this.label4.Size = new Size(13, 13);
      this.label4.TabIndex = 159;
      this.label4.Text = "$";
      this.label3.AutoSize = true;
      this.label3.Location = new Point(8, 33);
      this.label3.Name = "label3";
      this.label3.Size = new Size(73, 13);
      this.label3.TabIndex = 158;
      this.label3.Text = "Payment Year";
      this.cboPaymentYear.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cboPaymentYear.FormattingEnabled = true;
      this.cboPaymentYear.Location = new Point(167, 33);
      this.cboPaymentYear.Name = "cboPaymentYear";
      this.cboPaymentYear.Size = new Size(133, 21);
      this.cboPaymentYear.TabIndex = 157;
      this.cboPaymentYear.SelectedIndexChanged += new EventHandler(this.cboPaymentYear_SelectedIndexChanged);
      this.label29.AutoSize = true;
      this.label29.Location = new Point(151, 342);
      this.label29.Name = "label29";
      this.label29.Size = new Size(13, 13);
      this.label29.TabIndex = 153;
      this.label29.Text = "$";
      this.btnCancel.BackColor = SystemColors.Control;
      this.btnCancel.DialogResult = DialogResult.Cancel;
      this.btnCancel.Location = new Point(225, 454);
      this.btnCancel.Name = "btnCancel";
      this.btnCancel.Size = new Size(75, 23);
      this.btnCancel.TabIndex = 116;
      this.btnCancel.Text = "&Close";
      this.btnCancel.UseVisualStyleBackColor = true;
      this.label32.AutoSize = true;
      this.label32.Location = new Point(8, 104);
      this.label32.Name = "label32";
      this.label32.Size = new Size(29, 13);
      this.label32.TabIndex = 149;
      this.label32.Text = "P && I";
      this.label33.AutoSize = true;
      this.label33.Location = new Point(8, 341);
      this.label33.Name = "label33";
      this.label33.Size = new Size(112, 13);
      this.label33.TabIndex = 151;
      this.label33.Text = "Buydown Subsidy Amt";
      this.txtBuydownSubsidyAmount.BackColor = Color.WhiteSmoke;
      this.txtBuydownSubsidyAmount.Location = new Point(167, 337);
      this.txtBuydownSubsidyAmount.Name = "txtBuydownSubsidyAmount";
      this.txtBuydownSubsidyAmount.ReadOnly = true;
      this.txtBuydownSubsidyAmount.Size = new Size(133, 20);
      this.txtBuydownSubsidyAmount.TabIndex = 150;
      this.txtBuydownSubsidyAmount.Tag = (object) "";
      this.txtBuydownSubsidyAmount.TextAlign = HorizontalAlignment.Right;
      this.txtPnI.BackColor = Color.WhiteSmoke;
      this.txtPnI.Location = new Point(167, 102);
      this.txtPnI.Name = "txtPnI";
      this.txtPnI.ReadOnly = true;
      this.txtPnI.Size = new Size(133, 20);
      this.txtPnI.TabIndex = 148;
      this.txtPnI.Tag = (object) "";
      this.txtPnI.TextAlign = HorizontalAlignment.Right;
      this.label20.AutoSize = true;
      this.label20.Location = new Point(151, 363);
      this.label20.Name = "label20";
      this.label20.Size = new Size(13, 13);
      this.label20.TabIndex = 147;
      this.label20.Text = "$";
      this.label21.AutoSize = true;
      this.label21.Location = new Point(151, 410);
      this.label21.Name = "label21";
      this.label21.Size = new Size(13, 13);
      this.label21.TabIndex = 146;
      this.label21.Text = "$";
      this.label22.AutoSize = true;
      this.label22.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label22.Location = new Point(8, 409);
      this.label22.Name = "label22";
      this.label22.Size = new Size(118, 13);
      this.label22.TabIndex = 143;
      this.label22.Text = "Total Pmt Collected";
      this.label23.AutoSize = true;
      this.label23.Location = new Point(8, 364);
      this.label23.Name = "label23";
      this.label23.Size = new Size(49, 13);
      this.label23.TabIndex = 145;
      this.label23.Text = "Late Fee";
      this.txtLateFee.BackColor = Color.WhiteSmoke;
      this.txtLateFee.Location = new Point(167, 360);
      this.txtLateFee.Name = "txtLateFee";
      this.txtLateFee.ReadOnly = true;
      this.txtLateFee.Size = new Size(133, 20);
      this.txtLateFee.TabIndex = 144;
      this.txtLateFee.Tag = (object) "";
      this.txtLateFee.TextAlign = HorizontalAlignment.Right;
      this.txtTotalFeeCollected.BackColor = Color.WhiteSmoke;
      this.txtTotalFeeCollected.Location = new Point(167, 406);
      this.txtTotalFeeCollected.Name = "txtTotalFeeCollected";
      this.txtTotalFeeCollected.ReadOnly = true;
      this.txtTotalFeeCollected.Size = new Size(133, 20);
      this.txtTotalFeeCollected.TabIndex = 142;
      this.txtTotalFeeCollected.Tag = (object) "Escrow";
      this.txtTotalFeeCollected.TextAlign = HorizontalAlignment.Right;
      this.label2.AutoSize = true;
      this.label2.Location = new Point(151, 386);
      this.label2.Name = "label2";
      this.label2.Size = new Size(13, 13);
      this.label2.TabIndex = 139;
      this.label2.Text = "$";
      this.label6.AutoSize = true;
      this.label6.Location = new Point(151, 128);
      this.label6.Name = "label6";
      this.label6.Size = new Size(13, 13);
      this.label6.TabIndex = 138;
      this.label6.Text = "$";
      this.txtPrincipal.BackColor = Color.WhiteSmoke;
      this.txtPrincipal.Location = new Point(167, 57);
      this.txtPrincipal.Name = "txtPrincipal";
      this.txtPrincipal.ReadOnly = true;
      this.txtPrincipal.Size = new Size(133, 20);
      this.txtPrincipal.TabIndex = 128;
      this.txtPrincipal.Tag = (object) "";
      this.txtPrincipal.TextAlign = HorizontalAlignment.Right;
      this.label9.AutoSize = true;
      this.label9.Location = new Point(151, 81);
      this.label9.Name = "label9";
      this.label9.Size = new Size(13, 13);
      this.label9.TabIndex = 137;
      this.label9.Text = "$";
      this.txtInterest.BackColor = Color.WhiteSmoke;
      this.txtInterest.Location = new Point(167, 79);
      this.txtInterest.Name = "txtInterest";
      this.txtInterest.ReadOnly = true;
      this.txtInterest.Size = new Size(133, 20);
      this.txtInterest.TabIndex = 129;
      this.txtInterest.Tag = (object) "";
      this.txtInterest.TextAlign = HorizontalAlignment.Right;
      this.label10.AutoSize = true;
      this.label10.Location = new Point(151, 60);
      this.label10.Name = "label10";
      this.label10.Size = new Size(13, 13);
      this.label10.TabIndex = 136;
      this.label10.Text = "$";
      this.txtEscrow.BackColor = Color.WhiteSmoke;
      this.txtEscrow.Location = new Point(167, 124);
      this.txtEscrow.Name = "txtEscrow";
      this.txtEscrow.ReadOnly = true;
      this.txtEscrow.Size = new Size(133, 20);
      this.txtEscrow.TabIndex = 130;
      this.txtEscrow.Tag = (object) "";
      this.txtEscrow.TextAlign = HorizontalAlignment.Right;
      this.label14.AutoSize = true;
      this.label14.Location = new Point(8, 60);
      this.label14.Name = "label14";
      this.label14.Size = new Size(47, 13);
      this.label14.TabIndex = 131;
      this.label14.Text = "Principal";
      this.txtMiscFee.BackColor = Color.WhiteSmoke;
      this.txtMiscFee.Location = new Point(167, 383);
      this.txtMiscFee.Name = "txtMiscFee";
      this.txtMiscFee.ReadOnly = true;
      this.txtMiscFee.Size = new Size(133, 20);
      this.txtMiscFee.TabIndex = 134;
      this.txtMiscFee.Tag = (object) "";
      this.txtMiscFee.TextAlign = HorizontalAlignment.Right;
      this.label15.AutoSize = true;
      this.label15.Location = new Point(8, 82);
      this.label15.Name = "label15";
      this.label15.Size = new Size(42, 13);
      this.label15.TabIndex = 132;
      this.label15.Text = "Interest";
      this.label18.AutoSize = true;
      this.label18.Location = new Point(8, 386);
      this.label18.Name = "label18";
      this.label18.Size = new Size(53, 13);
      this.label18.TabIndex = 135;
      this.label18.Text = "Misc. Fee";
      this.label16.AutoSize = true;
      this.label16.Location = new Point(8, (int) sbyte.MaxValue);
      this.label16.Name = "label16";
      this.label16.Size = new Size(42, 13);
      this.label16.TabIndex = 133;
      this.label16.Text = "Escrow";
      this.label1.AutoSize = true;
      this.label1.Location = new Point(60, 149);
      this.label1.Name = "label1";
      this.label1.Size = new Size(36, 13);
      this.label1.TabIndex = 160;
      this.label1.Text = "Taxes";
      this.txtEscrowTaxes.Location = new Point(200, 146);
      this.txtEscrowTaxes.Name = "txtEscrowTaxes";
      this.txtEscrowTaxes.ReadOnly = true;
      this.txtEscrowTaxes.Size = new Size(100, 20);
      this.txtEscrowTaxes.TabIndex = 161;
      this.txtEscrowTaxes.TextAlign = HorizontalAlignment.Right;
      this.label5.AutoSize = true;
      this.label5.Location = new Point(184, 149);
      this.label5.Name = "label5";
      this.label5.Size = new Size(13, 13);
      this.label5.TabIndex = 162;
      this.label5.Text = "$";
      this.label7.AutoSize = true;
      this.label7.Location = new Point(184, 170);
      this.label7.Name = "label7";
      this.label7.Size = new Size(13, 13);
      this.label7.TabIndex = 165;
      this.label7.Text = "$";
      this.txtEscrowHazardInsurance.Location = new Point(200, 167);
      this.txtEscrowHazardInsurance.Name = "txtEscrowHazardInsurance";
      this.txtEscrowHazardInsurance.ReadOnly = true;
      this.txtEscrowHazardInsurance.Size = new Size(100, 20);
      this.txtEscrowHazardInsurance.TabIndex = 164;
      this.txtEscrowHazardInsurance.TextAlign = HorizontalAlignment.Right;
      this.label8.AutoSize = true;
      this.label8.Location = new Point(60, 170);
      this.label8.Name = "label8";
      this.label8.Size = new Size(91, 13);
      this.label8.TabIndex = 163;
      this.label8.Text = "Hazard Insurance";
      this.label11.AutoSize = true;
      this.label11.Location = new Point(184, 191);
      this.label11.Name = "label11";
      this.label11.Size = new Size(13, 13);
      this.label11.TabIndex = 168;
      this.label11.Text = "$";
      this.txtEscrowMortgageInsurance.Location = new Point(200, 188);
      this.txtEscrowMortgageInsurance.Name = "txtEscrowMortgageInsurance";
      this.txtEscrowMortgageInsurance.ReadOnly = true;
      this.txtEscrowMortgageInsurance.Size = new Size(100, 20);
      this.txtEscrowMortgageInsurance.TabIndex = 167;
      this.txtEscrowMortgageInsurance.TextAlign = HorizontalAlignment.Right;
      this.label12.AutoSize = true;
      this.label12.Location = new Point(60, 191);
      this.label12.Name = "label12";
      this.label12.Size = new Size(102, 13);
      this.label12.TabIndex = 166;
      this.label12.Text = "Mortgage Insurance";
      this.label13.AutoSize = true;
      this.label13.Location = new Point(184, 212);
      this.label13.Name = "label13";
      this.label13.Size = new Size(13, 13);
      this.label13.TabIndex = 171;
      this.label13.Text = "$";
      this.txtEscrowFloodInsurance.Location = new Point(200, 209);
      this.txtEscrowFloodInsurance.Name = "txtEscrowFloodInsurance";
      this.txtEscrowFloodInsurance.ReadOnly = true;
      this.txtEscrowFloodInsurance.Size = new Size(100, 20);
      this.txtEscrowFloodInsurance.TabIndex = 170;
      this.txtEscrowFloodInsurance.TextAlign = HorizontalAlignment.Right;
      this.label17.AutoSize = true;
      this.label17.Location = new Point(60, 212);
      this.label17.Name = "label17";
      this.label17.Size = new Size(83, 13);
      this.label17.TabIndex = 169;
      this.label17.Text = "Flood Insurance";
      this.label19.AutoSize = true;
      this.label19.Location = new Point(184, 233);
      this.label19.Name = "label19";
      this.label19.Size = new Size(13, 13);
      this.label19.TabIndex = 174;
      this.label19.Text = "$";
      this.txtEscrowCityPropertyTax.Location = new Point(200, 230);
      this.txtEscrowCityPropertyTax.Name = "txtEscrowCityPropertyTax";
      this.txtEscrowCityPropertyTax.ReadOnly = true;
      this.txtEscrowCityPropertyTax.Size = new Size(100, 20);
      this.txtEscrowCityPropertyTax.TabIndex = 173;
      this.txtEscrowCityPropertyTax.TextAlign = HorizontalAlignment.Right;
      this.label24.AutoSize = true;
      this.label24.Location = new Point(60, 233);
      this.label24.Name = "label24";
      this.label24.Size = new Size(87, 13);
      this.label24.TabIndex = 172;
      this.label24.Text = "City Property Tax";
      this.label25.AutoSize = true;
      this.label25.Location = new Point(184, 254);
      this.label25.Name = "label25";
      this.label25.Size = new Size(13, 13);
      this.label25.TabIndex = 177;
      this.label25.Text = "$";
      this.txtEscrowOther1.Location = new Point(200, 251);
      this.txtEscrowOther1.Name = "txtEscrowOther1";
      this.txtEscrowOther1.ReadOnly = true;
      this.txtEscrowOther1.Size = new Size(100, 20);
      this.txtEscrowOther1.TabIndex = 176;
      this.txtEscrowOther1.TextAlign = HorizontalAlignment.Right;
      this.label26.AutoSize = true;
      this.label26.Location = new Point(60, 254);
      this.label26.Name = "label26";
      this.label26.Size = new Size(42, 13);
      this.label26.TabIndex = 175;
      this.label26.Text = "Other 1";
      this.label27.AutoSize = true;
      this.label27.Location = new Point(184, 275);
      this.label27.Name = "label27";
      this.label27.Size = new Size(13, 13);
      this.label27.TabIndex = 180;
      this.label27.Text = "$";
      this.txtEscrowOther2.Location = new Point(200, 272);
      this.txtEscrowOther2.Name = "txtEscrowOther2";
      this.txtEscrowOther2.ReadOnly = true;
      this.txtEscrowOther2.Size = new Size(100, 20);
      this.txtEscrowOther2.TabIndex = 179;
      this.txtEscrowOther2.TextAlign = HorizontalAlignment.Right;
      this.label28.AutoSize = true;
      this.label28.Location = new Point(60, 275);
      this.label28.Name = "label28";
      this.label28.Size = new Size(42, 13);
      this.label28.TabIndex = 178;
      this.label28.Text = "Other 2";
      this.label30.AutoSize = true;
      this.label30.Location = new Point(184, 296);
      this.label30.Name = "label30";
      this.label30.Size = new Size(13, 13);
      this.label30.TabIndex = 183;
      this.label30.Text = "$";
      this.txtEscrowOther3.Location = new Point(200, 293);
      this.txtEscrowOther3.Name = "txtEscrowOther3";
      this.txtEscrowOther3.ReadOnly = true;
      this.txtEscrowOther3.Size = new Size(100, 20);
      this.txtEscrowOther3.TabIndex = 182;
      this.txtEscrowOther3.TextAlign = HorizontalAlignment.Right;
      this.label31.AutoSize = true;
      this.label31.Location = new Point(60, 296);
      this.label31.Name = "label31";
      this.label31.Size = new Size(42, 13);
      this.label31.TabIndex = 181;
      this.label31.Text = "Other 3";
      this.label34.AutoSize = true;
      this.label34.Location = new Point(184, 317);
      this.label34.Name = "label34";
      this.label34.Size = new Size(13, 13);
      this.label34.TabIndex = 186;
      this.label34.Text = "$";
      this.txtEscrowUsdaMonthlyPremium.Location = new Point(200, 314);
      this.txtEscrowUsdaMonthlyPremium.Name = "txtEscrowUsdaMonthlyPremium";
      this.txtEscrowUsdaMonthlyPremium.ReadOnly = true;
      this.txtEscrowUsdaMonthlyPremium.Size = new Size(100, 20);
      this.txtEscrowUsdaMonthlyPremium.TabIndex = 185;
      this.txtEscrowUsdaMonthlyPremium.TextAlign = HorizontalAlignment.Right;
      this.label35.AutoSize = true;
      this.label35.Location = new Point(60, 317);
      this.label35.Name = "label35";
      this.label35.Size = new Size(120, 13);
      this.label35.TabIndex = 184;
      this.label35.Text = "USDA Monthly Premium";
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(310, 481);
      this.Controls.Add((Control) this.groupContainer1);
      this.FormBorderStyle = FormBorderStyle.FixedDialog;
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = nameof (ServicingAnnualSummary);
      this.StartPosition = FormStartPosition.CenterScreen;
      this.Text = "Payment Summary History";
      this.groupContainer1.ResumeLayout(false);
      this.groupContainer1.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
