// Decompiled with JetBrains decompiler
// Type: Confluent.Kafka.GroupMemberInfo
// Assembly: Confluent.Kafka, Version=1.4.3.0, Culture=neutral, PublicKeyToken=12c514ca49093d1e
// MVID: D64D07A1-80DE-4516-9A12-7428C1CB46D3
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\Confluent.Kafka.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\Confluent.Kafka.xml

#nullable disable
namespace Confluent.Kafka
{
  /// <summary>
  ///     Encapsulates information describing a particular
  ///     member of a Kafka group.
  /// </summary>
  public class GroupMemberInfo
  {
    /// <summary>Initializes a new GroupMemberInfo class instance.</summary>
    /// <param name="memberId">
    ///     The member id (generated by the broker).
    /// </param>
    /// <param name="clientId">The client's client.id.</param>
    /// <param name="clientHost">The client's hostname.</param>
    /// <param name="memberMetadata">
    ///     Gets the member metadata (binary). The format of this data depends on the protocol type.
    /// </param>
    /// <param name="memberAssignment">
    ///     Gets the member assignment (binary). The format of this data depends on the protocol type.
    /// </param>
    public GroupMemberInfo(
      string memberId,
      string clientId,
      string clientHost,
      byte[] memberMetadata,
      byte[] memberAssignment)
    {
      this.MemberId = memberId;
      this.ClientId = clientId;
      this.ClientHost = clientHost;
      this.MemberMetadata = memberMetadata;
      this.MemberAssignment = memberAssignment;
    }

    /// <summary>Gets the member id (generated by broker).</summary>
    public string MemberId { get; }

    /// <summary>Gets the client's client.id.</summary>
    public string ClientId { get; }

    /// <summary>Gets the client's hostname.</summary>
    public string ClientHost { get; }

    /// <summary>
    ///     Gets the member metadata (binary). The format of this data depends on the protocol type.
    /// </summary>
    public byte[] MemberMetadata { get; }

    /// <summary>
    ///     Gets the member assignment (binary). The format of this data depends on the protocol type.
    /// </summary>
    public byte[] MemberAssignment { get; }
  }
}
