// Decompiled with JetBrains decompiler
// Type: EllieMae.EMLite.InputEngine.LockRequest.ONRPEffectiveSettings
// Assembly: EMInput, Version=24.3.0.5, Culture=neutral, PublicKeyToken=null
// MVID: ED3FE5F8-B05D-4E0B-8366-E502FB568694
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\EMInput.dll

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.LoanUtils.RateLocks;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace EllieMae.EMLite.InputEngine.LockRequest
{
  public class ONRPEffectiveSettings : Form
  {
    private IContainer components;
    private GroupBox groupBox2;
    private Label lblContinuousCoverage;
    private Label lblEnableLockDeskSettings;
    private Label label1;
    private Label lblLockEndTime;
    private Label label8;
    private Label lblLockStartTime;
    private Label label7;
    private Label lblBranchTolerance;
    private Label label13;
    private Label lblBranchDollarLimit;
    private Label label12;
    private Label lblNoMaxLimit;
    private Label label11;
    private Label label6;
    private Label lblChannelDefault;
    private Label lblBranchHWCoverage;
    private Label label10;
    private Label lblONRPEndTime;
    private Label label5;
    private Label labelChannel;
    private Label lblChannelEnabled;
    private Label label3;
    private Label lblTPOName;
    private Label label4;
    private Label label15;
    private Label label16;
    private Label label17;
    private Label label2;
    private Label label9;
    private Label label14;
    private Label label19;
    private Label label18;
    private Label lblONRPEndTimeSat;
    private Label lblONRPEndTimeSun;
    private Label lblLockStartTimeSun;
    private Label lblOnrpEnabledSat;
    private Label lblOnrpEnabledSun;
    private Label lblLockEndTimeSat;
    private Label lblLockEndTimeSun;
    private Label lblLockStartTimeSat;

    public ONRPEffectiveSettings(
      LoanDataMgr loanMgr,
      LockDeskHoursInfo hoursInfo,
      LockDeskOnrpInfo effectiveOnrpInfo)
    {
      this.InitializeComponent();
      this.lblEnableLockDeskSettings.Text = hoursInfo.IsEncompassLockDeskHoursEnabled.ToString();
      string field1 = loanMgr.LoanData.GetField("364");
      string field2 = loanMgr.LoanData.GetField("2626");
      string field3 = loanMgr.LoanData.GetField("TPO.X15");
      if (string.IsNullOrEmpty(field1))
        return;
      LoanChannel enumChannel = LockDeskHoursUtils.GetEnumChannel(field2);
      switch (enumChannel)
      {
        case LoanChannel.BankedRetail:
        case LoanChannel.BankedWholesale:
        case LoanChannel.Correspondent:
          if ((enumChannel == LoanChannel.Correspondent || enumChannel == LoanChannel.BankedWholesale) && string.IsNullOrEmpty(field3) || !effectiveOnrpInfo.IsONRPEnabled)
            break;
          this.lblChannelEnabled.Text = loanMgr.LoanData.GetField("2626") + " (" + effectiveOnrpInfo.IsONRPEnabled.ToString() + ")";
          this.lblChannelDefault.Text = effectiveOnrpInfo.IsUseChannelDefaults.ToString();
          this.lblContinuousCoverage.Text = effectiveOnrpInfo.IsContinuousONRPCoverage.ToString();
          Label lblLockStartTime = this.lblLockStartTime;
          TimeSpan timeSpan = hoursInfo.LockDeskStartTime;
          string str1 = timeSpan.ToString();
          lblLockStartTime.Text = str1;
          Label lblLockEndTime = this.lblLockEndTime;
          timeSpan = hoursInfo.LockDeskEndTime;
          string str2 = timeSpan.ToString();
          lblLockEndTime.Text = str2;
          Label lblOnrpEndTime = this.lblONRPEndTime;
          timeSpan = effectiveOnrpInfo.ONRPEndTime;
          string str3 = timeSpan.ToString();
          lblOnrpEndTime.Text = str3;
          Label branchHwCoverage = this.lblBranchHWCoverage;
          bool flag = effectiveOnrpInfo.IsWeekendHolidayCoverage;
          string str4 = flag.ToString();
          branchHwCoverage.Text = str4;
          Label lblNoMaxLimit = this.lblNoMaxLimit;
          flag = effectiveOnrpInfo.IsNoMaxLimit;
          string str5 = flag.ToString();
          lblNoMaxLimit.Text = str5;
          this.lblBranchDollarLimit.Text = effectiveOnrpInfo.ONRPLimitAmount.ToString();
          this.lblBranchTolerance.Text = effectiveOnrpInfo.ONRPTolerance.ToString();
          this.lblTPOName.Text = loanMgr.LoanData.GetField("TPO.X14");
          Label lockStartTimeSat = this.lblLockStartTimeSat;
          timeSpan = hoursInfo.LockDeskStartTimeSat;
          string str6 = timeSpan.ToString();
          lockStartTimeSat.Text = str6;
          Label lblLockEndTimeSat = this.lblLockEndTimeSat;
          timeSpan = hoursInfo.LockDeskEndTimeSat;
          string str7 = timeSpan.ToString();
          lblLockEndTimeSat.Text = str7;
          Label lblOnrpEndTimeSat = this.lblONRPEndTimeSat;
          timeSpan = effectiveOnrpInfo.ONRPSatEndTime;
          string str8 = timeSpan.ToString();
          lblOnrpEndTimeSat.Text = str8;
          Label lblOnrpEnabledSat = this.lblOnrpEnabledSat;
          flag = effectiveOnrpInfo.IsONRPSatEnabled;
          string str9 = flag.ToString();
          lblOnrpEnabledSat.Text = str9;
          Label lockStartTimeSun = this.lblLockStartTimeSun;
          timeSpan = hoursInfo.LockDeskStartTimeSun;
          string str10 = timeSpan.ToString();
          lockStartTimeSun.Text = str10;
          Label lblLockEndTimeSun = this.lblLockEndTimeSun;
          timeSpan = hoursInfo.LockDeskEndTimeSun;
          string str11 = timeSpan.ToString();
          lblLockEndTimeSun.Text = str11;
          Label lblOnrpEndTimeSun = this.lblONRPEndTimeSun;
          timeSpan = effectiveOnrpInfo.ONRPSunEndTime;
          string str12 = timeSpan.ToString();
          lblOnrpEndTimeSun.Text = str12;
          Label lblOnrpEnabledSun = this.lblOnrpEnabledSun;
          flag = effectiveOnrpInfo.IsONRPSunEnabled;
          string str13 = flag.ToString();
          lblOnrpEnabledSun.Text = str13;
          break;
      }
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.groupBox2 = new GroupBox();
      this.label19 = new Label();
      this.label18 = new Label();
      this.label15 = new Label();
      this.label16 = new Label();
      this.label17 = new Label();
      this.label2 = new Label();
      this.label9 = new Label();
      this.label14 = new Label();
      this.lblTPOName = new Label();
      this.label4 = new Label();
      this.lblBranchTolerance = new Label();
      this.label13 = new Label();
      this.lblBranchDollarLimit = new Label();
      this.label12 = new Label();
      this.lblNoMaxLimit = new Label();
      this.label11 = new Label();
      this.label6 = new Label();
      this.lblChannelDefault = new Label();
      this.lblBranchHWCoverage = new Label();
      this.label10 = new Label();
      this.lblONRPEndTime = new Label();
      this.label5 = new Label();
      this.labelChannel = new Label();
      this.lblChannelEnabled = new Label();
      this.label3 = new Label();
      this.lblLockEndTime = new Label();
      this.label8 = new Label();
      this.lblLockStartTime = new Label();
      this.label7 = new Label();
      this.lblContinuousCoverage = new Label();
      this.lblEnableLockDeskSettings = new Label();
      this.label1 = new Label();
      this.lblLockStartTimeSun = new Label();
      this.lblOnrpEnabledSat = new Label();
      this.lblOnrpEnabledSun = new Label();
      this.lblONRPEndTimeSat = new Label();
      this.lblONRPEndTimeSun = new Label();
      this.lblLockStartTimeSat = new Label();
      this.lblLockEndTimeSun = new Label();
      this.lblLockEndTimeSat = new Label();
      this.groupBox2.SuspendLayout();
      this.SuspendLayout();
      this.groupBox2.Controls.Add((Control) this.label19);
      this.groupBox2.Controls.Add((Control) this.label18);
      this.groupBox2.Controls.Add((Control) this.label15);
      this.groupBox2.Controls.Add((Control) this.label16);
      this.groupBox2.Controls.Add((Control) this.label17);
      this.groupBox2.Controls.Add((Control) this.label2);
      this.groupBox2.Controls.Add((Control) this.label9);
      this.groupBox2.Controls.Add((Control) this.label14);
      this.groupBox2.Controls.Add((Control) this.lblTPOName);
      this.groupBox2.Controls.Add((Control) this.label4);
      this.groupBox2.Controls.Add((Control) this.lblBranchTolerance);
      this.groupBox2.Controls.Add((Control) this.label13);
      this.groupBox2.Controls.Add((Control) this.lblBranchDollarLimit);
      this.groupBox2.Controls.Add((Control) this.label12);
      this.groupBox2.Controls.Add((Control) this.lblNoMaxLimit);
      this.groupBox2.Controls.Add((Control) this.label11);
      this.groupBox2.Controls.Add((Control) this.label6);
      this.groupBox2.Controls.Add((Control) this.lblChannelDefault);
      this.groupBox2.Controls.Add((Control) this.lblBranchHWCoverage);
      this.groupBox2.Controls.Add((Control) this.label10);
      this.groupBox2.Controls.Add((Control) this.lblONRPEndTime);
      this.groupBox2.Controls.Add((Control) this.label5);
      this.groupBox2.Controls.Add((Control) this.labelChannel);
      this.groupBox2.Controls.Add((Control) this.lblChannelEnabled);
      this.groupBox2.Controls.Add((Control) this.label3);
      this.groupBox2.Controls.Add((Control) this.lblLockEndTime);
      this.groupBox2.Controls.Add((Control) this.label8);
      this.groupBox2.Controls.Add((Control) this.lblLockStartTime);
      this.groupBox2.Controls.Add((Control) this.label7);
      this.groupBox2.Controls.Add((Control) this.lblContinuousCoverage);
      this.groupBox2.Controls.Add((Control) this.lblEnableLockDeskSettings);
      this.groupBox2.Controls.Add((Control) this.label1);
      this.groupBox2.Controls.Add((Control) this.lblLockEndTimeSat);
      this.groupBox2.Controls.Add((Control) this.lblLockEndTimeSun);
      this.groupBox2.Controls.Add((Control) this.lblLockStartTimeSat);
      this.groupBox2.Controls.Add((Control) this.lblLockStartTimeSun);
      this.groupBox2.Controls.Add((Control) this.lblOnrpEnabledSat);
      this.groupBox2.Controls.Add((Control) this.lblOnrpEnabledSun);
      this.groupBox2.Controls.Add((Control) this.lblONRPEndTimeSat);
      this.groupBox2.Controls.Add((Control) this.lblONRPEndTimeSun);
      this.groupBox2.Location = new Point(13, 13);
      this.groupBox2.Name = "groupBox2";
      this.groupBox2.Size = new Size(372, 529);
      this.groupBox2.TabIndex = 1;
      this.groupBox2.TabStop = false;
      this.groupBox2.Text = "Effective ONRP Settings";
      this.label19.AutoSize = true;
      this.label19.Location = new Point(84, 267);
      this.label19.Name = "label19";
      this.label19.Size = new Size(137, 13);
      this.label19.TabIndex = 36;
      this.label19.Text = "Saturday ONRP End Time :";
      this.label18.AutoSize = true;
      this.label18.Location = new Point(97, 350);
      this.label18.Name = "label18";
      this.label18.Size = new Size(125, 13);
      this.label18.TabIndex = 35;
      this.label18.Text = "Sunday ONRP Enabled :";
      this.label15.AutoSize = true;
      this.label15.Location = new Point(91, 370);
      this.label15.Name = "label15";
      this.label15.Size = new Size(131, 13);
      this.label15.TabIndex = 34;
      this.label15.Text = "Sunday ONRP End Time :";
      this.label16.AutoSize = true;
      this.label16.Location = new Point(70, 328);
      this.label16.Name = "label16";
      this.label16.Size = new Size(152, 13);
      this.label16.TabIndex = 33;
      this.label16.Text = "Sunday Lock Desk End Time :";
      this.label17.AutoSize = true;
      this.label17.Location = new Point(68, 306);
      this.label17.Name = "label17";
      this.label17.Size = new Size(155, 13);
      this.label17.TabIndex = 32;
      this.label17.Text = "Sunday Lock Desk Start Time :";
      this.label2.AutoSize = true;
      this.label2.Location = new Point(90, 247);
      this.label2.Name = "label2";
      this.label2.Size = new Size(131, 13);
      this.label2.TabIndex = 31;
      this.label2.Text = "Saturday ONRP Enabled :";
      this.label9.AutoSize = true;
      this.label9.Location = new Point(64, 225);
      this.label9.Name = "label9";
      this.label9.Size = new Size(158, 13);
      this.label9.TabIndex = 30;
      this.label9.Text = "Saturday Lock Desk End Time :";
      this.label14.AutoSize = true;
      this.label14.Location = new Point(61, 204);
      this.label14.Name = "label14";
      this.label14.Size = new Size(161, 13);
      this.label14.TabIndex = 29;
      this.label14.Text = "Saturday Lock Desk Start Time :";
      this.lblTPOName.AutoSize = true;
      this.lblTPOName.Location = new Point(228, 507);
      this.lblTPOName.Name = "lblTPOName";
      this.lblTPOName.Size = new Size(0, 13);
      this.lblTPOName.TabIndex = 28;
      this.label4.AutoSize = true;
      this.label4.Location = new Point(106, 506);
      this.label4.Name = "label4";
      this.label4.Size = new Size(116, 13);
      this.label4.TabIndex = 27;
      this.label4.Text = "TPO Company Name  :";
      this.lblBranchTolerance.AutoSize = true;
      this.lblBranchTolerance.Location = new Point(228, 485);
      this.lblBranchTolerance.Name = "lblBranchTolerance";
      this.lblBranchTolerance.Size = new Size(0, 13);
      this.lblBranchTolerance.TabIndex = 26;
      this.label13.AutoSize = true;
      this.label13.Location = new Point(113, 484);
      this.label13.Name = "label13";
      this.label13.Size = new Size(109, 13);
      this.label13.TabIndex = 25;
      this.label13.Text = "ONRP Tolerance %  :";
      this.lblBranchDollarLimit.AutoSize = true;
      this.lblBranchDollarLimit.Location = new Point(229, 459);
      this.lblBranchDollarLimit.Name = "lblBranchDollarLimit";
      this.lblBranchDollarLimit.Size = new Size(0, 13);
      this.lblBranchDollarLimit.TabIndex = 24;
      this.label12.AutoSize = true;
      this.label12.Location = new Point(124, 459);
      this.label12.Name = "label12";
      this.label12.Size = new Size(98, 13);
      this.label12.TabIndex = 23;
      this.label12.Text = "ONRP Dollar Limit :";
      this.lblNoMaxLimit.AutoSize = true;
      this.lblNoMaxLimit.Location = new Point(228, 436);
      this.lblNoMaxLimit.Name = "lblNoMaxLimit";
      this.lblNoMaxLimit.Size = new Size(0, 13);
      this.lblNoMaxLimit.TabIndex = 22;
      this.label11.AutoSize = true;
      this.label11.Location = new Point(124, 434);
      this.label11.Name = "label11";
      this.label11.Size = new Size(98, 13);
      this.label11.TabIndex = 21;
      this.label11.Text = "No Maximum Limit :";
      this.label6.AutoSize = true;
      this.label6.Location = new Point(112, 68);
      this.label6.Name = "label6";
      this.label6.Size = new Size(110, 13);
      this.label6.TabIndex = 20;
      this.label6.Text = "Use channel Default :";
      this.lblChannelDefault.AutoSize = true;
      this.lblChannelDefault.Location = new Point(229, 68);
      this.lblChannelDefault.Name = "lblChannelDefault";
      this.lblChannelDefault.Size = new Size(0, 13);
      this.lblChannelDefault.TabIndex = 19;
      this.lblBranchHWCoverage.AutoSize = true;
      this.lblBranchHWCoverage.Location = new Point(228, 412);
      this.lblBranchHWCoverage.Name = "lblBranchHWCoverage";
      this.lblBranchHWCoverage.Size = new Size(0, 13);
      this.lblBranchHWCoverage.TabIndex = 18;
      this.label10.AutoSize = true;
      this.label10.Location = new Point(73, 410);
      this.label10.Name = "label10";
      this.label10.Size = new Size(149, 13);
      this.label10.TabIndex = 17;
      this.label10.Text = "Weekend/Holiday Coverage :";
      this.lblONRPEndTime.AutoSize = true;
      this.lblONRPEndTime.Location = new Point(228, 168);
      this.lblONRPEndTime.Name = "lblONRPEndTime";
      this.lblONRPEndTime.Size = new Size(0, 13);
      this.lblONRPEndTime.TabIndex = 16;
      this.label5.AutoSize = true;
      this.label5.Location = new Point(130, 166);
      this.label5.Name = "label5";
      this.label5.Size = new Size(92, 13);
      this.label5.TabIndex = 15;
      this.label5.Text = "ONRP End Time :";
      this.labelChannel.AutoSize = true;
      this.labelChannel.Location = new Point(128, 46);
      this.labelChannel.Name = "labelChannel";
      this.labelChannel.Size = new Size(94, 13);
      this.labelChannel.TabIndex = 14;
      this.labelChannel.Text = "Channel Enabled :";
      this.lblChannelEnabled.AutoSize = true;
      this.lblChannelEnabled.Location = new Point(229, 46);
      this.lblChannelEnabled.Name = "lblChannelEnabled";
      this.lblChannelEnabled.Size = new Size(0, 13);
      this.lblChannelEnabled.TabIndex = 13;
      this.label3.AutoSize = true;
      this.label3.Location = new Point(107, 90);
      this.label3.Name = "label3";
      this.label3.RightToLeft = RightToLeft.No;
      this.label3.Size = new Size(115, 13);
      this.label3.TabIndex = 12;
      this.label3.Text = "Continuous Coverage :";
      this.label3.TextAlign = ContentAlignment.MiddleRight;
      this.lblLockEndTime.AutoSize = true;
      this.lblLockEndTime.Location = new Point(228, 147);
      this.lblLockEndTime.Name = "lblLockEndTime";
      this.lblLockEndTime.Size = new Size(0, 13);
      this.lblLockEndTime.TabIndex = 11;
      this.label8.AutoSize = true;
      this.label8.Location = new Point(109, 146);
      this.label8.Name = "label8";
      this.label8.Size = new Size(113, 13);
      this.label8.TabIndex = 10;
      this.label8.Text = "Lock Desk End Time :";
      this.lblLockStartTime.AutoSize = true;
      this.lblLockStartTime.Location = new Point(228, 128);
      this.lblLockStartTime.Name = "lblLockStartTime";
      this.lblLockStartTime.Size = new Size(0, 13);
      this.lblLockStartTime.TabIndex = 9;
      this.label7.AutoSize = true;
      this.label7.Location = new Point(106, 126);
      this.label7.Name = "label7";
      this.label7.Size = new Size(116, 13);
      this.label7.TabIndex = 8;
      this.label7.Text = "Lock Desk Start Time :";
      this.lblContinuousCoverage.AutoSize = true;
      this.lblContinuousCoverage.Location = new Point(229, 90);
      this.lblContinuousCoverage.Name = "lblContinuousCoverage";
      this.lblContinuousCoverage.Size = new Size(0, 13);
      this.lblContinuousCoverage.TabIndex = 3;
      this.lblEnableLockDeskSettings.AutoSize = true;
      this.lblEnableLockDeskSettings.Location = new Point(229, 25);
      this.lblEnableLockDeskSettings.Name = "lblEnableLockDeskSettings";
      this.lblEnableLockDeskSettings.Size = new Size(0, 13);
      this.lblEnableLockDeskSettings.TabIndex = 1;
      this.label1.AutoSize = true;
      this.label1.Location = new Point(22, 25);
      this.label1.Name = "label1";
      this.label1.Size = new Size(200, 13);
      this.label1.TabIndex = 0;
      this.label1.Text = "Enable Encompass Lock Desk Settings :";
      this.lblLockStartTimeSun.Location = new Point(228, 305);
      this.lblLockStartTimeSun.Name = "lblLockStartTimeSun";
      this.lblLockStartTimeSun.Size = new Size(100, 14);
      this.lblLockStartTimeSun.TabIndex = 40;
      this.lblOnrpEnabledSat.Location = new Point(229, 247);
      this.lblOnrpEnabledSat.Name = "lblOnrpEnabledSat";
      this.lblOnrpEnabledSat.Size = new Size(100, 13);
      this.lblOnrpEnabledSat.TabIndex = 41;
      this.lblOnrpEnabledSun.Location = new Point(228, 347);
      this.lblOnrpEnabledSun.Name = "lblOnrpEnabledSun";
      this.lblOnrpEnabledSun.Size = new Size(100, 16);
      this.lblOnrpEnabledSun.TabIndex = 42;
      this.lblONRPEndTimeSat.Location = new Point(227, 267);
      this.lblONRPEndTimeSat.Name = "lblONRPEndTimeSat";
      this.lblONRPEndTimeSat.Size = new Size(100, 14);
      this.lblONRPEndTimeSat.TabIndex = 43;
      this.lblONRPEndTimeSun.Location = new Point(227, 370);
      this.lblONRPEndTimeSun.Name = "lblONRPEndTimeSun";
      this.lblONRPEndTimeSun.Size = new Size(100, 16);
      this.lblONRPEndTimeSun.TabIndex = 44;
      this.lblLockStartTimeSat.Location = new Point(228, 204);
      this.lblLockStartTimeSat.Name = "lblLockStartTimeSat";
      this.lblLockStartTimeSat.Size = new Size(100, 18);
      this.lblLockStartTimeSat.TabIndex = 39;
      this.lblLockEndTimeSun.Location = new Point(228, 328);
      this.lblLockEndTimeSun.Name = "lblLockEndTimeSun";
      this.lblLockEndTimeSun.Size = new Size(100, 13);
      this.lblLockEndTimeSun.TabIndex = 38;
      this.lblLockEndTimeSat.Location = new Point(228, 225);
      this.lblLockEndTimeSat.Name = "lblLockEndTimeSat";
      this.lblLockEndTimeSat.Size = new Size(100, 15);
      this.lblLockEndTimeSat.TabIndex = 37;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(403, 554);
      this.Controls.Add((Control) this.groupBox2);
      this.Name = nameof (ONRPEffectiveSettings);
      this.Text = nameof (ONRPEffectiveSettings);
      this.groupBox2.ResumeLayout(false);
      this.groupBox2.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
