// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._1003PG3__LETTER_CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _1003PG3__LETTER_CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "FL0402");
      nameValueCollection.Add("FL0402", str1);
      string str2 = JS.GetStr(loan, "FL0403");
      nameValueCollection.Add("FL0403", str2);
      string str3 = JS.GetStr(loan, "FL0404");
      nameValueCollection.Add("FL0404", str3);
      string str4 = JS.GetStr(loan, "FL0405") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0406"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0406") + " " + JS.GetStr(loan, "FL0407");
      nameValueCollection.Add("FL0405_FL0406_FL0407", str4);
      string str5 = JS.GetStr(loan, "FL0410");
      nameValueCollection.Add("FL0410", str5);
      string str6 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0418"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0417"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0411") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0417"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0411", str6);
      string str7 = JS.GetStr(loan, "FL0412");
      nameValueCollection.Add("FL0412", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0418"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0417"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0413") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0417"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0413", str8);
      string str9 = JS.GetStr(loan, "FL0502");
      nameValueCollection.Add("FL0502", str9);
      string str10 = JS.GetStr(loan, "FL0503");
      nameValueCollection.Add("FL0503", str10);
      string str11 = JS.GetStr(loan, "FL0504");
      nameValueCollection.Add("FL0504", str11);
      string str12 = JS.GetStr(loan, "FL0505") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0506"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0506") + " " + JS.GetStr(loan, "FL0507");
      nameValueCollection.Add("FL0505_FL0506_FL0507", str12);
      string str13 = JS.GetStr(loan, "FL0510");
      nameValueCollection.Add("FL0510", str13);
      string str14 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0518"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0517"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0511") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0517"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0511", str14);
      string str15 = JS.GetStr(loan, "FL0512");
      nameValueCollection.Add("FL0512", str15);
      string str16 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0518"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0517"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0513") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0517"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0513", str16);
      string str17 = JS.GetStr(loan, "FL0602");
      nameValueCollection.Add("FL0602", str17);
      string str18 = JS.GetStr(loan, "FL0603");
      nameValueCollection.Add("FL0603", str18);
      string str19 = JS.GetStr(loan, "FL0604");
      nameValueCollection.Add("FL0604", str19);
      string str20 = JS.GetStr(loan, "FL0605") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0606"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0606") + " " + JS.GetStr(loan, "FL0607");
      nameValueCollection.Add("FL0605_FL0606_FL0607", str20);
      string str21 = JS.GetStr(loan, "FL0610");
      nameValueCollection.Add("FL0610", str21);
      string str22 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0618"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0617"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0611") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0617"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0611", str22);
      string str23 = JS.GetStr(loan, "FL0612");
      nameValueCollection.Add("FL0612", str23);
      string str24 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0618"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0617"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0613") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0617"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0613", str24);
      string str25 = JS.GetStr(loan, "FL0702");
      nameValueCollection.Add("FL0702", str25);
      string str26 = JS.GetStr(loan, "FL0703");
      nameValueCollection.Add("FL0703", str26);
      string str27 = JS.GetStr(loan, "FL0704");
      nameValueCollection.Add("FL0704", str27);
      string str28 = JS.GetStr(loan, "FL0705") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0706"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0706") + " " + JS.GetStr(loan, "FL0707");
      nameValueCollection.Add("FL0705_FL0706_FL0707", str28);
      string str29 = JS.GetStr(loan, "FL0710");
      nameValueCollection.Add("FL0710", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0718"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0717"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0711") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0717"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0711", str30);
      string str31 = JS.GetStr(loan, "FL0712");
      nameValueCollection.Add("FL0712", str31);
      string str32 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0718"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0717"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0713") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0717"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0713", str32);
      string str33 = JS.GetStr(loan, "271");
      nameValueCollection.Add("271", str33);
      string str34 = JS.GetStr(loan, "272");
      nameValueCollection.Add("272", str34);
      string str35 = JS.GetStr(loan, "255");
      nameValueCollection.Add("255", str35);
      string str36 = JS.GetStr(loan, "256");
      nameValueCollection.Add("256", str36);
      string str37 = JS.GetStr(loan, "1058");
      nameValueCollection.Add("1058", str37);
      string str38 = JS.GetStr(loan, "1062");
      nameValueCollection.Add("1062", str38);
      string str39 = JS.GetStr(loan, "350");
      nameValueCollection.Add("350", str39);
      string str40 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "734"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "734"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "734")), (byte) 18, 0));
      nameValueCollection.Add("734", str40);
      string str41 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "733"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "733"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "733")), (byte) 18, 0));
      nameValueCollection.Add("733", str41);
      string str42 = JS.GetStr(loan, "1604");
      nameValueCollection.Add("1604", str42);
      string str43 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1605"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1605"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1605")), (byte) 18, 0));
      nameValueCollection.Add("1605", str43);
      string str44 = JS.GetStr(loan, "1606");
      nameValueCollection.Add("1606", str44);
      string str45 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1607"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1607"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1607")), (byte) 18, 0));
      nameValueCollection.Add("1607", str45);
      string str46 = JS.GetStr(loan, "1608");
      nameValueCollection.Add("1608", str46);
      string str47 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1609"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1609"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1609")), (byte) 18, 0));
      nameValueCollection.Add("1609", str47);
      string str48 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "303"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "303"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "303")), (byte) 18, 0));
      nameValueCollection.Add("303", str48);
      string str49 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "210"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "210"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "210")), (byte) 18, 0));
      nameValueCollection.Add("210", str49);
      string str50 = JS.GetStr(loan, "915");
      nameValueCollection.Add("915", str50);
      string str51 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "919"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "919"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "919")), (byte) 18, 0));
      nameValueCollection.Add("919", str51);
      string str52 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "212"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "212"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "212")), (byte) 18, 0));
      nameValueCollection.Add("212", str52);
      string str53 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "213"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "213"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "213")), (byte) 18, 0));
      nameValueCollection.Add("213", str53);
      string str54 = JS.GetStr(loan, "214");
      nameValueCollection.Add("214", str54);
      string str55 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "215"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "215"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "215")), (byte) 18, 0));
      nameValueCollection.Add("215", str55);
      string str56 = JS.GetStr(loan, "216");
      nameValueCollection.Add("216", str56);
      string str57 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "217"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "217"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "217")), (byte) 18, 0));
      nameValueCollection.Add("217", str57);
      string str58 = JS.GetStr(loan, "1717");
      nameValueCollection.Add("1717", str58);
      string str59 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1718"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1718"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1718")), (byte) 18, 0));
      nameValueCollection.Add("1718", str59);
      string str60 = JS.GetStr(loan, "221");
      nameValueCollection.Add("221", str60);
      string str61 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "222"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "222"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "222")), (byte) 18, 0));
      nameValueCollection.Add("222", str61);
      string str62 = JS.GetStr(loan, "223");
      nameValueCollection.Add("223", str62);
      string str63 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "224"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "224"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "224")), (byte) 18, 0));
      nameValueCollection.Add("224", str63);
      string str64 = JS.GetStr(loan, "1052");
      nameValueCollection.Add("1052", str64);
      string str65 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1053"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1053"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1053")), (byte) 18, 0));
      nameValueCollection.Add("1053", str65);
      string str66 = JS.GetStr(loan, "1054");
      nameValueCollection.Add("1054", str66);
      string str67 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1055"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1055"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1055")), (byte) 18, 0));
      nameValueCollection.Add("1055", str67);
      string str68 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "732"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "732"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "732")), (byte) 18, 0));
      nameValueCollection.Add("732", str68);
      string str69 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315", str69);
      string str70 = JS.GetStr(loan, "FM0104") + "\r\n" + JS.GetStr(loan, "FM0106") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0107"), "", false) != 0, ", ") + JS.GetStr(loan, "FM0107") + " " + JS.GetStr(loan, "FM0108");
      nameValueCollection.Add("274", str70);
      string str71 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "Sold", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "PendingSale", false) == 0, "PS") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "RetainForRental", false) == 0, "R") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "RetainForPrimaryOrSecondaryResidence", false) == 0, "H");
      nameValueCollection.Add("275", str71);
      string str72 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "SingleFamily", false) == 0, "SFR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Condominium", false) == 0, "CONDO") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Townhouse", false) == 0, "TOWN") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Cooperative", false) == 0, "COOP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "TwoToFourUnitProperty", false) == 0, "2-4") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "MultifamilyMoreThanFourUnits", false) == 0, "MULTI") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "ManufacturedMobileHome", false) == 0, "MOBIL") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "CommercialNonResidential", false) == 0, "COMNR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "MixedUseResidential", false) == 0, "MIXED") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Farm", false) == 0, "FARM") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "HomeAndBusinessCombined", false) == 0, "COMR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Land", false) == 0, "LAND");
      nameValueCollection.Add("276", str72);
      string str73 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0119"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0119"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0119")), (byte) 18, 0));
      nameValueCollection.Add("277", str73);
      string str74 = JS.GetStr(loan, "FM0117");
      nameValueCollection.Add("278", str74);
      string str75 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0120"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0120"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0120")), (byte) 18, 0));
      nameValueCollection.Add("279", str75);
      string str76 = JS.GetStr(loan, "FM0116");
      nameValueCollection.Add("280", str76);
      string str77 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0141"), "SecondHome", false) == 0, "", Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0132"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0132"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0132")), (byte) 16, 0)));
      nameValueCollection.Add("916", str77);
      string str78 = Jed.BF((Jed.S2N(JS.GetStr(loan, "FM0121")) != 0.0 | Operators.CompareString(JS.GetStr(loan, "FM0121"), "", false) == 0) & Operators.CompareString(JS.GetStr(loan, "FM0117"), "", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0121")), (byte) 18, 0), JS.GetStr(loan, "FM0121"));
      nameValueCollection.Add("281", str78);
      string str79 = JS.GetStr(loan, "FM0204") + "\r\n" + JS.GetStr(loan, "FM0206") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0207"), "", false) != 0, ", ") + JS.GetStr(loan, "FM0207") + " " + JS.GetStr(loan, "FM0208");
      nameValueCollection.Add("282", str79);
      string str80 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "Sold", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "PendingSale", false) == 0, "PS") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "RetainForRental", false) == 0, "R") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "RetainForPrimaryOrSecondaryResidence", false) == 0, "H");
      nameValueCollection.Add("283", str80);
      string str81 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "SingleFamily", false) == 0, "SFR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Condominium", false) == 0, "CONDO") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Townhouse", false) == 0, "TOWN") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Cooperative", false) == 0, "COOP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "TwoToFourUnitProperty", false) == 0, "2-4") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "MultifamilyMoreThanFourUnits", false) == 0, "MULTI") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "ManufacturedMobileHome", false) == 0, "MOBIL") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "CommercialNonResidential", false) == 0, "COMNR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "MixedUseResidential", false) == 0, "MIXED") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Farm", false) == 0, "FARM") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "HomeAndBusinessCombined", false) == 0, "COMR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Land", false) == 0, "LAND");
      nameValueCollection.Add("284", str81);
      string str82 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0219"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0219"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0219")), (byte) 18, 0));
      nameValueCollection.Add("285", str82);
      string str83 = JS.GetStr(loan, "FM0217");
      nameValueCollection.Add("286", str83);
      string str84 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0220"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0220"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0220")), (byte) 18, 0));
      nameValueCollection.Add("287", str84);
      string str85 = JS.GetStr(loan, "FM0216");
      nameValueCollection.Add("288", str85);
      string str86 = Jed.BF((Jed.S2N(JS.GetStr(loan, "FM0221")) != 0.0 | Operators.CompareString(JS.GetStr(loan, "FM0221"), "", false) == 0) & Operators.CompareString(JS.GetStr(loan, "FM0217"), "", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0221")), (byte) 18, 0), JS.GetStr(loan, "FM0221"));
      nameValueCollection.Add("289", str86);
      string str87 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0241"), "SecondHome", false) == 0, "", Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0232"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0232"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0232")), (byte) 16, 0)));
      nameValueCollection.Add("917", str87);
      string str88 = JS.GetStr(loan, "FM0304") + "\r\n" + JS.GetStr(loan, "FM0306") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0307"), "", false) != 0, ", ") + JS.GetStr(loan, "FM0307") + " " + JS.GetStr(loan, "FM0308");
      nameValueCollection.Add("290", str88);
      string str89 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "Sold", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "PendingSale", false) == 0, "PS") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "RetainForRental", false) == 0, "R") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "RetainForPrimaryOrSecondaryResidence", false) == 0, "H");
      nameValueCollection.Add("291", str89);
      string str90 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "SingleFamily", false) == 0, "SFR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Condominium", false) == 0, "CONDO") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Townhouse", false) == 0, "TOWN") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Cooperative", false) == 0, "COOP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "TwoToFourUnitProperty", false) == 0, "2-4") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "MultifamilyMoreThanFourUnits", false) == 0, "MULTI") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "ManufacturedMobileHome", false) == 0, "MOBIL") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "CommercialNonResidential", false) == 0, "COMNR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "MixedUseResidential", false) == 0, "MIXED") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Farm", false) == 0, "FARM") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "HomeAndBusinessCombined", false) == 0, "COMR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Land", false) == 0, "LAND");
      nameValueCollection.Add("292", str90);
      string str91 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0319"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0319"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0319")), (byte) 18, 0));
      nameValueCollection.Add("293", str91);
      string str92 = JS.GetStr(loan, "FM0317");
      nameValueCollection.Add("294", str92);
      string str93 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0320"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0320"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0320")), (byte) 18, 0));
      nameValueCollection.Add("295", str93);
      string str94 = JS.GetStr(loan, "FM0316");
      nameValueCollection.Add("296", str94);
      string str95 = Jed.BF((Jed.S2N(JS.GetStr(loan, "FM0321")) != 0.0 | Operators.CompareString(JS.GetStr(loan, "FM0321"), "", false) == 0) & Operators.CompareString(JS.GetStr(loan, "FM0317"), "", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0321")), (byte) 18, 0), JS.GetStr(loan, "FM0321"));
      nameValueCollection.Add("297", str95);
      string str96 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0341"), "SecondHome", false) == 0, "", Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0332"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0332"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0332")), (byte) 16, 0)));
      nameValueCollection.Add("918", str96);
      string str97 = "";
      nameValueCollection.Add("VOMCONT", str97);
      string str98 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "919"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "919"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "919")), (byte) 18, 0));
      nameValueCollection.Add("919_A", str98);
      string str99 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "920"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "920"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "920")), (byte) 18, 0));
      nameValueCollection.Add("920", str99);
      string str100 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "921"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "921"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "921")), (byte) 18, 0));
      nameValueCollection.Add("921", str100);
      string str101 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "922"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "922"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "922")), (byte) 18, 0));
      nameValueCollection.Add("922", str101);
      string str102 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "923"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "923"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "923")), (byte) 18, 0));
      nameValueCollection.Add("923", str102);
      string str103 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "924"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "924"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "924")), (byte) 16, 0));
      nameValueCollection.Add("924", str103);
      string str104 = JS.GetStr(loan, "206");
      nameValueCollection.Add("206", str104);
      string str105 = JS.GetStr(loan, "203");
      nameValueCollection.Add("203", str105);
      string str106 = JS.GetStr(loan, "1734");
      nameValueCollection.Add("1734", str106);
      string str107 = JS.GetStr(loan, "1736");
      nameValueCollection.Add("1736", str107);
      string str108 = JS.GetStr(loan, "1735");
      nameValueCollection.Add("1735", str108);
      string str109 = JS.GetStr(loan, "1737");
      nameValueCollection.Add("1737", str109);
      string str110 = JS.GetStr(loan, "136");
      nameValueCollection.Add("136", str110);
      string str111 = JS.GetStr(loan, "967");
      nameValueCollection.Add("967", str111);
      string str112 = JS.GetStr(loan, "968");
      nameValueCollection.Add("968", str112);
      string str113 = JS.GetStr(loan, "1092");
      nameValueCollection.Add("1092", str113);
      string str114 = JS.GetStr(loan, "138");
      nameValueCollection.Add("138", str114);
      string str115 = JS.GetStr(loan, "137");
      nameValueCollection.Add("137", str115);
      string str116 = JS.GetStr(loan, "969");
      nameValueCollection.Add("969", str116);
      string str117 = JS.GetStr(loan, "1093");
      nameValueCollection.Add("1093", str117);
      string str118 = JS.GetStr(loan, "1073");
      nameValueCollection.Add("1073", str118);
      string str119 = JS.GetStr(loan, "140");
      nameValueCollection.Add("140", str119);
      string str120 = JS.GetStr(loan, "143");
      nameValueCollection.Add("143", str120);
      string str121 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "169"), "Y", false) == 0, "X");
      nameValueCollection.Add("169_Yes", str121);
      string str122 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "169"), "N", false) == 0, "X");
      nameValueCollection.Add("169_No", str122);
      string str123 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "175"), "Y", false) == 0, "X");
      nameValueCollection.Add("175_Yes", str123);
      string str124 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "175"), "N", false) == 0, "X");
      nameValueCollection.Add("175_No", str124);
      string str125 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "265"), "Y", false) == 0, "X");
      nameValueCollection.Add("265_Yes", str125);
      string str126 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "265"), "N", false) == 0, "X");
      nameValueCollection.Add("265_No", str126);
      string str127 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "266"), "Y", false) == 0, "X");
      nameValueCollection.Add("266_Yes", str127);
      string str128 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "266"), "N", false) == 0, "X");
      nameValueCollection.Add("266_No", str128);
      string str129 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "170"), "Y", false) == 0, "X");
      nameValueCollection.Add("170_Yes", str129);
      string str130 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "170"), "N", false) == 0, "X");
      nameValueCollection.Add("170_No", str130);
      string str131 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "176"), "Y", false) == 0, "X");
      nameValueCollection.Add("176_Yes", str131);
      string str132 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "176"), "N", false) == 0, "X");
      nameValueCollection.Add("176_No", str132);
      string str133 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "172"), "Y", false) == 0, "X");
      nameValueCollection.Add("172_Yes", str133);
      string str134 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "172"), "N", false) == 0, "X");
      nameValueCollection.Add("172_No", str134);
      string str135 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "178"), "Y", false) == 0, "X");
      nameValueCollection.Add("178_Yes", str135);
      string str136 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "178"), "N", false) == 0, "X");
      nameValueCollection.Add("178_No", str136);
      string str137 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1057"), "Y", false) == 0, "X");
      nameValueCollection.Add("1057_Yes", str137);
      string str138 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1057"), "N", false) == 0, "X");
      nameValueCollection.Add("1057_No", str138);
      string str139 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1197"), "Y", false) == 0, "X");
      nameValueCollection.Add("1197_Yes", str139);
      string str140 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1197"), "N", false) == 0, "X");
      nameValueCollection.Add("1197_No", str140);
      return nameValueCollection;
    }
  }
}
