// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._1003PG4_SPANISHCLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _1003PG4_SPANISHCLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315", str1);
      string str2 = JS.GetStr(loan, "1604");
      nameValueCollection.Add("1604", str2);
      string str3 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1605"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1605"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1605")), (byte) 18, 0));
      nameValueCollection.Add("1605", str3);
      string str4 = JS.GetStr(loan, "1606");
      nameValueCollection.Add("1606", str4);
      string str5 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1607"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1607"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1607")), (byte) 18, 0));
      nameValueCollection.Add("1607", str5);
      string str6 = JS.GetStr(loan, "1608");
      nameValueCollection.Add("1608", str6);
      string str7 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1609"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1609"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1609")), (byte) 18, 0));
      nameValueCollection.Add("1609", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "303"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "303"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "303")), (byte) 18, 0));
      nameValueCollection.Add("303", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "210"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "210"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "210")), (byte) 18, 0));
      nameValueCollection.Add("210", str9);
      string str10 = JS.GetStr(loan, "915");
      nameValueCollection.Add("915", str10);
      string str11 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "919"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "919"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "919")), (byte) 18, 0));
      nameValueCollection.Add("919", str11);
      string str12 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "212"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "212"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "212")), (byte) 18, 0));
      nameValueCollection.Add("212", str12);
      string str13 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "213"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "213"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "213")), (byte) 18, 0));
      nameValueCollection.Add("213", str13);
      string str14 = JS.GetStr(loan, "214");
      nameValueCollection.Add("214", str14);
      string str15 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "215"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "215"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "215")), (byte) 18, 0));
      nameValueCollection.Add("215", str15);
      string str16 = JS.GetStr(loan, "216");
      nameValueCollection.Add("216", str16);
      string str17 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "217"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "217"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "217")), (byte) 18, 0));
      nameValueCollection.Add("217", str17);
      string str18 = JS.GetStr(loan, "1717");
      nameValueCollection.Add("1717", str18);
      string str19 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1718"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1718"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1718")), (byte) 18, 0));
      nameValueCollection.Add("1718", str19);
      string str20 = JS.GetStr(loan, "221");
      nameValueCollection.Add("221", str20);
      string str21 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "222"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "222"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "222")), (byte) 18, 0));
      nameValueCollection.Add("222", str21);
      string str22 = JS.GetStr(loan, "223");
      nameValueCollection.Add("223", str22);
      string str23 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "224"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "224"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "224")), (byte) 18, 0));
      nameValueCollection.Add("224", str23);
      string str24 = JS.GetStr(loan, "1052");
      nameValueCollection.Add("1052", str24);
      string str25 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1053"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1053"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1053")), (byte) 18, 0));
      nameValueCollection.Add("1053", str25);
      string str26 = JS.GetStr(loan, "1054");
      nameValueCollection.Add("1054", str26);
      string str27 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1055"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "1055"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1055")), (byte) 18, 0));
      nameValueCollection.Add("1055", str27);
      string str28 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "732"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "732"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "732")), (byte) 18, 0));
      nameValueCollection.Add("732", str28);
      string str29 = JS.GetStr(loan, "FL0102");
      nameValueCollection.Add("FL0102", str29);
      string str30 = JS.GetStr(loan, "FL0103");
      nameValueCollection.Add("FL0103", str30);
      string str31 = JS.GetStr(loan, "FL0104");
      nameValueCollection.Add("FL0104", str31);
      string str32 = JS.GetStr(loan, "FL0105") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0106"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0106") + " " + JS.GetStr(loan, "FL0107");
      nameValueCollection.Add("FL0105_FL0106_FL0107", str32);
      string str33 = JS.GetStr(loan, "FL0110");
      nameValueCollection.Add("FL0110", str33);
      string str34 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0118"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0117"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0111") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0117"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0111", str34);
      string str35 = JS.GetStr(loan, "FL0112");
      nameValueCollection.Add("FL0112", str35);
      string str36 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0118"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0117"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0113") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0117"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0113", str36);
      string str37 = JS.GetStr(loan, "FL0202");
      nameValueCollection.Add("FL0202", str37);
      string str38 = JS.GetStr(loan, "FL0203");
      nameValueCollection.Add("FL0203", str38);
      string str39 = JS.GetStr(loan, "FL0204");
      nameValueCollection.Add("FL0204", str39);
      string str40 = JS.GetStr(loan, "FL0205") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0206"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0206") + " " + JS.GetStr(loan, "FL0207");
      nameValueCollection.Add("FL0205_FL0206_FL0207", str40);
      string str41 = JS.GetStr(loan, "FL0210");
      nameValueCollection.Add("FL0210", str41);
      string str42 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0218"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0217"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0211") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0217"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0211", str42);
      string str43 = JS.GetStr(loan, "FL0212");
      nameValueCollection.Add("FL0212", str43);
      string str44 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0218"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0217"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0213") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0217"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0213", str44);
      string str45 = JS.GetStr(loan, "FL0302");
      nameValueCollection.Add("FL0302", str45);
      string str46 = JS.GetStr(loan, "FL0303");
      nameValueCollection.Add("FL0303", str46);
      string str47 = JS.GetStr(loan, "FL0304");
      nameValueCollection.Add("FL0304", str47);
      string str48 = JS.GetStr(loan, "FL0305") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0306"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0306") + " " + JS.GetStr(loan, "FL0307");
      nameValueCollection.Add("FL0305_FL0306_FL0307", str48);
      string str49 = JS.GetStr(loan, "FL0310");
      nameValueCollection.Add("FL0310", str49);
      string str50 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0318"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0317"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0311") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0317"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0311", str50);
      string str51 = JS.GetStr(loan, "FL0312");
      nameValueCollection.Add("FL0312", str51);
      string str52 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0318"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0317"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0313") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0317"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0313", str52);
      string str53 = JS.GetStr(loan, "FL0402");
      nameValueCollection.Add("FL0402", str53);
      string str54 = JS.GetStr(loan, "FL0403");
      nameValueCollection.Add("FL0403", str54);
      string str55 = JS.GetStr(loan, "FL0404");
      nameValueCollection.Add("FL0404", str55);
      string str56 = JS.GetStr(loan, "FL0405") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0406"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0406") + " " + JS.GetStr(loan, "FL0407");
      nameValueCollection.Add("FL0405_FL0406_FL0407", str56);
      string str57 = JS.GetStr(loan, "FL0410");
      nameValueCollection.Add("FL0410", str57);
      string str58 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0418"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0417"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0411") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0417"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0411", str58);
      string str59 = JS.GetStr(loan, "FL0412");
      nameValueCollection.Add("FL0412", str59);
      string str60 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0418"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0417"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0413") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0417"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0413", str60);
      string str61 = JS.GetStr(loan, "FL0502");
      nameValueCollection.Add("FL0502", str61);
      string str62 = JS.GetStr(loan, "FL0503");
      nameValueCollection.Add("FL0503", str62);
      string str63 = JS.GetStr(loan, "FL0504");
      nameValueCollection.Add("FL0504", str63);
      string str64 = JS.GetStr(loan, "FL0505") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0506"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0506") + " " + JS.GetStr(loan, "FL0507");
      nameValueCollection.Add("FL0505_FL0506_FL0507", str64);
      string str65 = JS.GetStr(loan, "FL0510");
      nameValueCollection.Add("FL0510", str65);
      string str66 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0518"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0517"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0511") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0517"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0511", str66);
      string str67 = JS.GetStr(loan, "FL0512");
      nameValueCollection.Add("FL0512", str67);
      string str68 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0518"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0517"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0513") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0517"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0513", str68);
      string str69 = JS.GetStr(loan, "FL0602");
      nameValueCollection.Add("FL0602", str69);
      string str70 = JS.GetStr(loan, "FL0603");
      nameValueCollection.Add("FL0603", str70);
      string str71 = JS.GetStr(loan, "FL0604");
      nameValueCollection.Add("FL0604", str71);
      string str72 = JS.GetStr(loan, "FL0605") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0606"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0606") + " " + JS.GetStr(loan, "FL0607");
      nameValueCollection.Add("FL0605_FL0606_FL0607", str72);
      string str73 = JS.GetStr(loan, "FL0610");
      nameValueCollection.Add("FL0610", str73);
      string str74 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0618"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0617"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0611") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0617"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0611", str74);
      string str75 = JS.GetStr(loan, "FL0612");
      nameValueCollection.Add("FL0612", str75);
      string str76 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0618"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0617"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0613") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0617"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0613", str76);
      string str77 = JS.GetStr(loan, "FL0702");
      nameValueCollection.Add("FL0702", str77);
      string str78 = JS.GetStr(loan, "FL0703");
      nameValueCollection.Add("FL0703", str78);
      string str79 = JS.GetStr(loan, "FL0704");
      nameValueCollection.Add("FL0704", str79);
      string str80 = JS.GetStr(loan, "FL0705") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0706"), "", false) != 0, ", ") + JS.GetStr(loan, "FL0706") + " " + JS.GetStr(loan, "FL0707");
      nameValueCollection.Add("FL0705_FL0706_FL0707", str80);
      string str81 = JS.GetStr(loan, "FL0710");
      nameValueCollection.Add("FL0710", str81);
      string str82 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0718"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0717"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0711") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0717"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0711", str82);
      string str83 = JS.GetStr(loan, "FL0712");
      nameValueCollection.Add("FL0712", str83);
      string str84 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0718"), "Y", false) == 0, "*") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0717"), "Y", false) == 0, "(") + JS.GetStr(loan, "FL0713") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FL0717"), "Y", false) == 0, ")");
      nameValueCollection.Add("FL0713", str84);
      string str85 = JS.GetStr(loan, "271");
      nameValueCollection.Add("271", str85);
      string str86 = JS.GetStr(loan, "272");
      nameValueCollection.Add("272", str86);
      string str87 = JS.GetStr(loan, "255");
      nameValueCollection.Add("255", str87);
      string str88 = JS.GetStr(loan, "256");
      nameValueCollection.Add("256", str88);
      string str89 = JS.GetStr(loan, "1058");
      nameValueCollection.Add("1058", str89);
      string str90 = JS.GetStr(loan, "1062");
      nameValueCollection.Add("1062", str90);
      string str91 = JS.GetStr(loan, "350");
      nameValueCollection.Add("350", str91);
      string str92 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "734"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "734"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "734")), (byte) 18, 0));
      nameValueCollection.Add("734", str92);
      string str93 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "733"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "733"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "733")), (byte) 18, 0));
      nameValueCollection.Add("733", str93);
      string str94 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37_a", str94);
      return nameValueCollection;
    }
  }
}
