// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._1003_P1CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _1003_P1CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315", str1);
      string str2 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "307"), "Y", false) == 0, " X");
      nameValueCollection.Add("307", str2);
      string str3 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "35"), "Y", false) == 0, " X");
      nameValueCollection.Add("35", str3);
      string str4 = JS.GetStr(loan, "305");
      nameValueCollection.Add("305", str4);
      string str5 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "VA", false) == 0, " X");
      nameValueCollection.Add("1172_VA", str5);
      string str6 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "FHA", false) == 0, " X");
      nameValueCollection.Add("1172_FHA", str6);
      string str7 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "Other", false) == 0, " X");
      nameValueCollection.Add("1172_Oth", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "Conventional", false) == 0, " X");
      nameValueCollection.Add("1172_Conv", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "FarmersHomeAdministration", false) == 0, " X");
      nameValueCollection.Add("1172_FmHA", str9);
      string str10 = JS.GetStr(loan, "1063");
      nameValueCollection.Add("1063", str10);
      string str11 = JS.GetStr(loan, "1040");
      nameValueCollection.Add("1040", str11);
      string str12 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "Fixed", false) == 0, " X");
      nameValueCollection.Add("608_Fixed", str12);
      string str13 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "GraduatedPaymentMortgage", false) == 0, " X");
      nameValueCollection.Add("608_GPM", str13);
      string str14 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "AdjustableRate", false) == 0, "  X");
      nameValueCollection.Add("608_ARM", str14);
      string str15 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "OtherAmortizationType", false) == 0, " X");
      nameValueCollection.Add("608_Other", str15);
      string str16 = JS.GetStr(loan, "995");
      nameValueCollection.Add("995", str16);
      string str17 = JS.GetStr(loan, "994");
      nameValueCollection.Add("994", str17);
      string str18 = JS.GetStr(loan, "11") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "12"), "", false) != 0, ", ") + JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "13"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15") + " County: " + JS.GetStr(loan, "13");
      nameValueCollection.Add("11_12", str18);
      string str19 = JS.GetStr(loan, "18");
      nameValueCollection.Add("18", str19);
      string str20 = JS.GetStr(loan, "16");
      nameValueCollection.Add("16", str20);
      string str21 = JS.GetStr(loan, "17");
      nameValueCollection.Add("17", str21);
      string str22 = JS.GetStr(loan, "1824");
      nameValueCollection.Add("1824", str22);
      string str23 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0, " X");
      nameValueCollection.Add("19_Const", str23);
      string str24 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Cash-Out Refinance", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, " X");
      nameValueCollection.Add("19_Ref", str24);
      string str25 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, " X");
      nameValueCollection.Add("19_ConstP", str25);
      string str26 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Purchase", false) == 0, " X");
      nameValueCollection.Add("19_Pur", str26);
      string str27 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Other", false) == 0, "  X");
      nameValueCollection.Add("19_Other", str27);
      string str28 = JS.GetStr(loan, "9");
      nameValueCollection.Add("9", str28);
      string str29 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "Investor", false) == 0, " X");
      nameValueCollection.Add("190_Inv", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "PrimaryResidence", false) == 0, " X");
      nameValueCollection.Add("190_Prim", str30);
      string str31 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "SecondHome", false) == 0, " X");
      nameValueCollection.Add("190_Sec", str31);
      string str32 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "20"));
      nameValueCollection.Add("20", str32);
      string str33 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "21"));
      nameValueCollection.Add("21", str33);
      string str34 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "10"));
      nameValueCollection.Add("10", str34);
      string str35 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "22"));
      nameValueCollection.Add("22", str35);
      string str36 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "23"));
      nameValueCollection.Add("23", str36);
      string str37 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "1074"));
      nameValueCollection.Add("1074", str37);
      string str38 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Cash-Out Refinance", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, JS.GetStr(loan, "26"));
      nameValueCollection.Add("26", str38);
      string str39 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Cash-Out Refinance", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, JS.GetStr(loan, "25"));
      nameValueCollection.Add("25", str39);
      string str40 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Cash-Out Refinance", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, JS.GetStr(loan, "24"));
      nameValueCollection.Add("24", str40);
      string str41 = JS.GetStr(loan, "4");
      nameValueCollection.Add("4", str41);
      string str42 = JS.GetStr(loan, "3");
      nameValueCollection.Add("3", str42);
      string str43 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str43);
      string str44 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "CashOutDebtConsolidation", false) == 0, "Cash-out Debt Consolidation", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "CashOutHomeImprovement", false) == 0, "Cash-Out Home Improvement", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "CashOutLimited", false) == 0, "Cash-Out Limited", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "CashOutOther", false) == 0, "Cash-Out Other", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "ChangeInRateTerm", false) == 0, "No Cash-Out Rate/Term", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "NoCashOutOther", false) == 0, "No Cash-Out Other", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "NoCashOutFHAStreamlinedRefinance", false) == 0, "No Cash-Out FHA Streamlined", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "NoCashOutFREOwnedRefinance", false) == 0, "No Cash-Out Freddie Owned", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "NoCashOutStreamlinedRefinance", false) == 0, "No Cash-Out Streamlined", JS.GetStr(loan, "299"))))))))));
      nameValueCollection.Add("299_27", str44);
      string str45 = JS.GetStr(loan, "205");
      nameValueCollection.Add("205", str45);
      string str46 = JS.GetStr(loan, "29");
      nameValueCollection.Add("29", str46);
      string str47 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "30"), "Made", false) == 0, " X");
      nameValueCollection.Add("30_made", str47);
      string str48 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "30"), "ToBeMade", false) == 0, " X");
      nameValueCollection.Add("30_2bemade", str48);
      string str49 = JS.GetStr(loan, "31") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1602"), "", false) != 0, ", ") + JS.GetStr(loan, "1602");
      nameValueCollection.Add("31", str49);
      string str50 = JS.GetStr(loan, "33");
      nameValueCollection.Add("33", str50);
      string str51 = JS.GetStr(loan, "34");
      nameValueCollection.Add("34", str51);
      string str52 = JS.GetStr(loan, "191");
      nameValueCollection.Add("191", str52);
      string str53 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1066"), "FeeSimple", false) == 0, " X");
      nameValueCollection.Add("1066_Simple", str53);
      string str54 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1066"), "Leasehold", false) == 0, " X");
      nameValueCollection.Add("1066_Leasehold", str54);
      string str55 = JS.GetStr(loan, "1034");
      nameValueCollection.Add("1034", str55);
      string str56 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str56);
      string str57 = JS.GetStr(loan, "66");
      nameValueCollection.Add("66", str57);
      string str58 = JS.GetStr(loan, "65");
      nameValueCollection.Add("65", str58);
      string str59 = JS.GetStr(loan, "39");
      nameValueCollection.Add("39", str59);
      string str60 = JS.GetStr(loan, "38");
      nameValueCollection.Add("38", str60);
      string str61 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "52"), "Married", false) == 0, " X");
      nameValueCollection.Add("52_M", str61);
      string str62 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "52"), "Seperated", false) == 0, " X");
      nameValueCollection.Add("52_S", str62);
      string str63 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "52"), "Unmarried", false) == 0, " X");
      nameValueCollection.Add("52_U", str63);
      string str64 = JS.GetStr(loan, "53");
      nameValueCollection.Add("53", str64);
      string str65 = JS.GetStr(loan, "54");
      nameValueCollection.Add("54", str65);
      string str66 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0115"), "Own", false) == 0, " X");
      nameValueCollection.Add("FR0115_Own", str66);
      string str67 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0115"), "Rent", false) == 0, " X");
      nameValueCollection.Add("FR0115_Rent", str67);
      string str68 = "    " + JS.GetStr(loan, "FR0112") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0124"), "", false) != 0, ".") + JS.GetStr(loan, "FR0124");
      nameValueCollection.Add("FR0112", str68);
      string str69 = JS.GetStr(loan, "FR0104");
      nameValueCollection.Add("FR0104", str69);
      string str70 = JS.GetStr(loan, "FR0106") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0107"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0107") + " " + JS.GetStr(loan, "FR0108");
      nameValueCollection.Add("FR0106_FR0107_FR0108", str70);
      string str71 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0315"), "Own", false) == 0, " X");
      nameValueCollection.Add("FR0315_Own", str71);
      string str72 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0315"), "Rent", false) == 0, " X");
      nameValueCollection.Add("FR0315_Rent", str72);
      string str73 = Jed.NF(Jed.Num(JS.GetNum(loan, "FR0312")) + Jed.Num(JS.GetNum(loan, "FR0324")) / 12.0, (byte) 2, 0);
      nameValueCollection.Add("FR0312", str73);
      string str74 = JS.GetStr(loan, "FR0304");
      nameValueCollection.Add("FR0304", str74);
      string str75 = JS.GetStr(loan, "FR0306") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0307"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0307") + " " + JS.GetStr(loan, "FR0308");
      nameValueCollection.Add("FR0306_FR0307_FR0308", str75);
      string str76 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0515"), "Own", false) == 0, " X");
      nameValueCollection.Add("FR0515_Own", str76);
      string str77 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0515"), "Rent", false) == 0, " X");
      nameValueCollection.Add("FR0515_Rent", str77);
      string str78 = Jed.NF(Jed.Num(JS.GetNum(loan, "FR0512")) + Jed.Num(JS.GetNum(loan, "FR0524")) / 12.0, (byte) 2, 0);
      nameValueCollection.Add("FR0512", str78);
      string str79 = JS.GetStr(loan, "FR0504");
      nameValueCollection.Add("FR0504", str79);
      string str80 = JS.GetStr(loan, "FR0506") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0507"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0507") + " " + JS.GetStr(loan, "FR0508");
      nameValueCollection.Add("FR0506_FR0507_FR0508", str80);
      string str81 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69", str81);
      string str82 = JS.GetStr(loan, "97");
      nameValueCollection.Add("97", str82);
      string str83 = JS.GetStr(loan, "98");
      nameValueCollection.Add("98", str83);
      string str84 = JS.GetStr(loan, "70");
      nameValueCollection.Add("70", str84);
      string str85 = JS.GetStr(loan, "71");
      nameValueCollection.Add("71", str85);
      string str86 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "84"), "Married", false) == 0, " X");
      nameValueCollection.Add("84_M", str86);
      string str87 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "84"), "Seperated", false) == 0, " X");
      nameValueCollection.Add("84_S", str87);
      string str88 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "84"), "Unmarried", false) == 0, " X");
      nameValueCollection.Add("84_U", str88);
      string str89 = JS.GetStr(loan, "85");
      nameValueCollection.Add("85", str89);
      string str90 = JS.GetStr(loan, "86");
      nameValueCollection.Add("86", str90);
      string str91 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0215"), "Own", false) == 0, " X");
      nameValueCollection.Add("FR0215_Own", str91);
      string str92 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0215"), "Rent", false) == 0, " X");
      nameValueCollection.Add("FR0215_Rent", str92);
      string str93 = "    " + JS.GetStr(loan, "FR0212") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0224"), "", false) != 0, ".") + JS.GetStr(loan, "FR0224");
      nameValueCollection.Add("FR0212", str93);
      string str94 = JS.GetStr(loan, "FR0204");
      nameValueCollection.Add("FR0204", str94);
      string str95 = JS.GetStr(loan, "FR0206") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0207"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0207") + " " + JS.GetStr(loan, "FR0208");
      nameValueCollection.Add("FR0206_FR0207_FR0208", str95);
      string str96 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0415"), "Own", false) == 0, " X");
      nameValueCollection.Add("FR0415_Own", str96);
      string str97 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0415"), "Rent", false) == 0, " X");
      nameValueCollection.Add("FR0415_Rent", str97);
      string str98 = Jed.NF(Jed.Num(JS.GetNum(loan, "FR0412")) + Jed.Num(JS.GetNum(loan, "FR0424")) / 12.0, (byte) 2, 0);
      nameValueCollection.Add("FR0412", str98);
      string str99 = JS.GetStr(loan, "FR0404");
      nameValueCollection.Add("FR0404", str99);
      string str100 = JS.GetStr(loan, "FR0406") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0407"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0407") + " " + JS.GetStr(loan, "FR0408");
      nameValueCollection.Add("FR0406_FR0407_FR0408", str100);
      string str101 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0615"), "Own", false) == 0, " X");
      nameValueCollection.Add("FR0615_Own", str101);
      string str102 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0615"), "Rent", false) == 0, " X");
      nameValueCollection.Add("FR0615_Rent", str102);
      string str103 = Jed.NF(Jed.Num(JS.GetNum(loan, "FR0612")) + Jed.Num(JS.GetNum(loan, "FR0624")) / 12.0, (byte) 2, 0);
      nameValueCollection.Add("FR0612", str103);
      string str104 = JS.GetStr(loan, "FR0604");
      nameValueCollection.Add("FR0604", str104);
      string str105 = JS.GetStr(loan, "FR0606") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0607"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0607") + " " + JS.GetStr(loan, "FR0608");
      nameValueCollection.Add("FR0606_FR0607_FR0608", str105);
      string str106 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FE0115"), "Y", false) == 0, " X");
      nameValueCollection.Add("FE0115", str106);
      string str107 = JS.GetStr(loan, "FE0102");
      nameValueCollection.Add("FE0102", str107);
      string str108 = JS.GetStr(loan, "FE0104");
      nameValueCollection.Add("FE0104", str108);
      string str109 = JS.GetStr(loan, "FE0105") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FE0106"), "", false) != 0, ", ") + JS.GetStr(loan, "FE0106") + " " + JS.GetStr(loan, "FE0107");
      nameValueCollection.Add("FE0105_FE0106_FE0107", str109);
      string str110 = "    " + JS.GetStr(loan, "FE0113") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FE0133"), "", false) != 0, ".") + JS.GetStr(loan, "FE0133");
      nameValueCollection.Add("FE0113", str110);
      string str111 = "    " + JS.GetStr(loan, "FE0116");
      nameValueCollection.Add("FE0116", str111);
      string str112 = JS.GetStr(loan, "FE0110");
      nameValueCollection.Add("FE0110", str112);
      string str113 = JS.GetStr(loan, "FE0117");
      nameValueCollection.Add("FE0117", str113);
      string str114 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "BE0215"), "Y", false) == 0, " X");
      nameValueCollection.Add("FE0315", str114);
      string str115 = JS.GetStr(loan, "BE0202");
      nameValueCollection.Add("FE0302", str115);
      string str116 = JS.GetStr(loan, "BE0204");
      nameValueCollection.Add("FE0304", str116);
      string str117 = JS.GetStr(loan, "BE0205") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "BE0206"), "", false) != 0, ", ") + JS.GetStr(loan, "BE0206") + " " + JS.GetStr(loan, "BE0207");
      nameValueCollection.Add("FE0305_FE0306_FE0307", str117);
      string str118 = "         " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "BE0211"), "//", false) != 0, JS.GetStr(loan, "BE0211"), "") + "\r\n         " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "BE0214"), "//", false) != 0, JS.GetStr(loan, "BE0214"), "");
      nameValueCollection.Add("FE0311_FE0314", str118);
      string str119 = JS.GetStr(loan, "BE0212");
      nameValueCollection.Add("FE0312", str119);
      string str120 = JS.GetStr(loan, "BE0210");
      nameValueCollection.Add("FE0310", str120);
      string str121 = JS.GetStr(loan, "BE0217");
      nameValueCollection.Add("FE0317", str121);
      string str122 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "BE0315"), "Y", false) == 0, " X");
      nameValueCollection.Add("FE0515", str122);
      string str123 = JS.GetStr(loan, "BE0302");
      nameValueCollection.Add("FE0502", str123);
      string str124 = JS.GetStr(loan, "BE0304");
      nameValueCollection.Add("FE0504", str124);
      string str125 = JS.GetStr(loan, "BE0305") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "BE0306"), "", false) != 0, ", ") + JS.GetStr(loan, "BE0306") + " " + JS.GetStr(loan, "BE0307");
      nameValueCollection.Add("FE0505_FE0506_FE0507", str125);
      string str126 = "         " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "BE0311"), "//", false) != 0, JS.GetStr(loan, "BE0311"), "") + "\r\n         " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "BE0314"), "//", false) != 0, JS.GetStr(loan, "BE0314"), "");
      nameValueCollection.Add("FE0511_FE0514", str126);
      string str127 = JS.GetStr(loan, "BE0312");
      nameValueCollection.Add("FE0512", str127);
      string str128 = JS.GetStr(loan, "BE0310");
      nameValueCollection.Add("FE0510", str128);
      string str129 = JS.GetStr(loan, "BE0317");
      nameValueCollection.Add("FE0517", str129);
      string str130 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FE0215"), "Y", false) == 0, " X");
      nameValueCollection.Add("FE0215", str130);
      string str131 = JS.GetStr(loan, "FE0202");
      nameValueCollection.Add("FE0202", str131);
      string str132 = JS.GetStr(loan, "FE0204");
      nameValueCollection.Add("FE0204", str132);
      string str133 = JS.GetStr(loan, "FE0205") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FE0206"), "", false) != 0, ", ") + JS.GetStr(loan, "FE0206") + " " + JS.GetStr(loan, "FE0207");
      nameValueCollection.Add("FE0205_FE0206_FE0207", str133);
      string str134 = "    " + JS.GetStr(loan, "FE0213") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FE0233"), "", false) != 0, ".") + JS.GetStr(loan, "FE0233");
      nameValueCollection.Add("FE0213", str134);
      string str135 = "    " + JS.GetStr(loan, "FE0216");
      nameValueCollection.Add("FE0216", str135);
      string str136 = JS.GetStr(loan, "FE0210");
      nameValueCollection.Add("FE0210", str136);
      string str137 = JS.GetStr(loan, "FE0217");
      nameValueCollection.Add("FE0217", str137);
      string str138 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "CE0215"), "Y", false) == 0, " X");
      nameValueCollection.Add("FE0415", str138);
      string str139 = JS.GetStr(loan, "CE0202");
      nameValueCollection.Add("FE0402", str139);
      string str140 = JS.GetStr(loan, "CE0204");
      nameValueCollection.Add("FE0404", str140);
      string str141 = JS.GetStr(loan, "CE0205") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "CE0206"), "", false) != 0, ", ") + JS.GetStr(loan, "CE0206") + " " + JS.GetStr(loan, "CE0207");
      nameValueCollection.Add("FE0405_FE0406_FE0407", str141);
      string str142 = "         " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "CE0211"), "//", false) != 0, JS.GetStr(loan, "CE0211"), "") + "\r\n         " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "CE0214"), "//", false) != 0, JS.GetStr(loan, "CE0214"), "");
      nameValueCollection.Add("FE0411_FE0414", str142);
      string str143 = JS.GetStr(loan, "CE0212");
      nameValueCollection.Add("FE0412", str143);
      string str144 = JS.GetStr(loan, "CE0210");
      nameValueCollection.Add("FE0410", str144);
      string str145 = JS.GetStr(loan, "CE0217");
      nameValueCollection.Add("FE0417", str145);
      string str146 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "CE0315"), "Y", false) == 0, " X");
      nameValueCollection.Add("FE0615", str146);
      string str147 = JS.GetStr(loan, "CE0302");
      nameValueCollection.Add("FE0602", str147);
      string str148 = JS.GetStr(loan, "CE0304");
      nameValueCollection.Add("FE0604", str148);
      string str149 = JS.GetStr(loan, "CE0305") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "CE0306"), "", false) != 0, ", ") + JS.GetStr(loan, "CE0306") + " " + JS.GetStr(loan, "CE0307");
      nameValueCollection.Add("FE0605_FE0606_FE0607", str149);
      string str150 = "         " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "CE0311"), "//", false) != 0, JS.GetStr(loan, "CE0311"), "") + "\r\n         " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "CE0314"), "//", false) != 0, JS.GetStr(loan, "CE0314"), "");
      nameValueCollection.Add("FE0611_FE0614", str150);
      string str151 = JS.GetStr(loan, "CE0312");
      nameValueCollection.Add("FE0612", str151);
      string str152 = JS.GetStr(loan, "CE0310");
      nameValueCollection.Add("FE0610", str152);
      string str153 = JS.GetStr(loan, "CE0317");
      nameValueCollection.Add("FE0617", str153);
      return nameValueCollection;
    }
  }
}
