// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._1003PG5_SPANISHCLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _1003PG5_SPANISHCLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315", str1);
      string str2 = JS.GetStr(loan, "FM0104") + "\r\n" + JS.GetStr(loan, "FM0106") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0107"), "", false) != 0, ", ") + JS.GetStr(loan, "FM0107") + " " + JS.GetStr(loan, "FM0108");
      nameValueCollection.Add("274", str2);
      string str3 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "Sold", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "PendingSale", false) == 0, "PS") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "RetainForRental", false) == 0, "R") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "RetainForPrimaryOrSecondaryResidence", false) == 0, "H");
      nameValueCollection.Add("275", str3);
      string str4 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "SingleFamily", false) == 0, "SFR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Condominium", false) == 0, "CONDO") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Townhouse", false) == 0, "TOWN") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Cooperative", false) == 0, "COOP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "TwoToFourUnitProperty", false) == 0, "2-4") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "MultifamilyMoreThanFourUnits", false) == 0, "MULTI") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "ManufacturedMobileHome", false) == 0, "MOBIL") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "CommercialNonResidential", false) == 0, "COMNR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "MixedUseResidential", false) == 0, "MIXED") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Farm", false) == 0, "FARM") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "HomeAndBusinessCombined", false) == 0, "COMR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Land", false) == 0, "LAND");
      nameValueCollection.Add("276", str4);
      string str5 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0119"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0119"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0119")), (byte) 18, 0));
      nameValueCollection.Add("277", str5);
      string str6 = JS.GetStr(loan, "FM0117");
      nameValueCollection.Add("278", str6);
      string str7 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0120"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0120"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0120")), (byte) 18, 0));
      nameValueCollection.Add("279", str7);
      string str8 = JS.GetStr(loan, "FM0116");
      nameValueCollection.Add("280", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0141"), "SecondHome", false) == 0, "", Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0132"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0132"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0132")), (byte) 16, 0)));
      nameValueCollection.Add("916", str9);
      string str10 = Jed.BF((Jed.S2N(JS.GetStr(loan, "FM0121")) != 0.0 | Operators.CompareString(JS.GetStr(loan, "FM0121"), "", false) == 0) & Operators.CompareString(JS.GetStr(loan, "FM0117"), "", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0121")), (byte) 18, 0), JS.GetStr(loan, "FM0121"));
      nameValueCollection.Add("281", str10);
      string str11 = JS.GetStr(loan, "FM0204") + "\r\n" + JS.GetStr(loan, "FM0206") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0207"), "", false) != 0, ", ") + JS.GetStr(loan, "FM0207") + " " + JS.GetStr(loan, "FM0208");
      nameValueCollection.Add("282", str11);
      string str12 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "Sold", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "PendingSale", false) == 0, "PS") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "RetainForRental", false) == 0, "R") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "RetainForPrimaryOrSecondaryResidence", false) == 0, "H");
      nameValueCollection.Add("283", str12);
      string str13 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "SingleFamily", false) == 0, "SFR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Condominium", false) == 0, "CONDO") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Townhouse", false) == 0, "TOWN") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Cooperative", false) == 0, "COOP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "TwoToFourUnitProperty", false) == 0, "2-4") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "MultifamilyMoreThanFourUnits", false) == 0, "MULTI") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "ManufacturedMobileHome", false) == 0, "MOBIL") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "CommercialNonResidential", false) == 0, "COMNR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "MixedUseResidential", false) == 0, "MIXED") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Farm", false) == 0, "FARM") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "HomeAndBusinessCombined", false) == 0, "COMR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Land", false) == 0, "LAND");
      nameValueCollection.Add("284", str13);
      string str14 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0219"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0219"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0219")), (byte) 18, 0));
      nameValueCollection.Add("285", str14);
      string str15 = JS.GetStr(loan, "FM0217");
      nameValueCollection.Add("286", str15);
      string str16 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0220"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0220"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0220")), (byte) 18, 0));
      nameValueCollection.Add("287", str16);
      string str17 = JS.GetStr(loan, "FM0216");
      nameValueCollection.Add("288", str17);
      string str18 = Jed.BF((Jed.S2N(JS.GetStr(loan, "FM0221")) != 0.0 | Operators.CompareString(JS.GetStr(loan, "FM0221"), "", false) == 0) & Operators.CompareString(JS.GetStr(loan, "FM0217"), "", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0221")), (byte) 18, 0), JS.GetStr(loan, "FM0221"));
      nameValueCollection.Add("289", str18);
      string str19 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0241"), "SecondHome", false) == 0, "", Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0232"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0232"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0232")), (byte) 16, 0)));
      nameValueCollection.Add("917", str19);
      string str20 = JS.GetStr(loan, "FM0304") + "\r\n" + JS.GetStr(loan, "FM0306") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0307"), "", false) != 0, ", ") + JS.GetStr(loan, "FM0307") + " " + JS.GetStr(loan, "FM0308");
      nameValueCollection.Add("290", str20);
      string str21 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "Sold", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "PendingSale", false) == 0, "PS") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "RetainForRental", false) == 0, "R") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "RetainForPrimaryOrSecondaryResidence", false) == 0, "H");
      nameValueCollection.Add("291", str21);
      string str22 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "SingleFamily", false) == 0, "SFR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Condominium", false) == 0, "CONDO") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Townhouse", false) == 0, "TOWN") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Cooperative", false) == 0, "COOP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "TwoToFourUnitProperty", false) == 0, "2-4") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "MultifamilyMoreThanFourUnits", false) == 0, "MULTI") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "ManufacturedMobileHome", false) == 0, "MOBIL") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "CommercialNonResidential", false) == 0, "COMNR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "MixedUseResidential", false) == 0, "MIXED") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Farm", false) == 0, "FARM") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "HomeAndBusinessCombined", false) == 0, "COMR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Land", false) == 0, "LAND");
      nameValueCollection.Add("292", str22);
      string str23 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0319"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0319"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0319")), (byte) 18, 0));
      nameValueCollection.Add("293", str23);
      string str24 = JS.GetStr(loan, "FM0317");
      nameValueCollection.Add("294", str24);
      string str25 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0320"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0320"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0320")), (byte) 18, 0));
      nameValueCollection.Add("295", str25);
      string str26 = JS.GetStr(loan, "FM0316");
      nameValueCollection.Add("296", str26);
      string str27 = Jed.BF((Jed.S2N(JS.GetStr(loan, "FM0321")) != 0.0 | Operators.CompareString(JS.GetStr(loan, "FM0321"), "", false) == 0) & Operators.CompareString(JS.GetStr(loan, "FM0317"), "", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0321")), (byte) 18, 0), JS.GetStr(loan, "FM0321"));
      nameValueCollection.Add("297", str27);
      string str28 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0341"), "SecondHome", false) == 0, "", Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0332"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0332"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0332")), (byte) 16, 0)));
      nameValueCollection.Add("918", str28);
      string str29 = "";
      nameValueCollection.Add("VOMCONT", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "919"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "919"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "919")), (byte) 18, 0));
      nameValueCollection.Add("919", str30);
      string str31 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "920"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "920"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "920")), (byte) 18, 0));
      nameValueCollection.Add("920", str31);
      string str32 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "921"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "921"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "921")), (byte) 18, 0));
      nameValueCollection.Add("921", str32);
      string str33 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "922"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "922"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "922")), (byte) 18, 0));
      nameValueCollection.Add("922", str33);
      string str34 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "923"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "923"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "923")), (byte) 18, 0));
      nameValueCollection.Add("923", str34);
      string str35 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "924"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "924"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "924")), (byte) 16, 0));
      nameValueCollection.Add("924", str35);
      string str36 = JS.GetStr(loan, "206");
      nameValueCollection.Add("206", str36);
      string str37 = JS.GetStr(loan, "203");
      nameValueCollection.Add("203", str37);
      string str38 = JS.GetStr(loan, "1734");
      nameValueCollection.Add("1734", str38);
      string str39 = JS.GetStr(loan, "1736");
      nameValueCollection.Add("1736", str39);
      string str40 = JS.GetStr(loan, "1735");
      nameValueCollection.Add("1735", str40);
      string str41 = JS.GetStr(loan, "1737");
      nameValueCollection.Add("1737", str41);
      string str42 = JS.GetStr(loan, "136");
      nameValueCollection.Add("136", str42);
      string str43 = JS.GetStr(loan, "967");
      nameValueCollection.Add("967", str43);
      string str44 = JS.GetStr(loan, "968");
      nameValueCollection.Add("968", str44);
      string str45 = JS.GetStr(loan, "1092");
      nameValueCollection.Add("1092", str45);
      string str46 = JS.GetStr(loan, "138");
      nameValueCollection.Add("138", str46);
      string str47 = JS.GetStr(loan, "137");
      nameValueCollection.Add("137", str47);
      string str48 = JS.GetStr(loan, "969");
      nameValueCollection.Add("969", str48);
      string str49 = JS.GetStr(loan, "1093");
      nameValueCollection.Add("1093", str49);
      string str50 = JS.GetStr(loan, "1073");
      nameValueCollection.Add("1073", str50);
      string str51 = JS.GetStr(loan, "140");
      nameValueCollection.Add("140", str51);
      string str52 = JS.GetStr(loan, "143");
      nameValueCollection.Add("143", str52);
      string str53 = JS.GetStr(loan, "1109");
      nameValueCollection.Add("1109", str53);
      string str54 = JS.GetStr(loan, "1045");
      nameValueCollection.Add("1045", str54);
      string str55 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str55);
      string str56 = JS.GetStr(loan, "142");
      nameValueCollection.Add("142", str56);
      string str57 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "169"), "Y", false) == 0, "X");
      nameValueCollection.Add("169_Yes", str57);
      string str58 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "169"), "N", false) == 0, "X");
      nameValueCollection.Add("169_No", str58);
      string str59 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "175"), "Y", false) == 0, "X");
      nameValueCollection.Add("175_Yes", str59);
      string str60 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "175"), "N", false) == 0, "X");
      nameValueCollection.Add("175_No", str60);
      string str61 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "265"), "Y", false) == 0, "X");
      nameValueCollection.Add("265_Yes", str61);
      string str62 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "265"), "N", false) == 0, "X");
      nameValueCollection.Add("265_No", str62);
      string str63 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "266"), "Y", false) == 0, "X");
      nameValueCollection.Add("266_Yes", str63);
      string str64 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "266"), "N", false) == 0, "X");
      nameValueCollection.Add("266_No", str64);
      string str65 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "170"), "Y", false) == 0, "X");
      nameValueCollection.Add("170_Yes", str65);
      string str66 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "170"), "N", false) == 0, "X");
      nameValueCollection.Add("170_No", str66);
      string str67 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "176"), "Y", false) == 0, "X");
      nameValueCollection.Add("176_Yes", str67);
      string str68 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "176"), "N", false) == 0, "X");
      nameValueCollection.Add("176_No", str68);
      string str69 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "172"), "Y", false) == 0, "X");
      nameValueCollection.Add("172_Yes", str69);
      string str70 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "172"), "N", false) == 0, "X");
      nameValueCollection.Add("172_No", str70);
      string str71 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "178"), "Y", false) == 0, "X");
      nameValueCollection.Add("178_Yes", str71);
      string str72 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "178"), "N", false) == 0, "X");
      nameValueCollection.Add("178_No", str72);
      string str73 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1057"), "Y", false) == 0, "X");
      nameValueCollection.Add("1057_Yes", str73);
      string str74 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1057"), "N", false) == 0, "X");
      nameValueCollection.Add("1057_No", str74);
      string str75 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1197"), "Y", false) == 0, "X");
      nameValueCollection.Add("1197_Yes", str75);
      string str76 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1197"), "N", false) == 0, "X");
      nameValueCollection.Add("1197_No", str76);
      string str77 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "463"), "Y", false) == 0, "X");
      nameValueCollection.Add("463_Yes", str77);
      string str78 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "463"), "N", false) == 0, "X");
      nameValueCollection.Add("463_No", str78);
      string str79 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "464"), "Y", false) == 0, "X");
      nameValueCollection.Add("464_Yes", str79);
      string str80 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "464"), "N", false) == 0, "X");
      nameValueCollection.Add("464_No", str80);
      string str81 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "173"), "Y", false) == 0, "X");
      nameValueCollection.Add("173_Yes", str81);
      string str82 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "173"), "N", false) == 0, "X");
      nameValueCollection.Add("173_No", str82);
      string str83 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "179"), "Y", false) == 0, "X");
      nameValueCollection.Add("179_Yes", str83);
      string str84 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "179"), "N", false) == 0, "X");
      nameValueCollection.Add("179_No", str84);
      string str85 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "174"), "Y", false) == 0, "X");
      nameValueCollection.Add("174_Yes", str85);
      string str86 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "174"), "N", false) == 0, "X");
      nameValueCollection.Add("174_No", str86);
      string str87 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "180"), "Y", false) == 0, "X");
      nameValueCollection.Add("180_Yes", str87);
      string str88 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "180"), "N", false) == 0, "X");
      nameValueCollection.Add("180_No", str88);
      return nameValueCollection;
    }
  }
}
