// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._1003PG1__2006_CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _1003PG1__2006_CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315", str1);
      string str2 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "307"), "Y", false) == 0, "X");
      nameValueCollection.Add("307", str2);
      string str3 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "35"), "Y", false) == 0, "X");
      nameValueCollection.Add("35", str3);
      string str4 = JS.GetStr(loan, "305");
      nameValueCollection.Add("305", str4);
      string str5 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "VA", false) == 0, "X");
      nameValueCollection.Add("1172_VA", str5);
      string str6 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "FHA", false) == 0, "X");
      nameValueCollection.Add("1172_FHA", str6);
      string str7 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "Other", false) == 0, "X");
      nameValueCollection.Add("1172_Oth", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "Conventional", false) == 0, "X");
      nameValueCollection.Add("1172_Conv", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "FarmersHomeAdministration", false) == 0, "X");
      nameValueCollection.Add("1172_FmHA", str9);
      string str10 = JS.GetStr(loan, "1063");
      nameValueCollection.Add("1063", str10);
      string str11 = JS.GetStr(loan, "1040");
      nameValueCollection.Add("1040", str11);
      string str12 = JS.GetStr(loan, "4");
      nameValueCollection.Add("4", str12);
      string str13 = JS.GetStr(loan, "3");
      nameValueCollection.Add("3", str13);
      string str14 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str14);
      string str15 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "Fixed", false) == 0, "X");
      nameValueCollection.Add("608_Fixed", str15);
      string str16 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "GraduatedPaymentMortgage", false) == 0, "X");
      nameValueCollection.Add("608_GPM", str16);
      string str17 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "AdjustableRate", false) == 0, "X");
      nameValueCollection.Add("608_ARM", str17);
      string str18 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "OtherAmortizationType", false) == 0, "X");
      nameValueCollection.Add("608_Other", str18);
      string str19 = JS.GetStr(loan, "995");
      nameValueCollection.Add("995", str19);
      string str20 = JS.GetStr(loan, "994");
      nameValueCollection.Add("994", str20);
      string str21 = JS.GetStr(loan, "11") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "12"), "", false) != 0, ", ") + JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "13"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15") + " County: " + JS.GetStr(loan, "13");
      nameValueCollection.Add("11_12", str21);
      string str22 = JS.GetStr(loan, "18");
      nameValueCollection.Add("18", str22);
      string str23 = JS.GetStr(loan, "16");
      nameValueCollection.Add("16", str23);
      string str24 = JS.GetStr(loan, "17");
      nameValueCollection.Add("17", str24);
      string str25 = JS.GetStr(loan, "1824");
      nameValueCollection.Add("1824", str25);
      string str26 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0, "X");
      nameValueCollection.Add("19_Const", str26);
      string str27 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Cash-Out Refinance", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, "X");
      nameValueCollection.Add("19_Ref", str27);
      string str28 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, "X");
      nameValueCollection.Add("19_ConstP", str28);
      string str29 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Purchase", false) == 0, "X");
      nameValueCollection.Add("19_Pur", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Other", false) == 0, "X");
      nameValueCollection.Add("19_Other", str30);
      string str31 = JS.GetStr(loan, "9");
      nameValueCollection.Add("9", str31);
      string str32 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "Investor", false) == 0, "X");
      nameValueCollection.Add("190_Inv", str32);
      string str33 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "PrimaryResidence", false) == 0, "X");
      nameValueCollection.Add("190_Prim", str33);
      string str34 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "SecondHome", false) == 0, "X");
      nameValueCollection.Add("190_Sec", str34);
      string str35 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "20"));
      nameValueCollection.Add("20", str35);
      string str36 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "21"));
      nameValueCollection.Add("21", str36);
      string str37 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "10"));
      nameValueCollection.Add("10", str37);
      string str38 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "22"));
      nameValueCollection.Add("22", str38);
      string str39 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "23"));
      nameValueCollection.Add("23", str39);
      string str40 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, JS.GetStr(loan, "1074"));
      nameValueCollection.Add("1074", str40);
      string str41 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Cash-Out Refinance", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, JS.GetStr(loan, "26"));
      nameValueCollection.Add("26", str41);
      string str42 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Cash-Out Refinance", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, JS.GetStr(loan, "25"));
      nameValueCollection.Add("25", str42);
      string str43 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Cash-Out Refinance", false) == 0 | Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, JS.GetStr(loan, "24"));
      nameValueCollection.Add("24", str43);
      string str44 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "CashOutDebtConsolidation", false) == 0, "Cash-out Debt Consolidation", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "CashOutHomeImprovement", false) == 0, "Cash-Out Home Improvement", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "CashOutLimited", false) == 0, "Cash-Out Limited", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "CashOutOther", false) == 0, "Cash-Out Other", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "ChangeInRateTerm", false) == 0, "No Cash-Out Rate/Term", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "NoCashOutOther", false) == 0, "No Cash-Out Other", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "NoCashOutFHAStreamlinedRefinance", false) == 0, "No Cash-Out FHA Streamlined", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "NoCashOutFREOwnedRefinance", false) == 0, "No Cash-Out Freddie Owned", Jed.BF(Operators.CompareString(JS.GetStr(loan, "299"), "NoCashOutStreamlinedRefinance", false) == 0, "No Cash-Out Streamlined", JS.GetStr(loan, "299"))))))))));
      nameValueCollection.Add("299_27", str44);
      string str45 = JS.GetStr(loan, "205");
      nameValueCollection.Add("205", str45);
      string str46 = JS.GetStr(loan, "29");
      nameValueCollection.Add("29", str46);
      string str47 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "30"), "Made", false) == 0, "X");
      nameValueCollection.Add("30_made", str47);
      string str48 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "30"), "ToBeMade", false) == 0, "X");
      nameValueCollection.Add("30_2bemade", str48);
      string str49 = JS.GetStr(loan, "31") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1602"), "", false) != 0, ", ") + JS.GetStr(loan, "1602");
      nameValueCollection.Add("31", str49);
      string str50 = JS.GetStr(loan, "33");
      nameValueCollection.Add("33", str50);
      string str51 = JS.GetStr(loan, "34");
      nameValueCollection.Add("34", str51);
      string str52 = JS.GetStr(loan, "191");
      nameValueCollection.Add("191", str52);
      string str53 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1066"), "FeeSimple", false) == 0, "X");
      nameValueCollection.Add("1066_Simple", str53);
      string str54 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1066"), "Leasehold", false) == 0, "X");
      nameValueCollection.Add("1066_Leasehold", str54);
      string str55 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1034"), "//", false) != 0, JS.GetStr(loan, "1034"), "");
      nameValueCollection.Add("1034", str55);
      string str56 = JS.GetStr(loan, "36") + "  " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str56);
      string str57 = JS.GetStr(loan, "66");
      nameValueCollection.Add("66", str57);
      string str58 = JS.GetStr(loan, "65");
      nameValueCollection.Add("65", str58);
      string str59 = JS.GetStr(loan, "39");
      nameValueCollection.Add("39", str59);
      string str60 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "52"), "Married", false) == 0, "X");
      nameValueCollection.Add("52_Married", str60);
      string str61 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "52"), "Separated", false) == 0, "X");
      nameValueCollection.Add("52_Separated", str61);
      string str62 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "52"), "Unmarried", false) == 0, "X");
      nameValueCollection.Add("52_Unmarried", str62);
      string str63 = JS.GetStr(loan, "53");
      nameValueCollection.Add("53", str63);
      string str64 = JS.GetStr(loan, "54");
      nameValueCollection.Add("54", str64);
      string str65 = JS.GetStr(loan, "1402");
      nameValueCollection.Add("38", str65);
      string str66 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0115"), "Own", false) == 0, "X");
      nameValueCollection.Add("FR0115_Own", str66);
      string str67 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0115"), "Rent", false) == 0, "X");
      nameValueCollection.Add("FR0115_Rent", str67);
      string str68 = JS.GetStr(loan, "FR0112") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0112"), "", false) != 0, "Y") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0112"), "", false) == 0, "") + JS.GetStr(loan, "FR0124") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0124"), "", false) != 0, "M") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0124"), "", false) == 0, "");
      nameValueCollection.Add("FR0112_FR0124", str68);
      string str69 = JS.GetStr(loan, "FR0104");
      nameValueCollection.Add("FR0104", str69);
      string str70 = JS.GetStr(loan, "FR0106") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0107"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0107") + " " + JS.GetStr(loan, "FR0108");
      nameValueCollection.Add("FR0106_FR0107_FR0108", str70);
      string str71 = JS.GetStr(loan, "1416");
      nameValueCollection.Add("1416", str71);
      string str72 = JS.GetStr(loan, "1417") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1418"), "", false) != 0, ",") + JS.GetStr(loan, "1418") + " " + JS.GetStr(loan, "1419");
      nameValueCollection.Add("1417_1418_1419", str72);
      string str73 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0315"), "Own", false) == 0, "X");
      nameValueCollection.Add("FR0315_Own", str73);
      string str74 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0315"), "Rent", false) == 0, "X");
      nameValueCollection.Add("FR0315_Rent", str74);
      string str75 = JS.GetStr(loan, "FR0312") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0312"), "", false) != 0, "Y") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0312"), "", false) == 0, "") + JS.GetStr(loan, "FR0324") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0324"), "", false) != 0, "M") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0324"), "", false) == 0, "");
      nameValueCollection.Add("FR0312", str75);
      string str76 = JS.GetStr(loan, "FR0304");
      nameValueCollection.Add("FR0304", str76);
      string str77 = JS.GetStr(loan, "FR0306") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0307"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0307") + " " + JS.GetStr(loan, "FR0308");
      nameValueCollection.Add("FR0306_FR0307_FR0308", str77);
      string str78 = JS.GetStr(loan, "68") + "  " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69", str78);
      string str79 = JS.GetStr(loan, "97");
      nameValueCollection.Add("97", str79);
      string str80 = JS.GetStr(loan, "98");
      nameValueCollection.Add("98", str80);
      string str81 = JS.GetStr(loan, "71");
      nameValueCollection.Add("71", str81);
      string str82 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "84"), "Married", false) == 0, "X");
      nameValueCollection.Add("84_Married", str82);
      string str83 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "84"), "Separated", false) == 0, "X");
      nameValueCollection.Add("84_Separated", str83);
      string str84 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "84"), "Unmarried", false) == 0, "X");
      nameValueCollection.Add("84_Unmarried", str84);
      string str85 = JS.GetStr(loan, "85");
      nameValueCollection.Add("85", str85);
      string str86 = JS.GetStr(loan, "86");
      nameValueCollection.Add("86", str86);
      string str87 = JS.GetStr(loan, "1403");
      nameValueCollection.Add("70", str87);
      string str88 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0215"), "Own", false) == 0, "X");
      nameValueCollection.Add("FR0215_Own", str88);
      string str89 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0215"), "Rent", false) == 0, "X");
      nameValueCollection.Add("FR0215_Rent", str89);
      string str90 = JS.GetStr(loan, "FR0212") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0212"), "", false) != 0, "Y") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0212"), "", false) == 0, "") + JS.GetStr(loan, "FR0224") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0224"), "", false) != 0, "M") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0224"), "", false) == 0, "");
      nameValueCollection.Add("FR0212_FR0224", str90);
      string str91 = JS.GetStr(loan, "FR0204");
      nameValueCollection.Add("FR0204", str91);
      string str92 = JS.GetStr(loan, "FR0206") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0207"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0207") + " " + JS.GetStr(loan, "FR0208");
      nameValueCollection.Add("FR0206_FR0207_FR0208", str92);
      string str93 = JS.GetStr(loan, "1519");
      nameValueCollection.Add("1519", str93);
      string str94 = JS.GetStr(loan, "1520") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1521"), "", false) != 0, ", ") + JS.GetStr(loan, "1521") + " " + JS.GetStr(loan, "1522");
      nameValueCollection.Add("1520_1521_1522", str94);
      string str95 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0415"), "Own", false) == 0, "X");
      nameValueCollection.Add("FR0415_Own", str95);
      string str96 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0415"), "Rent", false) == 0, "X");
      nameValueCollection.Add("FR0415_Rent", str96);
      string str97 = JS.GetStr(loan, "FR0412") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0412"), "", false) != 0, "Y") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0412"), "", false) == 0, "") + JS.GetStr(loan, "FR0424") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0424"), "", false) != 0, "M") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0424"), "", false) == 0, "");
      nameValueCollection.Add("FR0412", str97);
      string str98 = JS.GetStr(loan, "FR0404");
      nameValueCollection.Add("FR0404", str98);
      string str99 = JS.GetStr(loan, "FR0406") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0407"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0407") + " " + JS.GetStr(loan, "FR0408");
      nameValueCollection.Add("FR0406_FR0407_FR0408", str99);
      return nameValueCollection;
    }
  }
}
