// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._AMORT__SCHEDULE_YEARLY_TOTALS_CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _AMORT__SCHEDULE_YEARLY_TOTALS_CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "36") + "  " + JS.GetStr(loan, "37") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "68"), "", false) != 0, ", ") + JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("36_37", str1);
      string str2 = JS.GetStr(loan, "363");
      nameValueCollection.Add("363", str2);
      string str3 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str3);
      string str4 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315", str4);
      string str5 = JS.GetStr(loan, "319");
      nameValueCollection.Add("319", str5);
      string str6 = JS.GetStr(loan, "313") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "321"), "", false) != 0, ", ") + JS.GetStr(loan, "321") + " " + JS.GetStr(loan, "323");
      nameValueCollection.Add("313_321_323", str6);
      string str7 = JS.GetStr(loan, "2");
      nameValueCollection.Add("1109", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 & Operators.CompareString(JS.GetStr(loan, "1677"), "", false) != 0, JS.GetStr(loan, "1677"), JS.GetStr(loan, "3"));
      nameValueCollection.Add("3", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0 & Operators.CompareString(JS.GetStr(loan, "1176"), "", false) != 0, JS.GetStr(loan, "1176"), JS.GetStr(loan, "4"));
      nameValueCollection.Add("4", str9);
      string str10 = "";
      nameValueCollection.Add("YRAMORT_1", str10);
      string str11 = "";
      nameValueCollection.Add("YRAMORT_2", str11);
      string str12 = "";
      nameValueCollection.Add("YRAMORT_3", str12);
      string str13 = "";
      nameValueCollection.Add("YRAMORT_4", str13);
      string str14 = "";
      nameValueCollection.Add("YRAMORT_5", str14);
      string str15 = "";
      nameValueCollection.Add("YRAMORT_6", str15);
      string str16 = "";
      nameValueCollection.Add("YRAMORT_7", str16);
      string str17 = "";
      nameValueCollection.Add("YRAMORT_8", str17);
      string str18 = "";
      nameValueCollection.Add("YRAMORT_9", str18);
      string str19 = "";
      nameValueCollection.Add("YRAMORT_10", str19);
      string str20 = "";
      nameValueCollection.Add("YRAMORT_11", str20);
      string str21 = "";
      nameValueCollection.Add("YRAMORT_12", str21);
      string str22 = "";
      nameValueCollection.Add("YRAMORT_13", str22);
      string str23 = "";
      nameValueCollection.Add("YRAMORT_14", str23);
      string str24 = "";
      nameValueCollection.Add("YRAMORT_15", str24);
      string str25 = "";
      nameValueCollection.Add("YRAMORT_16", str25);
      string str26 = "";
      nameValueCollection.Add("YRAMORT_17", str26);
      string str27 = "";
      nameValueCollection.Add("YRAMORT_18", str27);
      string str28 = "";
      nameValueCollection.Add("YRAMORT_19", str28);
      string str29 = "";
      nameValueCollection.Add("YRAMORT_20", str29);
      string str30 = "";
      nameValueCollection.Add("YRAMORT_21", str30);
      string str31 = "";
      nameValueCollection.Add("YRAMORT_22", str31);
      string str32 = "";
      nameValueCollection.Add("YRAMORT_23", str32);
      string str33 = "";
      nameValueCollection.Add("YRAMORT_24", str33);
      string str34 = "";
      nameValueCollection.Add("YRAMORT_25", str34);
      string str35 = "";
      nameValueCollection.Add("YRAMORT_26", str35);
      string str36 = "";
      nameValueCollection.Add("YRAMORT_27", str36);
      string str37 = "";
      nameValueCollection.Add("YRAMORT_28", str37);
      string str38 = "";
      nameValueCollection.Add("YRAMORT_29", str38);
      string str39 = "";
      nameValueCollection.Add("YRAMORT_30", str39);
      string str40 = "";
      nameValueCollection.Add("YRAMORT_31", str40);
      string str41 = "";
      nameValueCollection.Add("YRAMORT_32", str41);
      string str42 = "";
      nameValueCollection.Add("YRAMORT_33", str42);
      string str43 = "";
      nameValueCollection.Add("YRAMORT_34", str43);
      string str44 = "";
      nameValueCollection.Add("YRAMORT_35", str44);
      string str45 = "";
      nameValueCollection.Add("YRAMORT_36", str45);
      string str46 = "";
      nameValueCollection.Add("YRAMORT_37", str46);
      string str47 = "";
      nameValueCollection.Add("YRAMORT_38", str47);
      string str48 = "";
      nameValueCollection.Add("YRAMORT_39", str48);
      string str49 = "";
      nameValueCollection.Add("YRAMORT_40", str49);
      string str50 = "";
      nameValueCollection.Add("YRAMORT_41", str50);
      string str51 = "";
      nameValueCollection.Add("YRAMORT_42", str51);
      string str52 = "";
      nameValueCollection.Add("YRAMORT_43", str52);
      string str53 = "";
      nameValueCollection.Add("YRAMORT_44", str53);
      string str54 = "";
      nameValueCollection.Add("YRAMORT_45", str54);
      string str55 = "";
      nameValueCollection.Add("YRAMORT_46", str55);
      string str56 = "";
      nameValueCollection.Add("YRAMORT_47", str56);
      string str57 = "";
      nameValueCollection.Add("YRAMORT_48", str57);
      string str58 = "";
      nameValueCollection.Add("YRAMORT_49", str58);
      string str59 = "";
      nameValueCollection.Add("YRAMORT_50", str59);
      string str60 = "";
      nameValueCollection.Add("YRAMORT_51", str60);
      string str61 = "";
      nameValueCollection.Add("YRAMORT_52", str61);
      string str62 = "";
      nameValueCollection.Add("YRAMORT_53", str62);
      string str63 = "";
      nameValueCollection.Add("YRAMORT_54", str63);
      string str64 = "";
      nameValueCollection.Add("YRAMORT_55", str64);
      string str65 = "";
      nameValueCollection.Add("YRAMORT_56", str65);
      string str66 = "";
      nameValueCollection.Add("YRAMORT_57", str66);
      string str67 = "";
      nameValueCollection.Add("YRAMORT_58", str67);
      string str68 = "";
      nameValueCollection.Add("YRAMORT_59", str68);
      string str69 = "";
      nameValueCollection.Add("YRAMORT_60", str69);
      string str70 = "";
      nameValueCollection.Add("YRAMORT_61", str70);
      string str71 = "";
      nameValueCollection.Add("YRAMORT_62", str71);
      string str72 = "";
      nameValueCollection.Add("YRAMORT_63", str72);
      string str73 = "";
      nameValueCollection.Add("YRAMORT_64", str73);
      string str74 = "";
      nameValueCollection.Add("YRAMORT_65", str74);
      string str75 = "";
      nameValueCollection.Add("YRAMORT_66", str75);
      string str76 = "";
      nameValueCollection.Add("YRAMORT_67", str76);
      string str77 = "";
      nameValueCollection.Add("YRAMORT_68", str77);
      string str78 = "";
      nameValueCollection.Add("YRAMORT_69", str78);
      string str79 = "";
      nameValueCollection.Add("YRAMORT_70", str79);
      string str80 = "";
      nameValueCollection.Add("YRAMORT_71", str80);
      string str81 = "";
      nameValueCollection.Add("YRAMORT_72", str81);
      string str82 = "";
      nameValueCollection.Add("YRAMORT_73", str82);
      string str83 = "";
      nameValueCollection.Add("YRAMORT_74", str83);
      string str84 = "";
      nameValueCollection.Add("YRAMORT_75", str84);
      string str85 = "";
      nameValueCollection.Add("YRAMORT_76", str85);
      string str86 = "";
      nameValueCollection.Add("YRAMORT_77", str86);
      string str87 = "";
      nameValueCollection.Add("YRAMORT_78", str87);
      string str88 = "";
      nameValueCollection.Add("YRAMORT_79", str88);
      string str89 = "";
      nameValueCollection.Add("YRAMORT_80", str89);
      string str90 = "";
      nameValueCollection.Add("YRAMORT_81", str90);
      string str91 = "";
      nameValueCollection.Add("YRAMORT_82", str91);
      string str92 = "";
      nameValueCollection.Add("YRAMORT_83", str92);
      string str93 = "";
      nameValueCollection.Add("YRAMORT_84", str93);
      string str94 = "";
      nameValueCollection.Add("YRAMORT_85", str94);
      string str95 = "";
      nameValueCollection.Add("YRAMORT_86", str95);
      string str96 = "";
      nameValueCollection.Add("YRAMORT_87", str96);
      string str97 = "";
      nameValueCollection.Add("YRAMORT_88", str97);
      string str98 = "";
      nameValueCollection.Add("YRAMORT_89", str98);
      string str99 = "";
      nameValueCollection.Add("YRAMORT_90", str99);
      string str100 = "";
      nameValueCollection.Add("YRAMORT_91", str100);
      string str101 = "";
      nameValueCollection.Add("YRAMORT_92", str101);
      string str102 = "";
      nameValueCollection.Add("YRAMORT_93", str102);
      string str103 = "";
      nameValueCollection.Add("YRAMORT_94", str103);
      string str104 = "";
      nameValueCollection.Add("YRAMORT_95", str104);
      string str105 = "";
      nameValueCollection.Add("YRAMORT_96", str105);
      string str106 = "";
      nameValueCollection.Add("YRAMORT_97", str106);
      string str107 = "";
      nameValueCollection.Add("YRAMORT_98", str107);
      string str108 = "";
      nameValueCollection.Add("YRAMORT_99", str108);
      string str109 = "";
      nameValueCollection.Add("YRAMORT_100", str109);
      string str110 = "";
      nameValueCollection.Add("YRAMORT_101", str110);
      string str111 = "";
      nameValueCollection.Add("YRAMORT_102", str111);
      string str112 = "";
      nameValueCollection.Add("YRAMORT_103", str112);
      string str113 = "";
      nameValueCollection.Add("YRAMORT_104", str113);
      string str114 = "";
      nameValueCollection.Add("YRAMORT_105", str114);
      string str115 = "";
      nameValueCollection.Add("YRAMORT_106", str115);
      string str116 = "";
      nameValueCollection.Add("YRAMORT_107", str116);
      string str117 = "";
      nameValueCollection.Add("YRAMORT_108", str117);
      string str118 = "";
      nameValueCollection.Add("YRAMORT_109", str118);
      string str119 = "";
      nameValueCollection.Add("YRAMORT_110", str119);
      string str120 = "";
      nameValueCollection.Add("YRAMORT_111", str120);
      string str121 = "";
      nameValueCollection.Add("YRAMORT_112", str121);
      string str122 = "";
      nameValueCollection.Add("YRAMORT_113", str122);
      string str123 = "";
      nameValueCollection.Add("YRAMORT_114", str123);
      string str124 = "";
      nameValueCollection.Add("YRAMORT_115", str124);
      string str125 = "";
      nameValueCollection.Add("YRAMORT_116", str125);
      string str126 = "";
      nameValueCollection.Add("YRAMORT_117", str126);
      string str127 = "";
      nameValueCollection.Add("YRAMORT_118", str127);
      string str128 = "";
      nameValueCollection.Add("YRAMORT_119", str128);
      string str129 = "";
      nameValueCollection.Add("YRAMORT_120", str129);
      string str130 = "";
      nameValueCollection.Add("YRAMORT_121", str130);
      string str131 = "";
      nameValueCollection.Add("YRAMORT_122", str131);
      string str132 = "";
      nameValueCollection.Add("YRAMORT_123", str132);
      string str133 = "";
      nameValueCollection.Add("YRAMORT_124", str133);
      string str134 = "";
      nameValueCollection.Add("YRAMORT_125", str134);
      string str135 = "";
      nameValueCollection.Add("YRAMORT_126", str135);
      string str136 = "";
      nameValueCollection.Add("YRAMORT_127", str136);
      string str137 = "";
      nameValueCollection.Add("YRAMORT_128", str137);
      string str138 = "";
      nameValueCollection.Add("YRAMORT_129", str138);
      string str139 = "";
      nameValueCollection.Add("YRAMORT_130", str139);
      string str140 = "";
      nameValueCollection.Add("YRAMORT_131", str140);
      string str141 = "";
      nameValueCollection.Add("YRAMORT_132", str141);
      string str142 = "";
      nameValueCollection.Add("YRAMORT_133", str142);
      string str143 = "";
      nameValueCollection.Add("YRAMORT_134", str143);
      string str144 = "";
      nameValueCollection.Add("YRAMORT_135", str144);
      string str145 = "";
      nameValueCollection.Add("YRAMORT_136", str145);
      string str146 = "";
      nameValueCollection.Add("YRAMORT_137", str146);
      string str147 = "";
      nameValueCollection.Add("YRAMORT_138", str147);
      string str148 = "";
      nameValueCollection.Add("YRAMORT_139", str148);
      string str149 = "";
      nameValueCollection.Add("YRAMORT_140", str149);
      string str150 = "";
      nameValueCollection.Add("YRAMORT_141", str150);
      string str151 = "";
      nameValueCollection.Add("YRAMORT_142", str151);
      string str152 = "";
      nameValueCollection.Add("YRAMORT_143", str152);
      string str153 = "";
      nameValueCollection.Add("YRAMORT_144", str153);
      string str154 = "";
      nameValueCollection.Add("YRAMORT_145", str154);
      string str155 = "";
      nameValueCollection.Add("YRAMORT_146", str155);
      string str156 = "";
      nameValueCollection.Add("YRAMORT_147", str156);
      string str157 = "";
      nameValueCollection.Add("YRAMORT_148", str157);
      string str158 = "";
      nameValueCollection.Add("YRAMORT_149", str158);
      string str159 = "";
      nameValueCollection.Add("YRAMORT_150", str159);
      string str160 = "";
      nameValueCollection.Add("YRAMORT_151", str160);
      string str161 = "";
      nameValueCollection.Add("YRAMORT_152", str161);
      string str162 = "";
      nameValueCollection.Add("YRAMORT_153", str162);
      string str163 = "";
      nameValueCollection.Add("YRAMORT_154", str163);
      string str164 = "";
      nameValueCollection.Add("YRAMORT_155", str164);
      string str165 = "";
      nameValueCollection.Add("YRAMORT_156", str165);
      string str166 = "";
      nameValueCollection.Add("YRAMORT_157", str166);
      string str167 = "";
      nameValueCollection.Add("YRAMORT_158", str167);
      string str168 = "";
      nameValueCollection.Add("YRAMORT_159", str168);
      string str169 = "";
      nameValueCollection.Add("YRAMORT_160", str169);
      string str170 = "";
      nameValueCollection.Add("YRAMORT_161", str170);
      string str171 = "";
      nameValueCollection.Add("YRAMORT_162", str171);
      string str172 = "";
      nameValueCollection.Add("YRAMORT_163", str172);
      string str173 = "";
      nameValueCollection.Add("YRAMORT_164", str173);
      string str174 = "";
      nameValueCollection.Add("YRAMORT_165", str174);
      string str175 = "";
      nameValueCollection.Add("YRAMORT_166", str175);
      string str176 = "";
      nameValueCollection.Add("YRAMORT_167", str176);
      string str177 = "";
      nameValueCollection.Add("YRAMORT_168", str177);
      string str178 = "";
      nameValueCollection.Add("YRAMORT_169", str178);
      string str179 = "";
      nameValueCollection.Add("YRAMORT_170", str179);
      string str180 = "";
      nameValueCollection.Add("YRAMORT_171", str180);
      string str181 = "";
      nameValueCollection.Add("YRAMORT_172", str181);
      string str182 = "";
      nameValueCollection.Add("YRAMORT_173", str182);
      string str183 = "";
      nameValueCollection.Add("YRAMORT_174", str183);
      string str184 = "";
      nameValueCollection.Add("YRAMORT_175", str184);
      string str185 = "";
      nameValueCollection.Add("YRAMORT_176", str185);
      string str186 = "";
      nameValueCollection.Add("YRAMORT_177", str186);
      string str187 = "";
      nameValueCollection.Add("YRAMORT_178", str187);
      string str188 = "";
      nameValueCollection.Add("YRAMORT_179", str188);
      string str189 = "";
      nameValueCollection.Add("YRAMORT_180", str189);
      string str190 = "";
      nameValueCollection.Add("YRAMORT_181", str190);
      string str191 = "";
      nameValueCollection.Add("YRAMORT_182", str191);
      string str192 = "";
      nameValueCollection.Add("YRAMORT_183", str192);
      string str193 = "";
      nameValueCollection.Add("YRAMORT_184", str193);
      string str194 = "";
      nameValueCollection.Add("YRAMORT_185", str194);
      string str195 = "";
      nameValueCollection.Add("YRAMORT_186", str195);
      string str196 = "";
      nameValueCollection.Add("YRAMORT_187", str196);
      string str197 = "";
      nameValueCollection.Add("YRAMORT_188", str197);
      string str198 = "";
      nameValueCollection.Add("YRAMORT_189", str198);
      string str199 = "";
      nameValueCollection.Add("YRAMORT_190", str199);
      string str200 = "";
      nameValueCollection.Add("YRAMORT_191", str200);
      string str201 = "";
      nameValueCollection.Add("YRAMORT_192", str201);
      string str202 = "";
      nameValueCollection.Add("YRAMORT_193", str202);
      string str203 = "";
      nameValueCollection.Add("YRAMORT_194", str203);
      string str204 = "";
      nameValueCollection.Add("YRAMORT_195", str204);
      string str205 = "";
      nameValueCollection.Add("YRAMORT_196", str205);
      string str206 = "";
      nameValueCollection.Add("YRAMORT_197", str206);
      string str207 = "";
      nameValueCollection.Add("YRAMORT_198", str207);
      string str208 = "";
      nameValueCollection.Add("YRAMORT_199", str208);
      string str209 = "";
      nameValueCollection.Add("YRAMORT_200", str209);
      string str210 = "";
      nameValueCollection.Add("YRAMORT_201", str210);
      string str211 = "";
      nameValueCollection.Add("YRAMORT_202", str211);
      string str212 = "";
      nameValueCollection.Add("YRAMORT_203", str212);
      string str213 = "";
      nameValueCollection.Add("YRAMORT_204", str213);
      string str214 = "";
      nameValueCollection.Add("YRAMORT_205", str214);
      string str215 = "";
      nameValueCollection.Add("YRAMORT_206", str215);
      string str216 = "";
      nameValueCollection.Add("YRAMORT_207", str216);
      string str217 = "";
      nameValueCollection.Add("YRAMORT_208", str217);
      string str218 = "";
      nameValueCollection.Add("YRAMORT_209", str218);
      string str219 = "";
      nameValueCollection.Add("YRAMORT_210", str219);
      string str220 = "";
      nameValueCollection.Add("YRAMORT_211", str220);
      string str221 = "";
      nameValueCollection.Add("YRAMORT_212", str221);
      string str222 = "";
      nameValueCollection.Add("YRAMORT_213", str222);
      string str223 = "";
      nameValueCollection.Add("YRAMORT_214", str223);
      string str224 = "";
      nameValueCollection.Add("YRAMORT_215", str224);
      string str225 = "";
      nameValueCollection.Add("YRAMORT_216", str225);
      string str226 = "";
      nameValueCollection.Add("YRAMORT_217", str226);
      string str227 = "";
      nameValueCollection.Add("YRAMORT_218", str227);
      string str228 = "";
      nameValueCollection.Add("YRAMORT_219", str228);
      string str229 = "";
      nameValueCollection.Add("YRAMORT_220", str229);
      string str230 = "";
      nameValueCollection.Add("YRAMORT_221", str230);
      string str231 = "";
      nameValueCollection.Add("YRAMORT_222", str231);
      string str232 = "";
      nameValueCollection.Add("YRAMORT_223", str232);
      string str233 = "";
      nameValueCollection.Add("YRAMORT_224", str233);
      string str234 = "";
      nameValueCollection.Add("YRAMORT_225", str234);
      string str235 = "";
      nameValueCollection.Add("YRAMORT_226", str235);
      string str236 = "";
      nameValueCollection.Add("YRAMORT_227", str236);
      string str237 = "";
      nameValueCollection.Add("YRAMORT_228", str237);
      string str238 = "";
      nameValueCollection.Add("YRAMORT_229", str238);
      string str239 = "";
      nameValueCollection.Add("YRAMORT_230", str239);
      string str240 = "";
      nameValueCollection.Add("YRAMORT_231", str240);
      string str241 = "";
      nameValueCollection.Add("YRAMORT_232", str241);
      string str242 = "";
      nameValueCollection.Add("YRAMORT_233", str242);
      string str243 = "";
      nameValueCollection.Add("YRAMORT_234", str243);
      string str244 = "";
      nameValueCollection.Add("YRAMORT_235", str244);
      string str245 = "";
      nameValueCollection.Add("YRAMORT_236", str245);
      string str246 = "";
      nameValueCollection.Add("YRAMORT_237", str246);
      string str247 = "";
      nameValueCollection.Add("YRAMORT_238", str247);
      string str248 = "";
      nameValueCollection.Add("YRAMORT_239", str248);
      string str249 = "";
      nameValueCollection.Add("YRAMORT_240", str249);
      string str250 = "";
      nameValueCollection.Add("YRAMORT_241", str250);
      string str251 = "";
      nameValueCollection.Add("YRAMORT_242", str251);
      string str252 = "";
      nameValueCollection.Add("YRAMORT_243", str252);
      string str253 = "";
      nameValueCollection.Add("YRAMORT_244", str253);
      string str254 = "";
      nameValueCollection.Add("YRAMORT_245", str254);
      string str255 = "";
      nameValueCollection.Add("YRAMORT_246", str255);
      string str256 = "";
      nameValueCollection.Add("YRAMORT_247", str256);
      string str257 = "";
      nameValueCollection.Add("YRAMORT_248", str257);
      string str258 = "";
      nameValueCollection.Add("YRAMORT_249", str258);
      string str259 = "";
      nameValueCollection.Add("YRAMORT_250", str259);
      string str260 = "";
      nameValueCollection.Add("YRAMORT_251", str260);
      string str261 = "";
      nameValueCollection.Add("YRAMORT_252", str261);
      string str262 = "";
      nameValueCollection.Add("YRAMORT_253", str262);
      string str263 = "";
      nameValueCollection.Add("YRAMORT_254", str263);
      string str264 = "";
      nameValueCollection.Add("YRAMORT_255", str264);
      string str265 = "";
      nameValueCollection.Add("YRAMORT_256", str265);
      string str266 = "";
      nameValueCollection.Add("YRAMORT_257", str266);
      string str267 = "";
      nameValueCollection.Add("YRAMORT_258", str267);
      string str268 = "";
      nameValueCollection.Add("YRAMORT_259", str268);
      string str269 = "";
      nameValueCollection.Add("YRAMORT_260", str269);
      string str270 = "";
      nameValueCollection.Add("YRAMORT_261", str270);
      string str271 = "";
      nameValueCollection.Add("YRAMORT_262", str271);
      string str272 = "";
      nameValueCollection.Add("YRAMORT_263", str272);
      string str273 = "";
      nameValueCollection.Add("YRAMORT_264", str273);
      string str274 = "";
      nameValueCollection.Add("YRAMORT_265", str274);
      string str275 = "";
      nameValueCollection.Add("YRAMORT_266", str275);
      string str276 = "";
      nameValueCollection.Add("YRAMORT_267", str276);
      string str277 = "";
      nameValueCollection.Add("YRAMORT_268", str277);
      string str278 = "";
      nameValueCollection.Add("YRAMORT_269", str278);
      string str279 = "";
      nameValueCollection.Add("YRAMORT_270", str279);
      string str280 = "";
      nameValueCollection.Add("YRAMORT_271", str280);
      string str281 = "";
      nameValueCollection.Add("YRAMORT_272", str281);
      string str282 = "";
      nameValueCollection.Add("YRAMORT_273", str282);
      string str283 = "";
      nameValueCollection.Add("YRAMORT_274", str283);
      string str284 = "";
      nameValueCollection.Add("YRAMORT_275", str284);
      string str285 = "";
      nameValueCollection.Add("YRAMORT_276", str285);
      string str286 = "";
      nameValueCollection.Add("YRAMORT_277", str286);
      string str287 = "";
      nameValueCollection.Add("YRAMORT_278", str287);
      string str288 = "";
      nameValueCollection.Add("YRAMORT_279", str288);
      string str289 = "";
      nameValueCollection.Add("YRAMORT_280", str289);
      string str290 = "";
      nameValueCollection.Add("YRAMORT_281", str290);
      string str291 = "";
      nameValueCollection.Add("YRAMORT_282", str291);
      string str292 = "";
      nameValueCollection.Add("YRAMORT_283", str292);
      string str293 = "";
      nameValueCollection.Add("YRAMORT_284", str293);
      string str294 = "";
      nameValueCollection.Add("YRAMORT_285", str294);
      string str295 = "";
      nameValueCollection.Add("YRAMORT_286", str295);
      string str296 = "";
      nameValueCollection.Add("YRAMORT_287", str296);
      string str297 = "";
      nameValueCollection.Add("YRAMORT_288", str297);
      string str298 = "";
      nameValueCollection.Add("YRAMORT_289", str298);
      string str299 = "";
      nameValueCollection.Add("YRAMORT_290", str299);
      string str300 = "";
      nameValueCollection.Add("YRAMORT_291", str300);
      string str301 = "";
      nameValueCollection.Add("YRAMORT_292", str301);
      string str302 = "";
      nameValueCollection.Add("YRAMORT_293", str302);
      string str303 = "";
      nameValueCollection.Add("YRAMORT_294", str303);
      string str304 = "";
      nameValueCollection.Add("YRAMORT_295", str304);
      string str305 = "";
      nameValueCollection.Add("YRAMORT_296", str305);
      string str306 = "";
      nameValueCollection.Add("YRAMORT_297", str306);
      string str307 = "";
      nameValueCollection.Add("YRAMORT_298", str307);
      string str308 = "";
      nameValueCollection.Add("YRAMORT_299", str308);
      string str309 = "";
      nameValueCollection.Add("YRAMORT_300", str309);
      string str310 = "";
      nameValueCollection.Add("YRAMORT_301", str310);
      string str311 = "";
      nameValueCollection.Add("YRAMORT_302", str311);
      string str312 = "";
      nameValueCollection.Add("YRAMORT_303", str312);
      string str313 = "";
      nameValueCollection.Add("YRAMORT_304", str313);
      string str314 = "";
      nameValueCollection.Add("YRAMORT_305", str314);
      string str315 = "";
      nameValueCollection.Add("YRAMORT_306", str315);
      string str316 = "";
      nameValueCollection.Add("YRAMORT_307", str316);
      string str317 = "";
      nameValueCollection.Add("YRAMORT_308", str317);
      string str318 = "";
      nameValueCollection.Add("YRAMORT_309", str318);
      string str319 = "";
      nameValueCollection.Add("YRAMORT_310", str319);
      string str320 = "";
      nameValueCollection.Add("YRAMORT_311", str320);
      string str321 = "";
      nameValueCollection.Add("YRAMORT_312", str321);
      string str322 = "";
      nameValueCollection.Add("YRAMORT_313", str322);
      string str323 = "";
      nameValueCollection.Add("YRAMORT_314", str323);
      string str324 = "";
      nameValueCollection.Add("YRAMORT_315", str324);
      string str325 = "";
      nameValueCollection.Add("YRAMORT_316", str325);
      string str326 = "";
      nameValueCollection.Add("YRAMORT_317", str326);
      string str327 = "";
      nameValueCollection.Add("YRAMORT_318", str327);
      string str328 = "";
      nameValueCollection.Add("YRAMORT_319", str328);
      string str329 = "";
      nameValueCollection.Add("YRAMORT_320", str329);
      string str330 = "";
      nameValueCollection.Add("YRAMORT_321", str330);
      string str331 = "";
      nameValueCollection.Add("YRAMORT_322", str331);
      string str332 = "";
      nameValueCollection.Add("YRAMORT_323", str332);
      string str333 = "";
      nameValueCollection.Add("YRAMORT_324", str333);
      string str334 = "";
      nameValueCollection.Add("YRAMORT_325", str334);
      string str335 = "";
      nameValueCollection.Add("YRAMORT_326", str335);
      string str336 = "";
      nameValueCollection.Add("YRAMORT_327", str336);
      string str337 = "";
      nameValueCollection.Add("YRAMORT_328", str337);
      string str338 = "";
      nameValueCollection.Add("YRAMORT_329", str338);
      string str339 = "";
      nameValueCollection.Add("YRAMORT_330", str339);
      string str340 = "";
      nameValueCollection.Add("YRAMORT_331", str340);
      string str341 = "";
      nameValueCollection.Add("YRAMORT_332", str341);
      string str342 = "";
      nameValueCollection.Add("YRAMORT_333", str342);
      string str343 = "";
      nameValueCollection.Add("YRAMORT_334", str343);
      string str344 = "";
      nameValueCollection.Add("YRAMORT_335", str344);
      string str345 = "";
      nameValueCollection.Add("YRAMORT_336", str345);
      string str346 = "";
      nameValueCollection.Add("YRAMORT_337", str346);
      string str347 = "";
      nameValueCollection.Add("YRAMORT_338", str347);
      string str348 = "";
      nameValueCollection.Add("YRAMORT_339", str348);
      string str349 = "";
      nameValueCollection.Add("YRAMORT_340", str349);
      string str350 = "";
      nameValueCollection.Add("YRAMORT_341", str350);
      string str351 = "";
      nameValueCollection.Add("YRAMORT_342", str351);
      string str352 = "";
      nameValueCollection.Add("YRAMORT_343", str352);
      string str353 = "";
      nameValueCollection.Add("YRAMORT_344", str353);
      string str354 = "";
      nameValueCollection.Add("YRAMORT_345", str354);
      string str355 = "";
      nameValueCollection.Add("YRAMORT_346", str355);
      string str356 = "";
      nameValueCollection.Add("YRAMORT_347", str356);
      string str357 = "";
      nameValueCollection.Add("YRAMORT_348", str357);
      string str358 = "";
      nameValueCollection.Add("YRAMORT_349", str358);
      string str359 = "";
      nameValueCollection.Add("YRAMORT_350", str359);
      string str360 = "";
      nameValueCollection.Add("YRAMORT_351", str360);
      string str361 = "";
      nameValueCollection.Add("YRAMORT_352", str361);
      string str362 = "";
      nameValueCollection.Add("YRAMORT_353", str362);
      string str363 = "";
      nameValueCollection.Add("YRAMORT_354", str363);
      string str364 = "";
      nameValueCollection.Add("YRAMORT_355", str364);
      string str365 = "";
      nameValueCollection.Add("YRAMORT_356", str365);
      string str366 = "";
      nameValueCollection.Add("YRAMORT_357", str366);
      string str367 = "";
      nameValueCollection.Add("YRAMORT_358", str367);
      string str368 = "";
      nameValueCollection.Add("YRAMORT_359", str368);
      string str369 = "";
      nameValueCollection.Add("YRAMORT_360", str369);
      string str370 = "";
      nameValueCollection.Add("YRAMORT_361", str370);
      string str371 = "";
      nameValueCollection.Add("YRAMORT_362", str371);
      string str372 = "";
      nameValueCollection.Add("YRAMORT_363", str372);
      string str373 = "";
      nameValueCollection.Add("YRAMORT_364", str373);
      string str374 = "";
      nameValueCollection.Add("YRAMORT_365", str374);
      string str375 = "";
      nameValueCollection.Add("YRAMORT_366", str375);
      string str376 = "";
      nameValueCollection.Add("YRAMORT_367", str376);
      string str377 = "";
      nameValueCollection.Add("YRAMORT_368", str377);
      string str378 = "";
      nameValueCollection.Add("YRAMORT_369", str378);
      string str379 = "";
      nameValueCollection.Add("YRAMORT_370", str379);
      string str380 = "";
      nameValueCollection.Add("YRAMORT_371", str380);
      string str381 = "";
      nameValueCollection.Add("YRAMORT_372", str381);
      string str382 = "";
      nameValueCollection.Add("YRAMORT_373", str382);
      string str383 = "";
      nameValueCollection.Add("YRAMORT_374", str383);
      string str384 = "";
      nameValueCollection.Add("YRAMORT_375", str384);
      string str385 = "";
      nameValueCollection.Add("YRAMORT_376", str385);
      string str386 = "";
      nameValueCollection.Add("YRAMORT_377", str386);
      string str387 = "";
      nameValueCollection.Add("YRAMORT_378", str387);
      string str388 = "";
      nameValueCollection.Add("AMORTDATE_1", str388);
      string str389 = "";
      nameValueCollection.Add("AMORTDATE_2", str389);
      string str390 = "";
      nameValueCollection.Add("AMORTDATE_3", str390);
      string str391 = "";
      nameValueCollection.Add("AMORTDATE_4", str391);
      string str392 = "";
      nameValueCollection.Add("AMORTDATE_5", str392);
      string str393 = "";
      nameValueCollection.Add("AMORTDATE_6", str393);
      string str394 = "";
      nameValueCollection.Add("AMORTDATE_7", str394);
      string str395 = "";
      nameValueCollection.Add("AMORTDATE_8", str395);
      string str396 = "";
      nameValueCollection.Add("AMORTDATE_9", str396);
      string str397 = "";
      nameValueCollection.Add("AMORTDATE_10", str397);
      string str398 = "";
      nameValueCollection.Add("AMORTDATE_11", str398);
      string str399 = "";
      nameValueCollection.Add("AMORTDATE_12", str399);
      string str400 = "";
      nameValueCollection.Add("AMORTDATE_13", str400);
      string str401 = "";
      nameValueCollection.Add("AMORTDATE_14", str401);
      string str402 = "";
      nameValueCollection.Add("AMORTDATE_15", str402);
      string str403 = "";
      nameValueCollection.Add("AMORTDATE_16", str403);
      string str404 = "";
      nameValueCollection.Add("AMORTDATE_17", str404);
      string str405 = "";
      nameValueCollection.Add("AMORTDATE_18", str405);
      string str406 = "";
      nameValueCollection.Add("AMORTDATE_19", str406);
      string str407 = "";
      nameValueCollection.Add("AMORTDATE_20", str407);
      string str408 = "";
      nameValueCollection.Add("AMORTDATE_21", str408);
      string str409 = "";
      nameValueCollection.Add("AMORTDATE_22", str409);
      string str410 = "";
      nameValueCollection.Add("AMORTDATE_23", str410);
      string str411 = "";
      nameValueCollection.Add("AMORTDATE_24", str411);
      string str412 = "";
      nameValueCollection.Add("AMORTDATE_25", str412);
      string str413 = "";
      nameValueCollection.Add("AMORTDATE_26", str413);
      string str414 = "";
      nameValueCollection.Add("AMORTDATE_27", str414);
      string str415 = "";
      nameValueCollection.Add("AMORTDATE_28", str415);
      string str416 = "";
      nameValueCollection.Add("AMORTDATE_29", str416);
      string str417 = "";
      nameValueCollection.Add("AMORTDATE_30", str417);
      string str418 = "";
      nameValueCollection.Add("AMORTDATE_31", str418);
      string str419 = "";
      nameValueCollection.Add("AMORTDATE_32", str419);
      string str420 = "";
      nameValueCollection.Add("AMORTDATE_33", str420);
      string str421 = "";
      nameValueCollection.Add("AMORTDATE_34", str421);
      string str422 = "";
      nameValueCollection.Add("AMORTDATE_35", str422);
      string str423 = "";
      nameValueCollection.Add("AMORTDATE_36", str423);
      string str424 = "";
      nameValueCollection.Add("AMORTDATE_37", str424);
      string str425 = "";
      nameValueCollection.Add("AMORTDATE_38", str425);
      string str426 = "";
      nameValueCollection.Add("AMORTDATE_39", str426);
      string str427 = "";
      nameValueCollection.Add("AMORTDATE_40", str427);
      string str428 = "";
      nameValueCollection.Add("AMORTDATE_41", str428);
      string str429 = "";
      nameValueCollection.Add("AMORTDATE_42", str429);
      string str430 = "";
      nameValueCollection.Add("AMORTDATE_43", str430);
      string str431 = "";
      nameValueCollection.Add("AMORTDATE_44", str431);
      string str432 = "";
      nameValueCollection.Add("AMORTDATE_45", str432);
      string str433 = "";
      nameValueCollection.Add("AMORTDATE_46", str433);
      string str434 = "";
      nameValueCollection.Add("AMORTDATE_47", str434);
      string str435 = "";
      nameValueCollection.Add("AMORTDATE_48", str435);
      string str436 = "";
      nameValueCollection.Add("AMORTDATE_49", str436);
      string str437 = "";
      nameValueCollection.Add("AMORTDATE_50", str437);
      string str438 = "";
      nameValueCollection.Add("AMORTDATE_51", str438);
      string str439 = "";
      nameValueCollection.Add("AMORTDATE_52", str439);
      string str440 = "";
      nameValueCollection.Add("AMORTDATE_53", str440);
      string str441 = "";
      nameValueCollection.Add("AMORTDATE_54", str441);
      string str442 = "";
      nameValueCollection.Add("AMORTDATE_55", str442);
      string str443 = "";
      nameValueCollection.Add("AMORTDATE_56", str443);
      string str444 = "";
      nameValueCollection.Add("AMORTDATE_57", str444);
      string str445 = "";
      nameValueCollection.Add("AMORTDATE_58", str445);
      string str446 = "";
      nameValueCollection.Add("AMORTDATE_59", str446);
      string str447 = "";
      nameValueCollection.Add("AMORTDATE_60", str447);
      string str448 = "";
      nameValueCollection.Add("AMORTDATE_61", str448);
      string str449 = "";
      nameValueCollection.Add("AMORTDATE_62", str449);
      string str450 = "";
      nameValueCollection.Add("AMORTDATE_63", str450);
      string str451 = "";
      nameValueCollection.Add("AMORTDATE_64", str451);
      string str452 = "";
      nameValueCollection.Add("AMORTDATE_65", str452);
      string str453 = "";
      nameValueCollection.Add("AMORTDATE_66", str453);
      string str454 = "";
      nameValueCollection.Add("AMORTDATE_67", str454);
      string str455 = "";
      nameValueCollection.Add("AMORTDATE_68", str455);
      string str456 = "";
      nameValueCollection.Add("AMORTDATE_69", str456);
      string str457 = "";
      nameValueCollection.Add("AMORTDATE_70", str457);
      string str458 = "";
      nameValueCollection.Add("AMORTDATE_71", str458);
      string str459 = "";
      nameValueCollection.Add("AMORTDATE_72", str459);
      return nameValueCollection;
    }
  }
}
