// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._FILE_CONTACTS_PG_3CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _FILE_CONTACTS_PG_3CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "11");
      nameValueCollection.Add("11", str1);
      string str2 = JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "12"), "", false) != 0, ",") + " " + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("12_14_15", str2);
      string str3 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "363"), "//", false) != 0, JS.GetStr(loan, "363"));
      nameValueCollection.Add("363", str3);
      string str4 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str4);
      string str5 = JS.GetStr(loan, "VEND.X178");
      nameValueCollection.Add("VENDX178", str5);
      string str6 = JS.GetStr(loan, "VEND.X179");
      nameValueCollection.Add("VENDX179", str6);
      string str7 = JS.GetStr(loan, "VEND.X180") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X180"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X181") + " " + JS.GetStr(loan, "VEND.X182");
      nameValueCollection.Add("VENDX180_VENDX181_VENDX182", str7);
      string str8 = JS.GetStr(loan, "VEND.X183");
      nameValueCollection.Add("VENDX183", str8);
      string str9 = JS.GetStr(loan, "VEND.X184");
      nameValueCollection.Add("VENDX184", str9);
      string str10 = JS.GetStr(loan, "VEND.X185");
      nameValueCollection.Add("VENDX185", str10);
      string str11 = JS.GetStr(loan, "VEND.X186");
      nameValueCollection.Add("VENDX186", str11);
      string str12 = JS.GetStr(loan, "VEND.X187");
      nameValueCollection.Add("VENDX187", str12);
      string str13 = JS.GetStr(loan, "VEND.X188");
      nameValueCollection.Add("VENDX188", str13);
      string str14 = JS.GetStr(loan, "395");
      nameValueCollection.Add("VENDX189", str14);
      string str15 = JS.GetStr(loan, "VEND.X190");
      nameValueCollection.Add("VENDX190", str15);
      string str16 = JS.GetStr(loan, "VEND.X191") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X191"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X192") + " " + JS.GetStr(loan, "VEND.X193");
      nameValueCollection.Add("VENDX191_VENDX192_VENDX193", str16);
      string str17 = JS.GetStr(loan, "VEND.X194");
      nameValueCollection.Add("VENDX194", str17);
      string str18 = JS.GetStr(loan, "VEND.X195");
      nameValueCollection.Add("VENDX195", str18);
      string str19 = JS.GetStr(loan, "VEND.X196");
      nameValueCollection.Add("VENDX196", str19);
      string str20 = JS.GetStr(loan, "VEND.X197");
      nameValueCollection.Add("VENDX197", str20);
      string str21 = JS.GetStr(loan, "VEND.X198");
      nameValueCollection.Add("VENDX198", str21);
      string str22 = JS.GetStr(loan, "VEND.X199");
      nameValueCollection.Add("VENDX199", str22);
      string str23 = JS.GetStr(loan, "VEND.X200");
      nameValueCollection.Add("VENDX200", str23);
      string str24 = JS.GetStr(loan, "VEND.X201");
      nameValueCollection.Add("VENDX201", str24);
      string str25 = JS.GetStr(loan, "VEND.X202") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X202"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X203") + " " + JS.GetStr(loan, "VEND.X204");
      nameValueCollection.Add("VENDX202_VENDX203_VENDX204", str25);
      string str26 = JS.GetStr(loan, "VEND.X205");
      nameValueCollection.Add("VENDX205", str26);
      string str27 = JS.GetStr(loan, "VEND.X206");
      nameValueCollection.Add("VENDX206", str27);
      string str28 = JS.GetStr(loan, "VEND.X207");
      nameValueCollection.Add("VENDX207", str28);
      string str29 = JS.GetStr(loan, "VEND.X208");
      nameValueCollection.Add("VENDX208", str29);
      string str30 = JS.GetStr(loan, "VEND.X209");
      nameValueCollection.Add("VENDX209", str30);
      string str31 = JS.GetStr(loan, "VEND.X210");
      nameValueCollection.Add("VENDX210", str31);
      string str32 = JS.GetStr(loan, "VEND.X44");
      nameValueCollection.Add("VENDX44", str32);
      string str33 = JS.GetStr(loan, "VEND.X46");
      nameValueCollection.Add("VENDX46", str33);
      string str34 = JS.GetStr(loan, "VEND.X47") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X47"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X48") + " " + JS.GetStr(loan, "VEND.X49");
      nameValueCollection.Add("VENDX47_VENDX48_VENDX49", str34);
      string str35 = JS.GetStr(loan, "VEND.X50");
      nameValueCollection.Add("VENDX50", str35);
      string str36 = JS.GetStr(loan, "VEND.X45");
      nameValueCollection.Add("VENDX45", str36);
      string str37 = JS.GetStr(loan, "VEND.X51");
      nameValueCollection.Add("VENDX51", str37);
      string str38 = JS.GetStr(loan, "VEND.X53");
      nameValueCollection.Add("VENDX53", str38);
      string str39 = JS.GetStr(loan, "VEND.X52");
      nameValueCollection.Add("VENDX52", str39);
      string str40 = JS.GetStr(loan, "VEND.X211");
      nameValueCollection.Add("VENDX211", str40);
      string str41 = JS.GetStr(loan, "VEND.X263");
      nameValueCollection.Add("VENDX263", str41);
      string str42 = JS.GetStr(loan, "VEND.X264");
      nameValueCollection.Add("VENDX264", str42);
      string str43 = JS.GetStr(loan, "VEND.X265") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X265"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X266") + " " + JS.GetStr(loan, "VEND.X267");
      nameValueCollection.Add("VENDX265_VENDX266_VENDX267", str43);
      string str44 = JS.GetStr(loan, "VEND.X277");
      nameValueCollection.Add("VENDX277", str44);
      string str45 = JS.GetStr(loan, "VEND.X271");
      nameValueCollection.Add("VENDX271", str45);
      string str46 = JS.GetStr(loan, "VEND.X272");
      nameValueCollection.Add("VENDX272", str46);
      string str47 = JS.GetStr(loan, "VEND.X273");
      nameValueCollection.Add("VENDX273", str47);
      string str48 = JS.GetStr(loan, "VEND.X274");
      nameValueCollection.Add("VENDX274", str48);
      string str49 = JS.GetStr(loan, "VEND.X276");
      nameValueCollection.Add("VENDX276", str49);
      string str50 = JS.GetStr(loan, "VEND.X278");
      nameValueCollection.Add("VENDX278", str50);
      string str51 = JS.GetStr(loan, "VEND.X279");
      nameValueCollection.Add("VENDX279", str51);
      string str52 = JS.GetStr(loan, "VEND.X280") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X280"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X281") + " " + JS.GetStr(loan, "VEND.X282");
      nameValueCollection.Add("VENDX280_VENDX281_VENDX282", str52);
      string str53 = JS.GetStr(loan, "VEND.X292");
      nameValueCollection.Add("VENDX292", str53);
      string str54 = JS.GetStr(loan, "VEND.X286");
      nameValueCollection.Add("VENDX286", str54);
      string str55 = JS.GetStr(loan, "VEND.X287");
      nameValueCollection.Add("VENDX287", str55);
      string str56 = JS.GetStr(loan, "VEND.X288");
      nameValueCollection.Add("VENDX288", str56);
      string str57 = JS.GetStr(loan, "VEND.X289");
      nameValueCollection.Add("VENDX289", str57);
      string str58 = JS.GetStr(loan, "VEND.X291");
      nameValueCollection.Add("VENDX291", str58);
      string str59 = JS.GetStr(loan, "VEND.X293");
      nameValueCollection.Add("VENDX293", str59);
      string str60 = JS.GetStr(loan, "VEND.X294");
      nameValueCollection.Add("VENDX294", str60);
      string str61 = JS.GetStr(loan, "VEND.X295") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X295"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X296") + " " + JS.GetStr(loan, "VEND.X297");
      nameValueCollection.Add("VENDX295_VENDX296_VENDX297", str61);
      string str62 = JS.GetStr(loan, "VEND.X309");
      nameValueCollection.Add("VENDX309", str62);
      string str63 = JS.GetStr(loan, "VEND.X302");
      nameValueCollection.Add("VENDX302", str63);
      string str64 = JS.GetStr(loan, "VEND.X303");
      nameValueCollection.Add("VENDX303", str64);
      string str65 = JS.GetStr(loan, "VEND.X305");
      nameValueCollection.Add("VENDX305", str65);
      string str66 = JS.GetStr(loan, "VEND.X306");
      nameValueCollection.Add("VENDX306", str66);
      string str67 = JS.GetStr(loan, "VEND.X300");
      nameValueCollection.Add("VENDX300", str67);
      string str68 = JS.GetStr(loan, "VEND.X310");
      nameValueCollection.Add("VENDX310", str68);
      string str69 = JS.GetStr(loan, "VEND.X311");
      nameValueCollection.Add("VENDX311", str69);
      string str70 = JS.GetStr(loan, "VEND.X312") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X312"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X313") + " " + JS.GetStr(loan, "VEND.X314");
      nameValueCollection.Add("VENDX312_VENDX313_VENDX314", str70);
      string str71 = JS.GetStr(loan, "VEND.X322");
      nameValueCollection.Add("VENDX322", str71);
      string str72 = JS.GetStr(loan, "VEND.X317");
      nameValueCollection.Add("VENDX317", str72);
      string str73 = JS.GetStr(loan, "VEND.X318");
      nameValueCollection.Add("VENDX318", str73);
      string str74 = JS.GetStr(loan, "VEND.X319");
      nameValueCollection.Add("VENDX319", str74);
      string str75 = JS.GetStr(loan, "VEND.X320");
      nameValueCollection.Add("VENDX320", str75);
      string str76 = JS.GetStr(loan, "VEND.X321");
      nameValueCollection.Add("VENDX321", str76);
      string str77 = JS.GetStr(loan, "VEND.X84");
      nameValueCollection.Add("VENDX84", str77);
      string str78 = JS.GetStr(loan, "VEND.X54");
      nameValueCollection.Add("VENDX54", str78);
      string str79 = JS.GetStr(loan, "VEND.X56");
      nameValueCollection.Add("VENDX56", str79);
      string str80 = JS.GetStr(loan, "VEND.X57") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X57"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X58") + " " + JS.GetStr(loan, "VEND.X59");
      nameValueCollection.Add("VENDX57_VENDX58_VENDX59", str80);
      string str81 = JS.GetStr(loan, "VEND.X60");
      nameValueCollection.Add("VENDX60", str81);
      string str82 = JS.GetStr(loan, "VEND.X55");
      nameValueCollection.Add("VENDX55", str82);
      string str83 = JS.GetStr(loan, "VEND.X61");
      nameValueCollection.Add("VENDX61", str83);
      string str84 = JS.GetStr(loan, "VEND.X63");
      nameValueCollection.Add("VENDX63", str84);
      string str85 = JS.GetStr(loan, "VEND.X62");
      nameValueCollection.Add("VENDX62", str85);
      string str86 = JS.GetStr(loan, "VEND.X213");
      nameValueCollection.Add("VENDX213", str86);
      string str87 = JS.GetStr(loan, "VEND.X85");
      nameValueCollection.Add("VENDX85", str87);
      string str88 = JS.GetStr(loan, "VEND.X64");
      nameValueCollection.Add("VENDX64", str88);
      string str89 = JS.GetStr(loan, "VEND.X66");
      nameValueCollection.Add("VENDX66", str89);
      string str90 = JS.GetStr(loan, "VEND.X67") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X67"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X68") + " " + JS.GetStr(loan, "VEND.X69");
      nameValueCollection.Add("VENDX67_VENDX68_VENDX69", str90);
      string str91 = JS.GetStr(loan, "VEND.X70");
      nameValueCollection.Add("VENDX70", str91);
      string str92 = JS.GetStr(loan, "VEND.X65");
      nameValueCollection.Add("VENDX65", str92);
      string str93 = JS.GetStr(loan, "VEND.X71");
      nameValueCollection.Add("VENDX71", str93);
      string str94 = JS.GetStr(loan, "VEND.X73");
      nameValueCollection.Add("VENDX73", str94);
      string str95 = JS.GetStr(loan, "VEND.X72");
      nameValueCollection.Add("VENDX72", str95);
      string str96 = JS.GetStr(loan, "VEND.X215");
      nameValueCollection.Add("VENDX215", str96);
      return nameValueCollection;
    }
  }
}
