// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._FILE_CONTACTS_PG_2CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _FILE_CONTACTS_PG_2CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "11");
      nameValueCollection.Add("11", str1);
      string str2 = JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "12"), "", false) != 0, ",") + " " + JS.GetStr(loan, "14") + JS.GetStr(loan, "15");
      nameValueCollection.Add("12_14_15", str2);
      string str3 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "363"), "//", false) != 0, JS.GetStr(loan, "363"));
      nameValueCollection.Add("363", str3);
      string str4 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str4);
      string str5 = JS.GetStr(loan, "VEND.X144");
      nameValueCollection.Add("VENDX144", str5);
      string str6 = JS.GetStr(loan, "VEND.X145");
      nameValueCollection.Add("VENDX145", str6);
      string str7 = JS.GetStr(loan, "VEND.X146") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X146"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X147") + " " + JS.GetStr(loan, "VEND.X148");
      nameValueCollection.Add("VENDX146_VENDX147_VENDX148", str7);
      string str8 = JS.GetStr(loan, "VEND.X149");
      nameValueCollection.Add("VENDX149", str8);
      string str9 = JS.GetStr(loan, "VEND.X150");
      nameValueCollection.Add("VENDX150", str9);
      string str10 = JS.GetStr(loan, "VEND.X151");
      nameValueCollection.Add("VENDX151", str10);
      string str11 = JS.GetStr(loan, "VEND.X152");
      nameValueCollection.Add("VENDX152", str11);
      string str12 = JS.GetStr(loan, "VEND.X153");
      nameValueCollection.Add("VENDX153", str12);
      string str13 = JS.GetStr(loan, "VEND.X154");
      nameValueCollection.Add("VENDX154", str13);
      string str14 = JS.GetStr(loan, "638");
      nameValueCollection.Add("638", str14);
      string str15 = JS.GetStr(loan, "701");
      nameValueCollection.Add("701", str15);
      string str16 = JS.GetStr(loan, "702") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "702"), "", false) != 0, ",") + " " + JS.GetStr(loan, "1249") + " " + JS.GetStr(loan, "703");
      nameValueCollection.Add("702_1249_703", str16);
      string str17 = JS.GetStr(loan, "705");
      nameValueCollection.Add("705", str17);
      string str18 = JS.GetStr(loan, "704");
      nameValueCollection.Add("704", str18);
      string str19 = JS.GetStr(loan, "92");
      nameValueCollection.Add("92", str19);
      string str20 = JS.GetStr(loan, "VEND.X220");
      nameValueCollection.Add("VENDX220", str20);
      string str21 = JS.GetStr(loan, "1251");
      nameValueCollection.Add("1251", str21);
      string str22 = JS.GetStr(loan, "VEND.X412");
      nameValueCollection.Add("VENDX412", str22);
      string str23 = JS.GetStr(loan, "VEND.X413");
      nameValueCollection.Add("VENDX413", str23);
      string str24 = JS.GetStr(loan, "VEND.X414") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X414"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X415") + " " + JS.GetStr(loan, "VEND.X416");
      nameValueCollection.Add("VEND_X414_X415_X416", str24);
      string str25 = JS.GetStr(loan, "VEND.X420");
      nameValueCollection.Add("VENDX420", str25);
      string str26 = JS.GetStr(loan, "VEND.X417");
      nameValueCollection.Add("VENDX417", str26);
      string str27 = JS.GetStr(loan, "VEND.X421");
      nameValueCollection.Add("VENDX421", str27);
      string str28 = JS.GetStr(loan, "VEND.X419");
      nameValueCollection.Add("VENDX419", str28);
      string str29 = JS.GetStr(loan, "VEND.X418");
      nameValueCollection.Add("VENDX418", str29);
      string str30 = JS.GetStr(loan, "L252");
      nameValueCollection.Add("VENDX156", str30);
      string str31 = JS.GetStr(loan, "VEND.X157");
      nameValueCollection.Add("VENDX157", str31);
      string str32 = JS.GetStr(loan, "VEND.X158") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X158"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X159") + " " + JS.GetStr(loan, "VEND.X160");
      nameValueCollection.Add("VENDX158", str32);
      string str33 = JS.GetStr(loan, "VEND.X161");
      nameValueCollection.Add("VENDX161", str33);
      string str34 = JS.GetStr(loan, "VEND.X162");
      nameValueCollection.Add("VENDX162", str34);
      string str35 = JS.GetStr(loan, "VEND.X163");
      nameValueCollection.Add("VENDX163", str35);
      string str36 = JS.GetStr(loan, "VEND.X164");
      nameValueCollection.Add("VENDX164", str36);
      string str37 = JS.GetStr(loan, "VEND.X165");
      nameValueCollection.Add("VENDX165", str37);
      string str38 = JS.GetStr(loan, "VEND.X166");
      nameValueCollection.Add("VENDX166", str38);
      string str39 = JS.GetStr(loan, "L248");
      nameValueCollection.Add("706", str39);
      string str40 = JS.GetStr(loan, "708");
      nameValueCollection.Add("708", str40);
      string str41 = JS.GetStr(loan, "709") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "709"), "", false) != 0, ",") + " " + JS.GetStr(loan, "1252") + " " + JS.GetStr(loan, "710");
      nameValueCollection.Add("709", str41);
      string str42 = JS.GetStr(loan, "712");
      nameValueCollection.Add("712", str42);
      string str43 = JS.GetStr(loan, "707");
      nameValueCollection.Add("707", str43);
      string str44 = JS.GetStr(loan, "711");
      nameValueCollection.Add("711", str44);
      string str45 = JS.GetStr(loan, "93");
      nameValueCollection.Add("93", str45);
      string str46 = JS.GetStr(loan, "1254");
      nameValueCollection.Add("1254", str46);
      string str47 = JS.GetStr(loan, "VEND.X167");
      nameValueCollection.Add("VENDX167", str47);
      string str48 = JS.GetStr(loan, "VEND.X34");
      nameValueCollection.Add("VENDX34", str48);
      string str49 = JS.GetStr(loan, "VEND.X36");
      nameValueCollection.Add("VENDX36", str49);
      string str50 = JS.GetStr(loan, "VEND.X37") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X37"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X38") + " " + JS.GetStr(loan, "VEND.X39");
      nameValueCollection.Add("VENDX37", str50);
      string str51 = JS.GetStr(loan, "VEND.X40");
      nameValueCollection.Add("VENDX40", str51);
      string str52 = JS.GetStr(loan, "VEND.X35");
      nameValueCollection.Add("VENDX35", str52);
      string str53 = JS.GetStr(loan, "VEND.X41");
      nameValueCollection.Add("VENDX41", str53);
      string str54 = JS.GetStr(loan, "VEND.X43");
      nameValueCollection.Add("VENDX43", str54);
      string str55 = JS.GetStr(loan, "VEND.X42");
      nameValueCollection.Add("VENDX42", str55);
      string str56 = JS.GetStr(loan, "VEND.X168");
      nameValueCollection.Add("VENDX168", str56);
      string str57 = JS.GetStr(loan, "713");
      nameValueCollection.Add("713", str57);
      string str58 = JS.GetStr(loan, "715");
      nameValueCollection.Add("715", str58);
      string str59 = JS.GetStr(loan, "716") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "716"), "", false) != 0, ",") + " " + JS.GetStr(loan, "1253") + " " + JS.GetStr(loan, "717");
      nameValueCollection.Add("716", str59);
      string str60 = JS.GetStr(loan, "719");
      nameValueCollection.Add("719", str60);
      string str61 = JS.GetStr(loan, "714");
      nameValueCollection.Add("714", str61);
      string str62 = JS.GetStr(loan, "718");
      nameValueCollection.Add("718", str62);
      string str63 = JS.GetStr(loan, "94");
      nameValueCollection.Add("94", str63);
      string str64 = JS.GetStr(loan, "1255");
      nameValueCollection.Add("1255", str64);
      string str65 = JS.GetStr(loan, "972");
      nameValueCollection.Add("972", str65);
      string str66 = JS.GetStr(loan, "1500");
      nameValueCollection.Add("VENDX12", str66);
      string str67 = JS.GetStr(loan, "VEND.X14");
      nameValueCollection.Add("VENDX14", str67);
      string str68 = JS.GetStr(loan, "VEND.X15") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X15"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X16") + " " + JS.GetStr(loan, "VEND.X17");
      nameValueCollection.Add("VENDX15", str68);
      string str69 = JS.GetStr(loan, "VEND.X18");
      nameValueCollection.Add("VENDX18", str69);
      string str70 = JS.GetStr(loan, "VEND.X13");
      nameValueCollection.Add("VENDX13", str70);
      string str71 = JS.GetStr(loan, "VEND.X19");
      nameValueCollection.Add("VENDX19", str71);
      string str72 = JS.GetStr(loan, "VEND.X21");
      nameValueCollection.Add("VENDX21", str72);
      string str73 = JS.GetStr(loan, "VEND.X20");
      nameValueCollection.Add("VENDX20", str73);
      string str74 = JS.GetStr(loan, "VEND.X22");
      nameValueCollection.Add("VENDX22", str74);
      string str75 = JS.GetStr(loan, "624");
      nameValueCollection.Add("624", str75);
      string str76 = JS.GetStr(loan, "626");
      nameValueCollection.Add("626", str76);
      string str77 = JS.GetStr(loan, "627") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "627"), "", false) != 0, ",") + " " + JS.GetStr(loan, "1245") + " " + JS.GetStr(loan, "628");
      nameValueCollection.Add("627_1245_628", str77);
      string str78 = JS.GetStr(loan, "630");
      nameValueCollection.Add("630", str78);
      string str79 = JS.GetStr(loan, "625");
      nameValueCollection.Add("625", str79);
      string str80 = JS.GetStr(loan, "629");
      nameValueCollection.Add("629", str80);
      string str81 = JS.GetStr(loan, "90");
      nameValueCollection.Add("90", str81);
      string str82 = JS.GetStr(loan, "1247");
      nameValueCollection.Add("1247", str82);
      string str83 = JS.GetStr(loan, "VEND.X169");
      nameValueCollection.Add("VENDX169", str83);
      string str84 = JS.GetStr(loan, "REGZGFE.X8");
      nameValueCollection.Add("REGZGFEX8", str84);
      string str85 = JS.GetStr(loan, "VEND.X171");
      nameValueCollection.Add("VENDX171", str85);
      string str86 = JS.GetStr(loan, "VEND.X172") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X172"), "", false) != 0, ",") + " " + JS.GetStr(loan, "VEND.X173") + " " + JS.GetStr(loan, "VEND.X174");
      nameValueCollection.Add("VENDX172_VENDX173_VENDX174", str86);
      string str87 = JS.GetStr(loan, "VEND.X175");
      nameValueCollection.Add("VENDX175", str87);
      string str88 = JS.GetStr(loan, "984");
      nameValueCollection.Add("984", str88);
      string str89 = JS.GetStr(loan, "1410");
      nameValueCollection.Add("1410", str89);
      string str90 = JS.GetStr(loan, "1411");
      nameValueCollection.Add("1411", str90);
      string str91 = JS.GetStr(loan, "VEND.X176");
      nameValueCollection.Add("VENDX176", str91);
      string str92 = JS.GetStr(loan, "VEND.X177");
      nameValueCollection.Add("VENDX177", str92);
      return nameValueCollection;
    }
  }
}
