// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._GFE_CA___RE882_P1CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _GFE_CA___RE882_P1CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "68"), "", false) != 0 | Operators.CompareString(JS.GetStr(loan, "69"), "", false) != 0, ", ", "") + JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("36_37_68_69", str1);
      string str2 = JS.GetStr(loan, "11") + "  " + JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("11_12_14_15", str2);
      string str3 = JS.GetStr(loan, "RE88395.X150");
      nameValueCollection.Add("RE88395X150", str3);
      string str4 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1264"), "", false) != 0, JS.GetStr(loan, "1264") + "   ", "") + JS.GetStr(loan, "1257") + "  " + JS.GetStr(loan, "1258") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1259"), "", false) != 0, ", ") + JS.GetStr(loan, "1259") + " " + JS.GetStr(loan, "1260");
      nameValueCollection.Add("1264_1257_1258_1259_1260", str4);
      string str5 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1264"), "", false) == 0, "X", "");
      nameValueCollection.Add("1264_UNKNOWN", str5);
      string str6 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X18"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X147"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X18") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X147"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X18", str6);
      string str7 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X4"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X136"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X4") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X136"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X4", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X7"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X137"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X7") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X137"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X7", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X10"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X231"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X10") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X231"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X10", str9);
      string str10 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X9"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X231"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X9") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X231"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X9", str10);
      string str11 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X13"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X232"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X13") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X232"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X13", str11);
      string str12 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X12"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X232"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X232"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X12", str12);
      string str13 = JS.GetStr(loan, "RE88395.X16");
      nameValueCollection.Add("RE88395X16", str13);
      string str14 = JS.GetStr(loan, "RE88395.X15");
      nameValueCollection.Add("RE88395X15", str14);
      string str15 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X22"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X141"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X22") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X141"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X22", str15);
      string str16 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X21"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X141"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X21") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X141"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X21", str16);
      string str17 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X25"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X233"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X25") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X233"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X25", str17);
      string str18 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X24"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X233"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X24") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X233"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X24", str18);
      string str19 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X28"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X142"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X28") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X142"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X28", str19);
      string str20 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X27"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X142"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X27") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X142"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X27", str20);
      string str21 = JS.GetStr(loan, "RE88395.X31");
      nameValueCollection.Add("RE88395X31", str21);
      string str22 = JS.GetStr(loan, "RE88395.X30");
      nameValueCollection.Add("RE88395X30", str22);
      string str23 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "617"), "", false) != 0, "To: " + JS.GetStr(loan, "617"));
      nameValueCollection.Add("617", str23);
      string str24 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "624"), "", false) != 0, "To: " + JS.GetStr(loan, "624"));
      nameValueCollection.Add("624", str24);
      string str25 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "L224"), "", false) != 0, "To: " + JS.GetStr(loan, "L224"));
      nameValueCollection.Add("L224", str25);
      string str26 = JS.GetStr(loan, "332");
      nameValueCollection.Add("332", str26);
      string str27 = JS.GetStr(loan, "333");
      nameValueCollection.Add("333", str27);
      string str28 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X40"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X157"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X40") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X157"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X40", str28);
      string str29 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X39"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X157"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X39") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X157"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X39", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X46"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X159"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X46") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X159"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X46", str30);
      string str31 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X45"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X159"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X45") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X159"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X45", str31);
      string str32 = JS.GetStr(loan, "RE88395.X194");
      nameValueCollection.Add("RE88395X194", str32);
      string str33 = JS.GetStr(loan, "RE88395.X195");
      nameValueCollection.Add("RE88395X195", str33);
      string str34 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X43"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X158"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X43") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X158"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X43", str34);
      string str35 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X42"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X158"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X42") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X158"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X42", str35);
      string str36 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X52"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X235"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X52") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X235"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X52", str36);
      string str37 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X51"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X235"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X51") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X235"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X51", str37);
      string str38 = JS.GetStr(loan, "L259");
      nameValueCollection.Add("L259", str38);
      string str39 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X57"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X161"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X57") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X161"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X57", str39);
      string str40 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X56"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X161"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X56") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X161"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X56", str40);
      string str41 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "L252"), "", false) != 0, "To: " + JS.GetStr(loan, "L252"));
      nameValueCollection.Add("L252", str41);
      string str42 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1955"), "", false) != 0, "To: " + JS.GetStr(loan, "1955"));
      nameValueCollection.Add("1955", str42);
      string str43 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "L248"), "", false) != 0, "To: " + JS.GetStr(loan, "L248"));
      nameValueCollection.Add("L248", str43);
      string str44 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1956"), "", false) != 0, "To: " + JS.GetStr(loan, "1956"));
      nameValueCollection.Add("1956", str44);
      string str45 = JS.GetStr(loan, "1387");
      nameValueCollection.Add("1387", str45);
      string str46 = JS.GetStr(loan, "230");
      nameValueCollection.Add("230", str46);
      string str47 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X146"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X162"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X146") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X162"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X146", str47);
      string str48 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X60"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X162"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X60") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X162"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X60", str48);
      string str49 = JS.GetStr(loan, "1386");
      nameValueCollection.Add("1386", str49);
      string str50 = JS.GetStr(loan, "231");
      nameValueCollection.Add("231", str50);
      string str51 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X41"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X165"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X41") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X165"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X41", str51);
      string str52 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X44"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X165"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X44") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X165"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X44", str52);
      string str53 = JS.GetStr(loan, "1296");
      nameValueCollection.Add("1296", str53);
      string str54 = JS.GetStr(loan, "232");
      nameValueCollection.Add("232", str54);
      string str55 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X147"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X163"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X147") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X163"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X147", str55);
      string str56 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X63"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X163"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X63") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X163"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X63", str56);
      string str57 = JS.GetStr(loan, "1628");
      nameValueCollection.Add("1628", str57);
      string str58 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X160"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X239"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X160") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X239"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X160", str58);
      string str59 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X59"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X239"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X59") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X239"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X59", str59);
      string str60 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE882.X56"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X758"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE882.X56") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X758"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE882X56", str60);
      string str61 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE882.X57"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X758"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE882.X57") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X758"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE882X57", str61);
      string str62 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X77"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X174"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X77") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X174"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X77", str62);
      string str63 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X76"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X174"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X76") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X174"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X76", str63);
      string str64 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X80"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X175"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X80") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X175"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X80", str64);
      string str65 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X79"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X175"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X79") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X175"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X79", str65);
      string str66 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE882.X11"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X760"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE882.X11") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X760"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE882X11", str66);
      string str67 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE882.X12"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X760"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE882.X12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X760"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE882X12", str67);
      string str68 = JS.GetStr(loan, "NEWHUD.X208");
      nameValueCollection.Add("NEWHUDX208", str68);
      string str69 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE882.X58"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X763"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE882.X58") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X763"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE882X58", str69);
      string str70 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE882.X59"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X763"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE882.X59") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X763"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE882X59", str70);
      string str71 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X203"), "", false) != 0, "To: " + JS.GetStr(loan, "NEWHUD.X203"));
      nameValueCollection.Add("NEWHUDX203", str71);
      string str72 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "395"), "", false) != 0, "To: " + JS.GetStr(loan, "395"));
      nameValueCollection.Add("395", str72);
      string str73 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "391"), "", false) != 0, "To: " + JS.GetStr(loan, "391"));
      nameValueCollection.Add("391", str73);
      string str74 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X205"), "", false) != 0, "To: " + JS.GetStr(loan, "NEWHUD.X205"));
      nameValueCollection.Add("NEWHUDX205", str74);
      string str75 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X91"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X182"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X91") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X182"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X91", str75);
      string str76 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X90"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X182"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X90") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X182"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X90", str76);
      string str77 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X94"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X183"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X94") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X183"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X94", str77);
      string str78 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X93"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X183"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X93") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X183"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X93", str78);
      string str79 = JS.GetStr(loan, "373");
      nameValueCollection.Add("373", str79);
      string str80 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X99"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X185"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X99") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X185"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X99", str80);
      string str81 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X98"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X185"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X98") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X185"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X98", str81);
      string str82 = JS.GetStr(loan, "1636");
      nameValueCollection.Add("1636", str82);
      string str83 = JS.GetStr(loan, "1637");
      nameValueCollection.Add("1637", str83);
      string str84 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X15"), "", false) != 0, "To: " + JS.GetStr(loan, "REGZGFE.X15"));
      nameValueCollection.Add("REGZGFEX15", str84);
      string str85 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X102"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X187"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X102") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X187"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X102", str85);
      string str86 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "RE88395.X101"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X187"), "Y", false) == 0, "(") + JS.GetStr(loan, "RE88395.X101") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X187"), "Y", false) == 0, ")"));
      nameValueCollection.Add("RE88395X101", str86);
      string str87 = JS.GetStr(loan, "RE882.X30");
      nameValueCollection.Add("RE882X30", str87);
      string str88 = JS.GetStr(loan, "RE882.X31");
      nameValueCollection.Add("RE882X31", str88);
      string str89 = JS.GetStr(loan, "RE88395.X152");
      nameValueCollection.Add("RE88395X152", str89);
      string str90 = JS.GetStr(loan, "RE88395.X153");
      nameValueCollection.Add("RE88395X153", str90);
      string str91 = JS.GetStr(loan, "RE88395.X108");
      nameValueCollection.Add("RE88395X108", str91);
      string str92 = JS.GetStr(loan, "RE882.X66");
      nameValueCollection.Add("RE882X66", str92);
      string str93 = JS.GetStr(loan, "RE882.X67");
      nameValueCollection.Add("RE882X67", str93);
      string str94 = JS.GetStr(loan, "RE882.X63");
      nameValueCollection.Add("RE882X63", str94);
      return nameValueCollection;
    }
  }
}
