// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._HUD_1A__2010__P1CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _HUD_1A__2010__P1CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "1868");
      nameValueCollection.Add("1868", str1);
      string str2 = JS.GetStr(loan, "1873");
      nameValueCollection.Add("1873", str2);
      string str3 = JS.GetStr(loan, "FR0104");
      nameValueCollection.Add("FR0104", str3);
      string str4 = JS.GetStr(loan, "FR0106") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0107"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0107") + " " + JS.GetStr(loan, "FR0108");
      nameValueCollection.Add("FR0106_FR0107_FR0108", str4);
      string str5 = JS.GetStr(loan, "11");
      nameValueCollection.Add("11", str5);
      string str6 = JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("12_14_15", str6);
      string str7 = JS.GetStr(loan, "1264");
      nameValueCollection.Add("1264", str7);
      string str8 = JS.GetStr(loan, "1257");
      nameValueCollection.Add("1257", str8);
      string str9 = JS.GetStr(loan, "1258") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1259"), "", false) != 0, ", ") + JS.GetStr(loan, "1259") + " " + JS.GetStr(loan, "1260");
      nameValueCollection.Add("1258_1259_1260", str9);
      string str10 = JS.GetStr(loan, "L75");
      nameValueCollection.Add("L75", str10);
      string str11 = JS.GetStr(loan, "L74");
      nameValueCollection.Add("L74", str11);
      string str12 = JS.GetStr(loan, "L76");
      nameValueCollection.Add("L76", str12);
      string str13 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str13);
      string str14 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str14);
      string str15 = JS.GetStr(loan, "HUD1A.X33");
      nameValueCollection.Add("HUD1A_X33", str15);
      string str16 = JS.GetStr(loan, "L351");
      nameValueCollection.Add("L351", str16);
      string str17 = JS.GetStr(loan, "HUD1A.X31");
      nameValueCollection.Add("HUD1A_X31", str17);
      string str18 = JS.GetStr(loan, "HUD1A.X32");
      nameValueCollection.Add("HUD1A_X32", str18);
      string str19 = JS.GetStr(loan, "1868");
      nameValueCollection.Add("1868_B", str19);
      string str20 = JS.GetStr(loan, "1873");
      nameValueCollection.Add("1873_B", str20);
      string str21 = JS.GetStr(loan, "NEWHUD.X686");
      nameValueCollection.Add("NEWHUD_X686", str21);
      string str22 = JS.GetStr(loan, "NEWHUD.X687");
      nameValueCollection.Add("NEWHUD_X687", str22);
      string str23 = JS.GetStr(loan, "NEWHUD.X688");
      nameValueCollection.Add("NEWHUD_X688", str23);
      string str24 = JS.GetStr(loan, "617");
      nameValueCollection.Add("617", str24);
      string str25 = JS.GetStr(loan, "641");
      nameValueCollection.Add("641", str25);
      string str26 = JS.GetStr(loan, "624");
      nameValueCollection.Add("624", str26);
      string str27 = JS.GetStr(loan, "640");
      nameValueCollection.Add("640", str27);
      string str28 = JS.GetStr(loan, "L224");
      nameValueCollection.Add("L224", str28);
      string str29 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X399"), "", false) != 0, "to " + JS.GetStr(loan, "NEWHUD.X399"), "");
      nameValueCollection.Add("NEWHUD_X399", str29);
      string str30 = JS.GetStr(loan, "336");
      nameValueCollection.Add("336", str30);
      string str31 = JS.GetStr(loan, "NEWHUD.X400");
      nameValueCollection.Add("NEWHUD_X400", str31);
      string str32 = JS.GetStr(loan, "NEWHUD.X126") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1050"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1050"), "");
      nameValueCollection.Add("NEWHUD_X126", str32);
      string str33 = JS.GetStr(loan, "NEWHUD.X127") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1051"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1051"), "");
      nameValueCollection.Add("NEWHUD_X127", str33);
      string str34 = JS.GetStr(loan, "NEWHUD.X128") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1052"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1052"), "");
      nameValueCollection.Add("NEWHUD_X128", str34);
      string str35 = JS.GetStr(loan, "NEWHUD.X129") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1053"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1053"), "");
      nameValueCollection.Add("NEWHUD_X129", str35);
      string str36 = JS.GetStr(loan, "NEWHUD.X130") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1054"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1054"), "");
      nameValueCollection.Add("NEWHUD_X130", str36);
      string str37 = JS.GetStr(loan, "NEWHUD.X136");
      nameValueCollection.Add("NEWHUD_X136", str37);
      string str38 = JS.GetStr(loan, "NEWHUD.X137");
      nameValueCollection.Add("NEWHUD_X137", str38);
      string str39 = JS.GetStr(loan, "NEWHUD.X138");
      nameValueCollection.Add("NEWHUD_X138", str39);
      string str40 = JS.GetStr(loan, "NEWHUD.X139");
      nameValueCollection.Add("NEWHUD_X139", str40);
      string str41 = JS.GetStr(loan, "NEWHUD.X140");
      nameValueCollection.Add("NEWHUD_X140", str41);
      string str42 = JS.GetStr(loan, "369") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1055"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1055"), "");
      nameValueCollection.Add("369", str42);
      string str43 = JS.GetStr(loan, "370");
      nameValueCollection.Add("370", str43);
      string str44 = JS.GetStr(loan, "371") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1056"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1056"), "");
      nameValueCollection.Add("371", str44);
      string str45 = JS.GetStr(loan, "372");
      nameValueCollection.Add("372", str45);
      string str46 = JS.GetStr(loan, "348") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1057"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1057"), "");
      nameValueCollection.Add("348", str46);
      string str47 = JS.GetStr(loan, "349");
      nameValueCollection.Add("349", str47);
      string str48 = JS.GetStr(loan, "931") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1058"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1058"), "");
      nameValueCollection.Add("931", str48);
      string str49 = JS.GetStr(loan, "932");
      nameValueCollection.Add("932", str49);
      string str50 = JS.GetStr(loan, "1390") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1059"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1059"), "");
      nameValueCollection.Add("1390", str50);
      string str51 = JS.GetStr(loan, "1009");
      nameValueCollection.Add("1009", str51);
      string str52 = JS.GetStr(loan, "410") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1060"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1060"), "");
      nameValueCollection.Add("410", str52);
      string str53 = JS.GetStr(loan, "554");
      nameValueCollection.Add("554", str53);
      string str54 = JS.GetStr(loan, "NEWHUD.X656") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1061"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1061"), "");
      nameValueCollection.Add("NEWHUD_X656", str54);
      string str55 = JS.GetStr(loan, "NEWHUD.X657");
      nameValueCollection.Add("NEWHUD_X657", str55);
      string str56 = JS.GetStr(loan, "L244");
      nameValueCollection.Add("L244", str56);
      string str57 = JS.GetStr(loan, "L245");
      nameValueCollection.Add("L245", str57);
      string str58 = JS.GetStr(loan, "332");
      nameValueCollection.Add("332", str58);
      string str59 = JS.GetStr(loan, "333");
      nameValueCollection.Add("333", str59);
      string str60 = JS.GetStr(loan, "334");
      nameValueCollection.Add("334", str60);
      string str61 = JS.GetStr(loan, "1209");
      nameValueCollection.Add("1209", str61);
      string str62 = JS.GetStr(loan, "L248");
      nameValueCollection.Add("L248", str62);
      string str63 = JS.GetStr(loan, "337");
      nameValueCollection.Add("337", str63);
      string str64 = JS.GetStr(loan, "L252");
      nameValueCollection.Add("L252", str64);
      string str65 = JS.GetStr(loan, "642");
      nameValueCollection.Add("642", str65);
      string str66 = JS.GetStr(loan, "NEWHUD.X582") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1062"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1062"), "");
      nameValueCollection.Add("NEWHUD_X582", str66);
      string str67 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1956"), "", false) != 0, "to " + JS.GetStr(loan, "1956"), "");
      nameValueCollection.Add("1956", str67);
      string str68 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1500"), "", false) != 0, "to " + JS.GetStr(loan, "1500"), "");
      nameValueCollection.Add("1500", str68);
      string str69 = JS.GetStr(loan, "NEWHUD.X591");
      nameValueCollection.Add("NEWHUD_X591", str69);
      string str70 = JS.GetStr(loan, "1050");
      nameValueCollection.Add("1050", str70);
      string str71 = JS.GetStr(loan, "643");
      nameValueCollection.Add("643", str71);
      string str72 = JS.GetStr(loan, "L259") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1063"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1063"), "");
      nameValueCollection.Add("L259", str72);
      string str73 = JS.GetStr(loan, "L260");
      nameValueCollection.Add("L260", str73);
      string str74 = JS.GetStr(loan, "1666") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1064"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1064"), "");
      nameValueCollection.Add("1666", str74);
      string str75 = JS.GetStr(loan, "1667");
      nameValueCollection.Add("1667", str75);
      string str76 = JS.GetStr(loan, "NEWHUD.X583") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1065"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1065"), "");
      nameValueCollection.Add("NEWHUD_X583", str76);
      string str77 = JS.GetStr(loan, "NEWHUD.X592");
      nameValueCollection.Add("NEWHUD_X592", str77);
      string str78 = JS.GetStr(loan, "NEWHUD.X584") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1066"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1066"), "");
      nameValueCollection.Add("NEWHUD_X584", str78);
      string str79 = JS.GetStr(loan, "NEWHUD.X593");
      nameValueCollection.Add("NEWHUD_X593", str79);
      string str80 = JS.GetStr(loan, "NEWHUD.X1719");
      nameValueCollection.Add("NEWHUD_X1719", str80);
      string str81 = JS.GetStr(loan, "1387");
      nameValueCollection.Add("1387", str81);
      string str82 = JS.GetStr(loan, "230");
      nameValueCollection.Add("230", str82);
      string str83 = JS.GetStr(loan, "656");
      nameValueCollection.Add("656", str83);
      string str84 = JS.GetStr(loan, "1296");
      nameValueCollection.Add("1296", str84);
      string str85 = JS.GetStr(loan, "232");
      nameValueCollection.Add("232", str85);
      string str86 = JS.GetStr(loan, "338");
      nameValueCollection.Add("338", str86);
      string str87 = JS.GetStr(loan, "1386");
      nameValueCollection.Add("1386", str87);
      string str88 = JS.GetStr(loan, "231");
      nameValueCollection.Add("231", str88);
      string str89 = JS.GetStr(loan, "655");
      nameValueCollection.Add("655", str89);
      string str90 = JS.GetStr(loan, "L267");
      nameValueCollection.Add("L267", str90);
      string str91 = JS.GetStr(loan, "L268");
      nameValueCollection.Add("L268", str91);
      string str92 = JS.GetStr(loan, "L269");
      nameValueCollection.Add("L269", str92);
      string str93 = JS.GetStr(loan, "1388");
      nameValueCollection.Add("1388", str93);
      string str94 = JS.GetStr(loan, "235");
      nameValueCollection.Add("235", str94);
      string str95 = JS.GetStr(loan, "657");
      nameValueCollection.Add("657", str95);
      string str96 = JS.GetStr(loan, "1628") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X341"), "", false) != 0, " to " + JS.GetStr(loan, "VEND.X341"), "");
      nameValueCollection.Add("1628", str96);
      string str97 = JS.GetStr(loan, "1629");
      nameValueCollection.Add("1629", str97);
      string str98 = JS.GetStr(loan, "1630");
      nameValueCollection.Add("1630", str98);
      string str99 = JS.GetStr(loan, "1631");
      nameValueCollection.Add("1631", str99);
      string str100 = JS.GetStr(loan, "660") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X350"), "", false) != 0, " to " + JS.GetStr(loan, "VEND.X350"), "");
      nameValueCollection.Add("660", str100);
      string str101 = JS.GetStr(loan, "340");
      nameValueCollection.Add("340", str101);
      string str102 = JS.GetStr(loan, "253");
      nameValueCollection.Add("253", str102);
      string str103 = JS.GetStr(loan, "658");
      nameValueCollection.Add("658", str103);
      string str104 = JS.GetStr(loan, "661") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X359"), "", false) != 0, " to " + JS.GetStr(loan, "VEND.X359"), "");
      nameValueCollection.Add("661", str104);
      string str105 = JS.GetStr(loan, "341");
      nameValueCollection.Add("341", str105);
      string str106 = JS.GetStr(loan, "254");
      nameValueCollection.Add("254", str106);
      string str107 = JS.GetStr(loan, "659");
      nameValueCollection.Add("659", str107);
      string str108 = JS.GetStr(loan, "558");
      nameValueCollection.Add("558", str108);
      return nameValueCollection;
    }
  }
}
