// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._HUD1PG3_2010CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _HUD1PG3_2010CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      nameValueCollection.Add("NEWHUD_X12", JS.GetStr(loan, "NEWHUD.X12"));
      nameValueCollection.Add("NEWHUD_X13", JS.GetStr(loan, "NEWHUD.X13"));
      nameValueCollection.Add("NEWHUD_X16", JS.GetStr(loan, "NEWHUD.X16"));
      nameValueCollection.Add("NEWHUD_X76", JS.GetStr(loan, "NEWHUD.X76"));
      nameValueCollection.Add("NEWHUD_X795", JS.GetStr(loan, "NEWHUD.X795"));
      nameValueCollection.Add("NEWHUD_X797", JS.GetStr(loan, "NEWHUD.X797"));
      nameValueCollection.Add("NEWHUD_X796", JS.GetStr(loan, "NEWHUD.X796"));
      nameValueCollection.Add("NEWHUD_X700", JS.GetStr(loan, "NEWHUD.X700"));
      nameValueCollection.Add("NEWHUD_X947", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X947"), "", false) != 0, "to " + JS.GetStr(loan, "NEWHUD.X947"), ""));
      nameValueCollection.Add("NEWHUD_X279", JS.GetStr(loan, "NEWHUD.X279"));
      nameValueCollection.Add("NEWHUD_X280", JS.GetStr(loan, "NEWHUD.X280"));
      nameValueCollection.Add("NEWHUD_X281", JS.GetStr(loan, "NEWHUD.X281"));
      nameValueCollection.Add("NEWHUD_X282", JS.GetStr(loan, "NEWHUD.X282"));
      nameValueCollection.Add("NEWHUD_X283", JS.GetStr(loan, "NEWHUD.X283"));
      nameValueCollection.Add("NEWHUD_X284", JS.GetStr(loan, "NEWHUD.X284"));
      nameValueCollection.Add("NEWHUD_X285", JS.GetStr(loan, "NEWHUD.X285"));
      nameValueCollection.Add("NEWHUD_X286", JS.GetStr(loan, "NEWHUD.X286"));
      nameValueCollection.Add("NEWHUD_X422", JS.GetStr(loan, "NEWHUD.X422"));
      nameValueCollection.Add("NEWHUD_X423", JS.GetStr(loan, "NEWHUD.X423"));
      nameValueCollection.Add("NEWHUD_X424", JS.GetStr(loan, "NEWHUD.X424"));
      nameValueCollection.Add("NEWHUD_X425", JS.GetStr(loan, "NEWHUD.X425"));
      nameValueCollection.Add("NEWHUD_X426", JS.GetStr(loan, "NEWHUD.X426"));
      nameValueCollection.Add("NEWHUD_X427", JS.GetStr(loan, "NEWHUD.X427"));
      nameValueCollection.Add("NEWHUD_X428", JS.GetStr(loan, "NEWHUD.X428"));
      nameValueCollection.Add("NEWHUD_X429", JS.GetStr(loan, "NEWHUD.X429"));
      nameValueCollection.Add("NEWHUD_X430", JS.GetStr(loan, "NEWHUD.X430"));
      nameValueCollection.Add("NEWHUD_X431", JS.GetStr(loan, "NEWHUD.X431"));
      nameValueCollection.Add("NEWHUD_X432", JS.GetStr(loan, "NEWHUD.X432"));
      nameValueCollection.Add("NEWHUD_X433", JS.GetStr(loan, "NEWHUD.X433"));
      nameValueCollection.Add("NEWHUD_X434", JS.GetStr(loan, "NEWHUD.X434"));
      nameValueCollection.Add("NEWHUD_X435", JS.GetStr(loan, "NEWHUD.X435"));
      nameValueCollection.Add("NEWHUD_X436", JS.GetStr(loan, "NEWHUD.X436"));
      nameValueCollection.Add("NEWHUD_X437", JS.GetStr(loan, "NEWHUD.X437"));
      nameValueCollection.Add("NEWHUD_X287", JS.GetStr(loan, "NEWHUD.X287"));
      nameValueCollection.Add("NEWHUD_X288", JS.GetStr(loan, "NEWHUD.X288"));
      nameValueCollection.Add("NEWHUD_X289", JS.GetStr(loan, "NEWHUD.X289"));
      nameValueCollection.Add("NEWHUD_X290", JS.GetStr(loan, "NEWHUD.X290"));
      nameValueCollection.Add("NEWHUD_X291", JS.GetStr(loan, "NEWHUD.X291"));
      nameValueCollection.Add("NEWHUD_X292", JS.GetStr(loan, "NEWHUD.X292"));
      nameValueCollection.Add("NEWHUD_X293", JS.GetStr(loan, "NEWHUD.X293"));
      nameValueCollection.Add("NEWHUD_X294", JS.GetStr(loan, "NEWHUD.X294"));
      nameValueCollection.Add("NEWHUD_X447", JS.GetStr(loan, "NEWHUD.X447"));
      nameValueCollection.Add("NEWHUD_X448", JS.GetStr(loan, "NEWHUD.X448"));
      nameValueCollection.Add("NEWHUD_X449", JS.GetStr(loan, "NEWHUD.X449"));
      nameValueCollection.Add("NEWHUD_X450", JS.GetStr(loan, "NEWHUD.X450"));
      nameValueCollection.Add("NEWHUD_X451", JS.GetStr(loan, "NEWHUD.X451"));
      nameValueCollection.Add("NEWHUD_X452", JS.GetStr(loan, "NEWHUD.X452"));
      nameValueCollection.Add("NEWHUD_X453", JS.GetStr(loan, "NEWHUD.X453"));
      nameValueCollection.Add("NEWHUD_X454", JS.GetStr(loan, "NEWHUD.X454"));
      nameValueCollection.Add("NEWHUD_X455", JS.GetStr(loan, "NEWHUD.X455"));
      nameValueCollection.Add("NEWHUD_X456", JS.GetStr(loan, "NEWHUD.X456"));
      nameValueCollection.Add("NEWHUD_X457", JS.GetStr(loan, "NEWHUD.X457"));
      nameValueCollection.Add("NEWHUD_X458", JS.GetStr(loan, "NEWHUD.X458"));
      nameValueCollection.Add("NEWHUD_X459", JS.GetStr(loan, "NEWHUD.X459"));
      nameValueCollection.Add("NEWHUD_X460", JS.GetStr(loan, "NEWHUD.X460"));
      nameValueCollection.Add("NEWHUD_X461", JS.GetStr(loan, "NEWHUD.X461"));
      nameValueCollection.Add("NEWHUD_X462", JS.GetStr(loan, "NEWHUD.X462"));
      nameValueCollection.Add("NEWHUD_X214", JS.GetStr(loan, "NEWHUD.X214"));
      nameValueCollection.Add("NEWHUD_X296", JS.GetStr(loan, "NEWHUD.X296"));
      nameValueCollection.Add("NEWHUD_X297", JS.GetStr(loan, "NEWHUD.X297"));
      nameValueCollection.Add("NEWHUD_X298", JS.GetStr(loan, "NEWHUD.X298"));
      nameValueCollection.Add("NEWHUD_X299", JS.GetStr(loan, "NEWHUD.X299"));
      nameValueCollection.Add("NEWHUD_X300", JS.GetStr(loan, "NEWHUD.X300"));
      nameValueCollection.Add("NEWHUD_X301", JS.GetStr(loan, "NEWHUD.X301"));
      nameValueCollection.Add("NEWHUD_X302", JS.GetStr(loan, "NEWHUD.X302"));
      nameValueCollection.Add("NEWHUD_X303", JS.GetStr(loan, "NEWHUD.X303"));
      nameValueCollection.Add("NEWHUD_X472", JS.GetStr(loan, "NEWHUD.X472"));
      nameValueCollection.Add("NEWHUD_X473", JS.GetStr(loan, "NEWHUD.X473"));
      nameValueCollection.Add("NEWHUD_X474", JS.GetStr(loan, "NEWHUD.X474"));
      nameValueCollection.Add("NEWHUD_X475", JS.GetStr(loan, "NEWHUD.X475"));
      nameValueCollection.Add("NEWHUD_X476", JS.GetStr(loan, "NEWHUD.X476"));
      nameValueCollection.Add("NEWHUD_X477", JS.GetStr(loan, "NEWHUD.X477"));
      nameValueCollection.Add("NEWHUD_X478", JS.GetStr(loan, "NEWHUD.X478"));
      nameValueCollection.Add("NEWHUD_X479", JS.GetStr(loan, "NEWHUD.X479"));
      nameValueCollection.Add("NEWHUD_X480", JS.GetStr(loan, "NEWHUD.X480"));
      nameValueCollection.Add("NEWHUD_X481", JS.GetStr(loan, "NEWHUD.X481"));
      nameValueCollection.Add("NEWHUD_X482", JS.GetStr(loan, "NEWHUD.X482"));
      nameValueCollection.Add("NEWHUD_X483", JS.GetStr(loan, "NEWHUD.X483"));
      nameValueCollection.Add("NEWHUD_X484", JS.GetStr(loan, "NEWHUD.X484"));
      nameValueCollection.Add("NEWHUD_X485", JS.GetStr(loan, "NEWHUD.X485"));
      nameValueCollection.Add("NEWHUD_X486", JS.GetStr(loan, "NEWHUD.X486"));
      nameValueCollection.Add("NEWHUD_X487", JS.GetStr(loan, "NEWHUD.X487"));
      nameValueCollection.Add("NEWHUD_X336", JS.GetStr(loan, "NEWHUD.X336"));
      nameValueCollection.Add("NEWHUD_X304", JS.GetStr(loan, "NEWHUD.X304"));
      nameValueCollection.Add("NEWHUD_X305", JS.GetStr(loan, "NEWHUD.X305"));
      nameValueCollection.Add("NEWHUD_X306", JS.GetStr(loan, "NEWHUD.X306"));
      nameValueCollection.Add("NEWHUD_X307", JS.GetStr(loan, "NEWHUD.X307"));
      nameValueCollection.Add("NEWHUD_X308", JS.GetStr(loan, "NEWHUD.X308"));
      nameValueCollection.Add("NEWHUD_X309", JS.GetStr(loan, "NEWHUD.X309"));
      nameValueCollection.Add("NEWHUD_X310", JS.GetStr(loan, "NEWHUD.X310"));
      nameValueCollection.Add("NEWHUD_X311", JS.GetStr(loan, "NEWHUD.X311"));
      nameValueCollection.Add("NEWHUD_X497", JS.GetStr(loan, "NEWHUD.X497"));
      nameValueCollection.Add("NEWHUD_X498", JS.GetStr(loan, "NEWHUD.X498"));
      nameValueCollection.Add("NEWHUD_X499", JS.GetStr(loan, "NEWHUD.X499"));
      nameValueCollection.Add("NEWHUD_X500", JS.GetStr(loan, "NEWHUD.X500"));
      nameValueCollection.Add("NEWHUD_X501", JS.GetStr(loan, "NEWHUD.X501"));
      nameValueCollection.Add("NEWHUD_X502", JS.GetStr(loan, "NEWHUD.X502"));
      nameValueCollection.Add("NEWHUD_X503", JS.GetStr(loan, "NEWHUD.X503"));
      nameValueCollection.Add("NEWHUD_X504", JS.GetStr(loan, "NEWHUD.X504"));
      nameValueCollection.Add("NEWHUD_X505", JS.GetStr(loan, "NEWHUD.X505"));
      nameValueCollection.Add("NEWHUD_X506", JS.GetStr(loan, "NEWHUD.X506"));
      nameValueCollection.Add("NEWHUD_X507", JS.GetStr(loan, "NEWHUD.X507"));
      nameValueCollection.Add("NEWHUD_X508", JS.GetStr(loan, "NEWHUD.X508"));
      nameValueCollection.Add("NEWHUD_X509", JS.GetStr(loan, "NEWHUD.X509"));
      nameValueCollection.Add("NEWHUD_X510", JS.GetStr(loan, "NEWHUD.X510"));
      nameValueCollection.Add("NEWHUD_X511", JS.GetStr(loan, "NEWHUD.X511"));
      nameValueCollection.Add("NEWHUD_X512", JS.GetStr(loan, "NEWHUD.X512"));
      nameValueCollection.Add("NEWHUD_X312", JS.GetStr(loan, "NEWHUD.X312"));
      nameValueCollection.Add("NEWHUD_X313", JS.GetStr(loan, "NEWHUD.X313"));
      nameValueCollection.Add("NEWHUD_X314", JS.GetStr(loan, "NEWHUD.X314"));
      nameValueCollection.Add("NEWHUD_X315", JS.GetStr(loan, "NEWHUD.X315"));
      nameValueCollection.Add("NEWHUD_X316", JS.GetStr(loan, "NEWHUD.X316"));
      nameValueCollection.Add("NEWHUD_X317", JS.GetStr(loan, "NEWHUD.X317"));
      nameValueCollection.Add("NEWHUD_X318", JS.GetStr(loan, "NEWHUD.X318"));
      nameValueCollection.Add("333", JS.GetStr(loan, "333"));
      nameValueCollection.Add("NEWHUD_X319", JS.GetStr(loan, "NEWHUD.X319"));
      nameValueCollection.Add("NEWHUD_X320", JS.GetStr(loan, "NEWHUD.X320"));
      nameValueCollection.Add("NEWHUD_X321", JS.GetStr(loan, "NEWHUD.X321"));
      nameValueCollection.Add("NEWHUD_X691", JS.GetStr(loan, "NEWHUD.X691"));
      nameValueCollection.Add("NEWHUD_X701", JS.GetStr(loan, "NEWHUD.X701"));
      nameValueCollection.Add("NEWHUD_X79", JS.GetStr(loan, "NEWHUD.X650"));
      nameValueCollection.Add("NEWHUD_X325", JS.GetStr(loan, "NEWHUD.X325"));
      nameValueCollection.Add("NEWHUD_X326", JS.GetStr(loan, "NEWHUD.X326"));
      nameValueCollection.Add("NEWHUD_X327", JS.GetStr(loan, "NEWHUD.X327"));
      nameValueCollection.Add("NEWHUD_X1719", JS.GetStr(loan, "NEWHUD.X1719"));
      nameValueCollection.Add("NEWHUD_X949", JS.GetStr(loan, "NEWHUD.X949"));
      nameValueCollection.Add("NEWHUD_X723", JS.GetStr(loan, "NEWHUD.X723"));
      nameValueCollection.Add("NEWHUD_X328", JS.GetStr(loan, "NEWHUD.X328"));
      nameValueCollection.Add("NEWHUD_X329", JS.GetStr(loan, "NEWHUD.X329"));
      nameValueCollection.Add("NEWHUD_X330", JS.GetStr(loan, "NEWHUD.X330"));
      nameValueCollection.Add("NEWHUD_X1095", JS.GetStr(loan, "NEWHUD.X1095"));
      nameValueCollection.Add("NEWHUD_X1096", JS.GetStr(loan, "NEWHUD.X1096"));
      nameValueCollection.Add("NEWHUD_X1097", JS.GetStr(loan, "NEWHUD.X1097"));
      nameValueCollection.Add("NEWHUD_X1098", JS.GetStr(loan, "NEWHUD.X1098"));
      nameValueCollection.Add("NEWHUD_X1099", JS.GetStr(loan, "NEWHUD.X1099"));
      nameValueCollection.Add("NEWHUD_X1100", JS.GetStr(loan, "NEWHUD.X1100"));
      nameValueCollection.Add("NEWHUD_X1101", JS.GetStr(loan, "NEWHUD.X1101"));
      nameValueCollection.Add("NEWHUD_X1102", JS.GetStr(loan, "NEWHUD.X1102"));
      nameValueCollection.Add("NEWHUD_X1103", JS.GetStr(loan, "NEWHUD.X1103"));
      nameValueCollection.Add("NEWHUD_X1104", JS.GetStr(loan, "NEWHUD.X1104"));
      nameValueCollection.Add("NEWHUD_X1105", JS.GetStr(loan, "NEWHUD.X1105"));
      nameValueCollection.Add("NEWHUD_X1106", JS.GetStr(loan, "NEWHUD.X1106"));
      nameValueCollection.Add("NEWHUD_X1107", JS.GetStr(loan, "NEWHUD.X1107"));
      nameValueCollection.Add("NEWHUD_X1108", JS.GetStr(loan, "NEWHUD.X1108"));
      nameValueCollection.Add("NEWHUD_X1109", JS.GetStr(loan, "NEWHUD.X1109"));
      nameValueCollection.Add("NEWHUD_X1110", JS.GetStr(loan, "NEWHUD.X1110"));
      nameValueCollection.Add("NEWHUD_X1111", JS.GetStr(loan, "NEWHUD.X1111"));
      nameValueCollection.Add("NEWHUD_X1112", JS.GetStr(loan, "NEWHUD.X1112"));
      nameValueCollection.Add("NEWHUD_X1113", JS.GetStr(loan, "NEWHUD.X1113"));
      nameValueCollection.Add("NEWHUD_X1114", JS.GetStr(loan, "NEWHUD.X1114"));
      nameValueCollection.Add("NEWHUD_X1115", JS.GetStr(loan, "NEWHUD.X1115"));
      nameValueCollection.Add("NEWHUD_X1116", JS.GetStr(loan, "NEWHUD.X1116"));
      nameValueCollection.Add("NEWHUD_X1117", JS.GetStr(loan, "NEWHUD.X1117"));
      nameValueCollection.Add("NEWHUD_X1118", JS.GetStr(loan, "NEWHUD.X1118"));
      nameValueCollection.Add("NEWHUD_X1119", JS.GetStr(loan, "NEWHUD.X1119"));
      nameValueCollection.Add("NEWHUD_X1120", JS.GetStr(loan, "NEWHUD.X1120"));
      nameValueCollection.Add("NEWHUD_X1121", JS.GetStr(loan, "NEWHUD.X1121"));
      nameValueCollection.Add("NEWHUD_X1122", JS.GetStr(loan, "NEWHUD.X1122"));
      nameValueCollection.Add("NEWHUD_X1123", JS.GetStr(loan, "NEWHUD.X1123"));
      nameValueCollection.Add("NEWHUD_X1124", JS.GetStr(loan, "NEWHUD.X1124"));
      nameValueCollection.Add("NEWHUD_X1125", JS.GetStr(loan, "NEWHUD.X1125"));
      nameValueCollection.Add("NEWHUD_X1126", JS.GetStr(loan, "NEWHUD.X1126"));
      nameValueCollection.Add("NEWHUD_X1127", JS.GetStr(loan, "NEWHUD.X1127"));
      nameValueCollection.Add("NEWHUD_X1128", JS.GetStr(loan, "NEWHUD.X1128"));
      nameValueCollection.Add("NEWHUD_X1129", JS.GetStr(loan, "NEWHUD.X1129"));
      nameValueCollection.Add("NEWHUD_X1130", JS.GetStr(loan, "NEWHUD.X1130"));
      nameValueCollection.Add("NEWHUD_X1131", JS.GetStr(loan, "NEWHUD.X1131"));
      nameValueCollection.Add("NEWHUD_X1132", JS.GetStr(loan, "NEWHUD.X1132"));
      nameValueCollection.Add("NEWHUD_X1133", JS.GetStr(loan, "NEWHUD.X1133"));
      nameValueCollection.Add("NEWHUD_X1134", JS.GetStr(loan, "NEWHUD.X1134"));
      nameValueCollection.Add("NEWHUD_X1135", JS.GetStr(loan, "NEWHUD.X1135"));
      nameValueCollection.Add("NEWHUD_X1136", JS.GetStr(loan, "NEWHUD.X1136"));
      nameValueCollection.Add("NEWHUD_X1137", JS.GetStr(loan, "NEWHUD.X1137"));
      nameValueCollection.Add("NEWHUD_X1138", JS.GetStr(loan, "NEWHUD.X1138"));
      nameValueCollection.Add("NEWHUD_X4", JS.GetStr(loan, "NEWHUD.X4"));
      nameValueCollection.Add("1347", JS.GetStr(loan, "1347"));
      nameValueCollection.Add("3", JS.GetStr(loan, "3"));
      nameValueCollection.Add("NEWHUD_X217", JS.GetStr(loan, "NEWHUD.X217"));
      nameValueCollection.Add("NEWHUD_X355", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X355"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X356", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X356"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X357", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X357"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X5_Y", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X5"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X5_N", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X5"), "N", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X555", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X5"), "Y", false) == 0, JS.GetStr(loan, "NEWHUD.X555"), ""));
      nameValueCollection.Add("NEWHUD_X556", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X5"), "Y", false) == 0, Jed.BF(Jed.Num(JS.GetNum(loan, "NEWHUD.X556")) == 1.0, JS.GetStr(loan, "NEWHUD.X556") + " month", Jed.BF(Jed.Num(JS.GetNum(loan, "NEWHUD.X556")) > 1.0, JS.GetStr(loan, "NEWHUD.X556") + " months", "")), ""));
      nameValueCollection.Add("NEWHUD_X557", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X5"), "Y", false) == 0, Jed.BF(Jed.Num(JS.GetNum(loan, "NEWHUD.X557")) == 1.0, JS.GetStr(loan, "NEWHUD.X557") + " month", Jed.BF(Jed.Num(JS.GetNum(loan, "NEWHUD.X557")) > 1.0, JS.GetStr(loan, "NEWHUD.X557") + " months", "")), ""));
      nameValueCollection.Add("NEWHUD_X332", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X5"), "Y", false) == 0, JS.GetStr(loan, "NEWHUD.X332")));
      nameValueCollection.Add("NEWHUD_X558", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X5"), "Y", false) == 0, JS.GetStr(loan, "NEWHUD.X558")));
      nameValueCollection.Add("NEWHUD_X333", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X5"), "Y", false) == 0, JS.GetStr(loan, "NEWHUD.X333")));
      nameValueCollection.Add("NEWHUD_X334", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X5"), "Y", false) == 0, JS.GetStr(loan, "NEWHUD.X334")));
      nameValueCollection.Add("NEWHUD_X6_Y", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X6"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X6_N", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X6"), "N", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X7", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X6"), "Y", false) == 0, JS.GetStr(loan, "NEWHUD.X7"), ""));
      nameValueCollection.Add("NEWHUD_X8_Y", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X8"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X8_N", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X8"), "N", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X9", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X8"), "Y", false) == 0, Jed.BF(Jed.Num(JS.GetNum(loan, "NEWHUD.X9")) == 1.0, JS.GetStr(loan, "NEWHUD.X9") + " month", Jed.BF(Jed.Num(JS.GetNum(loan, "NEWHUD.X9")) > 1.0, JS.GetStr(loan, "NEWHUD.X9") + " months", "")), ""));
      nameValueCollection.Add("NEWHUD_X10", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X8"), "Y", false) == 0, JS.GetStr(loan, "NEWHUD.X10"), ""));
      nameValueCollection.Add("NEWHUD_X11", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X8"), "Y", false) == 0, JS.GetStr(loan, "NEWHUD.X11"), ""));
      nameValueCollection.Add("675_Y", Jed.BF(Operators.CompareString(JS.GetStr(loan, "675"), "Y", false) == 0, "X"));
      nameValueCollection.Add("675_N", Jed.BF(Operators.CompareString(JS.GetStr(loan, "675"), "N", false) == 0, "X"));
      nameValueCollection.Add("RE88395_X315", Jed.BF(Operators.CompareString(JS.GetStr(loan, "675"), "Y", false) == 0, JS.GetStr(loan, "RE88395.X315"), ""));
      nameValueCollection.Add("1659_Y", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1659"), "Y", false) == 0, "X"));
      nameValueCollection.Add("1659_N", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1659"), "N", false) == 0, "X"));
      nameValueCollection.Add("RE88395_X121", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1659"), "Y", false) == 0, JS.GetStr(loan, "RE88395.X121"), ""));
      nameValueCollection.Add("NEWHUD_X348", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1659"), "Y", false) == 0, JS.GetStr(loan, "NEWHUD.X348"), ""));
      nameValueCollection.Add("RE88395_X122", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1659"), "Y", false) == 0, JS.GetStr(loan, "RE88395.X122"), ""));
      nameValueCollection.Add("NEWHUD_X335_N", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X335"), "No", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X335_Y", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X335"), "Yes", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X950", JS.GetStr(loan, "NEWHUD.X950"));
      nameValueCollection.Add("NEWHUD_X802", JS.GetStr(loan, "NEWHUD.X802"));
      nameValueCollection.Add("NEWHUD_X337", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X337"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X338", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X338"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X339", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X339"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X340", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X340"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X341", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X341"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X342", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X342"), "Y", false) == 0, "X"));
      nameValueCollection.Add("NEWHUD_X343", Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X343"), "Y", false) == 0, "X"));
      nameValueCollection.Add("1628", JS.GetStr(loan, "1628"));
      nameValueCollection.Add("660", JS.GetStr(loan, "660"));
      nameValueCollection.Add("661", JS.GetStr(loan, "661"));
      return nameValueCollection;
    }
  }
}
