// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._HUD_1ESCLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _HUD_1ESCLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str1);
      string str2 = JS.GetStr(loan, "VEND.X184");
      nameValueCollection.Add("611", str2);
      string str3 = JS.GetStr(loan, "VEND.X179");
      nameValueCollection.Add("631", str3);
      string str4 = JS.GetStr(loan, "VEND.X180") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "VEND.X181"), "", false) != 0, ", ") + JS.GetStr(loan, "VEND.X181") + " " + JS.GetStr(loan, "VEND.X182");
      nameValueCollection.Add("632_633_634", str4);
      string str5 = JS.GetStr(loan, "VEND.X185");
      nameValueCollection.Add("635", str5);
      string str6 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str6);
      string str7 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "682"), "//", false) == 0, "", JS.GetStr(loan, "682"));
      nameValueCollection.Add("682", str7);
      string str8 = JS.GetStr(loan, "11");
      nameValueCollection.Add("11", str8);
      string str9 = JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("12_14_15", str9);
      string str10 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "N", false) == 0 | Operators.CompareString(JS.GetStr(loan, "423"), "", false) == 0, " X");
      nameValueCollection.Add("423_Monthly", str10);
      string str11 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, " X");
      nameValueCollection.Add("423_Biweekly", str11);
      string str12 = "";
      nameValueCollection.Add("HUDPAYMENT", str12);
      string str13 = "";
      nameValueCollection.Add("HUDPANDI", str13);
      string str14 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24", str14);
      string str15 = JS.GetStr(loan, "HUD23");
      nameValueCollection.Add("HUD23", str15);
      string str16 = JS.GetStr(loan, "HUD0101");
      nameValueCollection.Add("HUD0101", str16);
      string str17 = JS.GetStr(loan, "HUD0201");
      nameValueCollection.Add("HUD0201", str17);
      string str18 = JS.GetStr(loan, "HUD0301");
      nameValueCollection.Add("HUD0301", str18);
      string str19 = JS.GetStr(loan, "HUD0401");
      nameValueCollection.Add("HUD0401", str19);
      string str20 = JS.GetStr(loan, "HUD0501");
      nameValueCollection.Add("HUD0501", str20);
      string str21 = JS.GetStr(loan, "HUD0601");
      nameValueCollection.Add("HUD0601", str21);
      string str22 = JS.GetStr(loan, "HUD0701");
      nameValueCollection.Add("HUD0701", str22);
      string str23 = JS.GetStr(loan, "HUD0801");
      nameValueCollection.Add("HUD0801", str23);
      string str24 = JS.GetStr(loan, "HUD0901");
      nameValueCollection.Add("HUD0901", str24);
      string str25 = JS.GetStr(loan, "HUD1001");
      nameValueCollection.Add("HUD1001", str25);
      string str26 = JS.GetStr(loan, "HUD1101");
      nameValueCollection.Add("HUD1101", str26);
      string str27 = JS.GetStr(loan, "HUD1201");
      nameValueCollection.Add("HUD1201", str27);
      string str28 = JS.GetStr(loan, "HUD1301");
      nameValueCollection.Add("HUD1301", str28);
      string str29 = JS.GetStr(loan, "HUD1401");
      nameValueCollection.Add("HUD1401", str29);
      string str30 = JS.GetStr(loan, "HUD1501");
      nameValueCollection.Add("HUD1501", str30);
      string str31 = JS.GetStr(loan, "HUD1601");
      nameValueCollection.Add("HUD1601", str31);
      string str32 = JS.GetStr(loan, "HUD1701");
      nameValueCollection.Add("HUD1701", str32);
      string str33 = JS.GetStr(loan, "HUD1801");
      nameValueCollection.Add("HUD1801", str33);
      string str34 = JS.GetStr(loan, "HUD1901");
      nameValueCollection.Add("HUD1901", str34);
      string str35 = JS.GetStr(loan, "HUD2001");
      nameValueCollection.Add("HUD2001", str35);
      string str36 = JS.GetStr(loan, "HUD2101");
      nameValueCollection.Add("HUD2101", str36);
      string str37 = JS.GetStr(loan, "HUD2201");
      nameValueCollection.Add("HUD2201", str37);
      string str38 = JS.GetStr(loan, "HUD2301");
      nameValueCollection.Add("HUD2301", str38);
      string str39 = JS.GetStr(loan, "HUD2401");
      nameValueCollection.Add("HUD2401", str39);
      string str40 = JS.GetStr(loan, "HUD2501");
      nameValueCollection.Add("HUD2501", str40);
      string str41 = JS.GetStr(loan, "HUD2601");
      nameValueCollection.Add("HUD2601", str41);
      string str42 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_1", str42);
      string str43 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_2", str43);
      string str44 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_3", str44);
      string str45 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_4", str45);
      string str46 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_5", str46);
      string str47 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_6", str47);
      string str48 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_7", str48);
      string str49 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_8", str49);
      string str50 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_9", str50);
      string str51 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_10", str51);
      string str52 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_11", str52);
      string str53 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24_12", str53);
      string str54 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_13", str54);
      string str55 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_14", str55);
      string str56 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_15", str56);
      string str57 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_16", str57);
      string str58 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_17", str58);
      string str59 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_18", str59);
      string str60 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_19", str60);
      string str61 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_20", str61);
      string str62 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_21", str62);
      string str63 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_22", str63);
      string str64 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_23", str64);
      string str65 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_24", str65);
      string str66 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_25", str66);
      string str67 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, JS.GetStr(loan, "HUD24"), "");
      nameValueCollection.Add("HUD24_26", str67);
      string str68 = JS.GetStr(loan, "HUD0110");
      nameValueCollection.Add("HUD0110", str68);
      string str69 = JS.GetStr(loan, "HUD0210");
      nameValueCollection.Add("HUD0210", str69);
      string str70 = JS.GetStr(loan, "HUD0310");
      nameValueCollection.Add("HUD0310", str70);
      string str71 = JS.GetStr(loan, "HUD0410");
      nameValueCollection.Add("HUD0410", str71);
      string str72 = JS.GetStr(loan, "HUD0510");
      nameValueCollection.Add("HUD0510", str72);
      string str73 = JS.GetStr(loan, "HUD0610");
      nameValueCollection.Add("HUD0610", str73);
      string str74 = JS.GetStr(loan, "HUD0710");
      nameValueCollection.Add("HUD0710", str74);
      string str75 = JS.GetStr(loan, "HUD0810");
      nameValueCollection.Add("HUD0810", str75);
      string str76 = JS.GetStr(loan, "HUD0910");
      nameValueCollection.Add("HUD0910", str76);
      string str77 = JS.GetStr(loan, "HUD1010");
      nameValueCollection.Add("HUD1010", str77);
      string str78 = JS.GetStr(loan, "HUD1110");
      nameValueCollection.Add("HUD1110", str78);
      string str79 = JS.GetStr(loan, "HUD1210");
      nameValueCollection.Add("HUD1210", str79);
      string str80 = JS.GetStr(loan, "HUD1310");
      nameValueCollection.Add("HUD1310", str80);
      string str81 = JS.GetStr(loan, "HUD1410");
      nameValueCollection.Add("HUD1410", str81);
      string str82 = JS.GetStr(loan, "HUD1510");
      nameValueCollection.Add("HUD1510", str82);
      string str83 = JS.GetStr(loan, "HUD1610");
      nameValueCollection.Add("HUD1610", str83);
      string str84 = JS.GetStr(loan, "HUD1710");
      nameValueCollection.Add("HUD1710", str84);
      string str85 = JS.GetStr(loan, "HUD1810");
      nameValueCollection.Add("HUD1810", str85);
      string str86 = JS.GetStr(loan, "HUD1910");
      nameValueCollection.Add("HUD1910", str86);
      string str87 = JS.GetStr(loan, "HUD2010");
      nameValueCollection.Add("HUD2010", str87);
      string str88 = JS.GetStr(loan, "HUD2110");
      nameValueCollection.Add("HUD2110", str88);
      string str89 = JS.GetStr(loan, "HUD2210");
      nameValueCollection.Add("HUD2210", str89);
      string str90 = JS.GetStr(loan, "HUD2310");
      nameValueCollection.Add("HUD2310", str90);
      string str91 = JS.GetStr(loan, "HUD2410");
      nameValueCollection.Add("HUD2410", str91);
      string str92 = JS.GetStr(loan, "HUD2510");
      nameValueCollection.Add("HUD2510", str92);
      string str93 = JS.GetStr(loan, "HUD2610");
      nameValueCollection.Add("HUD2610", str93);
      string str94 = "";
      nameValueCollection.Add("HUDDESC1", str94);
      string str95 = "";
      nameValueCollection.Add("HUDDESC2", str95);
      string str96 = "";
      nameValueCollection.Add("HUDDESC3", str96);
      string str97 = "";
      nameValueCollection.Add("HUDDESC4", str97);
      string str98 = "";
      nameValueCollection.Add("HUDDESC5", str98);
      string str99 = "";
      nameValueCollection.Add("HUDDESC6", str99);
      string str100 = "";
      nameValueCollection.Add("HUDDESC7", str100);
      string str101 = "";
      nameValueCollection.Add("HUDDESC8", str101);
      string str102 = "";
      nameValueCollection.Add("HUDDESC9", str102);
      string str103 = "";
      nameValueCollection.Add("HUDDESC10", str103);
      string str104 = "";
      nameValueCollection.Add("HUDDESC11", str104);
      string str105 = "";
      nameValueCollection.Add("HUDDESC12", str105);
      string str106 = "";
      nameValueCollection.Add("HUDDESC13", str106);
      string str107 = "";
      nameValueCollection.Add("HUDDESC14", str107);
      string str108 = "";
      nameValueCollection.Add("HUDDESC15", str108);
      string str109 = "";
      nameValueCollection.Add("HUDDESC16", str109);
      string str110 = "";
      nameValueCollection.Add("HUDDESC17", str110);
      string str111 = "";
      nameValueCollection.Add("HUDDESC18", str111);
      string str112 = "";
      nameValueCollection.Add("HUDDESC19", str112);
      string str113 = "";
      nameValueCollection.Add("HUDDESC20", str113);
      string str114 = "";
      nameValueCollection.Add("HUDDESC21", str114);
      string str115 = "";
      nameValueCollection.Add("HUDDESC22", str115);
      string str116 = "";
      nameValueCollection.Add("HUDDESC23", str116);
      string str117 = "";
      nameValueCollection.Add("HUDDESC24", str117);
      string str118 = "";
      nameValueCollection.Add("HUDDESC25", str118);
      string str119 = "";
      nameValueCollection.Add("HUDDESC26", str119);
      string str120 = "";
      nameValueCollection.Add("HUDDESC27", str120);
      string str121 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD0111")), (byte) 2, 0);
      nameValueCollection.Add("HUD0111", str121);
      string str122 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD0211")), (byte) 2, 0);
      nameValueCollection.Add("HUD0211", str122);
      string str123 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD0311")), (byte) 2, 0);
      nameValueCollection.Add("HUD0311", str123);
      string str124 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD0411")), (byte) 2, 0);
      nameValueCollection.Add("HUD0411", str124);
      string str125 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD0511")), (byte) 2, 0);
      nameValueCollection.Add("HUD0511", str125);
      string str126 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD0611")), (byte) 2, 0);
      nameValueCollection.Add("HUD0611", str126);
      string str127 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD0711")), (byte) 2, 0);
      nameValueCollection.Add("HUD0711", str127);
      string str128 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD0811")), (byte) 2, 0);
      nameValueCollection.Add("HUD0811", str128);
      string str129 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD0911")), (byte) 2, 0);
      nameValueCollection.Add("HUD0911", str129);
      string str130 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD1011")), (byte) 2, 0);
      nameValueCollection.Add("HUD1011", str130);
      string str131 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD1111")), (byte) 2, 0);
      nameValueCollection.Add("HUD1111", str131);
      string str132 = Jed.NF(Jed.Num(JS.GetNum(loan, "HUD1211")), (byte) 2, 0);
      nameValueCollection.Add("HUD1211", str132);
      string str133 = JS.GetStr(loan, "HUD1311");
      nameValueCollection.Add("HUD1311", str133);
      string str134 = JS.GetStr(loan, "HUD1411");
      nameValueCollection.Add("HUD1411", str134);
      string str135 = JS.GetStr(loan, "HUD1511");
      nameValueCollection.Add("HUD1511", str135);
      string str136 = JS.GetStr(loan, "HUD1611");
      nameValueCollection.Add("HUD1611", str136);
      string str137 = JS.GetStr(loan, "HUD1711");
      nameValueCollection.Add("HUD1711", str137);
      string str138 = JS.GetStr(loan, "HUD1811");
      nameValueCollection.Add("HUD1811", str138);
      string str139 = JS.GetStr(loan, "HUD1911");
      nameValueCollection.Add("HUD1911", str139);
      string str140 = JS.GetStr(loan, "HUD2011");
      nameValueCollection.Add("HUD2011", str140);
      string str141 = JS.GetStr(loan, "HUD2111");
      nameValueCollection.Add("HUD2111", str141);
      string str142 = JS.GetStr(loan, "HUD2211");
      nameValueCollection.Add("HUD2211", str142);
      string str143 = JS.GetStr(loan, "HUD2311");
      nameValueCollection.Add("HUD2311", str143);
      string str144 = JS.GetStr(loan, "HUD2411");
      nameValueCollection.Add("HUD2411", str144);
      string str145 = JS.GetStr(loan, "HUD2511");
      nameValueCollection.Add("HUD2511", str145);
      string str146 = JS.GetStr(loan, "HUD2611");
      nameValueCollection.Add("HUD2611", str146);
      string str147 = "";
      nameValueCollection.Add("HUDCUSHION", str147);
      string str148 = "";
      nameValueCollection.Add("HUDTOTAL", str148);
      string str149 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str149);
      string str150 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69", str150);
      return nameValueCollection;
    }
  }
}
