// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._HUD_1ACLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _HUD_1ACLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "1868");
      nameValueCollection.Add("1868", str1);
      string str2 = JS.GetStr(loan, "1873");
      nameValueCollection.Add("1873", str2);
      string str3 = JS.GetStr(loan, "FR0104");
      nameValueCollection.Add("FR0104", str3);
      string str4 = JS.GetStr(loan, "FR0106") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FR0107"), "", false) != 0, ", ") + JS.GetStr(loan, "FR0107") + " " + JS.GetStr(loan, "FR0108");
      nameValueCollection.Add("FR0106_FR0107_FR0108", str4);
      string str5 = JS.GetStr(loan, "11");
      nameValueCollection.Add("11", str5);
      string str6 = JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("12_14_15", str6);
      string str7 = JS.GetStr(loan, "1264");
      nameValueCollection.Add("1264", str7);
      string str8 = JS.GetStr(loan, "1257");
      nameValueCollection.Add("1257", str8);
      string str9 = JS.GetStr(loan, "1258") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1259"), "", false) != 0, ", ") + JS.GetStr(loan, "1259") + " " + JS.GetStr(loan, "1260");
      nameValueCollection.Add("1258_1259_1260", str9);
      string str10 = JS.GetStr(loan, "L75");
      nameValueCollection.Add("L75", str10);
      string str11 = JS.GetStr(loan, "L74");
      nameValueCollection.Add("L74", str11);
      string str12 = JS.GetStr(loan, "L76");
      nameValueCollection.Add("L76", str12);
      string str13 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str13);
      string str14 = JS.GetStr(loan, "2553");
      nameValueCollection.Add("2553", str14);
      string str15 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str15);
      string str16 = JS.GetStr(loan, "HUD1A.X33");
      nameValueCollection.Add("HUD1A_X33", str16);
      string str17 = JS.GetStr(loan, "L351");
      nameValueCollection.Add("L351", str17);
      string str18 = JS.GetStr(loan, "HUD1A.X31");
      nameValueCollection.Add("HUD1A_X31", str18);
      string str19 = JS.GetStr(loan, "HUD1A.X32");
      nameValueCollection.Add("HUD1A_X32", str19);
      string str20 = JS.GetStr(loan, "1868");
      nameValueCollection.Add("1868_B", str20);
      string str21 = JS.GetStr(loan, "1873");
      nameValueCollection.Add("1873_B", str21);
      string str22 = JS.GetStr(loan, "1955");
      nameValueCollection.Add("1955", str22);
      string str23 = JS.GetStr(loan, "1956");
      nameValueCollection.Add("1956", str23);
      string str24 = JS.GetStr(loan, "L248");
      nameValueCollection.Add("L248", str24);
      string str25 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X235"), "Y", false) == 0, JS.GetStr(loan, "1050") + ")", "");
      nameValueCollection.Add("1050_P", str25);
      string str26 = JS.GetStr(loan, "L244");
      nameValueCollection.Add("L244", str26);
      string str27 = JS.GetStr(loan, "L245");
      nameValueCollection.Add("L245", str27);
      string str28 = JS.GetStr(loan, "304");
      nameValueCollection.Add("304", str28);
      string str29 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X182"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("390_$", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X248"), "Y", false) == 0, JS.GetStr(loan, "1783") + ")", "");
      nameValueCollection.Add("1783_P", str30);
      string str31 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X247"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1778_$", str31);
      string str32 = JS.GetStr(loan, "1629");
      nameValueCollection.Add("1629", str32);
      string str33 = JS.GetStr(loan, "1628");
      nameValueCollection.Add("1628", str33);
      string str34 = JS.GetStr(loan, "1627");
      nameValueCollection.Add("1627", str34);
      string str35 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X243"), "Y", false) != 0, JS.GetStr(loan, "1625"), "");
      nameValueCollection.Add("1625", str35);
      string str36 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X183"), "Y", false) != 0, JS.GetStr(loan, "647"), "");
      nameValueCollection.Add("647", str36);
      string str37 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X234"), "Y", false) != 0, JS.GetStr(loan, "1623"), "");
      nameValueCollection.Add("1623", str37);
      string str38 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X233"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "GFE3"), "Y", false) != 0, JS.GetStr(loan, "1621"), "");
      nameValueCollection.Add("1621", str38);
      string str39 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X190"), "Y", false) != 0, JS.GetStr(loan, "644"), "");
      nameValueCollection.Add("644", str39);
      string str40 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X153"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1009_$", str40);
      string str41 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X159"), "Y", false) != 0, JS.GetStr(loan, "642"), "");
      nameValueCollection.Add("642", str41);
      string str42 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X293"), "Y", false) == 0, JS.GetStr(loan, "1839") + ")", "");
      nameValueCollection.Add("1839_P", str42);
      string str43 = JS.GetStr(loan, "43");
      nameValueCollection.Add("43", str43);
      string str44 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X176"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("978_$", str44);
      string str45 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X140"), "Y", false) != 0, JS.GetStr(loan, "L230"), "");
      nameValueCollection.Add("L230", str45);
      string str46 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X238"), "Y", false) == 0, JS.GetStr(loan, "1667") + ")", "");
      nameValueCollection.Add("1667_P", str46);
      string str47 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X169"), "Y", false) == 0, JS.GetStr(loan, "659") + ")", "");
      nameValueCollection.Add("659_P", str47);
      string str48 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X165"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("655_$", str48);
      string str49 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X142"), "Y", false) == 0, JS.GetStr(loan, "367") + ")", "");
      nameValueCollection.Add("367_P", str49);
      string str50 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X248"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1783_$", str50);
      string str51 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X171"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("L288_$", str51);
      string str52 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X245"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1768_$", str52);
      string str53 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X173"), "Y", false) == 0, JS.GetStr(loan, "L294") + ")", "");
      nameValueCollection.Add("L294_P", str53);
      string str54 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X141"), "Y", false) == 0, JS.GetStr(loan, "336") + ")", "");
      nameValueCollection.Add("336_P", str54);
      string str55 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X139"), "Y", false) != 0, JS.GetStr(loan, "L228"), "");
      nameValueCollection.Add("L228", str55);
      string str56 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X235"), "Y", false) != 0, JS.GetStr(loan, "1050"), "");
      nameValueCollection.Add("1050", str56);
      string str57 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X293"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1839_$", str57);
      string str58 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X155"), "Y", false) != 0, JS.GetStr(loan, "81"), "");
      nameValueCollection.Add("81", str58);
      string str59 = JS.GetStr(loan, "1762");
      nameValueCollection.Add("1762", str59);
      string str60 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X238"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1667_$", str60);
      string str61 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X169"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("659_$", str61);
      string str62 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X250"), "Y", false) == 0, JS.GetStr(loan, "1793") + ")", "");
      nameValueCollection.Add("1793_P", str62);
      string str63 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X142"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("367_$", str63);
      string str64 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X173"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("L294_$", str64);
      string str65 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X141"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("336_$", str65);
      string str66 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X388"), "Y", false) == 0, JS.GetStr(loan, "1849") + ")", "");
      nameValueCollection.Add("1849_P", str66);
      string str67 = JS.GetStr(loan, "254");
      nameValueCollection.Add("254", str67);
      string str68 = JS.GetStr(loan, "253");
      nameValueCollection.Add("253", str68);
      string str69 = JS.GetStr(loan, "661");
      nameValueCollection.Add("661", str69);
      string str70 = JS.GetStr(loan, "660");
      nameValueCollection.Add("660", str70);
      string str71 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X250"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1793_$", str71);
      string str72 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X137"), "Y", false) == 0, JS.GetStr(loan, "1093") + ")", "");
      nameValueCollection.Add("1093_P", str72);
      string str73 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X152"), "Y", false) == 0, JS.GetStr(loan, "932") + ")", "");
      nameValueCollection.Add("932_P", str73);
      string str74 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X175"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("392_$", str74);
      string str75 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X232"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "GFE2"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "449"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "449"), "", false) != 0, JS.GetStr(loan, "449") + ")", JS.GetStr(loan, "640") + ")"), "");
      nameValueCollection.Add("640_P", str75);
      string str76 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X169"), "Y", false) != 0, JS.GetStr(loan, "659"), "");
      nameValueCollection.Add("659", str76);
      string str77 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X168"), "Y", false) != 0, JS.GetStr(loan, "658"), "");
      nameValueCollection.Add("658", str77);
      string str78 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X167"), "Y", false) != 0, JS.GetStr(loan, "657"), "");
      nameValueCollection.Add("657", str78);
      string str79 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X162"), "Y", false) != 0, JS.GetStr(loan, "656"), "");
      nameValueCollection.Add("656", str79);
      string str80 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X165"), "Y", false) != 0, JS.GetStr(loan, "655"), "");
      nameValueCollection.Add("655", str80);
      string str81 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X388"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1849_$", str81);
      string str82 = JS.GetStr(loan, "652");
      nameValueCollection.Add("652", str82);
      string str83 = JS.GetStr(loan, "651");
      nameValueCollection.Add("651", str83);
      string str84 = JS.GetStr(loan, "650");
      nameValueCollection.Add("650", str84);
      string str85 = JS.GetStr(loan, "56");
      nameValueCollection.Add("56", str85);
      string str86 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X186"), "Y", false) == 0, JS.GetStr(loan, "383") + ")", "");
      nameValueCollection.Add("383_P", str86);
      string str87 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X152"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("932_$", str87);
      string str88 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X190"), "Y", false) == 0, JS.GetStr(loan, "644") + ")", "");
      nameValueCollection.Add("644_P", str88);
      string str89 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X184"), "Y", false) != 0, JS.GetStr(loan, "648"), "");
      nameValueCollection.Add("648", str89);
      string str90 = JS.GetStr(loan, "235");
      nameValueCollection.Add("235", str90);
      string str91 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X181"), "Y", false) != 0, JS.GetStr(loan, "646"), "");
      nameValueCollection.Add("646", str91);
      string str92 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X233"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "GFE3"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "1878"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "1878"), "", false) != 0, JS.GetStr(loan, "1878") + ")", JS.GetStr(loan, "1621") + ")"), "");
      nameValueCollection.Add("1621_P", str92);
      string str93 = JS.GetStr(loan, "232");
      nameValueCollection.Add("232", str93);
      string str94 = JS.GetStr(loan, "231");
      nameValueCollection.Add("231", str94);
      string str95 = JS.GetStr(loan, "230");
      nameValueCollection.Add("230", str95);
      string str96 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X231"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "GFE1"), "Y", false) != 0, JS.GetStr(loan, "641"), "");
      nameValueCollection.Add("641", str96);
      string str97 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X232"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "GFE2"), "Y", false) != 0, JS.GetStr(loan, "640"), "");
      nameValueCollection.Add("640", str97);
      string str98 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X147"), "Y", false) == 0, JS.GetStr(loan, "439") + ")", "");
      nameValueCollection.Add("439_P", str98);
      string str99 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X193"), "Y", false) == 0, JS.GetStr(loan, "44") + ")", "");
      nameValueCollection.Add("44_P", str99);
      string str100 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X193"), "Y", false) != 0, JS.GetStr(loan, "44"), "");
      nameValueCollection.Add("44", str100);
      string str101 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X170"), "Y", false) == 0, JS.GetStr(loan, "387") + ")", "");
      nameValueCollection.Add("387_P", str101);
      string str102 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X192"), "Y", false) != 0, JS.GetStr(loan, "41"), "");
      nameValueCollection.Add("41", str102);
      string str103 = JS.GetStr(loan, "40");
      nameValueCollection.Add("40", str103);
      string str104 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X186"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("383_$", str104);
      string str105 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X190"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("644_$", str105);
      string str106 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X243"), "Y", false) == 0, JS.GetStr(loan, "1625") + ")", "");
      nameValueCollection.Add("1625_P", str106);
      string str107 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X233"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "GFE3"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "1878"), "", false) != 0, "POC($", "");
      nameValueCollection.Add("1621_$", str107);
      string str108 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X147"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("439_$", str108);
      string str109 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X155"), "Y", false) == 0, JS.GetStr(loan, "81") + ")", "");
      nameValueCollection.Add("81_P", str109);
      string str110 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X137"), "Y", false) != 0, JS.GetStr(loan, "1093"), "");
      nameValueCollection.Add("1093", str110);
      string str111 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X193"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("44_$", str111);
      string str112 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X170"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("387_$", str112);
      string str113 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X184"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("648_$", str113);
      string str114 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X243"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1625_$", str114);
      string str115 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X239"), "Y", false) == 0, JS.GetStr(loan, "1631") + ")", "");
      nameValueCollection.Add("1631_P", str115);
      string str116 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X138"), "Y", false) == 0, JS.GetStr(loan, "329") + ")", "");
      nameValueCollection.Add("329_P", str116);
      string str117 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X155"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("81_$", str117);
      string str118 = JS.GetStr(loan, "610");
      nameValueCollection.Add("610", str118);
      string str119 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X168"), "Y", false) == 0, JS.GetStr(loan, "658") + ")", "");
      nameValueCollection.Add("658_P", str119);
      string str120 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X185"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("374_$", str120);
      string str121 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X239"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1631_$", str121);
      string str122 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X138"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("329_$", str122);
      string str123 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X184"), "Y", false) == 0, JS.GetStr(loan, "648") + ")", "");
      nameValueCollection.Add("648_P", str123);
      string str124 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X168"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("658_$", str124);
      string str125 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X150"), "Y", false) == 0, JS.GetStr(loan, "372") + ")", "");
      nameValueCollection.Add("372_P", str125);
      string str126 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X241"), "Y", false) == 0, JS.GetStr(loan, "1641") + ")", "");
      nameValueCollection.Add("1641_P", str126);
      string str127 = JS.GetStr(loan, "1500");
      nameValueCollection.Add("1500", str127);
      string str128 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X187"), "Y", false) == 0, JS.GetStr(loan, "339") + ")", "");
      nameValueCollection.Add("339_P", str128);
      string str129 = JS.GetStr(loan, "1880");
      nameValueCollection.Add("1880", str129);
      string str130 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X156"), "Y", false) != 0, JS.GetStr(loan, "155"), "");
      nameValueCollection.Add("155", str130);
      string str131 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X176"), "Y", false) != 0, JS.GetStr(loan, "978"), "");
      nameValueCollection.Add("978", str131);
      string str132 = JS.GetStr(loan, "1879");
      nameValueCollection.Add("1879", str132);
      string str133 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X150"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("372_$", str133);
      string str134 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X241"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1641_$", str134);
      string str135 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X187"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("339_$", str135);
      string str136 = JS.GetStr(loan, "558");
      nameValueCollection.Add("558", str136);
      string str137 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X154"), "Y", false) != 0, JS.GetStr(loan, "554"), "");
      nameValueCollection.Add("554", str137);
      string str138 = JS.GetStr(loan, "154");
      nameValueCollection.Add("154", str138);
      string str139 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X165"), "Y", false) == 0, JS.GetStr(loan, "655") + ")", "");
      nameValueCollection.Add("655_P", str139);
      string str140 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X154"), "Y", false) == 0, JS.GetStr(loan, "554") + ")", "");
      nameValueCollection.Add("554_P", str140);
      string str141 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X151"), "Y", false) == 0, JS.GetStr(loan, "349") + ")", "");
      nameValueCollection.Add("349_P", str141);
      string str142 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X160"), "Y", false) == 0, JS.GetStr(loan, "643") + ")", "");
      nameValueCollection.Add("643_P", str142);
      string str143 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X154"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("554_$", str143);
      string str144 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X183"), "Y", false) == 0, JS.GetStr(loan, "647") + ")", "");
      nameValueCollection.Add("647_P", str144);
      string str145 = JS.GetStr(loan, "1636");
      nameValueCollection.Add("1636", str145);
      string str146 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X151"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("349_$", str146);
      string str147 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X160"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("643_$", str147);
      string str148 = JS.GetStr(loan, "1630");
      nameValueCollection.Add("1630", str148);
      string str149 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X161"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("L260_$", str149);
      string str150 = JS.GetStr(loan, "REGZGFE.X15");
      nameValueCollection.Add("REGZGFE_X15", str150);
      string str151 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X388"), "Y", false) != 0, JS.GetStr(loan, "1849"), "");
      nameValueCollection.Add("1849", str151);
      string str152 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X298"), "Y", false) != 0, JS.GetStr(loan, "1842"), "");
      nameValueCollection.Add("1842", str152);
      string str153 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X298"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1842_$", str153);
      string str154 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X175"), "Y", false) == 0, JS.GetStr(loan, "392") + ")", "");
      nameValueCollection.Add("392_P", str154);
      string str155 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X183"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("647_$", str155);
      string str156 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X152"), "Y", false) != 0, JS.GetStr(loan, "932"), "");
      nameValueCollection.Add("932", str156);
      string str157 = JS.GetStr(loan, "931");
      nameValueCollection.Add("931", str157);
      string str158 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X293"), "Y", false) != 0, JS.GetStr(loan, "1839"), "");
      nameValueCollection.Add("1839", str158);
      string str159 = JS.GetStr(loan, "1838");
      nameValueCollection.Add("1838", str159);
      string str160 = JS.GetStr(loan, "1391");
      nameValueCollection.Add("1391", str160);
      string str161 = JS.GetStr(loan, "1390");
      nameValueCollection.Add("1390", str161);
      string str162 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X174"), "Y", false) == 0, JS.GetStr(loan, "396") + ")", "");
      nameValueCollection.Add("396_P", str162);
      string str163 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X167"), "Y", false) == 0, JS.GetStr(loan, "657") + ")", "");
      nameValueCollection.Add("657_P", str163);
      string str164 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X153"), "Y", false) != 0, JS.GetStr(loan, "1009"), "");
      nameValueCollection.Add("1009", str164);
      string str165 = JS.GetStr(loan, "1388");
      nameValueCollection.Add("1388", str165);
      string str166 = JS.GetStr(loan, "1387");
      nameValueCollection.Add("1387", str166);
      string str167 = JS.GetStr(loan, "1386");
      nameValueCollection.Add("1386", str167);
      string str168 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X136"), "Y", false) == 0, JS.GetStr(loan, "454") + ")", "");
      nameValueCollection.Add("454_P", str168);
      string str169 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X250"), "Y", false) != 0, JS.GetStr(loan, "1793"), "");
      nameValueCollection.Add("1793", str169);
      string str170 = JS.GetStr(loan, "1792");
      nameValueCollection.Add("1792", str170);
      string str171 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X139"), "Y", false) == 0, JS.GetStr(loan, "L228") + ")", "");
      nameValueCollection.Add("L228_P", str171);
      string str172 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X140"), "Y", false) == 0, JS.GetStr(loan, "L230") + ")", "");
      nameValueCollection.Add("L230_P", str172);
      string str173 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X174"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("396_$", str173);
      string str174 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X167"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("657_$", str174);
      string str175 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X163"), "Y", false) == 0, JS.GetStr(loan, "338") + ")", "");
      nameValueCollection.Add("338_P", str175);
      string str176 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X240"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1634_$", str176);
      string str177 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1812"), "", false) != 0, " to " + JS.GetStr(loan, "1812"), "");
      nameValueCollection.Add("810", str177);
      string str178 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X249"), "Y", false) != 0, JS.GetStr(loan, "1788"), "");
      nameValueCollection.Add("1788", str178);
      string str179 = JS.GetStr(loan, "1787");
      nameValueCollection.Add("1787", str179);
      string str180 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X248"), "Y", false) != 0, JS.GetStr(loan, "1783"), "");
      nameValueCollection.Add("1783", str180);
      string str181 = JS.GetStr(loan, "1782");
      nameValueCollection.Add("1782", str181);
      string str182 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X235"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1050_$", str182);
      string str183 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X136"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("454_$", str183);
      string str184 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X139"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("L228_$", str184);
      string str185 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X140"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("L230_$", str185);
      string str186 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X232"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "GFE2"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "449"), "", false) != 0, "POC($", "");
      nameValueCollection.Add("640_$", str186);
      string str187 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X242"), "Y", false) == 0, JS.GetStr(loan, "1644") + ")", "");
      nameValueCollection.Add("1644_P", str187);
      string str188 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X247"), "Y", false) != 0, JS.GetStr(loan, "1778"), "");
      nameValueCollection.Add("1778", str188);
      string str189 = JS.GetStr(loan, "1777");
      nameValueCollection.Add("1777", str189);
      string str190 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X249"), "Y", false) == 0, JS.GetStr(loan, "1788") + ")", "");
      nameValueCollection.Add("1788_P", str190);
      string str191 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X246"), "Y", false) != 0, JS.GetStr(loan, "1773"), "");
      nameValueCollection.Add("1773", str191);
      string str192 = JS.GetStr(loan, "1772");
      nameValueCollection.Add("1772", str192);
      string str193 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X163"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("338_$", str193);
      string str194 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X164"), "Y", false) == 0, JS.GetStr(loan, "L269") + ")", "");
      nameValueCollection.Add("L269_P", str194);
      string str195 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X136"), "Y", false) != 0, JS.GetStr(loan, "454"), "");
      nameValueCollection.Add("454", str195);
      string str196 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X245"), "Y", false) != 0, JS.GetStr(loan, "1768"), "");
      nameValueCollection.Add("1768", str196);
      string str197 = JS.GetStr(loan, "1767");
      nameValueCollection.Add("1767", str197);
      string str198 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X244"), "Y", false) != 0, JS.GetStr(loan, "1763"), "");
      nameValueCollection.Add("1763", str198);
      string str199 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X242"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1644_$", str199);
      string str200 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X245"), "Y", false) == 0, JS.GetStr(loan, "1768") + ")", "");
      nameValueCollection.Add("1768_P", str200);
      string str201 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X159"), "Y", false) == 0, JS.GetStr(loan, "642") + ")", "");
      nameValueCollection.Add("642_P", str201);
      string str202 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X164"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("L269_$", str202);
      string str203 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X173"), "Y", false) != 0, JS.GetStr(loan, "L294"), "");
      nameValueCollection.Add("L294", str203);
      string str204 = JS.GetStr(loan, "L293");
      nameValueCollection.Add("L293", str204);
      string str205 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X177"), "Y", false) == 0, JS.GetStr(loan, "385") + ")", "");
      nameValueCollection.Add("385_P", str205);
      string str206 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X157"), "Y", false) == 0, JS.GetStr(loan, "334") + ")", "");
      nameValueCollection.Add("334_P", str206);
      string str207 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X181"), "Y", false) == 0, JS.GetStr(loan, "646") + ")", "");
      nameValueCollection.Add("646_P", str207);
      string str208 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X147"), "Y", false) != 0, JS.GetStr(loan, "439"), "");
      nameValueCollection.Add("439", str208);
      string str209 = JS.GetStr(loan, "410");
      nameValueCollection.Add("410", str209);
      string str210 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X159"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("642_$", str210);
      string str211 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X234"), "Y", false) == 0, JS.GetStr(loan, "1623") + ")", "");
      nameValueCollection.Add("1623_P", str211);
      string str212 = JS.GetStr(loan, "369");
      nameValueCollection.Add("369", str212);
      string str213 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X177"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("385_$", str213);
      string str214 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X247"), "Y", false) == 0, JS.GetStr(loan, "1778") + ")", "");
      nameValueCollection.Add("1778_P", str214);
      string str215 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X181"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("646_$", str215);
      string str216 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X174"), "Y", false) != 0, JS.GetStr(loan, "396"), "");
      nameValueCollection.Add("396", str216);
      string str217 = JS.GetStr(loan, "395");
      nameValueCollection.Add("395", str217);
      string str218 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X234"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1623_$", str218);
      string str219 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X175"), "Y", false) != 0, JS.GetStr(loan, "392"), "");
      nameValueCollection.Add("392", str219);
      string str220 = JS.GetStr(loan, "391");
      nameValueCollection.Add("391", str220);
      string str221 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X182"), "Y", false) != 0, JS.GetStr(loan, "390"), "");
      nameValueCollection.Add("390", str221);
      string str222 = JS.GetStr(loan, "1296");
      nameValueCollection.Add("1296", str222);
      string str223 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X156"), "Y", false) == 0, JS.GetStr(loan, "155") + ")", "");
      nameValueCollection.Add("155_P", str223);
      string str224 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X137"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1093_$", str224);
      string str225 = JS.GetStr(loan, "L267");
      nameValueCollection.Add("L267", str225);
      string str226 = JS.GetStr(loan, "411");
      nameValueCollection.Add("411", str226);
      string str227 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X170"), "Y", false) != 0, JS.GetStr(loan, "387"), "");
      nameValueCollection.Add("387", str227);
      string str228 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X162"), "Y", false) == 0, JS.GetStr(loan, "656") + ")", "");
      nameValueCollection.Add("656_P", str228);
      string str229 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X177"), "Y", false) != 0, JS.GetStr(loan, "385"), "");
      nameValueCollection.Add("385", str229);
      string str230 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X186"), "Y", false) != 0, JS.GetStr(loan, "383"), "");
      nameValueCollection.Add("383", str230);
      string str231 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X161"), "Y", false) != 0, JS.GetStr(loan, "L260"), "");
      nameValueCollection.Add("L260", str231);
      string str232 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X244"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1763_$", str232);
      string str233 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X172"), "Y", false) == 0, JS.GetStr(loan, "L291") + ")", "");
      nameValueCollection.Add("L291_P", str233);
      string str234 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X161"), "Y", false) == 0, JS.GetStr(loan, "L260") + ")", "");
      nameValueCollection.Add("L260_P", str234);
      string str235 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X156"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("155_$", str235);
      string str236 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X142"), "Y", false) != 0, JS.GetStr(loan, "367"), "");
      nameValueCollection.Add("367", str236);
      string str237 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X298"), "Y", false) == 0, JS.GetStr(loan, "1842") + ")", "");
      nameValueCollection.Add("1842_P", str237);
      string str238 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1813"), "", false) != 0, " to " + JS.GetStr(loan, "1813"), "");
      nameValueCollection.Add("812", str238);
      string str239 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X8"), "", false) != 0, " to " + JS.GetStr(loan, "REGZGFE.X8"), "");
      nameValueCollection.Add("811", str239);
      string str240 = JS.GetStr(loan, "375");
      nameValueCollection.Add("375", str240);
      string str241 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X185"), "Y", false) != 0, JS.GetStr(loan, "374"), "");
      nameValueCollection.Add("374", str241);
      string str242 = JS.GetStr(loan, "373");
      nameValueCollection.Add("373", str242);
      string str243 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X150"), "Y", false) != 0, JS.GetStr(loan, "372"), "");
      nameValueCollection.Add("372", str243);
      string str244 = JS.GetStr(loan, "371");
      nameValueCollection.Add("371", str244);
      string str245 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X149"), "Y", false) != 0, JS.GetStr(loan, "370"), "");
      nameValueCollection.Add("370", str245);
      string str246 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X162"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("656_$", str246);
      string str247 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X149"), "Y", false) == 0, JS.GetStr(loan, "370") + ")", "");
      nameValueCollection.Add("370_P", str247);
      string str248 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X158"), "Y", false) == 0, JS.GetStr(loan, "337") + ")", "");
      nameValueCollection.Add("337_P", str248);
      string str249 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X172"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("L291_$", str249);
      string str250 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X240"), "Y", false) == 0, JS.GetStr(loan, "1634") + ")", "");
      nameValueCollection.Add("1634_P", str250);
      string str251 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "L224"), "", false) != 0, " to " + JS.GetStr(loan, "L224"), "");
      nameValueCollection.Add("809", str251);
      string str252 = JS.GetStr(loan, "389") + "% + $" + JS.GetStr(loan, "1620") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X14"), "", false) != 0, " to " + JS.GetStr(loan, "REGZGFE.X14"), "");
      nameValueCollection.Add("808", str252);
      string str253 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X7"), "", false) != 0, " to " + JS.GetStr(loan, "REGZGFE.X7"), "");
      nameValueCollection.Add("807", str253);
      string str254 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "L227"), "", false) != 0, " to " + JS.GetStr(loan, "L227"), "");
      nameValueCollection.Add("806", str254);
      string str255 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "704"), "", false) != 0, " to " + JS.GetStr(loan, "704"), "");
      nameValueCollection.Add("805", str255);
      string str256 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "624"), "", false) != 0, " to " + JS.GetStr(loan, "624"), "");
      nameValueCollection.Add("804", str256);
      string str257 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "617"), "", false) != 0, " to " + JS.GetStr(loan, "617"), "");
      nameValueCollection.Add("803", str257);
      string str258 = JS.GetStr(loan, "1061") + "% + $" + JS.GetStr(loan, "436") + " " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X6"), "", false) != 0, " to " + JS.GetStr(loan, "REGZGFE.X6"), "");
      nameValueCollection.Add("802", str258);
      string str259 = JS.GetStr(loan, "388") + "% + $" + JS.GetStr(loan, "1619") + " " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X5"), "", false) != 0, " to " + JS.GetStr(loan, "REGZGFE.X5"), "");
      nameValueCollection.Add("801", str259);
      string str260 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X172"), "Y", false) != 0, JS.GetStr(loan, "L291"), "");
      nameValueCollection.Add("L291", str260);
      string str261 = JS.GetStr(loan, "L290");
      nameValueCollection.Add("L290", str261);
      string str262 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X249"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1788_$", str262);
      string str263 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X185"), "Y", false) == 0, JS.GetStr(loan, "374") + ")", "");
      nameValueCollection.Add("374_P", str263);
      string str264 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X149"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("370_$", str264);
      string str265 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X244"), "Y", false) == 0, JS.GetStr(loan, "1763") + ")", "");
      nameValueCollection.Add("1763_P", str265);
      string str266 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X158"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("337_$", str266);
      string str267 = JS.GetStr(loan, "1841");
      nameValueCollection.Add("1841", str267);
      string str268 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X171"), "Y", false) != 0, JS.GetStr(loan, "L288"), "");
      nameValueCollection.Add("L288", str268);
      string str269 = JS.GetStr(loan, "L287");
      nameValueCollection.Add("L287", str269);
      string str270 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X191"), "Y", false) != 0, JS.GetStr(loan, "645"), "");
      nameValueCollection.Add("645", str270);
      string str271 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X160"), "Y", false) != 0, JS.GetStr(loan, "643"), "");
      nameValueCollection.Add("643", str271);
      string str272 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X157"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("334_$", str272);
      string str273 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X238"), "Y", false) != 0, JS.GetStr(loan, "1667"), "");
      nameValueCollection.Add("1667", str273);
      string str274 = JS.GetStr(loan, "1666");
      nameValueCollection.Add("1666", str274);
      string str275 = JS.GetStr(loan, "1665");
      nameValueCollection.Add("1665", str275);
      string str276 = JS.GetStr(loan, "1664");
      nameValueCollection.Add("1664", str276);
      string str277 = JS.GetStr(loan, "1663");
      nameValueCollection.Add("1663", str277);
      string str278 = JS.GetStr(loan, "1662");
      nameValueCollection.Add("1662", str278);
      string str279 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X231"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "GFE1"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "448"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "448"), "", false) != 0, JS.GetStr(loan, "448") + ")", JS.GetStr(loan, "641")), "");
      nameValueCollection.Add("641_P", str279);
      string str280 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X163"), "Y", false) != 0, JS.GetStr(loan, "338"), "");
      nameValueCollection.Add("338", str280);
      string str281 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X151"), "Y", false) != 0, JS.GetStr(loan, "349"), "");
      nameValueCollection.Add("349", str281);
      string str282 = JS.GetStr(loan, "348");
      nameValueCollection.Add("348", str282);
      string str283 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X171"), "Y", false) == 0, JS.GetStr(loan, "L288") + ")", "");
      nameValueCollection.Add("L288_P", str283);
      string str284 = JS.GetStr(loan, "341");
      nameValueCollection.Add("341", str284);
      string str285 = JS.GetStr(loan, "340");
      nameValueCollection.Add("340", str285);
      string str286 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X192"), "Y", false) == 0, JS.GetStr(loan, "41") + ")", "");
      nameValueCollection.Add("41_P", str286);
      string str287 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X164"), "Y", false) != 0, JS.GetStr(loan, "L269"), "");
      nameValueCollection.Add("L269", str287);
      string str288 = JS.GetStr(loan, "L268");
      nameValueCollection.Add("L268", str288);
      string str289 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X191"), "Y", false) == 0, JS.GetStr(loan, "645") + ")", "");
      nameValueCollection.Add("645_P", str289);
      string str290 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X187"), "Y", false) != 0, JS.GetStr(loan, "339"), "");
      nameValueCollection.Add("339", str290);
      string str291 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X246"), "Y", false) == 0, JS.GetStr(loan, "1773") + ")", "");
      nameValueCollection.Add("1773_P", str291);
      string str292 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X158"), "Y", false) != 0, JS.GetStr(loan, "337"), "");
      nameValueCollection.Add("337", str292);
      string str293 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X141"), "Y", false) != 0, JS.GetStr(loan, "336"), "");
      nameValueCollection.Add("336", str293);
      string str294 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X231"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "GFE1"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "448"), "", false) != 0, "POC($", "");
      nameValueCollection.Add("641_$", str294);
      string str295 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X157"), "Y", false) != 0, JS.GetStr(loan, "334"), "");
      nameValueCollection.Add("334", str295);
      string str296 = JS.GetStr(loan, "333");
      nameValueCollection.Add("333", str296);
      string str297 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X242"), "Y", false) != 0, JS.GetStr(loan, "1644"), "");
      nameValueCollection.Add("1644", str297);
      string str298 = JS.GetStr(loan, "1643");
      nameValueCollection.Add("1643", str298);
      string str299 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X241"), "Y", false) != 0, JS.GetStr(loan, "1641"), "");
      nameValueCollection.Add("1641", str299);
      string str300 = JS.GetStr(loan, "1640");
      nameValueCollection.Add("1640", str300);
      string str301 = JS.GetStr(loan, "L259");
      nameValueCollection.Add("L259", str301);
      string str302 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X192"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("41_$", str302);
      string str303 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X138"), "Y", false) != 0, JS.GetStr(loan, "329"), "");
      nameValueCollection.Add("329", str303);
      string str304 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X182"), "Y", false) == 0, JS.GetStr(loan, "390") + ")", "");
      nameValueCollection.Add("390_P", str304);
      string str305 = JS.GetStr(loan, "L252");
      nameValueCollection.Add("L252", str305);
      string str306 = JS.GetStr(loan, "L251");
      nameValueCollection.Add("L251", str306);
      string str307 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X191"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("645_$", str307);
      string str308 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X246"), "Y", false) == 0, "POC($", "");
      nameValueCollection.Add("1773_$", str308);
      string str309 = JS.GetStr(loan, "1638");
      nameValueCollection.Add("1638", str309);
      string str310 = JS.GetStr(loan, "1637");
      nameValueCollection.Add("1637", str310);
      string str311 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X153"), "Y", false) == 0, JS.GetStr(loan, "1009") + ")", "");
      nameValueCollection.Add("1009_P", str311);
      string str312 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X240"), "Y", false) != 0, JS.GetStr(loan, "1634"), "");
      nameValueCollection.Add("1634", str312);
      string str313 = JS.GetStr(loan, "1633");
      nameValueCollection.Add("1633", str313);
      string str314 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X239"), "Y", false) != 0, JS.GetStr(loan, "1631"), "");
      nameValueCollection.Add("1631", str314);
      string str315 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X176"), "Y", false) == 0, JS.GetStr(loan, "978") + ")", "");
      nameValueCollection.Add("978_P", str315);
      return nameValueCollection;
    }
  }
}
