// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._HUD92900LTP1CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _HUD92900LTP1CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "1040");
      nameValueCollection.Add("1040", str1);
      string str2 = JS.GetStr(loan, "1039");
      nameValueCollection.Add("1039", str2);
      string str3 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str3);
      string str4 = JS.GetStr(loan, "65");
      nameValueCollection.Add("65", str4);
      string str5 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69", str5);
      string str6 = JS.GetStr(loan, "97");
      nameValueCollection.Add("97", str6);
      string str7 = JS.GetStr(loan, "11") + "  " + JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("11_12_14_15", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2996"), "1 Unit", false) == 0, "X");
      nameValueCollection.Add("2996_1", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2996"), "2 Units", false) == 0, "X");
      nameValueCollection.Add("2996_2", str9);
      string str10 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2996"), "3-4 Units", false) == 0, "X");
      nameValueCollection.Add("2996_3", str10);
      string str11 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2996"), "Condominium", false) == 0, "X");
      nameValueCollection.Add("2996_4", str11);
      string str12 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2996"), "Cooperative", false) == 0, "X");
      nameValueCollection.Add("2996_5", str12);
      string str13 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2996"), "ManufacturedHousing", false) == 0, "X");
      nameValueCollection.Add("2996_6", str13);
      string str14 = JS.GetStr(loan, "136");
      nameValueCollection.Add("136", str14);
      string str15 = JS.GetStr(loan, "356");
      nameValueCollection.Add("356", str15);
      string str16 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1066"), "FeeSimple", false) == 0, "X");
      nameValueCollection.Add("1066_1", str16);
      string str17 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1066"), "Leasehold", false) == 0, "X");
      nameValueCollection.Add("1066_2", str17);
      string str18 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1067"), "ExistingConstruction", false) == 0, "X");
      nameValueCollection.Add("1067_1", str18);
      string str19 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1067"), "ProposedConstruction", false) == 0, "X");
      nameValueCollection.Add("1067_2", str19);
      string str20 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1067"), "NewConstruction", false) == 0, "X");
      nameValueCollection.Add("1067_3", str20);
      string str21 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "Fixed", false) == 0, "X");
      nameValueCollection.Add("608_1", str21);
      string str22 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "AdjustableRate", false) == 0, "X");
      nameValueCollection.Add("608_2", str22);
      string str23 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "425"), "Y", false) == 0, "X");
      nameValueCollection.Add("608_3", str23);
      string str24 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST1YW", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST3YW", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST5YW", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST7YW", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST10YW", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST20YW", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST30YW", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST1Y", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST3Y", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST5Y", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST7Y", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST10Y", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST20Y", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST30Y", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "UST6M", false) == 0, "1-Year CMT", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "FHLMCLIBOR1M", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "FHLMCLIBOR3M", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "FHLMCLIBOR6M", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "FHLMCLIBOR1Y", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "FNMALIBOR1M", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "FNMALIBOR3M", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "FNMALIBOR6M", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "FNMALIBOR1Y", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "LIBOR1M", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "LIBOR3M", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "LIBOR6M", false) == 0, "1-Year LIBOR", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1959"), "LIBOR12M", false) == 0, "1-Year LIBOR")))))))))))))))))))))))))));
      nameValueCollection.Add("1959", str24);
      string str25 = JS.GetStr(loan, "689");
      nameValueCollection.Add("689", str25);
      string str26 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "696"), "12", false) == 0, "X");
      nameValueCollection.Add("ARM_1", str26);
      string str27 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "696"), "36", false) == 0, "X");
      nameValueCollection.Add("ARM_3", str27);
      string str28 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "696"), "60", false) == 0, "X");
      nameValueCollection.Add("ARM_5", str28);
      string str29 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "696"), "84", false) == 0, "X");
      nameValueCollection.Add("ARM_7", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "696"), "120", false) == 0, "X");
      nameValueCollection.Add("ARM_10", str30);
      string str31 = JS.GetStr(loan, "1109");
      nameValueCollection.Add("1109", str31);
      string str32 = JS.GetStr(loan, "1045");
      nameValueCollection.Add("1045", str32);
      string str33 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str33);
      string str34 = JS.GetStr(loan, "3");
      nameValueCollection.Add("3", str34);
      string str35 = JS.GetStr(loan, "1014");
      nameValueCollection.Add("1014", str35);
      string str36 = JS.GetStr(loan, "4");
      nameValueCollection.Add("4", str36);
      string str37 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Purchase", false) == 0, "X");
      nameValueCollection.Add("19_1", str37);
      string str38 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, "X");
      nameValueCollection.Add("19_2", str38);
      string str39 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Cash-Out Refinance", false) == 0, "X");
      nameValueCollection.Add("19_3", str39);
      string str40 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "MORNET.X40"), "StreamlineWithAppraisal", false) == 0 | Operators.CompareString(JS.GetStr(loan, "MORNET.X40"), "StreamlineWithoutAppraisal", false) == 0, "X");
      nameValueCollection.Add("19_4", str40);
      string str41 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "MORNET.X40"), "StreamlineWithAppraisal", false) == 0, "X");
      nameValueCollection.Add("19_5", str41);
      string str42 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "MORNET.X40"), "StreamlineWithoutAppraisal", false) == 0, "X");
      nameValueCollection.Add("19_6", str42);
      string str43 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, "X");
      nameValueCollection.Add("19_7", str43);
      string str44 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2997"), "Y", false) == 0, "X");
      nameValueCollection.Add("19_8", str44);
      string str45 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2998"), "Y", false) == 0, "X");
      nameValueCollection.Add("19_9", str45);
      string str46 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2999"), "Y", false) == 0, "X");
      nameValueCollection.Add("19_10", str46);
      string str47 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3000"), "Y", false) == 0, "X");
      nameValueCollection.Add("19_11", str47);
      string str48 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Other", false) == 0, "X");
      nameValueCollection.Add("19_12", str48);
      string str49 = JS.GetStr(loan, "3001");
      nameValueCollection.Add("3001", str49);
      string str50 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3002"), "Y", false) == 0, "X");
      nameValueCollection.Add("3002", str50);
      string str51 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3003"), "Y", false) == 0, "X");
      nameValueCollection.Add("3003", str51);
      string str52 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3004"), "Y", false) == 0, "X");
      nameValueCollection.Add("3004", str52);
      string str53 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3005"), "Y", false) == 0, "X");
      nameValueCollection.Add("3005", str53);
      string str54 = JS.GetStr(loan, "3006");
      nameValueCollection.Add("3006", str54);
      string str55 = JS.GetStr(loan, "3007");
      nameValueCollection.Add("3007", str55);
      string str56 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3008"), "Y", false) == 0, "X");
      nameValueCollection.Add("3008_Y", str56);
      string str57 = JS.GetStr(loan, "3009");
      nameValueCollection.Add("3009", str57);
      string str58 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3010"), "Y", false) == 0, "X");
      nameValueCollection.Add("3010", str58);
      string str59 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3011"), "Y", false) == 0, "X");
      nameValueCollection.Add("3011", str59);
      string str60 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3012"), "Y", false) == 0, "X");
      nameValueCollection.Add("3012", str60);
      string str61 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3013"), "Y", false) == 0, "X");
      nameValueCollection.Add("3013", str61);
      string str62 = JS.GetStr(loan, "3014");
      nameValueCollection.Add("3014", str62);
      string str63 = JS.GetStr(loan, "3015");
      nameValueCollection.Add("3015", str63);
      string str64 = JS.GetStr(loan, "3016");
      nameValueCollection.Add("3016", str64);
      string str65 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3017"), "Y", false) == 0, "X");
      nameValueCollection.Add("3017", str65);
      string str66 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3018"), "Y", false) == 0, "X");
      nameValueCollection.Add("3018", str66);
      string str67 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3019"), "Y", false) == 0, "X");
      nameValueCollection.Add("3019", str67);
      string str68 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3020"), "Y", false) == 0, "X");
      nameValueCollection.Add("3020", str68);
      string str69 = JS.GetStr(loan, "3021");
      nameValueCollection.Add("3021", str69);
      string str70 = JS.GetStr(loan, "3022");
      nameValueCollection.Add("3022", str70);
      string str71 = JS.GetStr(loan, "101");
      nameValueCollection.Add("101", str71);
      string str72 = JS.GetStr(loan, "110");
      nameValueCollection.Add("110", str72);
      string str73 = JS.GetStr(loan, "273");
      nameValueCollection.Add("273", str73);
      string str74 = JS.GetStr(loan, "1145");
      nameValueCollection.Add("1145", str74);
      string str75 = JS.GetStr(loan, "1146");
      nameValueCollection.Add("1146", str75);
      string str76 = JS.GetStr(loan, "1168");
      nameValueCollection.Add("1168", str76);
      string str77 = JS.GetStr(loan, "1169");
      nameValueCollection.Add("1169", str77);
      string str78 = JS.GetStr(loan, "1170");
      nameValueCollection.Add("1170", str78);
      string str79 = JS.GetStr(loan, "1171");
      nameValueCollection.Add("1171", str79);
      string str80 = JS.GetStr(loan, "1758");
      nameValueCollection.Add("1758", str80);
      string str81 = JS.GetStr(loan, "1759");
      nameValueCollection.Add("1759", str81);
      string str82 = JS.GetStr(loan, "1389");
      nameValueCollection.Add("1389", str82);
      string str83 = JS.GetStr(loan, "382");
      nameValueCollection.Add("382", str83);
      string str84 = JS.GetStr(loan, "733");
      nameValueCollection.Add("733", str84);
      string str85 = JS.GetStr(loan, "272");
      nameValueCollection.Add("272", str85);
      string str86 = JS.GetStr(loan, "3023");
      nameValueCollection.Add("3023", str86);
      string str87 = JS.GetStr(loan, "462");
      nameValueCollection.Add("462", str87);
      string str88 = JS.GetStr(loan, "3024");
      nameValueCollection.Add("3024", str88);
      string str89 = JS.GetStr(loan, "1161");
      nameValueCollection.Add("1161", str89);
      string str90 = JS.GetStr(loan, "1163");
      nameValueCollection.Add("1163", str90);
      string str91 = JS.GetStr(loan, "1742");
      nameValueCollection.Add("1742", str91);
      string str92 = Jed.BF(Jed.Num(JS.GetNum(loan, "142")) >= 0.0, JS.GetStr(loan, "142"), "(" + Jed.NF(Jed.Num(JS.GetNum(loan, "142")) * -1.0, (byte) 2, 0) + ")");
      nameValueCollection.Add("142", str92);
      string str93 = JS.GetStr(loan, "1094");
      nameValueCollection.Add("1094", str93);
      string str94 = JS.GetStr(loan, "386");
      nameValueCollection.Add("386", str94);
      string str95 = JS.GetStr(loan, "34");
      nameValueCollection.Add("34", str95);
      string str96 = JS.GetStr(loan, "1548");
      nameValueCollection.Add("1548", str96);
      string str97 = JS.GetStr(loan, "3048");
      nameValueCollection.Add("3048", str97);
      string str98 = JS.GetStr(loan, "1724");
      nameValueCollection.Add("1724", str98);
      string str99 = JS.GetStr(loan, "1728");
      nameValueCollection.Add("1728", str99);
      string str100 = JS.GetStr(loan, "1729");
      nameValueCollection.Add("1729", str100);
      string str101 = JS.GetStr(loan, "1730");
      nameValueCollection.Add("1730", str101);
      string str102 = JS.GetStr(loan, "1725");
      nameValueCollection.Add("1725", str102);
      string str103 = JS.GetStr(loan, "1726");
      nameValueCollection.Add("1726", str103);
      string str104 = JS.GetStr(loan, "1727");
      nameValueCollection.Add("1727", str104);
      string str105 = JS.GetStr(loan, "739");
      nameValueCollection.Add("739", str105);
      string str106 = JS.GetStr(loan, "353");
      nameValueCollection.Add("353", str106);
      string str107 = JS.GetStr(loan, "976");
      nameValueCollection.Add("976", str107);
      string str108 = JS.GetStr(loan, "MCAWPUR.X22");
      nameValueCollection.Add("MCAWPUR_X22", str108);
      string str109 = JS.GetStr(loan, "MCAWPUR.X23");
      nameValueCollection.Add("MCAWPUR_X23", str109);
      string str110 = JS.GetStr(loan, "1018");
      nameValueCollection.Add("1018", str110);
      string str111 = JS.GetStr(loan, "1144");
      nameValueCollection.Add("1144", str111);
      string str112 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3026"), "Yes", false) == 0, "X");
      nameValueCollection.Add("3026_Y", str112);
      string str113 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3026"), "No", false) == 0, "X");
      nameValueCollection.Add("3026_N", str113);
      string str114 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3027"), "Yes", false) == 0, "X");
      nameValueCollection.Add("3027_Y", str114);
      string str115 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3027"), "No", false) == 0, "X");
      nameValueCollection.Add("3027_N", str115);
      string str116 = JS.GetStr(loan, "1216");
      nameValueCollection.Add("1216", str116);
      string str117 = JS.GetStr(loan, "1217");
      nameValueCollection.Add("1217", str117);
      string str118 = JS.GetStr(loan, "1218");
      nameValueCollection.Add("1218", str118);
      string str119 = JS.GetStr(loan, "1219");
      nameValueCollection.Add("1219", str119);
      string str120 = JS.GetStr(loan, "1220");
      nameValueCollection.Add("1220", str120);
      string str121 = JS.GetStr(loan, "1221");
      nameValueCollection.Add("1221", str121);
      string str122 = JS.GetStr(loan, "1222");
      nameValueCollection.Add("1222", str122);
      string str123 = JS.GetStr(loan, "1829");
      nameValueCollection.Add("1829", str123);
      string str124 = JS.GetStr(loan, "980");
      nameValueCollection.Add("980", str124);
      string str125 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3028"), "Yes", false) == 0, "X");
      nameValueCollection.Add("3028_Y", str125);
      string str126 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3028"), "No", false) == 0, "X");
      nameValueCollection.Add("3028_N", str126);
      string str127 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3029"), "A/A", false) == 0, "X");
      nameValueCollection.Add("3029_1", str127);
      string str128 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3029"), "Refer", false) == 0, "X");
      nameValueCollection.Add("3029_2", str128);
      string str129 = JS.GetStr(loan, "3030");
      nameValueCollection.Add("3030", str129);
      return nameValueCollection;
    }
  }
}
