// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._HUD1PG2CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _HUD1PG2CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "1955");
      nameValueCollection.Add("1955", str1);
      string str2 = JS.GetStr(loan, "1956");
      nameValueCollection.Add("1956", str2);
      string str3 = JS.GetStr(loan, "L248");
      nameValueCollection.Add("L248", str3);
      string str4 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X235"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X311"), "Lender", false) == 0, JS.GetStr(loan, "1050") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X311"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1050_P", str4);
      string str5 = JS.GetStr(loan, "L244");
      nameValueCollection.Add("L244", str5);
      string str6 = JS.GetStr(loan, "L245");
      nameValueCollection.Add("L245", str6);
      string str7 = JS.GetStr(loan, "304");
      nameValueCollection.Add("304", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X182"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X355"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("390_$", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X248"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X382"), "Lender", false) == 0, JS.GetStr(loan, "1783") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X382"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1783_P", str9);
      string str10 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X247"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X353"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1778_$", str10);
      string str11 = JS.GetStr(loan, "1629");
      nameValueCollection.Add("1629", str11);
      string str12 = JS.GetStr(loan, "1628");
      nameValueCollection.Add("1628", str12);
      string str13 = JS.GetStr(loan, "1627");
      nameValueCollection.Add("1627", str13);
      string str14 = JS.GetStr(loan, "1626");
      nameValueCollection.Add("1626", str14);
      string str15 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X243"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X291"), "Lender", false) != 0, JS.GetStr(loan, "1625"), "");
      nameValueCollection.Add("1625", str15);
      string str16 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X183"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X357"), "Lender", false) != 0, JS.GetStr(loan, "647"), "");
      nameValueCollection.Add("647", str16);
      string str17 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X234"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X273"), "Lender", false) != 0, JS.GetStr(loan, "1623"), "");
      nameValueCollection.Add("1623", str17);
      string str18 = JS.GetStr(loan, "1622");
      nameValueCollection.Add("1622", str18);
      string str19 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X233"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "GFE3"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X269"), "Lender", false) != 0, JS.GetStr(loan, "1621"), "");
      nameValueCollection.Add("1621", str19);
      string str20 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X190"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X374"), "Lender", false) != 0, JS.GetStr(loan, "644"), "");
      nameValueCollection.Add("644", str20);
      string str21 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X153"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X283"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1009_$", str21);
      string str22 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X159"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X307"), "Lender", false) != 0, JS.GetStr(loan, "642"), "");
      nameValueCollection.Add("642", str22);
      string str23 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X293"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X296"), "Lender", false) == 0, JS.GetStr(loan, "1839") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X296"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1839_P", str23);
      string str24 = JS.GetStr(loan, "1779");
      nameValueCollection.Add("1779", str24);
      string str25 = JS.GetStr(loan, "43");
      nameValueCollection.Add("43", str25);
      string str26 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X176"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X339"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("978_$", str26);
      string str27 = JS.GetStr(loan, "L231");
      nameValueCollection.Add("L231", str27);
      string str28 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X140"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X263"), "Lender", false) != 0, JS.GetStr(loan, "L230"), "");
      nameValueCollection.Add("L230", str28);
      string str29 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X238"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X315"), "Lender", false) == 0, JS.GetStr(loan, "1667") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X315"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1667_P", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X169"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X331"), "Lender", false) == 0, JS.GetStr(loan, "659") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X331"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("659_P", str30);
      string str31 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X165"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X323"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("655_$", str31);
      string str32 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X142"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X271"), "Lender", false) == 0, JS.GetStr(loan, "367") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X271"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("367_P", str32);
      string str33 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X248"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X382"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1783_$", str33);
      string str34 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X171"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X403"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("L288_$", str34);
      string str35 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X245"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X349"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1768_$", str35);
      string str36 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X173"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X407"), "Lender", false) == 0, JS.GetStr(loan, "L294") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X407"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("L294_P", str36);
      string str37 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X141"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X267"), "Lender", false) == 0, JS.GetStr(loan, "336") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X267"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("336_P", str37);
      string str38 = JS.GetStr(loan, "L229");
      nameValueCollection.Add("L229", str38);
      string str39 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X139"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X261"), "Lender", false) != 0, JS.GetStr(loan, "L228"), "");
      nameValueCollection.Add("L228", str39);
      string str40 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X235"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X311"), "Lender", false) != 0, JS.GetStr(loan, "1050"), "");
      nameValueCollection.Add("1050", str40);
      string str41 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X293"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X296"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1839_$", str41);
      string str42 = JS.GetStr(loan, "82");
      nameValueCollection.Add("82", str42);
      string str43 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X155"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X287"), "Lender", false) != 0, JS.GetStr(loan, "81"), "");
      nameValueCollection.Add("81", str43);
      string str44 = JS.GetStr(loan, "1762");
      nameValueCollection.Add("1762", str44);
      string str45 = JS.GetStr(loan, "678");
      nameValueCollection.Add("678", str45);
      string str46 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X238"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X315"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1667_$", str46);
      string str47 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X169"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X331"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("659_$", str47);
      string str48 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X250"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X386"), "Lender", false) == 0, JS.GetStr(loan, "1793") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X386"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1793_P", str48);
      string str49 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X142"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X271"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("367_$", str49);
      string str50 = JS.GetStr(loan, "1049");
      nameValueCollection.Add("1049", str50);
      string str51 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X173"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X407"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("L294_$", str51);
      string str52 = JS.GetStr(loan, "L219");
      nameValueCollection.Add("L219", str52);
      string str53 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X398"), "Y", false) != 0, JS.GetStr(loan, "L218"), "");
      nameValueCollection.Add("L218", str53);
      string str54 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X141"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X267"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("336_$", str54);
      string str55 = JS.GetStr(loan, "L216");
      nameValueCollection.Add("L216", str55);
      string str56 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X393"), "Y", false) != 0, JS.GetStr(loan, "L215"), "");
      nameValueCollection.Add("L215", str56);
      string str57 = JS.GetStr(loan, "L214");
      nameValueCollection.Add("L214", str57);
      string str58 = JS.GetStr(loan, "L213");
      nameValueCollection.Add("L213", str58);
      string str59 = JS.GetStr(loan, "L212");
      nameValueCollection.Add("L212", str59);
      string str60 = JS.GetStr(loan, "L211");
      nameValueCollection.Add("L211", str60);
      string str61 = JS.GetStr(loan, "L210");
      nameValueCollection.Add("L210", str61);
      string str62 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X388"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X391"), "Lender", false) == 0, JS.GetStr(loan, "1849") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X391"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1849_P", str62);
      string str63 = JS.GetStr(loan, "55");
      nameValueCollection.Add("55", str63);
      string str64 = JS.GetStr(loan, "254");
      nameValueCollection.Add("254", str64);
      string str65 = JS.GetStr(loan, "253");
      nameValueCollection.Add("253", str65);
      string str66 = JS.GetStr(loan, "661");
      nameValueCollection.Add("661", str66);
      string str67 = JS.GetStr(loan, "660");
      nameValueCollection.Add("660", str67);
      string str68 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X250"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X386"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1793_$", str68);
      string str69 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X137"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X253"), "Lender", false) == 0, JS.GetStr(loan, "1093") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X253"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1093_P", str69);
      string str70 = JS.GetStr(loan, "L209");
      nameValueCollection.Add("L209", str70);
      string str71 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X152"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X281"), "Lender", false) == 0, JS.GetStr(loan, "932") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X281"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("932_P", str71);
      string str72 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X175"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X337"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("392_$", str72);
      string str73 = JS.GetStr(loan, "593");
      nameValueCollection.Add("593", str73);
      string str74 = JS.GetStr(loan, "591");
      nameValueCollection.Add("591", str74);
      string str75 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X232"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X257"), "Lender", false) == 0, Jed.BF(Jed.S2N(JS.GetStr(loan, "449")) != 0.0 | Jed.S2N(JS.GetStr(loan, "640")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "449")) + Jed.S2N(JS.GetStr(loan, "640")), (byte) 18, 0) + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X257"), "Lender", false) == 0, "-L", ""), ""), Jed.BF(Operators.CompareString(JS.GetStr(loan, "GFE2"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "449"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "449"), "", false) != 0, JS.GetStr(loan, "449") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X257"), "Lender", false) == 0, "-L", ""), "")));
      nameValueCollection.Add("640_P", str75);
      string str76 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X169"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X331"), "Lender", false) != 0, JS.GetStr(loan, "659"), "");
      nameValueCollection.Add("659", str76);
      string str77 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X168"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X329"), "Lender", false) != 0, JS.GetStr(loan, "658"), "");
      nameValueCollection.Add("658", str77);
      string str78 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X167"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X325"), "Lender", false) != 0, JS.GetStr(loan, "657"), "");
      nameValueCollection.Add("657", str78);
      string str79 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X162"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X317"), "Lender", false) != 0, JS.GetStr(loan, "656"), "");
      nameValueCollection.Add("656", str79);
      string str80 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X165"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X323"), "Lender", false) != 0, JS.GetStr(loan, "655"), "");
      nameValueCollection.Add("655", str80);
      string str81 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X388"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X391"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1849_$", str81);
      string str82 = JS.GetStr(loan, "652");
      nameValueCollection.Add("652", str82);
      string str83 = JS.GetStr(loan, "651");
      nameValueCollection.Add("651", str83);
      string str84 = JS.GetStr(loan, "650");
      nameValueCollection.Add("650", str84);
      string str85 = JS.GetStr(loan, "587");
      nameValueCollection.Add("587", str85);
      string str86 = JS.GetStr(loan, "56");
      nameValueCollection.Add("56", str86);
      string str87 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X186"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X370"), "Lender", false) == 0, JS.GetStr(loan, "383") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X370"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("383_P", str87);
      string str88 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X152"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X281"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("932_$", str88);
      string str89 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X190"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X374"), "Lender", false) == 0, JS.GetStr(loan, "644") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X374"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("644_P", str89);
      string str90 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X184"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X359"), "Lender", false) != 0, JS.GetStr(loan, "648"), "");
      nameValueCollection.Add("648", str90);
      string str91 = JS.GetStr(loan, "235");
      nameValueCollection.Add("235", str91);
      string str92 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X181"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X343"), "Lender", false) != 0, JS.GetStr(loan, "646"), "");
      nameValueCollection.Add("646", str92);
      string str93 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X233"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X269"), "Lender", false) == 0, Jed.BF(Jed.S2N(JS.GetStr(loan, "1878")) != 0.0 | Jed.S2N(JS.GetStr(loan, "1621")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1878")) + Jed.S2N(JS.GetStr(loan, "1621")), (byte) 18, 0) + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X269"), "Lender", false) == 0, "-L", ""), ""), Jed.BF(Operators.CompareString(JS.GetStr(loan, "GFE3"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "1878"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "1878"), "", false) != 0, JS.GetStr(loan, "1878") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X269"), "Lender", false) == 0, "-L", ""), "")));
      nameValueCollection.Add("1621_P", str93);
      string str94 = JS.GetStr(loan, "232");
      nameValueCollection.Add("232", str94);
      string str95 = JS.GetStr(loan, "231");
      nameValueCollection.Add("231", str95);
      string str96 = JS.GetStr(loan, "230");
      nameValueCollection.Add("230", str96);
      string str97 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X231"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "GFE1"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X255"), "Lender", false) != 0, JS.GetStr(loan, "641"), "");
      nameValueCollection.Add("641", str97);
      string str98 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X232"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "GFE2"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X257"), "Lender", false) != 0, JS.GetStr(loan, "640"), "");
      nameValueCollection.Add("640", str98);
      string str99 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X147"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X265"), "Lender", false) == 0, JS.GetStr(loan, "439") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X265"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("439_P", str99);
      string str100 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X193"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X380"), "Lender", false) == 0, JS.GetStr(loan, "44") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X380"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("44_P", str100);
      string str101 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X193"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X380"), "Lender", false) != 0, JS.GetStr(loan, "44"), "");
      nameValueCollection.Add("44", str101);
      string str102 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X170"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X333"), "Lender", false) == 0, JS.GetStr(loan, "387") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X333"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("387_P", str102);
      string str103 = JS.GetStr(loan, "42");
      nameValueCollection.Add("42", str103);
      string str104 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X192"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X378"), "Lender", false) != 0, JS.GetStr(loan, "41"), "");
      nameValueCollection.Add("41", str104);
      string str105 = JS.GetStr(loan, "40");
      nameValueCollection.Add("40", str105);
      string str106 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X186"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X370"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("383_$", str106);
      string str107 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X190"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X374"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("644_$", str107);
      string str108 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X243"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X291"), "Lender", false) == 0, JS.GetStr(loan, "1625") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X291"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1625_P", str108);
      string str109 = Jed.BF((Operators.CompareString(JS.GetStr(loan, "SYS.X233"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "GFE3"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "1878"), "", false) != 0) & (Jed.S2N(JS.GetStr(loan, "1878")) != 0.0 | Jed.S2N(JS.GetStr(loan, "1621")) != 0.0), "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X269"), "Lender", false) == 0 & (Jed.S2N(JS.GetStr(loan, "1878")) != 0.0 | Jed.S2N(JS.GetStr(loan, "1621")) != 0.0), "($", ""));
      nameValueCollection.Add("1621_$", str109);
      string str110 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X147"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X265"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("439_$", str110);
      string str111 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X155"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X287"), "Lender", false) == 0, JS.GetStr(loan, "81") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X287"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("81_P", str111);
      string str112 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X137"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X253"), "Lender", false) != 0, JS.GetStr(loan, "1093"), "");
      nameValueCollection.Add("1093", str112);
      string str113 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X193"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X380"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("44_$", str113);
      string str114 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X170"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X333"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("387_$", str114);
      string str115 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X184"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X359"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("648_$", str115);
      string str116 = JS.GetStr(loan, "599");
      nameValueCollection.Add("599", str116);
      string str117 = JS.GetStr(loan, "598");
      nameValueCollection.Add("598", str117);
      string str118 = JS.GetStr(loan, "597");
      nameValueCollection.Add("597", str118);
      string str119 = JS.GetStr(loan, "596");
      nameValueCollection.Add("596", str119);
      string str120 = JS.GetStr(loan, "595");
      nameValueCollection.Add("595", str120);
      string str121 = JS.GetStr(loan, "594");
      nameValueCollection.Add("594", str121);
      string str122 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X243"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X291"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1625_$", str122);
      string str123 = JS.GetStr(loan, "592");
      nameValueCollection.Add("592", str123);
      string str124 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X239"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X327"), "Lender", false) == 0, JS.GetStr(loan, "1631") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X327"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1631_P", str124);
      string str125 = JS.GetStr(loan, "590");
      nameValueCollection.Add("590", str125);
      string str126 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X138"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X259"), "Lender", false) == 0, JS.GetStr(loan, "329") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X259"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("329_P", str126);
      string str127 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X155"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X287"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("81_$", str127);
      string str128 = JS.GetStr(loan, "200");
      nameValueCollection.Add("200", str128);
      string str129 = JS.GetStr(loan, "610");
      nameValueCollection.Add("610", str129);
      string str130 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X168"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X329"), "Lender", false) == 0, JS.GetStr(loan, "658") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X329"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("658_P", str130);
      string str131 = JS.GetStr(loan, "585");
      nameValueCollection.Add("585", str131);
      string str132 = JS.GetStr(loan, "584");
      nameValueCollection.Add("584", str132);
      string str133 = JS.GetStr(loan, "583");
      nameValueCollection.Add("583", str133);
      string str134 = JS.GetStr(loan, "582");
      nameValueCollection.Add("582", str134);
      string str135 = JS.GetStr(loan, "581");
      nameValueCollection.Add("581", str135);
      string str136 = JS.GetStr(loan, "580");
      nameValueCollection.Add("580", str136);
      string str137 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X185"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X361"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("374_$", str137);
      string str138 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X239"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X327"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1631_$", str138);
      string str139 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X138"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X259"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("329_$", str139);
      string str140 = JS.GetStr(loan, "579");
      nameValueCollection.Add("579", str140);
      string str141 = JS.GetStr(loan, "578");
      nameValueCollection.Add("578", str141);
      string str142 = JS.GetStr(loan, "577");
      nameValueCollection.Add("577", str142);
      string str143 = JS.GetStr(loan, "576");
      nameValueCollection.Add("576", str143);
      string str144 = JS.GetStr(loan, "575");
      nameValueCollection.Add("575", str144);
      string str145 = JS.GetStr(loan, "574");
      nameValueCollection.Add("574", str145);
      string str146 = JS.GetStr(loan, "572");
      nameValueCollection.Add("572", str146);
      string str147 = JS.GetStr(loan, "571");
      nameValueCollection.Add("571", str147);
      string str148 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X184"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X359"), "Lender", false) == 0, JS.GetStr(loan, "648") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X359"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("648_P", str148);
      string str149 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X168"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X329"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("658_$", str149);
      string str150 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X150"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X277"), "Lender", false) == 0, JS.GetStr(loan, "372") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X277"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("372_P", str150);
      string str151 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X241"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X363"), "Lender", false) == 0, JS.GetStr(loan, "1641") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X363"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1641_P", str151);
      string str152 = JS.GetStr(loan, "1500");
      nameValueCollection.Add("1500", str152);
      string str153 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X187"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X372"), "Lender", false) == 0, JS.GetStr(loan, "339") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X372"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("339_P", str153);
      string str154 = JS.GetStr(loan, "1880");
      nameValueCollection.Add("1880", str154);
      string str155 = JS.GetStr(loan, "569");
      nameValueCollection.Add("569", str155);
      string str156 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X156"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X289"), "Lender", false) != 0, JS.GetStr(loan, "155"), "");
      nameValueCollection.Add("155", str156);
      string str157 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X176"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X339"), "Lender", false) != 0, JS.GetStr(loan, "978"), "");
      nameValueCollection.Add("978", str157);
      string str158 = JS.GetStr(loan, "565");
      nameValueCollection.Add("565", str158);
      string str159 = JS.GetStr(loan, "564");
      nameValueCollection.Add("564", str159);
      string str160 = JS.GetStr(loan, "563");
      nameValueCollection.Add("563", str160);
      string str161 = JS.GetStr(loan, "562");
      nameValueCollection.Add("562", str161);
      string str162 = JS.GetStr(loan, "561");
      nameValueCollection.Add("561", str162);
      string str163 = JS.GetStr(loan, "560");
      nameValueCollection.Add("560", str163);
      string str164 = JS.GetStr(loan, "1879");
      nameValueCollection.Add("1879", str164);
      string str165 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X150"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X277"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("372_$", str165);
      string str166 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X241"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X363"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1641_$", str166);
      string str167 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X187"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X372"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("339_$", str167);
      string str168 = JS.GetStr(loan, "559");
      nameValueCollection.Add("559", str168);
      string str169 = JS.GetStr(loan, "558");
      nameValueCollection.Add("558", str169);
      string str170 = JS.GetStr(loan, "557");
      nameValueCollection.Add("557", str170);
      string str171 = JS.GetStr(loan, "143");
      nameValueCollection.Add("143", str171);
      string str172 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X154"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X285"), "Lender", false) != 0, JS.GetStr(loan, "554"), "");
      nameValueCollection.Add("554", str172);
      string str173 = JS.GetStr(loan, "154");
      nameValueCollection.Add("154", str173);
      string str174 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X165"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X323"), "Lender", false) == 0, JS.GetStr(loan, "655") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X323"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("655_P", str174);
      string str175 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X154"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X285"), "Lender", false) == 0, JS.GetStr(loan, "554") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X285"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("554_P", str175);
      string str176 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X151"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X279"), "Lender", false) == 0, JS.GetStr(loan, "349") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X279"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("349_P", str176);
      string str177 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X160"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X309"), "Lender", false) == 0, JS.GetStr(loan, "643") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X309"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("643_P", str177);
      string str178 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X154"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X285"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("554_$", str178);
      string str179 = JS.GetStr(loan, "1850");
      nameValueCollection.Add("1850", str179);
      string str180 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X183"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X357"), "Lender", false) == 0, JS.GetStr(loan, "647") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X357"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("647_P", str180);
      string str181 = JS.GetStr(loan, "1636");
      nameValueCollection.Add("1636", str181);
      string str182 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X151"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X279"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("349_$", str182);
      string str183 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X160"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X309"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("643_$", str183);
      string str184 = JS.GetStr(loan, "1630");
      nameValueCollection.Add("1630", str184);
      string str185 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X161"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X313"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("L260_$", str185);
      string str186 = JS.GetStr(loan, "REGZGFE.X15");
      nameValueCollection.Add("REGZGFE_X15", str186);
      string str187 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X388"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X391"), "Lender", false) != 0, JS.GetStr(loan, "1849"), "");
      nameValueCollection.Add("1849", str187);
      string str188 = JS.GetStr(loan, "1843");
      nameValueCollection.Add("1843", str188);
      string str189 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X298"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X301"), "Lender", false) != 0, JS.GetStr(loan, "1842"), "");
      nameValueCollection.Add("1842", str189);
      string str190 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X298"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X301"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1842_$", str190);
      string str191 = JS.GetStr(loan, "1840");
      nameValueCollection.Add("1840", str191);
      string str192 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X175"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X337"), "Lender", false) == 0, JS.GetStr(loan, "392") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X337"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("392_P", str192);
      string str193 = JS.GetStr(loan, "1624");
      nameValueCollection.Add("1624", str193);
      string str194 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X183"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X357"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("647_$", str194);
      string str195 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X152"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X281"), "Lender", false) != 0, JS.GetStr(loan, "932"), "");
      nameValueCollection.Add("932", str195);
      string str196 = JS.GetStr(loan, "931");
      nameValueCollection.Add("931", str196);
      string str197 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X293"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X296"), "Lender", false) != 0, JS.GetStr(loan, "1839"), "");
      nameValueCollection.Add("1839", str197);
      string str198 = JS.GetStr(loan, "1838");
      nameValueCollection.Add("1838", str198);
      string str199 = JS.GetStr(loan, "1391");
      nameValueCollection.Add("1391", str199);
      string str200 = JS.GetStr(loan, "1390");
      nameValueCollection.Add("1390", str200);
      string str201 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X174"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X335"), "Lender", false) == 0, JS.GetStr(loan, "396") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X335"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("396_P", str201);
      string str202 = JS.GetStr(loan, "L289");
      nameValueCollection.Add("L289", str202);
      string str203 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X167"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X325"), "Lender", false) == 0, JS.GetStr(loan, "657") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X325"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("657_P", str203);
      string str204 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X153"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X283"), "Lender", false) != 0, JS.GetStr(loan, "1009"), "");
      nameValueCollection.Add("1009", str204);
      string str205 = JS.GetStr(loan, "1388");
      nameValueCollection.Add("1388", str205);
      string str206 = JS.GetStr(loan, "1387");
      nameValueCollection.Add("1387", str206);
      string str207 = JS.GetStr(loan, "1386");
      nameValueCollection.Add("1386", str207);
      string str208 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X136"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X251"), "Lender", false) == 0, JS.GetStr(loan, "454") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X251"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("454_P", str208);
      string str209 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X250"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X386"), "Lender", false) != 0, JS.GetStr(loan, "1793"), "");
      nameValueCollection.Add("1793", str209);
      string str210 = JS.GetStr(loan, "1792");
      nameValueCollection.Add("1792", str210);
      string str211 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X139"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X261"), "Lender", false) == 0, JS.GetStr(loan, "L228") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X261"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("L228_P", str211);
      string str212 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X140"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X263"), "Lender", false) == 0, JS.GetStr(loan, "L230") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X263"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("L230_P", str212);
      string str213 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X174"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X335"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("396_$", str213);
      string str214 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X167"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X325"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("657_$", str214);
      string str215 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X163"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X319"), "Lender", false) == 0, JS.GetStr(loan, "338") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X319"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("338_P", str215);
      string str216 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X240"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X345"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1634_$", str216);
      string str217 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1812"), "", false) != 0, " to " + JS.GetStr(loan, "1812"), "");
      nameValueCollection.Add("810", str217);
      string str218 = JS.GetStr(loan, "1789");
      nameValueCollection.Add("1789", str218);
      string str219 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X249"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X384"), "Lender", false) != 0, JS.GetStr(loan, "1788"), "");
      nameValueCollection.Add("1788", str219);
      string str220 = JS.GetStr(loan, "1787");
      nameValueCollection.Add("1787", str220);
      string str221 = JS.GetStr(loan, "1784");
      nameValueCollection.Add("1784", str221);
      string str222 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X248"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X382"), "Lender", false) != 0, JS.GetStr(loan, "1783"), "");
      nameValueCollection.Add("1783", str222);
      string str223 = JS.GetStr(loan, "1782");
      nameValueCollection.Add("1782", str223);
      string str224 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X235"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X311"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1050_$", str224);
      string str225 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X136"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X251"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("454_$", str225);
      string str226 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X139"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X261"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("L228_$", str226);
      string str227 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X140"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X263"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("L230_$", str227);
      string str228 = Jed.BF((Operators.CompareString(JS.GetStr(loan, "SYS.X232"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "GFE2"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "449"), "", false) != 0) & (Jed.S2N(JS.GetStr(loan, "449")) != 0.0 | Jed.S2N(JS.GetStr(loan, "640")) != 0.0), "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X257"), "Lender", false) == 0 & (Jed.S2N(JS.GetStr(loan, "449")) != 0.0 | Jed.S2N(JS.GetStr(loan, "640")) != 0.0), "($", ""));
      nameValueCollection.Add("640_$", str228);
      string str229 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X242"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X365"), "Lender", false) == 0, JS.GetStr(loan, "1644") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X365"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1644_P", str229);
      string str230 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X247"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X353"), "Lender", false) != 0, JS.GetStr(loan, "1778"), "");
      nameValueCollection.Add("1778", str230);
      string str231 = JS.GetStr(loan, "1777");
      nameValueCollection.Add("1777", str231);
      string str232 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X249"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X384"), "Lender", false) == 0, JS.GetStr(loan, "1788") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X384"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1788_P", str232);
      string str233 = JS.GetStr(loan, "1774");
      nameValueCollection.Add("1774", str233);
      string str234 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X246"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X351"), "Lender", false) != 0, JS.GetStr(loan, "1773"), "");
      nameValueCollection.Add("1773", str234);
      string str235 = JS.GetStr(loan, "1772");
      nameValueCollection.Add("1772", str235);
      string str236 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X163"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X319"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("338_$", str236);
      string str237 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X164"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X321"), "Lender", false) == 0, JS.GetStr(loan, "L269") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X321"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("L269_P", str237);
      string str238 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X136"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X251"), "Lender", false) != 0, JS.GetStr(loan, "454"), "");
      nameValueCollection.Add("454", str238);
      string str239 = JS.GetStr(loan, "1769");
      nameValueCollection.Add("1769", str239);
      string str240 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X245"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X349"), "Lender", false) != 0, JS.GetStr(loan, "1768"), "");
      nameValueCollection.Add("1768", str240);
      string str241 = JS.GetStr(loan, "1767");
      nameValueCollection.Add("1767", str241);
      string str242 = JS.GetStr(loan, "1764");
      nameValueCollection.Add("1764", str242);
      string str243 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X244"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X347"), "Lender", false) != 0, JS.GetStr(loan, "1763"), "");
      nameValueCollection.Add("1763", str243);
      string str244 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X242"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X365"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1644_$", str244);
      string str245 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X245"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X349"), "Lender", false) == 0, JS.GetStr(loan, "1768") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X349"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1768_P", str245);
      string str246 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X159"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X307"), "Lender", false) == 0, JS.GetStr(loan, "642") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X307"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("642_P", str246);
      string str247 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X164"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X321"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("L269_$", str247);
      string str248 = JS.GetStr(loan, "L295");
      nameValueCollection.Add("L295", str248);
      string str249 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X173"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X407"), "Lender", false) != 0, JS.GetStr(loan, "L294"), "");
      nameValueCollection.Add("L294", str249);
      string str250 = JS.GetStr(loan, "L293");
      nameValueCollection.Add("L293", str250);
      string str251 = JS.GetStr(loan, "1345");
      nameValueCollection.Add("1345", str251);
      string str252 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X177"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X341"), "Lender", false) == 0, JS.GetStr(loan, "385") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X341"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("385_P", str252);
      string str253 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X157"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X303"), "Lender", false) == 0, JS.GetStr(loan, "334") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X303"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("334_P", str253);
      string str254 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X181"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X343"), "Lender", false) == 0, JS.GetStr(loan, "646") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X343"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("646_P", str254);
      string str255 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X147"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X265"), "Lender", false) != 0, JS.GetStr(loan, "439"), "");
      nameValueCollection.Add("439", str255);
      string str256 = JS.GetStr(loan, "410");
      nameValueCollection.Add("410", str256);
      string str257 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X159"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X307"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("642_$", str257);
      string str258 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X234"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X273"), "Lender", false) == 0, JS.GetStr(loan, "1623") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X273"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1623_P", str258);
      string str259 = JS.GetStr(loan, "369");
      nameValueCollection.Add("369", str259);
      string str260 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X177"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X341"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("385_$", str260);
      string str261 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X247"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X353"), "Lender", false) == 0, JS.GetStr(loan, "1778") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X353"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1778_P", str261);
      string str262 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X181"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X343"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("646_$", str262);
      string str263 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X174"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X335"), "Lender", false) != 0, JS.GetStr(loan, "396"), "");
      nameValueCollection.Add("396", str263);
      string str264 = JS.GetStr(loan, "395");
      nameValueCollection.Add("395", str264);
      string str265 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X234"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X273"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1623_$", str265);
      string str266 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X175"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X337"), "Lender", false) != 0, JS.GetStr(loan, "392"), "");
      nameValueCollection.Add("392", str266);
      string str267 = JS.GetStr(loan, "391");
      nameValueCollection.Add("391", str267);
      string str268 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X182"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X355"), "Lender", false) != 0, JS.GetStr(loan, "390"), "");
      nameValueCollection.Add("390", str268);
      string str269 = JS.GetStr(loan, "1296");
      nameValueCollection.Add("1296", str269);
      string str270 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X156"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X289"), "Lender", false) == 0, JS.GetStr(loan, "155") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X289"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("155_P", str270);
      string str271 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X137"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X253"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1093_$", str271);
      string str272 = JS.GetStr(loan, "L267");
      nameValueCollection.Add("L267", str272);
      string str273 = JS.GetStr(loan, "411");
      nameValueCollection.Add("411", str273);
      string str274 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X170"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X333"), "Lender", false) != 0, JS.GetStr(loan, "387"), "");
      nameValueCollection.Add("387", str274);
      string str275 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X162"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X317"), "Lender", false) == 0, JS.GetStr(loan, "656") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X317"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("656_P", str275);
      string str276 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X177"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X341"), "Lender", false) != 0, JS.GetStr(loan, "385"), "");
      nameValueCollection.Add("385", str276);
      string str277 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X186"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X370"), "Lender", false) != 0, JS.GetStr(loan, "383"), "");
      nameValueCollection.Add("383", str277);
      string str278 = JS.GetStr(loan, "L261");
      nameValueCollection.Add("L261", str278);
      string str279 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X161"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X313"), "Lender", false) != 0, JS.GetStr(loan, "L260"), "");
      nameValueCollection.Add("L260", str279);
      string str280 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X244"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X347"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1763_$", str280);
      string str281 = JS.GetStr(loan, "L217");
      nameValueCollection.Add("L217", str281);
      string str282 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X172"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X405"), "Lender", false) == 0, JS.GetStr(loan, "L291") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X405"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("L291_P", str282);
      string str283 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X161"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X313"), "Lender", false) == 0, JS.GetStr(loan, "L260") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X313"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("L260_P", str283);
      string str284 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X156"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X289"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("155_$", str284);
      string str285 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X142"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X271"), "Lender", false) != 0, JS.GetStr(loan, "367"), "");
      nameValueCollection.Add("367", str285);
      string str286 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X298"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X301"), "Lender", false) == 0, JS.GetStr(loan, "1842") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X301"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1842_P", str286);
      string str287 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1813"), "", false) != 0, " to " + JS.GetStr(loan, "1813"), "");
      nameValueCollection.Add("812", str287);
      string str288 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X8"), "", false) != 0, " to " + JS.GetStr(loan, "REGZGFE.X8"), "");
      nameValueCollection.Add("811", str288);
      string str289 = JS.GetStr(loan, "375");
      nameValueCollection.Add("375", str289);
      string str290 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X185"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X361"), "Lender", false) != 0, JS.GetStr(loan, "374"), "");
      nameValueCollection.Add("374", str290);
      string str291 = JS.GetStr(loan, "373");
      nameValueCollection.Add("373", str291);
      string str292 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X150"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X277"), "Lender", false) != 0, JS.GetStr(loan, "372"), "");
      nameValueCollection.Add("372", str292);
      string str293 = JS.GetStr(loan, "371");
      nameValueCollection.Add("371", str293);
      string str294 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X149"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X275"), "Lender", false) != 0, JS.GetStr(loan, "370"), "");
      nameValueCollection.Add("370", str294);
      string str295 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X162"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X317"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("656_$", str295);
      string str296 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X149"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X275"), "Lender", false) == 0, JS.GetStr(loan, "370") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X275"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("370_P", str296);
      string str297 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X158"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X305"), "Lender", false) == 0, JS.GetStr(loan, "337") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X305"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("337_P", str297);
      string str298 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X172"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X405"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("L291_$", str298);
      string str299 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X240"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X345"), "Lender", false) == 0, JS.GetStr(loan, "1634") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X345"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1634_P", str299);
      string str300 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "L224"), "", false) != 0, " to " + JS.GetStr(loan, "L224"), "");
      nameValueCollection.Add("809", str300);
      string str301 = JS.GetStr(loan, "389") + "% + $" + JS.GetStr(loan, "1620") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X14"), "", false) != 0, " to " + JS.GetStr(loan, "REGZGFE.X14"), "");
      nameValueCollection.Add("808", str301);
      string str302 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X7"), "", false) != 0, " to " + JS.GetStr(loan, "REGZGFE.X7"), "");
      nameValueCollection.Add("807", str302);
      string str303 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "L227"), "", false) != 0, " to " + JS.GetStr(loan, "L227"), "");
      nameValueCollection.Add("806", str303);
      string str304 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "L704"), "", false) != 0, " to " + JS.GetStr(loan, "L704"), "");
      nameValueCollection.Add("805", str304);
      string str305 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "624"), "", false) != 0, " to " + JS.GetStr(loan, "624"), "");
      nameValueCollection.Add("804", str305);
      string str306 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "617"), "", false) != 0, " to " + JS.GetStr(loan, "617"), "");
      nameValueCollection.Add("803", str306);
      string str307 = JS.GetStr(loan, "1061") + "% + $" + JS.GetStr(loan, "436") + " " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X6"), "", false) != 0, " to " + JS.GetStr(loan, "REGZGFE.X6"), "");
      nameValueCollection.Add("802", str307);
      string str308 = JS.GetStr(loan, "388") + "% + $" + JS.GetStr(loan, "1619") + " " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZGFE.X5"), "", false) != 0, " to " + JS.GetStr(loan, "REGZGFE.X5"), "");
      nameValueCollection.Add("801", str308);
      string str309 = JS.GetStr(loan, "L292");
      nameValueCollection.Add("L292", str309);
      string str310 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X172"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X405"), "Lender", false) != 0, JS.GetStr(loan, "L291"), "");
      nameValueCollection.Add("L291", str310);
      string str311 = JS.GetStr(loan, "L290");
      nameValueCollection.Add("L290", str311);
      string str312 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X249"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X384"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1788_$", str312);
      string str313 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X185"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X361"), "Lender", false) == 0, JS.GetStr(loan, "374") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X361"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("374_P", str313);
      string str314 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X149"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X275"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("370_$", str314);
      string str315 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X244"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X347"), "Lender", false) == 0, JS.GetStr(loan, "1763") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X347"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1763_P", str315);
      string str316 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X158"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X305"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("337_$", str316);
      string str317 = JS.GetStr(loan, "L725");
      nameValueCollection.Add("L725", str317);
      string str318 = JS.GetStr(loan, "1841");
      nameValueCollection.Add("1841", str318);
      string str319 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X171"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X403"), "Lender", false) != 0, JS.GetStr(loan, "L288"), "");
      nameValueCollection.Add("L288", str319);
      string str320 = JS.GetStr(loan, "L287");
      nameValueCollection.Add("L287", str320);
      string str321 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X191"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X376"), "Lender", false) != 0, JS.GetStr(loan, "645"), "");
      nameValueCollection.Add("645", str321);
      string str322 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X160"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X309"), "Lender", false) != 0, JS.GetStr(loan, "643"), "");
      nameValueCollection.Add("643", str322);
      string str323 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X157"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X303"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("334_$", str323);
      string str324 = JS.GetStr(loan, "1668");
      nameValueCollection.Add("1668", str324);
      string str325 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X238"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X315"), "Lender", false) != 0, JS.GetStr(loan, "1667"), "");
      nameValueCollection.Add("1667", str325);
      string str326 = JS.GetStr(loan, "1666");
      nameValueCollection.Add("1666", str326);
      string str327 = JS.GetStr(loan, "1665");
      nameValueCollection.Add("1665", str327);
      string str328 = JS.GetStr(loan, "1664");
      nameValueCollection.Add("1664", str328);
      string str329 = JS.GetStr(loan, "1663");
      nameValueCollection.Add("1663", str329);
      string str330 = JS.GetStr(loan, "1662");
      nameValueCollection.Add("1662", str330);
      string str331 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X231"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X255"), "Lender", false) == 0, Jed.BF(Jed.S2N(JS.GetStr(loan, "448")) != 0.0 | Jed.S2N(JS.GetStr(loan, "641")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "448")) + Jed.S2N(JS.GetStr(loan, "641")), (byte) 18, 0) + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X255"), "Lender", false) == 0, "-L", ""), ""), Jed.BF(Operators.CompareString(JS.GetStr(loan, "GFE1"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "448"), "", false) != 0, Jed.BF(Operators.CompareString(JS.GetStr(loan, "448"), "", false) != 0, JS.GetStr(loan, "448") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X255"), "Lender", false) == 0, "-L", ""), "")));
      nameValueCollection.Add("641_P", str331);
      string str332 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X163"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X319"), "Lender", false) != 0, JS.GetStr(loan, "338"), "");
      nameValueCollection.Add("338", str332);
      string str333 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X151"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X279"), "Lender", false) != 0, JS.GetStr(loan, "349"), "");
      nameValueCollection.Add("349", str333);
      string str334 = JS.GetStr(loan, "348");
      nameValueCollection.Add("348", str334);
      string str335 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X171"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X403"), "Lender", false) == 0, JS.GetStr(loan, "L288") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X403"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("L288_P", str335);
      string str336 = JS.GetStr(loan, "L270");
      nameValueCollection.Add("L270", str336);
      string str337 = JS.GetStr(loan, "341");
      nameValueCollection.Add("341", str337);
      string str338 = JS.GetStr(loan, "340");
      nameValueCollection.Add("340", str338);
      string str339 = JS.GetStr(loan, "96");
      nameValueCollection.Add("96", str339);
      string str340 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X192"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X378"), "Lender", false) == 0, JS.GetStr(loan, "41") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X378"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("41_P", str340);
      string str341 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X164"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X321"), "Lender", false) != 0, JS.GetStr(loan, "L269"), "");
      nameValueCollection.Add("L269", str341);
      string str342 = JS.GetStr(loan, "L268");
      nameValueCollection.Add("L268", str342);
      string str343 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X191"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X376"), "Lender", false) == 0, JS.GetStr(loan, "645") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X376"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("645_P", str343);
      string str344 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X187"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X372"), "Lender", false) != 0, JS.GetStr(loan, "339"), "");
      nameValueCollection.Add("339", str344);
      string str345 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X246"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X351"), "Lender", false) == 0, JS.GetStr(loan, "1773") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X351"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1773_P", str345);
      string str346 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X158"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X305"), "Lender", false) != 0, JS.GetStr(loan, "337"), "");
      nameValueCollection.Add("337", str346);
      string str347 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X141"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X267"), "Lender", false) != 0, JS.GetStr(loan, "336"), "");
      nameValueCollection.Add("336", str347);
      string str348 = Jed.BF((Operators.CompareString(JS.GetStr(loan, "SYS.X231"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "GFE1"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "448"), "", false) != 0) & (Jed.S2N(JS.GetStr(loan, "448")) != 0.0 | Jed.S2N(JS.GetStr(loan, "641")) != 0.0), "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X255"), "Lender", false) == 0 & (Jed.S2N(JS.GetStr(loan, "448")) != 0.0 | Jed.S2N(JS.GetStr(loan, "641")) != 0.0), "($", ""));
      nameValueCollection.Add("641_$", str348);
      string str349 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X157"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X303"), "Lender", false) != 0, JS.GetStr(loan, "334"), "");
      nameValueCollection.Add("334", str349);
      string str350 = JS.GetStr(loan, "333");
      nameValueCollection.Add("333", str350);
      string str351 = JS.GetStr(loan, "6");
      nameValueCollection.Add("6", str351);
      string str352 = JS.GetStr(loan, "1645");
      nameValueCollection.Add("1645", str352);
      string str353 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X242"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X365"), "Lender", false) != 0, JS.GetStr(loan, "1644"), "");
      nameValueCollection.Add("1644", str353);
      string str354 = JS.GetStr(loan, "1643");
      nameValueCollection.Add("1643", str354);
      string str355 = JS.GetStr(loan, "1642");
      nameValueCollection.Add("1642", str355);
      string str356 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X241"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X363"), "Lender", false) != 0, JS.GetStr(loan, "1641"), "");
      nameValueCollection.Add("1641", str356);
      string str357 = JS.GetStr(loan, "1640");
      nameValueCollection.Add("1640", str357);
      string str358 = JS.GetStr(loan, "L259");
      nameValueCollection.Add("L259", str358);
      string str359 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X192"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X378"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("41_$", str359);
      string str360 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X138"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X259"), "Lender", false) != 0, JS.GetStr(loan, "329"), "");
      nameValueCollection.Add("329", str360);
      string str361 = JS.GetStr(loan, "1794");
      nameValueCollection.Add("1794", str361);
      string str362 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X182"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X355"), "Lender", false) == 0, JS.GetStr(loan, "390") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X355"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("390_P", str362);
      string str363 = JS.GetStr(loan, "L252");
      nameValueCollection.Add("L252", str363);
      string str364 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X191"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X376"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("645_$", str364);
      string str365 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X246"), "Y", false) == 0, "POC($", Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X351"), "Lender", false) == 0, "($", ""));
      nameValueCollection.Add("1773_$", str365);
      string str366 = JS.GetStr(loan, "1638");
      nameValueCollection.Add("1638", str366);
      string str367 = JS.GetStr(loan, "1637");
      nameValueCollection.Add("1637", str367);
      string str368 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X153"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X283"), "Lender", false) == 0, JS.GetStr(loan, "1009") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X283"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("1009_P", str368);
      string str369 = JS.GetStr(loan, "1635");
      nameValueCollection.Add("1635", str369);
      string str370 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X240"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X345"), "Lender", false) != 0, JS.GetStr(loan, "1634"), "");
      nameValueCollection.Add("1634", str370);
      string str371 = JS.GetStr(loan, "1633");
      nameValueCollection.Add("1633", str371);
      string str372 = JS.GetStr(loan, "1632");
      nameValueCollection.Add("1632", str372);
      string str373 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X239"), "Y", false) != 0 & Operators.CompareString(JS.GetStr(loan, "SYS.X327"), "Lender", false) != 0, JS.GetStr(loan, "1631"), "");
      nameValueCollection.Add("1631", str373);
      string str374 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X176"), "Y", false) == 0 | Operators.CompareString(JS.GetStr(loan, "SYS.X339"), "Lender", false) == 0, JS.GetStr(loan, "978") + ")" + Jed.BF(Operators.CompareString(JS.GetStr(loan, "SYS.X339"), "Lender", false) == 0, "-L", ""), "");
      nameValueCollection.Add("978_P", str374);
      return nameValueCollection;
    }
  }
}
