// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._ITEMIZEDFEEWORKSHEETCLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _ITEMIZEDFEEWORKSHEETCLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "363");
      nameValueCollection.Add("363", str1);
      string str2 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315", str2);
      string str3 = JS.GetStr(loan, "319");
      nameValueCollection.Add("319", str3);
      string str4 = JS.GetStr(loan, "313") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "321"), "", false) != 0, ", ") + JS.GetStr(loan, "321") + " " + JS.GetStr(loan, "323");
      nameValueCollection.Add("313_321_323", str4);
      string str5 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2026"), "", false) != 0, JS.GetStr(loan, "2026"), JS.GetStr(loan, "317")) + " " + Jed.BF(Operators.CompareString(JS.GetStr(loan, "2026"), "", false) != 0, JS.GetStr(loan, "2027"), JS.GetStr(loan, "324"));
      nameValueCollection.Add("317_324", str5);
      string str6 = JS.GetStr(loan, "11");
      nameValueCollection.Add("11", str6);
      string str7 = JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("12_14_15", str7);
      string str8 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str8);
      string str9 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69", str9);
      string str10 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37_a", str10);
      string str11 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69_a", str11);
      string str12 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str12);
      string str13 = JS.GetStr(loan, "1401");
      nameValueCollection.Add("1401", str13);
      string str14 = JS.GetStr(loan, "3") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "3"), "", false) != 0, " %");
      nameValueCollection.Add("3", str14);
      string str15 = JS.GetStr(loan, "4");
      nameValueCollection.Add("4", str15);
      string str16 = JS.GetStr(loan, "1172");
      nameValueCollection.Add("1172", str16);
      string str17 = JS.GetStr(loan, "136");
      nameValueCollection.Add("136", str17);
      string str18 = JS.GetStr(loan, "1109");
      nameValueCollection.Add("1109", str18);
      string str19 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str19);
      string str20 = JS.GetStr(loan, "388");
      nameValueCollection.Add("388", str20);
      string str21 = JS.GetStr(loan, "1619");
      nameValueCollection.Add("1619", str21);
      string str22 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "389"), "", false) != 0 | Operators.CompareString(JS.GetStr(loan, "1620"), "", false) != 0, JS.GetStr(loan, "389") + "%") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1620"), "", false) != 0, " + ") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1620"), "", false) != 0, "$ " + JS.GetStr(loan, "1620"));
      nameValueCollection.Add("389", str22);
      string str23 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X223"), "", false) != 0 | Operators.CompareString(JS.GetStr(loan, "NEWHUD.X224"), "", false) != 0, JS.GetStr(loan, "NEWHUD.X223") + "%") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X224"), "", false) != 0, "+") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X224"), "", false) != 0, "$ " + JS.GetStr(loan, "NEWHUD.X224"));
      nameValueCollection.Add("NEWHUD_X223", str23);
      string str24 = JS.GetStr(loan, "617");
      nameValueCollection.Add("617", str24);
      string str25 = JS.GetStr(loan, "624");
      nameValueCollection.Add("624", str25);
      string str26 = JS.GetStr(loan, "L224");
      nameValueCollection.Add("L224", str26);
      string str27 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X399"), "", false) != 0, "to " + JS.GetStr(loan, "NEWHUD.X399"), "");
      nameValueCollection.Add("NEWHUD_X399", str27);
      string str28 = JS.GetStr(loan, "NEWHUD.X126") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1050"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1050"), "");
      nameValueCollection.Add("NEWHUD_X126", str28);
      string str29 = JS.GetStr(loan, "NEWHUD.X127") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1051"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1051"), "");
      nameValueCollection.Add("NEWHUD_X127", str29);
      string str30 = JS.GetStr(loan, "NEWHUD.X128") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1052"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1052"), "");
      nameValueCollection.Add("NEWHUD_X128", str30);
      string str31 = JS.GetStr(loan, "NEWHUD.X129") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1053"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1053"), "");
      nameValueCollection.Add("NEWHUD_X129", str31);
      string str32 = JS.GetStr(loan, "NEWHUD.X130") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1054"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1054"), "");
      nameValueCollection.Add("NEWHUD_X130", str32);
      string str33 = JS.GetStr(loan, "369") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1055"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1055"), "");
      nameValueCollection.Add("369", str33);
      string str34 = JS.GetStr(loan, "371") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1056"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1056"), "");
      nameValueCollection.Add("371", str34);
      string str35 = JS.GetStr(loan, "348") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1057"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1057"), "");
      nameValueCollection.Add("348", str35);
      string str36 = JS.GetStr(loan, "931") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1058"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1058"), "");
      nameValueCollection.Add("931", str36);
      string str37 = JS.GetStr(loan, "1390") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1059"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1059"), "");
      nameValueCollection.Add("1390", str37);
      string str38 = JS.GetStr(loan, "410") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1060"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1060"), "");
      nameValueCollection.Add("410", str38);
      string str39 = JS.GetStr(loan, "NEWHUD.X656") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1061"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1061"), "");
      nameValueCollection.Add("NEWHUD_X656", str39);
      string str40 = JS.GetStr(loan, "NEWHUD.X1291") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1292"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1292"), "");
      nameValueCollection.Add("NEWHUD_X1291", str40);
      string str41 = JS.GetStr(loan, "NEWHUD.X1299") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1300"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1300"), "");
      nameValueCollection.Add("NEWHUD_X1299", str41);
      string str42 = JS.GetStr(loan, "NEWHUD.X1307") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1308"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1308"), "");
      nameValueCollection.Add("NEWHUD_X1307", str42);
      string str43 = JS.GetStr(loan, "NEWHUD.X1315") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1316"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1316"), "");
      nameValueCollection.Add("NEWHUD_X1315", str43);
      string str44 = JS.GetStr(loan, "NEWHUD.X1323") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1324"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1324"), "");
      nameValueCollection.Add("NEWHUD_X1323", str44);
      string str45 = JS.GetStr(loan, "NEWHUD.X1331") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1332"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1332"), "");
      nameValueCollection.Add("NEWHUD_X1331", str45);
      string str46 = JS.GetStr(loan, "NEWHUD.X1339") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1340"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1340"), "");
      nameValueCollection.Add("NEWHUD_X1339", str46);
      string str47 = JS.GetStr(loan, "NEWHUD.X1347") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1348"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1348"), "");
      nameValueCollection.Add("NEWHUD_X1347", str47);
      string str48 = JS.GetStr(loan, "NEWHUD.X1355") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1356"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1356"), "");
      nameValueCollection.Add("NEWHUD_X1355", str48);
      string str49 = JS.GetStr(loan, "NEWHUD.X1363") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1364"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1364"), "");
      nameValueCollection.Add("NEWHUD_X1363", str49);
      string str50 = JS.GetStr(loan, "NEWHUD.X1371") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1372"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1372"), "");
      nameValueCollection.Add("NEWHUD_X1371", str50);
      string str51 = JS.GetStr(loan, "NEWHUD.X1379") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1380"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1380"), "");
      nameValueCollection.Add("NEWHUD_X1379", str51);
      string str52 = JS.GetStr(loan, "NEWHUD.X1387") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1388"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1388"), "");
      nameValueCollection.Add("NEWHUD_X1387", str52);
      string str53 = JS.GetStr(loan, "NEWHUD.X1395") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1396"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1396"), "");
      nameValueCollection.Add("NEWHUD_X1395", str53);
      string str54 = JS.GetStr(loan, "NEWHUD.X1403") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1404"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1404"), "");
      nameValueCollection.Add("NEWHUD_X1403", str54);
      string str55 = JS.GetStr(loan, "NEWHUD.X1411") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1411"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1411"), "");
      nameValueCollection.Add("NEWHUD_X1411", str55);
      string str56 = JS.GetStr(loan, "NEWHUD.X951") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1070"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1070"), "");
      nameValueCollection.Add("NEWHUD_X951", str56);
      string str57 = JS.GetStr(loan, "NEWHUD.X960") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1071"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1071"), "");
      nameValueCollection.Add("NEWHUD_X960", str57);
      string str58 = JS.GetStr(loan, "NEWHUD.X969") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1072"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1072"), "");
      nameValueCollection.Add("NEWHUD_X969", str58);
      string str59 = JS.GetStr(loan, "NEWHUD.X978") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1073"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1073"), "");
      nameValueCollection.Add("NEWHUD_X978", str59);
      string str60 = JS.GetStr(loan, "NEWHUD.X987") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1074"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1074"), "");
      nameValueCollection.Add("NEWHUD_X987", str60);
      string str61 = JS.GetStr(loan, "NEWHUD.X996") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1075"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1075"), "");
      nameValueCollection.Add("NEWHUD_X996", str61);
      string str62 = JS.GetStr(loan, "NEWHUD.X208") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1076"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1076"), "");
      nameValueCollection.Add("NEWHUD_X208", str62);
      string str63 = JS.GetStr(loan, "NEWHUD.X209") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1077"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1077"), "");
      nameValueCollection.Add("NEWHUD_X209", str63);
      string str64 = JS.GetStr(loan, "1762") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1078"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1078"), "");
      nameValueCollection.Add("1762", str64);
      string str65 = JS.GetStr(loan, "1767") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1079"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1079"), "");
      nameValueCollection.Add("1767", str65);
      string str66 = JS.GetStr(loan, "1772") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1080"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1080"), "");
      nameValueCollection.Add("1772", str66);
      string str67 = JS.GetStr(loan, "1777") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1081"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1081"), "");
      nameValueCollection.Add("1777", str67);
      string str68 = JS.GetStr(loan, "NEWHUD.X1602") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1603"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1603"), "");
      nameValueCollection.Add("NEWHUD_X1602", str68);
      string str69 = JS.GetStr(loan, "NEWHUD.X1610") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1611"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1611"), "");
      nameValueCollection.Add("NEWHUD_X1610", str69);
      string str70 = JS.GetStr(loan, "373") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1082"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1082"), "");
      nameValueCollection.Add("373", str70);
      string str71 = JS.GetStr(loan, "1640") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1083"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1083"), "");
      nameValueCollection.Add("1640", str71);
      string str72 = JS.GetStr(loan, "1643") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1084"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1084"), "");
      nameValueCollection.Add("1643", str72);
      string str73 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X947"), "", false) != 0, "to " + JS.GetStr(loan, "NEWHUD.X947"), "");
      nameValueCollection.Add("NEWHUD_X947", str73);
      string str74 = JS.GetStr(loan, "NEWHUD.X1618") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1619"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1619"), "");
      nameValueCollection.Add("NEWHUD_X1618", str74);
      string str75 = JS.GetStr(loan, "NEWHUD.X1625") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1626"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1626"), "");
      nameValueCollection.Add("NEWHUD_X1625", str75);
      string str76 = JS.GetStr(loan, "NEWHUD.X251") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1085"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1085"), "");
      nameValueCollection.Add("NEWHUD_X251", str76);
      string str77 = JS.GetStr(loan, "650") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1086"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1086"), "");
      nameValueCollection.Add("650", str77);
      string str78 = JS.GetStr(loan, "651") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1087"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1087"), "");
      nameValueCollection.Add("651", str78);
      string str79 = JS.GetStr(loan, "40") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1088"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1088"), "");
      nameValueCollection.Add("40", str79);
      string str80 = JS.GetStr(loan, "43") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1089"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1089"), "");
      nameValueCollection.Add("43", str80);
      string str81 = JS.GetStr(loan, "1782") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1090"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1090"), "");
      nameValueCollection.Add("1782", str81);
      string str82 = JS.GetStr(loan, "1787") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1091"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1091"), "");
      nameValueCollection.Add("1787", str82);
      string str83 = JS.GetStr(loan, "1792") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1092"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1092"), "");
      nameValueCollection.Add("1792", str83);
      string str84 = JS.GetStr(loan, "NEWHUD.X252") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1093"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1093"), "");
      nameValueCollection.Add("NEWHUD_X252", str84);
      string str85 = JS.GetStr(loan, "NEWHUD.X253") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1094"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1094"), "");
      nameValueCollection.Add("NEWHUD_X253", str85);
      string str86 = JS.GetStr(loan, "NEWHUD.X1632") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1633"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1633"), "");
      nameValueCollection.Add("NEWHUD_X1632", str86);
      string str87 = JS.GetStr(loan, "NEWHUD.X1640") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1641"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1641"), "");
      nameValueCollection.Add("NEWHUD_X1640", str87);
      string str88 = JS.GetStr(loan, "NEWHUD.X1648") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1649"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1649"), "");
      nameValueCollection.Add("NEWHUD_X1648", str88);
      string str89 = JS.GetStr(loan, "NEWHUD.X1656") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X1657"), "", false) != 0, " to " + JS.GetStr(loan, "NEWHUD.X1657"), "");
      nameValueCollection.Add("NEWHUD_X1656", str89);
      string str90 = JS.GetStr(loan, "228");
      nameValueCollection.Add("228", str90);
      string str91 = JS.GetStr(loan, "229");
      nameValueCollection.Add("229", str91);
      string str92 = JS.GetStr(loan, "230");
      nameValueCollection.Add("230_a", str92);
      string str93 = JS.GetStr(loan, "1405");
      nameValueCollection.Add("1405", str93);
      string str94 = JS.GetStr(loan, "232");
      nameValueCollection.Add("232_a", str94);
      string str95 = JS.GetStr(loan, "233");
      nameValueCollection.Add("233", str95);
      string str96 = JS.GetStr(loan, "234");
      nameValueCollection.Add("234", str96);
      string str97 = JS.GetStr(loan, "912");
      nameValueCollection.Add("912", str97);
      string str98 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "Purchase", false) == 0, JS.GetStr(loan, "136"), JS.GetStr(loan, "1092"));
      nameValueCollection.Add("136_a", str98);
      string str99 = JS.GetStr(loan, "137");
      nameValueCollection.Add("137_a", str99);
      string str100 = JS.GetStr(loan, "138");
      nameValueCollection.Add("138_a", str100);
      string str101 = JS.GetStr(loan, "1093");
      nameValueCollection.Add("1093_a", str101);
      string str102 = JS.GetStr(loan, "969");
      nameValueCollection.Add("969", str102);
      string str103 = JS.GetStr(loan, "1073");
      nameValueCollection.Add("1073", str103);
      string str104 = JS.GetStr(loan, "1109");
      nameValueCollection.Add("1109_2", str104);
      string str105 = JS.GetStr(loan, "TNBPCC");
      nameValueCollection.Add("TNBPCC", str105);
      string str106 = JS.GetStr(loan, "1045");
      nameValueCollection.Add("1045", str106);
      string str107 = JS.GetStr(loan, "141");
      nameValueCollection.Add("141", str107);
      string str108 = JS.GetStr(loan, "1095");
      nameValueCollection.Add("1095", str108);
      string str109 = JS.GetStr(loan, "1115");
      nameValueCollection.Add("1115", str109);
      string str110 = JS.GetStr(loan, "1647");
      nameValueCollection.Add("1647", str110);
      string str111 = JS.GetStr(loan, "1845");
      nameValueCollection.Add("1845", str111);
      string str112 = JS.GetStr(loan, "140");
      nameValueCollection.Add("140", str112);
      string str113 = JS.GetStr(loan, "1851");
      nameValueCollection.Add("1851", str113);
      string str114 = JS.GetStr(loan, "1844");
      nameValueCollection.Add("1844", str114);
      string str115 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "202"), "RelocationFunds", false) == 0, "Relocation Funds", Jed.BF(Operators.CompareString(JS.GetStr(loan, "202"), "EmployerAssistedHousing", false) == 0, "Employer Assisted Housing", Jed.BF(Operators.CompareString(JS.GetStr(loan, "202"), "LeasePurchaseFund", false) == 0, "Lease Purchase Fund", Jed.BF(Operators.CompareString(JS.GetStr(loan, "202"), "CashDepositOnSalesContract", false) == 0, "Cash Deposit On Sales Contract", Jed.BF(Operators.CompareString(JS.GetStr(loan, "202"), "SellerCredit", false) == 0, "Seller Credit", Jed.BF(Operators.CompareString(JS.GetStr(loan, "202"), "LenderCredit", false) == 0, "Lender Credit", Jed.BF(Operators.CompareString(JS.GetStr(loan, "202"), "BorrowerPaidFees", false) == 0, "Borrower Paid Fees", Jed.BF(Operators.CompareString(JS.GetStr(loan, "202"), "Other", false) == 0, "Other", JS.GetStr(loan, "202")))))))));
      nameValueCollection.Add("202", str115);
      string str116 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1091"), "RelocationFunds", false) == 0, "Relocation Funds", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1091"), "EmployerAssistedHousing", false) == 0, "Employer Assisted Housing", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1091"), "LeasePurchaseFund", false) == 0, "Lease Purchase Fund", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1091"), "CashDepositOnSalesContract", false) == 0, "Cash Deposit On Sales Contract", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1091"), "SellerCredit", false) == 0, "Seller Credit", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1091"), "LenderCredit", false) == 0, "Lender Credit", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1091"), "BorrowerPaidFees", false) == 0, "Borrower Paid Fees", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1091"), "Other", false) == 0, "Other", JS.GetStr(loan, "1091")))))))));
      nameValueCollection.Add("1091", str116);
      string str117 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1106"), "RelocationFunds", false) == 0, "Relocation Funds", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1106"), "EmployerAssistedHousing", false) == 0, "Employer Assisted Housing", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1106"), "LeasePurchaseFund", false) == 0, "Lease Purchase Fund", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1106"), "CashDepositOnSalesContract", false) == 0, "Cash Deposit On Sales Contract", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1106"), "SellerCredit", false) == 0, "Seller Credit", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1106"), "LenderCredit", false) == 0, "Lender Credit", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1106"), "BorrowerPaidFees", false) == 0, "Borrower Paid Fees", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1106"), "Other", false) == 0, "Other", JS.GetStr(loan, "1106")))))))));
      nameValueCollection.Add("1106", str117);
      string str118 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1646"), "RelocationFunds", false) == 0, "Relocation Funds", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1646"), "EmployerAssistedHousing", false) == 0, "Employer Assisted Housing", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1646"), "LeasePurchaseFund", false) == 0, "Lease Purchase Fund", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1646"), "CashDepositOnSalesContract", false) == 0, "Cash Deposit On Sales Contract", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1646"), "SellerCredit", false) == 0, "Seller Credit", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1646"), "LenderCredit", false) == 0, "Lender Credit", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1646"), "BorrowerPaidFees", false) == 0, "Borrower Paid Fees", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1646"), "Other", false) == 0, "Other", JS.GetStr(loan, "1646")))))))));
      nameValueCollection.Add("1646", str118);
      string str119 = JS.GetStr(loan, "TNBPCC");
      nameValueCollection.Add("TNBPCC_a", str119);
      string str120 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "420"), "SecondLien", false) == 0, "1st Lien", "2nd Lien");
      nameValueCollection.Add("CC_FROM", str120);
      string str121 = JS.GetStr(loan, "142");
      nameValueCollection.Add("142", str121);
      string str122 = Jed.BF(Jed.S2N(JS.GetStr(loan, "142")) >= 0.0, "Cash from borrower", "Cash to borrower");
      nameValueCollection.Add("CASH_FROM_TO_BORROWER", str122);
      string str123 = JS.GetStr(loan, "BORPCC");
      nameValueCollection.Add("BORPCC", str123);
      string str124 = JS.GetStr(loan, "TOTPCC");
      nameValueCollection.Add("TOTPCC", str124);
      string str125 = JS.GetStr(loan, "138");
      nameValueCollection.Add("TOTAL_PREPAID", str125);
      string str126 = JS.GetStr(loan, "137");
      nameValueCollection.Add("TOTAL_CC", str126);
      string str127 = JS.GetStr(loan, "454");
      nameValueCollection.Add("454", str127);
      string str128 = JS.GetStr(loan, "L228");
      nameValueCollection.Add("L228", str128);
      string str129 = JS.GetStr(loan, "1621");
      nameValueCollection.Add("1621", str129);
      string str130 = "@367";
      nameValueCollection.Add("367", str130);
      string str131 = JS.GetStr(loan, "439");
      nameValueCollection.Add("439", str131);
      string str132 = JS.GetStr(loan, "NEWHUD.X255");
      nameValueCollection.Add("NEWHUD_X225", str132);
      string str133 = JS.GetStr(loan, "NEWHUD.X688");
      nameValueCollection.Add("NEWHUD_X688", str133);
      string str134 = JS.GetStr(loan, "641");
      nameValueCollection.Add("641", str134);
      string str135 = JS.GetStr(loan, "640");
      nameValueCollection.Add("640", str135);
      string str136 = JS.GetStr(loan, "336");
      nameValueCollection.Add("336", str136);
      string str137 = JS.GetStr(loan, "NEWHUD.X400");
      nameValueCollection.Add("NEWHUD_X400", str137);
      string str138 = JS.GetStr(loan, "NEWHUD.X136");
      nameValueCollection.Add("NEWHUD_X136", str138);
      string str139 = JS.GetStr(loan, "NEWHUD.X137");
      nameValueCollection.Add("NEWHUD_X137", str139);
      string str140 = JS.GetStr(loan, "NEWHUD.X138");
      nameValueCollection.Add("NEWHUD_X138", str140);
      string str141 = JS.GetStr(loan, "NEWHUD.X139");
      nameValueCollection.Add("NEWHUD_X139", str141);
      string str142 = JS.GetStr(loan, "NEWHUD.X140");
      nameValueCollection.Add("NEWHUD_X140", str142);
      string str143 = JS.GetStr(loan, "370");
      nameValueCollection.Add("370", str143);
      string str144 = JS.GetStr(loan, "372");
      nameValueCollection.Add("372", str144);
      string str145 = JS.GetStr(loan, "349");
      nameValueCollection.Add("349", str145);
      string str146 = JS.GetStr(loan, "932");
      nameValueCollection.Add("932", str146);
      string str147 = JS.GetStr(loan, "1009");
      nameValueCollection.Add("1009", str147);
      string str148 = JS.GetStr(loan, "554");
      nameValueCollection.Add("554", str148);
      string str149 = JS.GetStr(loan, "NEWHUD.X657");
      nameValueCollection.Add("NEWHUD_X657", str149);
      string str150 = JS.GetStr(loan, "NEWHUD.X952");
      nameValueCollection.Add("NEWHUD_X952", str150);
      string str151 = JS.GetStr(loan, "NEWHUD.X961");
      nameValueCollection.Add("NEWHUD_X961", str151);
      string str152 = JS.GetStr(loan, "NEWHUD.X970");
      nameValueCollection.Add("NEWHUD_X970", str152);
      string str153 = JS.GetStr(loan, "NEWHUD.X979");
      nameValueCollection.Add("NEWHUD_X979", str153);
      string str154 = JS.GetStr(loan, "NEWHUD.X988");
      nameValueCollection.Add("NEWHUD_X988", str154);
      string str155 = JS.GetStr(loan, "NEWHUD.X997");
      nameValueCollection.Add("NEWHUD_X997", str155);
      string str156 = JS.GetStr(loan, "NEWHUD.X645");
      nameValueCollection.Add("NEWHUD_X645", str156);
      string str157 = JS.GetStr(loan, "NEWHUD.X572");
      nameValueCollection.Add("NEWHUD_X572", str157);
      string str158 = JS.GetStr(loan, "NEWHUD.X639");
      nameValueCollection.Add("NEWHUD_X639", str158);
      string str159 = JS.GetStr(loan, "NEWHUD.X215");
      nameValueCollection.Add("NEWHUD_X215", str159);
      string str160 = JS.GetStr(loan, "NEWHUD.X216");
      nameValueCollection.Add("NEWHUD_X216", str160);
      string str161 = JS.GetStr(loan, "1763");
      nameValueCollection.Add("1763", str161);
      string str162 = JS.GetStr(loan, "1768");
      nameValueCollection.Add("1768", str162);
      string str163 = JS.GetStr(loan, "1773");
      nameValueCollection.Add("1773", str163);
      string str164 = JS.GetStr(loan, "1778");
      nameValueCollection.Add("1778", str164);
      string str165 = JS.GetStr(loan, "NEWHUD.X1604");
      nameValueCollection.Add("NEWHUD_X1604", str165);
      string str166 = JS.GetStr(loan, "NEWHUD.X1612");
      nameValueCollection.Add("NEWHUD_X1612", str166);
      string str167 = JS.GetStr(loan, "390");
      nameValueCollection.Add("390", str167);
      string str168 = JS.GetStr(loan, "NEWHUD.X731");
      nameValueCollection.Add("NEWHUD_X731", str168);
      string str169 = JS.GetStr(loan, "647");
      nameValueCollection.Add("647", str169);
      string str170 = JS.GetStr(loan, "648");
      nameValueCollection.Add("648", str170);
      string str171 = JS.GetStr(loan, "374");
      nameValueCollection.Add("374", str171);
      string str172 = JS.GetStr(loan, "1641");
      nameValueCollection.Add("1641", str172);
      string str173 = JS.GetStr(loan, "1644");
      nameValueCollection.Add("1644", str173);
      string str174 = JS.GetStr(loan, "NEWHUD.X1620");
      nameValueCollection.Add("NEWHUD_X1620", str174);
      string str175 = JS.GetStr(loan, "NEWHUD.X1627");
      nameValueCollection.Add("NEWHUD_X1627", str175);
      string str176 = JS.GetStr(loan, "NEWHUD.X254");
      nameValueCollection.Add("NEWHUD_X254", str176);
      string str177 = JS.GetStr(loan, "644");
      nameValueCollection.Add("644", str177);
      string str178 = JS.GetStr(loan, "645");
      nameValueCollection.Add("645", str178);
      string str179 = JS.GetStr(loan, "41");
      nameValueCollection.Add("41", str179);
      string str180 = JS.GetStr(loan, "44");
      nameValueCollection.Add("44", str180);
      string str181 = JS.GetStr(loan, "1783");
      nameValueCollection.Add("1783", str181);
      string str182 = JS.GetStr(loan, "1788");
      nameValueCollection.Add("1788", str182);
      string str183 = JS.GetStr(loan, "1793");
      nameValueCollection.Add("1793", str183);
      string str184 = JS.GetStr(loan, "NEWHUD.X255");
      nameValueCollection.Add("NEWHUD_X255", str184);
      string str185 = JS.GetStr(loan, "NEWHUD.X256");
      nameValueCollection.Add("NEWHUD_X256", str185);
      string str186 = JS.GetStr(loan, "NEWHUD.X1634");
      nameValueCollection.Add("NEWHUD_X1634", str186);
      string str187 = JS.GetStr(loan, "NEWHUD.X1642");
      nameValueCollection.Add("NEWHUD_X1642", str187);
      string str188 = JS.GetStr(loan, "NEWHUD.X1650");
      nameValueCollection.Add("NEWHUD_X1650", str188);
      string str189 = JS.GetStr(loan, "NEWHUD.X1658");
      nameValueCollection.Add("NEWHUD_X1658", str189);
      string str190 = JS.GetStr(loan, "202");
      nameValueCollection.Add("CC_SUMMARY_1", str190);
      string str191 = JS.GetStr(loan, "1091");
      nameValueCollection.Add("CC_SUMMARY_2", str191);
      string str192 = JS.GetStr(loan, "1106");
      nameValueCollection.Add("CC_SUMMARY_3", str192);
      string str193 = JS.GetStr(loan, "1646");
      nameValueCollection.Add("CC_SUMMARY_4", str193);
      string str194 = JS.GetStr(loan, "141");
      nameValueCollection.Add("CCS_1", str194);
      string str195 = JS.GetStr(loan, "1095");
      nameValueCollection.Add("CCS_2", str195);
      string str196 = JS.GetStr(loan, "1115");
      nameValueCollection.Add("CCS_3", str196);
      string str197 = JS.GetStr(loan, "1647");
      nameValueCollection.Add("CCS_4", str197);
      return nameValueCollection;
    }
  }
}
