// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._LOAN_COMPARISONCLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _LOAN_COMPARISONCLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str1);
      string str2 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69", str2);
      string str3 = JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("12_14_15", str3);
      string str4 = JS.GetStr(loan, "313") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "321"), "", false) != 0, ", ") + JS.GetStr(loan, "321") + " " + JS.GetStr(loan, "323");
      nameValueCollection.Add("313_321_323", str4);
      string str5 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, "Construction To Permanent", Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, "No Cash-Out Refinance", JS.GetStr(loan, "19")));
      nameValueCollection.Add("19", str5);
      string str6 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "Investor", false) == 0, "Investor", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "PrimaryResidence", false) == 0, "Primary Residence", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "SecondHome", false) == 0, "Second Home", "")));
      nameValueCollection.Add("1811", str6);
      string str7 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "420"), "FirstLien", false) == 0, "First", Jed.BF(Operators.CompareString(JS.GetStr(loan, "420"), "SecondLien", false) == 0, "Second", ""));
      nameValueCollection.Add("420", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "FarmersHomeAdministration", false) == 0, "USDA-RHS", JS.GetStr(loan, "1172"));
      nameValueCollection.Add("1172", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0101"), "FarmersHomeAdministration", false) == 0, "USDA-RHS", JS.GetStr(loan, "LP0101"));
      nameValueCollection.Add("LP0101", str9);
      string str10 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0201"), "FarmersHomeAdministration", false) == 0, "USDA-RHS", JS.GetStr(loan, "LP0201"));
      nameValueCollection.Add("LP0201", str10);
      string str11 = JS.GetStr(loan, "PREQUAL.X289");
      nameValueCollection.Add("PREQUAL_X289", str11);
      string str12 = JS.GetStr(loan, "PREQUAL.X288");
      nameValueCollection.Add("PREQUAL_X288", str12);
      string str13 = JS.GetStr(loan, "PREQUAL.X285");
      nameValueCollection.Add("PREQUAL_X285", str13);
      string str14 = JS.GetStr(loan, "PREQUAL.X284");
      nameValueCollection.Add("PREQUAL_X284", str14);
      string str15 = JS.GetStr(loan, "PREQUAL.X283");
      nameValueCollection.Add("PREQUAL_X283", str15);
      string str16 = JS.GetStr(loan, "PREQUAL.X282");
      nameValueCollection.Add("PREQUAL_X282", str16);
      string str17 = JS.GetStr(loan, "PREQUAL.X281");
      nameValueCollection.Add("PREQUAL_X281", str17);
      string str18 = JS.GetStr(loan, "PREQUAL.X280");
      nameValueCollection.Add("PREQUAL_X280", str18);
      string str19 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0249"), "", false) != 0, JS.GetStr(loan, "LP0249") + " % /", "");
      nameValueCollection.Add("LP0249", str19);
      string str20 = JS.GetStr(loan, "740") + " %";
      nameValueCollection.Add("740", str20);
      string str21 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0246"), "", false) != 0, JS.GetStr(loan, "LP0246") + " % /", "");
      nameValueCollection.Add("LP0246", str21);
      string str22 = JS.GetStr(loan, "LP0244");
      nameValueCollection.Add("LP0244", str22);
      string str23 = JS.GetStr(loan, "363");
      nameValueCollection.Add("363", str23);
      string str24 = JS.GetStr(loan, "LP0111");
      nameValueCollection.Add("LP0111", str24);
      string str25 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0110"), "", false) != 0, JS.GetStr(loan, "LP0110") + " /", "");
      nameValueCollection.Add("LP0110", str25);
      string str26 = JS.GetStr(loan, "PREQUAL.X279");
      nameValueCollection.Add("PREQUAL_X279", str26);
      string str27 = JS.GetStr(loan, "PREQUAL.X278");
      nameValueCollection.Add("PREQUAL_X278", str27);
      string str28 = JS.GetStr(loan, "PREQUAL.X277");
      nameValueCollection.Add("PREQUAL_X277", str28);
      string str29 = JS.GetStr(loan, "PREQUAL.X276");
      nameValueCollection.Add("PREQUAL_X276", str29);
      string str30 = JS.GetStr(loan, "PREQUAL.X275");
      nameValueCollection.Add("PREQUAL_X275", str30);
      string str31 = JS.GetStr(loan, "PREQUAL.X272");
      nameValueCollection.Add("PREQUAL_X272", str31);
      string str32 = JS.GetStr(loan, "PREQUAL.X271");
      nameValueCollection.Add("PREQUAL_X271", str32);
      string str33 = JS.GetStr(loan, "PREQUAL.X270");
      nameValueCollection.Add("PREQUAL_X270", str33);
      string str34 = JS.GetStr(loan, "PREQUAL.X57");
      nameValueCollection.Add("PREQUAL_X57", str34);
      string str35 = JS.GetStr(loan, "PREQUAL.X56");
      nameValueCollection.Add("PREQUAL_X56", str35);
      string str36 = JS.GetStr(loan, "353") + " %";
      nameValueCollection.Add("353", str36);
      string str37 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0247"), "", false) != 0, JS.GetStr(loan, "LP0247") + " % /", "");
      nameValueCollection.Add("LP0247", str37);
      string str38 = JS.GetStr(loan, "1844");
      nameValueCollection.Add("1844", str38);
      string str39 = JS.GetStr(loan, "PREQUAL.X269");
      nameValueCollection.Add("PREQUAL_X269", str39);
      string str40 = JS.GetStr(loan, "PREQUAL.X268");
      nameValueCollection.Add("PREQUAL_X268", str40);
      string str41 = JS.GetStr(loan, "PREQUAL.X267");
      nameValueCollection.Add("PREQUAL_X267", str41);
      string str42 = JS.GetStr(loan, "PREQUAL.X266");
      nameValueCollection.Add("PREQUAL_X266", str42);
      string str43 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X265"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X265") + " %", "");
      nameValueCollection.Add("PREQUAL_X265", str43);
      string str44 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X264"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X264") + " %", "");
      nameValueCollection.Add("PREQUAL_X264", str44);
      string str45 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X263"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X263") + " %", "");
      nameValueCollection.Add("PREQUAL_X263", str45);
      string str46 = JS.GetStr(loan, "1045");
      nameValueCollection.Add("1045", str46);
      string str47 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X48"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X48") + " %", "");
      nameValueCollection.Add("PREQUAL_X48", str47);
      string str48 = JS.GetStr(loan, "PREQUAL.X44");
      nameValueCollection.Add("PREQUAL_X44", str48);
      string str49 = JS.GetStr(loan, "PREQUAL.X43");
      nameValueCollection.Add("PREQUAL_X43", str49);
      string str50 = JS.GetStr(loan, "976") + " %";
      nameValueCollection.Add("976", str50);
      string str51 = JS.GetStr(loan, "PREQUAL.X257");
      nameValueCollection.Add("PREQUAL_X257", str51);
      string str52 = JS.GetStr(loan, "PREQUAL.X256");
      nameValueCollection.Add("PREQUAL_X256", str52);
      string str53 = JS.GetStr(loan, "PREQUAL.X255");
      nameValueCollection.Add("PREQUAL_X255", str53);
      string str54 = JS.GetStr(loan, "PREQUAL.X254");
      nameValueCollection.Add("PREQUAL_X254", str54);
      string str55 = JS.GetStr(loan, "PREQUAL.X33");
      nameValueCollection.Add("PREQUAL_X33", str55);
      string str56 = JS.GetStr(loan, "LP0211");
      nameValueCollection.Add("LP0211", str56);
      string str57 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0210"), "", false) != 0, JS.GetStr(loan, "LP0210") + " /", "");
      nameValueCollection.Add("LP0210", str57);
      string str58 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X244"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X244") + " %", "");
      nameValueCollection.Add("PREQUAL_X244", str58);
      string str59 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X243"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X243") + " %", "");
      nameValueCollection.Add("PREQUAL_X243", str59);
      string str60 = JS.GetStr(loan, "PREQUAL.X242");
      nameValueCollection.Add("PREQUAL_X242", str60);
      string str61 = JS.GetStr(loan, "PREQUAL.X241");
      nameValueCollection.Add("PREQUAL_X241", str61);
      string str62 = JS.GetStr(loan, "PREQUAL.X240");
      nameValueCollection.Add("PREQUAL_X240", str62);
      string str63 = JS.GetStr(loan, "799") + " %";
      nameValueCollection.Add("799", str63);
      string str64 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0209"), "", false) != 0, JS.GetStr(loan, "LP0209") + " %", "");
      nameValueCollection.Add("LP0209", str64);
      string str65 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0208"), "", false) != 0, JS.GetStr(loan, "LP0208") + " % /", "");
      nameValueCollection.Add("LP0208", str65);
      string str66 = JS.GetStr(loan, "325");
      nameValueCollection.Add("325", str66);
      string str67 = JS.GetStr(loan, "1335");
      nameValueCollection.Add("1335", str67);
      string str68 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X238"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X238") + " %", "");
      nameValueCollection.Add("PREQUAL_X238", str68);
      string str69 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X237"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X237") + " %", "");
      nameValueCollection.Add("PREQUAL_X237", str69);
      string str70 = JS.GetStr(loan, "PREQUAL.X236");
      nameValueCollection.Add("PREQUAL_X236", str70);
      string str71 = JS.GetStr(loan, "PREQUAL.X235");
      nameValueCollection.Add("PREQUAL_X235", str71);
      string str72 = JS.GetStr(loan, "PREQUAL.X234");
      nameValueCollection.Add("PREQUAL_X234", str72);
      string str73 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X233"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X233") + " %", "");
      nameValueCollection.Add("PREQUAL_X233", str73);
      string str74 = JS.GetStr(loan, "1014") + " %";
      nameValueCollection.Add("1014", str74);
      string str75 = JS.GetStr(loan, "1401");
      nameValueCollection.Add("1401", str75);
      string str76 = JS.GetStr(loan, "317");
      nameValueCollection.Add("317", str76);
      string str77 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315", str77);
      string str78 = JS.GetStr(loan, "11");
      nameValueCollection.Add("11", str78);
      string str79 = JS.GetStr(loan, "1791") + " %";
      nameValueCollection.Add("1791", str79);
      string str80 = JS.GetStr(loan, "1790") + " %";
      nameValueCollection.Add("1790", str80);
      string str81 = JS.GetStr(loan, "462");
      nameValueCollection.Add("462", str81);
      string str82 = JS.GetStr(loan, "142");
      nameValueCollection.Add("142", str82);
      string str83 = JS.GetStr(loan, "140");
      nameValueCollection.Add("140", str83);
      string str84 = JS.GetStr(loan, "LP0197");
      nameValueCollection.Add("LP0197", str84);
      string str85 = JS.GetStr(loan, "1785");
      nameValueCollection.Add("1785", str85);
      string str86 = JS.GetStr(loan, "138");
      nameValueCollection.Add("138", str86);
      string str87 = JS.GetStr(loan, "137");
      nameValueCollection.Add("137", str87);
      string str88 = JS.GetStr(loan, "136");
      nameValueCollection.Add("136", str88);
      string str89 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X239"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X239") + " %", "");
      nameValueCollection.Add("PREQUAL_X239", str89);
      string str90 = JS.GetStr(loan, "PREQUAL.X210") + " %";
      nameValueCollection.Add("PREQUAL_X210", str90);
      string str91 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1771"), "", false) != 0, JS.GetStr(loan, "1771") + " %", "");
      nameValueCollection.Add("1771", str91);
      string str92 = JS.GetStr(loan, "PREQUAL.X209") + " %";
      nameValueCollection.Add("PREQUAL_X209", str92);
      string str93 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0150"), "", false) != 0, JS.GetStr(loan, "LP0150") + " % /", "");
      nameValueCollection.Add("LP0150", str93);
      string str94 = JS.GetStr(loan, "912");
      nameValueCollection.Add("912", str94);
      string str95 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0149"), "", false) != 0, JS.GetStr(loan, "LP0149") + " % /", "");
      nameValueCollection.Add("LP0149", str95);
      string str96 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0147"), "", false) != 0, JS.GetStr(loan, "LP0147") + " % /", "");
      nameValueCollection.Add("LP0147", str96);
      string str97 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0146"), "", false) != 0, JS.GetStr(loan, "LP0146") + " % /", "");
      nameValueCollection.Add("LP0146", str97);
      string str98 = JS.GetStr(loan, "742") + " %";
      nameValueCollection.Add("742", str98);
      string str99 = JS.GetStr(loan, "LP0297");
      nameValueCollection.Add("LP0297", str99);
      string str100 = JS.GetStr(loan, "1073");
      nameValueCollection.Add("1073", str100);
      string str101 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X262"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X262") + " %", "");
      nameValueCollection.Add("PREQUAL_X262", str101);
      string str102 = JS.GetStr(loan, "319");
      nameValueCollection.Add("319", str102);
      string str103 = JS.GetStr(loan, "356");
      nameValueCollection.Add("356", str103);
      string str104 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1107"), "", false) != 0, JS.GetStr(loan, "1107") + " % /", "");
      nameValueCollection.Add("1107", str104);
      string str105 = JS.GetStr(loan, "PREQUAL.X97");
      nameValueCollection.Add("PREQUAL_X97", str105);
      string str106 = JS.GetStr(loan, "PREQUAL.X96");
      nameValueCollection.Add("PREQUAL_X96", str106);
      string str107 = JS.GetStr(loan, "1733");
      nameValueCollection.Add("1733", str107);
      string str108 = JS.GetStr(loan, "LP0144");
      nameValueCollection.Add("LP0144", str108);
      string str109 = JS.GetStr(loan, "5");
      nameValueCollection.Add("5", str109);
      string str110 = JS.GetStr(loan, "4") + " /";
      nameValueCollection.Add("4", str110);
      string str111 = JS.GetStr(loan, "3") + " %";
      nameValueCollection.Add("3", str111);
      string str112 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str112);
      string str113 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X88"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X88") + " %", "");
      nameValueCollection.Add("PREQUAL_X88", str113);
      string str114 = JS.GetStr(loan, "PREQUAL.X84");
      nameValueCollection.Add("PREQUAL_X84", str114);
      string str115 = JS.GetStr(loan, "PREQUAL.X83");
      nameValueCollection.Add("PREQUAL_X83", str115);
      string str116 = JS.GetStr(loan, "PREQUAL.X8");
      nameValueCollection.Add("PREQUAL_X8", str116);
      string str117 = JS.GetStr(loan, "PREQUAL.X7");
      nameValueCollection.Add("PREQUAL_X7", str117);
      string str118 = JS.GetStr(loan, "PREQUAL.X299");
      nameValueCollection.Add("PREQUAL_X299", str118);
      string str119 = JS.GetStr(loan, "PREQUAL.X298");
      nameValueCollection.Add("PREQUAL_X298", str119);
      string str120 = JS.GetStr(loan, "PREQUAL.X297");
      nameValueCollection.Add("PREQUAL_X297", str120);
      string str121 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X296"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X296") + " % /", "");
      nameValueCollection.Add("PREQUAL_X296", str121);
      string str122 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X295"), "", false) != 0, JS.GetStr(loan, "PREQUAL.X295") + " % /", "");
      nameValueCollection.Add("PREQUAL_X295", str122);
      string str123 = JS.GetStr(loan, "PREQUAL.X293");
      nameValueCollection.Add("PREQUAL_X293", str123);
      string str124 = JS.GetStr(loan, "PREQUAL.X292");
      nameValueCollection.Add("PREQUAL_X292", str124);
      string str125 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0109"), "", false) != 0, JS.GetStr(loan, "LP0109") + " %", "");
      nameValueCollection.Add("LP0109", str125);
      string str126 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0108"), "", false) != 0, JS.GetStr(loan, "LP0108") + " % /", "");
      nameValueCollection.Add("LP0108", str126);
      string str127 = JS.GetStr(loan, "PREQUAL.X302");
      nameValueCollection.Add("PREQUAL_X302", str127);
      string str128 = JS.GetStr(loan, "PREQUAL.X301");
      nameValueCollection.Add("PREQUAL_X301", str128);
      string str129 = JS.GetStr(loan, "PREQUAL.X300");
      nameValueCollection.Add("PREQUAL_X300", str129);
      string str130 = JS.GetStr(loan, "PREQUAL.X73");
      nameValueCollection.Add("PREQUAL_X73", str130);
      string str131 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "LP0250"), "", false) != 0, JS.GetStr(loan, "LP0250") + " % /", "");
      nameValueCollection.Add("LP0250", str131);
      string str132 = JS.GetStr(loan, "1389");
      nameValueCollection.Add("1389", str132);
      string str133 = JS.GetStr(loan, "PREQUAL.X202");
      nameValueCollection.Add("PREQUAL_X202", str133);
      string str134 = JS.GetStr(loan, "PREQUAL.X260");
      nameValueCollection.Add("PREQUAL_X260", str134);
      string str135 = JS.GetStr(loan, "PREQUAL.X261");
      nameValueCollection.Add("PREQUAL_X261", str135);
      string str136 = Jed.BF(Jed.S2N(JS.GetStr(loan, "142")) >= 0.0, "From", "To");
      nameValueCollection.Add("FROMTO_1", str136);
      string str137 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X44"), "", false) == 0, "", Jed.BF(Jed.S2N(JS.GetStr(loan, "PREQUAL.X44")) >= 0.0, "From", "To"));
      nameValueCollection.Add("FROMTO_2", str137);
      string str138 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X84"), "", false) == 0, "", Jed.BF(Jed.S2N(JS.GetStr(loan, "PREQUAL.X84")) >= 0.0, "From", "To"));
      nameValueCollection.Add("FROMTO_3", str138);
      string str139 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X274"), "Red", false) == 0, "No", Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X274"), "Green", false) == 0, "Yes", ""));
      nameValueCollection.Add("QUALIFIED_1", str139);
      string str140 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X303"), "Red", false) == 0, "No", Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X303"), "Green", false) == 0, "Yes", ""));
      nameValueCollection.Add("QUALIFIED_2", str140);
      string str141 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X304"), "Red", false) == 0, "No", Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X304"), "Green", false) == 0, "Yes", ""));
      nameValueCollection.Add("QUALIFIED_3", str141);
      return nameValueCollection;
    }
  }
}
