// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._OHIO_1003_P3CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _OHIO_1003_P3CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315", str1);
      string str2 = JS.GetStr(loan, "FM0104") + "\r\n" + JS.GetStr(loan, "FM0106") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0107"), "", false) != 0, ", ") + JS.GetStr(loan, "FM0107") + " " + JS.GetStr(loan, "FM0108");
      nameValueCollection.Add("274", str2);
      string str3 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "Sold", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "PendingSale", false) == 0, "PS") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "RetainForRental", false) == 0, "R") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0124"), "RetainForPrimaryOrSecondaryResidence", false) == 0, "H");
      nameValueCollection.Add("275", str3);
      string str4 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "SingleFamily", false) == 0, "SFR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Condominium", false) == 0, "CONDO") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Townhouse", false) == 0, "TOWN") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Cooperative", false) == 0, "COOP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "TwoToFourUnitProperty", false) == 0, "2-4") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "MultifamilyMoreThanFourUnits", false) == 0, "MULTI") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "ManufacturedMobileHome", false) == 0, "MOBIL") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "CommercialNonResidential", false) == 0, "COMNR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "MixedUseResidential", false) == 0, "MIXED") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Farm", false) == 0, "FARM") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "HomeAndBusinessCombined", false) == 0, "COMR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0118"), "Land", false) == 0, "LAND");
      nameValueCollection.Add("276", str4);
      string str5 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0119"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0119"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0119")), (byte) 18, 0));
      nameValueCollection.Add("277", str5);
      string str6 = JS.GetStr(loan, "FM0117");
      nameValueCollection.Add("278", str6);
      string str7 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0120"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0120"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0120")), (byte) 18, 0));
      nameValueCollection.Add("279", str7);
      string str8 = JS.GetStr(loan, "FM0116");
      nameValueCollection.Add("280", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0121"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0121"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0121")), (byte) 18, 0));
      nameValueCollection.Add("281", str9);
      string str10 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0141"), "SecondHome", false) == 0, "", Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0132"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0132"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0132")), (byte) 18, 0)));
      nameValueCollection.Add("916", str10);
      string str11 = JS.GetStr(loan, "FM0204") + "\r\n" + JS.GetStr(loan, "FM0206") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0207"), "", false) != 0, ", ") + JS.GetStr(loan, "FM0207") + " " + JS.GetStr(loan, "FM0208");
      nameValueCollection.Add("282", str11);
      string str12 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "Sold", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "PendingSale", false) == 0, "PS") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "RetainForRental", false) == 0, "R") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0224"), "RetainForPrimaryOrSecondaryResidence", false) == 0, "H");
      nameValueCollection.Add("283", str12);
      string str13 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "SingleFamily", false) == 0, "SFR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Condominium", false) == 0, "CONDO") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Townhouse", false) == 0, "TOWN") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Cooperative", false) == 0, "COOP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "TwoToFourUnitProperty", false) == 0, "2-4") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "MultifamilyMoreThanFourUnits", false) == 0, "MULTI") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "ManufacturedMobileHome", false) == 0, "MOBIL") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "CommercialNonResidential", false) == 0, "COMNR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "MixedUseResidential", false) == 0, "MIXED") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Farm", false) == 0, "FARM") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "HomeAndBusinessCombined", false) == 0, "COMR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0218"), "Land", false) == 0, "LAND");
      nameValueCollection.Add("284", str13);
      string str14 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0219"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0219"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0219")), (byte) 18, 0));
      nameValueCollection.Add("285", str14);
      string str15 = JS.GetStr(loan, "FM0217");
      nameValueCollection.Add("286", str15);
      string str16 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0220"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0220"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0220")), (byte) 18, 0));
      nameValueCollection.Add("287", str16);
      string str17 = JS.GetStr(loan, "FM0216");
      nameValueCollection.Add("288", str17);
      string str18 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0221"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0221"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0221")), (byte) 18, 0));
      nameValueCollection.Add("289", str18);
      string str19 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0241"), "SecondHome", false) == 0, "", Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0232"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0232"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0232")), (byte) 18, 0)));
      nameValueCollection.Add("917", str19);
      string str20 = JS.GetStr(loan, "FM0304") + "\r\n" + JS.GetStr(loan, "FM0306") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0307"), "", false) != 0, ", ") + JS.GetStr(loan, "FM0307") + " " + JS.GetStr(loan, "FM0308");
      nameValueCollection.Add("290", str20);
      string str21 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "Sold", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "PendingSale", false) == 0, "PS") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "RetainForRental", false) == 0, "R") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0324"), "RetainForPrimaryOrSecondaryResidence", false) == 0, "H");
      nameValueCollection.Add("291", str21);
      string str22 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "SingleFamily", false) == 0, "SFR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Condominium", false) == 0, "CONDO") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Townhouse", false) == 0, "TOWN") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Cooperative", false) == 0, "COOP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "TwoToFourUnitProperty", false) == 0, "2-4") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "MultifamilyMoreThanFourUnits", false) == 0, "MULTI") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "ManufacturedMobileHome", false) == 0, "MOBIL") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "CommercialNonResidential", false) == 0, "COMNR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "MixedUseResidential", false) == 0, "MIXED") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Farm", false) == 0, "FARM") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "HomeAndBusinessCombined", false) == 0, "COMR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0318"), "Land", false) == 0, "LAND");
      nameValueCollection.Add("292", str22);
      string str23 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0319"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0319"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0319")), (byte) 18, 0));
      nameValueCollection.Add("293", str23);
      string str24 = JS.GetStr(loan, "FM0317");
      nameValueCollection.Add("294", str24);
      string str25 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0320"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0320"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0320")), (byte) 18, 0));
      nameValueCollection.Add("295", str25);
      string str26 = JS.GetStr(loan, "FM0316");
      nameValueCollection.Add("296", str26);
      string str27 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0321"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0321"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0321")), (byte) 18, 0));
      nameValueCollection.Add("297", str27);
      string str28 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0341"), "SecondHome", false) == 0, "", Jed.BF(Operators.CompareString(JS.GetStr(loan, "FM0332"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "FM0332"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "FM0332")), (byte) 18, 0)));
      nameValueCollection.Add("918", str28);
      string str29 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "919"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "919"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "919")), (byte) 18, 0));
      nameValueCollection.Add("919", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "920"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "920"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "920")), (byte) 18, 0));
      nameValueCollection.Add("920", str30);
      string str31 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "921"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "921"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "921")), (byte) 18, 0));
      nameValueCollection.Add("921", str31);
      string str32 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "922"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "922"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "922")), (byte) 18, 0));
      nameValueCollection.Add("922", str32);
      string str33 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "923"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "923"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "923")), (byte) 18, 0));
      nameValueCollection.Add("923", str33);
      string str34 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "924"), "", false) != 0 & Operators.CompareString(JS.GetStr(loan, "924"), "0.00", false) != 0, Jed.NF(Jed.S2N(JS.GetStr(loan, "924")), (byte) 18, 0));
      nameValueCollection.Add("924", str34);
      string str35 = JS.GetStr(loan, "206");
      nameValueCollection.Add("206", str35);
      string str36 = JS.GetStr(loan, "203");
      nameValueCollection.Add("203", str36);
      string str37 = JS.GetStr(loan, "1734");
      nameValueCollection.Add("1734", str37);
      string str38 = JS.GetStr(loan, "1736");
      nameValueCollection.Add("1736", str38);
      string str39 = JS.GetStr(loan, "1735");
      nameValueCollection.Add("1735", str39);
      string str40 = JS.GetStr(loan, "1737");
      nameValueCollection.Add("1737", str40);
      string str41 = JS.GetStr(loan, "136");
      nameValueCollection.Add("136", str41);
      string str42 = JS.GetStr(loan, "967");
      nameValueCollection.Add("967", str42);
      string str43 = JS.GetStr(loan, "968");
      nameValueCollection.Add("968", str43);
      string str44 = JS.GetStr(loan, "1092");
      nameValueCollection.Add("1092", str44);
      string str45 = JS.GetStr(loan, "138");
      nameValueCollection.Add("138", str45);
      string str46 = JS.GetStr(loan, "137");
      nameValueCollection.Add("137", str46);
      string str47 = JS.GetStr(loan, "969");
      nameValueCollection.Add("969", str47);
      string str48 = JS.GetStr(loan, "1093");
      nameValueCollection.Add("1093", str48);
      string str49 = JS.GetStr(loan, "1073");
      nameValueCollection.Add("1073", str49);
      string str50 = JS.GetStr(loan, "140");
      nameValueCollection.Add("140", str50);
      string str51 = JS.GetStr(loan, "143");
      nameValueCollection.Add("143", str51);
      string str52 = JS.GetStr(loan, "1109");
      nameValueCollection.Add("1109", str52);
      string str53 = JS.GetStr(loan, "1045");
      nameValueCollection.Add("1045", str53);
      string str54 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str54);
      string str55 = JS.GetStr(loan, "142");
      nameValueCollection.Add("142", str55);
      string str56 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "169"), "Y", false) == 0, "X");
      nameValueCollection.Add("169_Yes", str56);
      string str57 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "169"), "N", false) == 0, "X");
      nameValueCollection.Add("169_No", str57);
      string str58 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "175"), "Y", false) == 0, "X");
      nameValueCollection.Add("175_Yes", str58);
      string str59 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "175"), "N", false) == 0, "X");
      nameValueCollection.Add("175_No", str59);
      string str60 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "265"), "Y", false) == 0, "X");
      nameValueCollection.Add("265_Yes", str60);
      string str61 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "265"), "N", false) == 0, "X");
      nameValueCollection.Add("265_No", str61);
      string str62 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "266"), "Y", false) == 0, "X");
      nameValueCollection.Add("266_Yes", str62);
      string str63 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "266"), "N", false) == 0, "X");
      nameValueCollection.Add("266_No", str63);
      string str64 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "170"), "Y", false) == 0, "X");
      nameValueCollection.Add("170_Yes", str64);
      string str65 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "170"), "N", false) == 0, "X");
      nameValueCollection.Add("170_No", str65);
      string str66 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "176"), "Y", false) == 0, "X");
      nameValueCollection.Add("176_Yes", str66);
      string str67 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "176"), "N", false) == 0, "X");
      nameValueCollection.Add("176_No", str67);
      string str68 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "172"), "Y", false) == 0, "X");
      nameValueCollection.Add("172_Yes", str68);
      string str69 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "172"), "N", false) == 0, "X");
      nameValueCollection.Add("172_No", str69);
      string str70 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "178"), "Y", false) == 0, "X");
      nameValueCollection.Add("178_Yes", str70);
      string str71 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "178"), "N", false) == 0, "X");
      nameValueCollection.Add("178_No", str71);
      string str72 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1057"), "Y", false) == 0, "X");
      nameValueCollection.Add("1057_Yes", str72);
      string str73 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1057"), "N", false) == 0, "X");
      nameValueCollection.Add("1057_No", str73);
      string str74 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1197"), "Y", false) == 0, "X");
      nameValueCollection.Add("1197_Yes", str74);
      string str75 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1197"), "N", false) == 0, "X");
      nameValueCollection.Add("1197_No", str75);
      string str76 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "463"), "Y", false) == 0, "X");
      nameValueCollection.Add("463_Yes", str76);
      string str77 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "463"), "N", false) == 0, "X");
      nameValueCollection.Add("463_No", str77);
      string str78 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "464"), "Y", false) == 0, "X");
      nameValueCollection.Add("464_Yes", str78);
      string str79 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "464"), "N", false) == 0, "X");
      nameValueCollection.Add("464_No", str79);
      string str80 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "173"), "Y", false) == 0, "X");
      nameValueCollection.Add("173_Yes", str80);
      string str81 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "173"), "N", false) == 0, "X");
      nameValueCollection.Add("173_No", str81);
      string str82 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "179"), "Y", false) == 0, "X");
      nameValueCollection.Add("179_Yes", str82);
      string str83 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "179"), "N", false) == 0, "X");
      nameValueCollection.Add("179_No", str83);
      string str84 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "174"), "Y", false) == 0, "X");
      nameValueCollection.Add("174_Yes", str84);
      string str85 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "174"), "N", false) == 0, "X");
      nameValueCollection.Add("174_No", str85);
      string str86 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "180"), "Y", false) == 0, "X");
      nameValueCollection.Add("180_Yes", str86);
      string str87 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "180"), "N", false) == 0, "X");
      nameValueCollection.Add("180_No", str87);
      string str88 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "171"), "Y", false) == 0, "X");
      nameValueCollection.Add("171_Yes", str88);
      string str89 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "171"), "N", false) == 0, "X");
      nameValueCollection.Add("171_No", str89);
      string str90 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "177"), "Y", false) == 0, "X");
      nameValueCollection.Add("177_Yes", str90);
      string str91 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "177"), "N", false) == 0, "X");
      nameValueCollection.Add("177_No", str91);
      string str92 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "965"), "Y", false) == 0, "X");
      nameValueCollection.Add("965_Yes", str92);
      string str93 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "965"), "N", false) == 0, "X");
      nameValueCollection.Add("965_No", str93);
      string str94 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "985"), "Y", false) == 0, "X");
      nameValueCollection.Add("985_Yes", str94);
      string str95 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "985"), "N", false) == 0, "X");
      nameValueCollection.Add("985_No", str95);
      string str96 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "466"), "Y", false) == 0, "X");
      nameValueCollection.Add("466_Yes", str96);
      string str97 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "466"), "N", false) == 0, "X");
      nameValueCollection.Add("466_No", str97);
      string str98 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "467"), "Y", false) == 0, "X");
      nameValueCollection.Add("467_Yes", str98);
      string str99 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "467"), "N", false) == 0, "X");
      nameValueCollection.Add("467_No", str99);
      string str100 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "418"), "Yes", false) == 0, "X");
      nameValueCollection.Add("418_Yes", str100);
      string str101 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "418"), "No", false) == 0, "X");
      nameValueCollection.Add("418_No", str101);
      string str102 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1343"), "Yes", false) == 0, "X");
      nameValueCollection.Add("1343_Yes", str102);
      string str103 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1343"), "No", false) == 0, "X");
      nameValueCollection.Add("1343_No", str103);
      string str104 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "403"), "Yes", false) == 0, "X");
      nameValueCollection.Add("403_Yes", str104);
      string str105 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "403"), "No", false) == 0, "X");
      nameValueCollection.Add("403_No", str105);
      string str106 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1108"), "Yes", false) == 0, "X");
      nameValueCollection.Add("1108_Yes", str106);
      string str107 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1108"), "No", false) == 0, "X");
      nameValueCollection.Add("1108_No", str107);
      string str108 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "981"), "PrimaryResidence", false) == 0, "PR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "981"), "Investment", false) == 0, "IP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "981"), "SecondaryResidence", false) == 0, "SH");
      nameValueCollection.Add("981", str108);
      string str109 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1015"), "PrimaryResidence", false) == 0, "PR") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1015"), "Investment", false) == 0, "IP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1015"), "SecondaryResidence", false) == 0, "SH");
      nameValueCollection.Add("1015", str109);
      string str110 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1069"), "Sole", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1069"), "JointWithSpouse", false) == 0, "SP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1069"), "JointWithOtherThanSpouse", false) == 0, "O");
      nameValueCollection.Add("1069", str110);
      string str111 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1070"), "Sole", false) == 0, "S") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1070"), "JointWithSpouse", false) == 0, "SP") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "1070"), "JointWithOtherThanSpouse", false) == 0, "O");
      nameValueCollection.Add("1070", str111);
      string str112 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "188"), "Y", false) == 0, "X");
      nameValueCollection.Add("188", str112);
      string str113 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1523"), "Hispanic or Latino", false) == 0, "X");
      nameValueCollection.Add("1523_a", str113);
      string str114 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1523"), "Not Hispanic or Latino", false) == 0, "X");
      nameValueCollection.Add("1523_b", str114);
      string str115 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1524"), "Y", false) == 0, "X");
      nameValueCollection.Add("1524", str115);
      string str116 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1525"), "Y", false) == 0, "X");
      nameValueCollection.Add("1525", str116);
      string str117 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1526"), "Y", false) == 0, "X");
      nameValueCollection.Add("1526", str117);
      string str118 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1527"), "Y", false) == 0, "X");
      nameValueCollection.Add("1527", str118);
      string str119 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1528"), "Y", false) == 0, "X");
      nameValueCollection.Add("1528", str119);
      string str120 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "471"), "Female", false) == 0, "X");
      nameValueCollection.Add("471_Female", str120);
      string str121 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "471"), "Male", false) == 0, "X");
      nameValueCollection.Add("471_Male", str121);
      string str122 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "189"), "Y", false) == 0, "X");
      nameValueCollection.Add("189", str122);
      string str123 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1531"), "Hispanic or Latino", false) == 0, "X");
      nameValueCollection.Add("1531_a", str123);
      string str124 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1531"), "Not Hispanic or Latino", false) == 0, "X");
      nameValueCollection.Add("1531_b", str124);
      string str125 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1532"), "Y", false) == 0, "X");
      nameValueCollection.Add("1532", str125);
      string str126 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1533"), "Y", false) == 0, "X");
      nameValueCollection.Add("1533", str126);
      string str127 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1534"), "Y", false) == 0, "X");
      nameValueCollection.Add("1534", str127);
      string str128 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1535"), "Y", false) == 0, "X");
      nameValueCollection.Add("1535", str128);
      string str129 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1536"), "Y", false) == 0, "X");
      nameValueCollection.Add("1536", str129);
      string str130 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "478"), "Female", false) == 0, "X");
      nameValueCollection.Add("478_Female", str130);
      string str131 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "478"), "Male", false) == 0, "X");
      nameValueCollection.Add("478_Male", str131);
      string str132 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "479"), "FaceToFace", false) == 0, "X");
      nameValueCollection.Add("479_Face2Face", str132);
      string str133 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "479"), "Mail", false) == 0, "X");
      nameValueCollection.Add("479_Mail", str133);
      string str134 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "479"), "Telephone", false) == 0, "X");
      nameValueCollection.Add("479_Telephone", str134);
      string str135 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "479"), "Internet", false) == 0, "X");
      nameValueCollection.Add("479_Internet", str135);
      string str136 = JS.GetStr(loan, "1612");
      nameValueCollection.Add("1612", str136);
      string str137 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315_A", str137);
      string str138 = JS.GetStr(loan, "3237");
      nameValueCollection.Add("3237", str138);
      string str139 = JS.GetStr(loan, "3238");
      nameValueCollection.Add("3238", str139);
      string str140 = JS.GetStr(loan, "1823");
      nameValueCollection.Add("1823", str140);
      string str141 = JS.GetStr(loan, "319");
      nameValueCollection.Add("319", str141);
      string str142 = JS.GetStr(loan, "313") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "321"), "", false) != 0, ", ") + JS.GetStr(loan, "321") + " " + JS.GetStr(loan, "323");
      nameValueCollection.Add("313_321_323", str142);
      return nameValueCollection;
    }
  }
}
