// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._PREQUALIFICATIONCLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _PREQUALIFICATIONCLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "315");
      nameValueCollection.Add("315", str1);
      string str2 = JS.GetStr(loan, "319");
      nameValueCollection.Add("319", str2);
      string str3 = JS.GetStr(loan, "313") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "321"), "", false) != 0, ", ") + JS.GetStr(loan, "321") + " " + JS.GetStr(loan, "323");
      nameValueCollection.Add("313_321_323", str3);
      string str4 = JS.GetStr(loan, "363");
      nameValueCollection.Add("363", str4);
      string str5 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str5);
      string str6 = JS.GetStr(loan, "66") + " / " + JS.GetStr(loan, "FE0117");
      nameValueCollection.Add("66_FE0117", str6);
      string str7 = JS.GetStr(loan, "1240");
      nameValueCollection.Add("1240", str7);
      string str8 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69", str8);
      string str9 = JS.GetStr(loan, "98") + "/" + JS.GetStr(loan, "FE0217");
      nameValueCollection.Add("98_FE0217", str9);
      string str10 = JS.GetStr(loan, "1268");
      nameValueCollection.Add("1268", str10);
      string str11 = JS.GetStr(loan, "101");
      nameValueCollection.Add("101", str11);
      string str12 = JS.GetStr(loan, "102");
      nameValueCollection.Add("102", str12);
      string str13 = JS.GetStr(loan, "103");
      nameValueCollection.Add("103", str13);
      string str14 = JS.GetStr(loan, "104");
      nameValueCollection.Add("104", str14);
      string str15 = JS.GetStr(loan, "105");
      nameValueCollection.Add("105", str15);
      string str16 = JS.GetStr(loan, "106");
      nameValueCollection.Add("106", str16);
      string str17 = JS.GetStr(loan, "107");
      nameValueCollection.Add("107", str17);
      string str18 = JS.GetStr(loan, "108");
      nameValueCollection.Add("108", str18);
      string str19 = JS.GetStr(loan, "1818");
      nameValueCollection.Add("1818", str19);
      string str20 = JS.GetStr(loan, "1815");
      nameValueCollection.Add("1815", str20);
      string str21 = JS.GetStr(loan, "910");
      nameValueCollection.Add("910", str21);
      string str22 = JS.GetStr(loan, "110");
      nameValueCollection.Add("110", str22);
      string str23 = JS.GetStr(loan, "111");
      nameValueCollection.Add("111", str23);
      string str24 = JS.GetStr(loan, "112");
      nameValueCollection.Add("112", str24);
      string str25 = JS.GetStr(loan, "113");
      nameValueCollection.Add("113", str25);
      string str26 = JS.GetStr(loan, "114");
      nameValueCollection.Add("114", str26);
      string str27 = JS.GetStr(loan, "115");
      nameValueCollection.Add("115", str27);
      string str28 = JS.GetStr(loan, "116");
      nameValueCollection.Add("116", str28);
      string str29 = JS.GetStr(loan, "117");
      nameValueCollection.Add("117", str29);
      string str30 = JS.GetStr(loan, "1816");
      nameValueCollection.Add("1816", str30);
      string str31 = JS.GetStr(loan, "911");
      nameValueCollection.Add("911", str31);
      string str32 = JS.GetStr(loan, "1723");
      nameValueCollection.Add("1723", str32);
      string str33 = JS.GetStr(loan, "1724");
      nameValueCollection.Add("1724", str33);
      string str34 = JS.GetStr(loan, "1725");
      nameValueCollection.Add("1725", str34);
      string str35 = JS.GetStr(loan, "1726");
      nameValueCollection.Add("1726", str35);
      string str36 = JS.GetStr(loan, "1727");
      nameValueCollection.Add("1727", str36);
      string str37 = JS.GetStr(loan, "1728");
      nameValueCollection.Add("1728", str37);
      string str38 = JS.GetStr(loan, "1729");
      nameValueCollection.Add("1729", str38);
      string str39 = JS.GetStr(loan, "1730");
      nameValueCollection.Add("1730", str39);
      string str40 = JS.GetStr(loan, "1379");
      nameValueCollection.Add("1379", str40);
      string str41 = JS.GetStr(loan, "1731");
      nameValueCollection.Add("1731", str41);
      string str42 = JS.GetStr(loan, "979");
      nameValueCollection.Add("979", str42);
      string str43 = Jed.BF(Jed.S2N(JS.GetStr(loan, "1605")) + Jed.S2N(JS.GetStr(loan, "1607")) + Jed.S2N(JS.GetStr(loan, "1609")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "1605")) + Jed.S2N(JS.GetStr(loan, "1607")) + Jed.S2N(JS.GetStr(loan, "1609")), (byte) 18, 0), "");
      nameValueCollection.Add("1605_1607_1609", str43);
      string str44 = Jed.BF(Jed.S2N(JS.GetStr(loan, "183")) + Jed.S2N(JS.GetStr(loan, "1716")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "183")) + Jed.S2N(JS.GetStr(loan, "1716")), (byte) 18, 0), "");
      nameValueCollection.Add("183_1716", str44);
      string str45 = JS.GetStr(loan, "210");
      nameValueCollection.Add("210", str45);
      string str46 = JS.GetStr(loan, "915");
      nameValueCollection.Add("915", str46);
      string str47 = JS.GetStr(loan, "382");
      nameValueCollection.Add("382", str47);
      string str48 = JS.GetStr(loan, "LOANSUB.X1");
      nameValueCollection.Add("LOANSUB_X1", str48);
      string str49 = JS.GetStr(loan, "272");
      nameValueCollection.Add("272", str49);
      string str50 = Jed.BF(Jed.S2N(JS.GetStr(loan, "256")) + Jed.S2N(JS.GetStr(loan, "1062")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "256")) + Jed.S2N(JS.GetStr(loan, "1062")), (byte) 18, 0), "");
      nameValueCollection.Add("256_1062", str50);
      string str51 = JS.GetStr(loan, "462");
      nameValueCollection.Add("462", str51);
      string str52 = JS.GetStr(loan, "1742");
      nameValueCollection.Add("1742_A", str52);
      string str53 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "FarmersHomeAdministration", false) == 0, "USDA-RHS", JS.GetStr(loan, "1172"));
      nameValueCollection.Add("1172", str53);
      string str54 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "Investor", false) == 0, "Investor", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "PrimaryResidence", false) == 0, "Primary Residence", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1811"), "SecondHome", false) == 0, "Second Home", "")));
      nameValueCollection.Add("1811", str54);
      string str55 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "AdjustableRate", false) == 0, "Adjustable Rate", Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "OtherAmortizationType", false) == 0, "Other Amortization Type", Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "GraduatedPaymentMortgage", false) == 0, "Graduated Payment Mortgage", JS.GetStr(loan, "608"))));
      nameValueCollection.Add("608", str55);
      string str56 = JS.GetStr(loan, "1401");
      nameValueCollection.Add("1401", str56);
      string str57 = JS.GetStr(loan, "1785");
      nameValueCollection.Add("1785", str57);
      string str58 = JS.GetStr(loan, "136");
      nameValueCollection.Add("136", str58);
      string str59 = JS.GetStr(loan, "3");
      nameValueCollection.Add("3", str59);
      string str60 = JS.GetStr(loan, "1014");
      nameValueCollection.Add("1014", str60);
      string str61 = JS.GetStr(loan, "4");
      nameValueCollection.Add("4", str61);
      string str62 = JS.GetStr(loan, "325");
      nameValueCollection.Add("325", str62);
      string str63 = JS.GetStr(loan, "1107");
      nameValueCollection.Add("1107", str63);
      string str64 = JS.GetStr(loan, "1045");
      nameValueCollection.Add("1045", str64);
      string str65 = JS.GetStr(loan, "1771");
      nameValueCollection.Add("1771", str65);
      string str66 = JS.GetStr(loan, "1335");
      nameValueCollection.Add("1335", str66);
      string str67 = JS.GetStr(loan, "140");
      nameValueCollection.Add("140", str67);
      string str68 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2_A", str68);
      string str69 = JS.GetStr(loan, "799");
      nameValueCollection.Add("799", str69);
      string str70 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "420"), "FirstLien", false) == 0, "First", Jed.BF(Operators.CompareString(JS.GetStr(loan, "420"), "SecondLien", false) == 0, "Second", ""));
      nameValueCollection.Add("420", str70);
      string str71 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, "Construction To Permanent", Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, "No Cash-Out Refinance", JS.GetStr(loan, "19")));
      nameValueCollection.Add("19", str71);
      string str72 = JS.GetStr(loan, "PREQUAL.X272");
      nameValueCollection.Add("PREQUAL_X272", str72);
      string str73 = JS.GetStr(loan, "137");
      nameValueCollection.Add("137", str73);
      string str74 = JS.GetStr(loan, "138");
      nameValueCollection.Add("138", str74);
      string str75 = JS.GetStr(loan, "1073");
      nameValueCollection.Add("1073", str75);
      string str76 = JS.GetStr(loan, "1844");
      nameValueCollection.Add("1844", str76);
      string str77 = Jed.BF(Jed.S2N(JS.GetStr(loan, "142")) >= 0.0, "From Borrower", "To Borrower");
      nameValueCollection.Add("CASHFROMTO", str77);
      string str78 = JS.GetStr(loan, "142");
      nameValueCollection.Add("142", str78);
      string str79 = JS.GetStr(loan, "915");
      nameValueCollection.Add("915_B", str79);
      string str80 = JS.GetStr(loan, "PREQUAL.X275");
      nameValueCollection.Add("PREQUAL_X275", str80);
      string str81 = JS.GetStr(loan, "2");
      nameValueCollection.Add("2", str81);
      string str82 = JS.GetStr(loan, "740");
      nameValueCollection.Add("740", str82);
      string str83 = JS.GetStr(loan, "742");
      nameValueCollection.Add("742", str83);
      string str84 = JS.GetStr(loan, "353");
      nameValueCollection.Add("353", str84);
      string str85 = JS.GetStr(loan, "976");
      nameValueCollection.Add("976", str85);
      string str86 = JS.GetStr(loan, "1389");
      nameValueCollection.Add("1389", str86);
      string str87 = JS.GetStr(loan, "1742");
      nameValueCollection.Add("1742", str87);
      string str88 = JS.GetStr(loan, "915");
      nameValueCollection.Add("915_A", str88);
      string str89 = JS.GetStr(loan, "PREQUAL.X202");
      nameValueCollection.Add("PREQUAL_X202", str89);
      string str90 = JS.GetStr(loan, "1790");
      nameValueCollection.Add("1790", str90);
      string str91 = JS.GetStr(loan, "1791");
      nameValueCollection.Add("1791", str91);
      string str92 = JS.GetStr(loan, "PREQUAL.X209");
      nameValueCollection.Add("PREQUAL_X209", str92);
      string str93 = JS.GetStr(loan, "PREQUAL.X210");
      nameValueCollection.Add("PREQUAL_X210", str93);
      string str94 = JS.GetStr(loan, "PREQUAL.X7");
      nameValueCollection.Add("PREQUAL_X7", str94);
      string str95 = JS.GetStr(loan, "PREQUAL.X8");
      nameValueCollection.Add("PREQUAL_X8", str95);
      string str96 = JS.GetStr(loan, "142");
      nameValueCollection.Add("142_A", str96);
      string str97 = JS.GetStr(loan, "PREQUAL.X308");
      nameValueCollection.Add("PREQUAL_X308", str97);
      string str98 = JS.GetStr(loan, "PREQUAL.X309");
      nameValueCollection.Add("PREQUAL_X309", str98);
      string str99 = JS.GetStr(loan, "PREQUAL.X310");
      nameValueCollection.Add("PREQUAL_X310", str99);
      string str100 = JS.GetStr(loan, "PREQUAL.X311");
      nameValueCollection.Add("PREQUAL_X311", str100);
      string str101 = JS.GetStr(loan, "PREQUAL.X312");
      nameValueCollection.Add("PREQUAL_X312", str101);
      string str102 = JS.GetStr(loan, "PREQUAL.X313");
      nameValueCollection.Add("PREQUAL_X313", str102);
      string str103 = JS.GetStr(loan, "PREQUAL.X314");
      nameValueCollection.Add("PREQUAL_X314", str103);
      string str104 = JS.GetStr(loan, "PREQUAL.X315");
      nameValueCollection.Add("PREQUAL_X315", str104);
      string str105 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X274"), "Green", false) == 0, "Congratulations! You are qualified.", Jed.BF(Operators.CompareString(JS.GetStr(loan, "PREQUAL.X274"), "Red", false) == 0, "You are not qualified.", "Not enough information has been entered to qualify."));
      nameValueCollection.Add("QUALIFIED", str105);
      return nameValueCollection;
    }
  }
}
