// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._RD_410_4_PAGE_6CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _RD_410_4_PAGE_6CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X43"), "Section 502", false) == 0, "X");
      nameValueCollection.Add("USDA_X43_502", str1);
      string str2 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X43"), "Section 504 Loan", false) == 0, "X");
      nameValueCollection.Add("USDA_X43_504", str2);
      string str3 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X43"), "Grant", false) == 0, "X");
      nameValueCollection.Add("USDA_X43_GRANT", str3);
      string str4 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X44"), "Y", false) == 0, "X");
      nameValueCollection.Add("USDA_X44_Y", str4);
      string str5 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X44"), "N", false) == 0, "X");
      nameValueCollection.Add("USDA_X44_N", str5);
      string str6 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X46"), "Y", false) == 0, "X");
      nameValueCollection.Add("USDA_X46_Y", str6);
      string str7 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X46"), "N", false) == 0, "X");
      nameValueCollection.Add("USDA_X46_N", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X10"), "Y", false) == 0, "X");
      nameValueCollection.Add("USDA_X10_Y", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X10"), "N", false) == 0, "X");
      nameValueCollection.Add("USDA_X10_N", str9);
      string str10 = JS.GetStr(loan, "USDA.X45");
      nameValueCollection.Add("USDA_X45", str10);
      string str11 = JS.GetStr(loan, "USDA.X11");
      nameValueCollection.Add("USDA_X11", str11);
      string str12 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X13"), "Y", false) == 0, "X");
      nameValueCollection.Add("USDA_X13_Y", str12);
      string str13 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X13"), "N", false) == 0, "X");
      nameValueCollection.Add("USDA_X13_N", str13);
      string str14 = JS.GetStr(loan, "USDA.X47");
      nameValueCollection.Add("USDA_X47", str14);
      string str15 = JS.GetStr(loan, "USDA.X14");
      nameValueCollection.Add("USDA_X14", str15);
      string str16 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X1"), "Y", false) == 0, "X");
      nameValueCollection.Add("USDA_X1_Y", str16);
      string str17 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X1"), "N", false) == 0, "X");
      nameValueCollection.Add("USDA_X1_N", str17);
      string str18 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X4"), "Y", false) == 0, "X");
      nameValueCollection.Add("USDA_X4_Y", str18);
      string str19 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X4"), "N", false) == 0, "X");
      nameValueCollection.Add("USDA_X4_N", str19);
      string str20 = JS.GetStr(loan, "USDA.X48");
      nameValueCollection.Add("USDA_X48", str20);
      string str21 = JS.GetStr(loan, "USDA.X49");
      nameValueCollection.Add("USDA_X49", str21);
      string str22 = JS.GetStr(loan, "USDA.X50");
      nameValueCollection.Add("USDA_X50", str22);
      string str23 = JS.GetStr(loan, "USDA.X51");
      nameValueCollection.Add("USDA_X51", str23);
      string str24 = JS.GetStr(loan, "USDA.X52");
      nameValueCollection.Add("USDA_X52", str24);
      string str25 = JS.GetStr(loan, "USDA.X53");
      nameValueCollection.Add("USDA_X53", str25);
      string str26 = JS.GetStr(loan, "USDA.X54");
      nameValueCollection.Add("USDA_X54", str26);
      string str27 = JS.GetStr(loan, "USDA.X55");
      nameValueCollection.Add("USDA_X55", str27);
      string str28 = JS.GetStr(loan, "USDA.X56");
      nameValueCollection.Add("USDA_X56", str28);
      string str29 = JS.GetStr(loan, "USDA.X57");
      nameValueCollection.Add("USDA_X57", str29);
      string str30 = JS.GetStr(loan, "USDA.X58");
      nameValueCollection.Add("USDA_X58", str30);
      string str31 = JS.GetStr(loan, "USDA.X59");
      nameValueCollection.Add("USDA_X59", str31);
      string str32 = JS.GetStr(loan, "USDA.X60");
      nameValueCollection.Add("USDA_X60", str32);
      string str33 = JS.GetStr(loan, "USDA.X61");
      nameValueCollection.Add("USDA_X61", str33);
      string str34 = JS.GetStr(loan, "USDA.X62");
      nameValueCollection.Add("USDA_X62", str34);
      string str35 = JS.GetStr(loan, "USDA.X63");
      nameValueCollection.Add("USDA_X63", str35);
      string str36 = JS.GetStr(loan, "USDA.X64");
      nameValueCollection.Add("USDA_X64", str36);
      string str37 = JS.GetStr(loan, "USDA.X65");
      nameValueCollection.Add("USDA_X65", str37);
      string str38 = JS.GetStr(loan, "USDA.X66");
      nameValueCollection.Add("USDA_X66", str38);
      string str39 = JS.GetStr(loan, "USDA.X67");
      nameValueCollection.Add("USDA_X67", str39);
      string str40 = JS.GetStr(loan, "USDA.X68");
      nameValueCollection.Add("USDA_X68", str40);
      string str41 = JS.GetStr(loan, "USDA.X69");
      nameValueCollection.Add("USDA_X69", str41);
      string str42 = JS.GetStr(loan, "USDA.X70");
      nameValueCollection.Add("USDA_X70", str42);
      string str43 = JS.GetStr(loan, "USDA.X71");
      nameValueCollection.Add("USDA_X71", str43);
      string str44 = JS.GetStr(loan, "USDA.X72");
      nameValueCollection.Add("USDA_X72", str44);
      string str45 = JS.GetStr(loan, "USDA.X73");
      nameValueCollection.Add("USDA_X73", str45);
      string str46 = JS.GetStr(loan, "USDA.X74");
      nameValueCollection.Add("USDA_X74", str46);
      string str47 = JS.GetStr(loan, "USDA.X75");
      nameValueCollection.Add("USDA_X75", str47);
      string str48 = JS.GetStr(loan, "USDA.X76");
      nameValueCollection.Add("USDA_X76", str48);
      string str49 = JS.GetStr(loan, "USDA.X77");
      nameValueCollection.Add("USDA_X77", str49);
      string str50 = JS.GetStr(loan, "USDA.X78");
      nameValueCollection.Add("USDA_X78", str50);
      string str51 = JS.GetStr(loan, "USDA.X79");
      nameValueCollection.Add("USDA_X79", str51);
      string str52 = JS.GetStr(loan, "USDA.X80");
      nameValueCollection.Add("USDA_X80", str52);
      string str53 = JS.GetStr(loan, "USDA.X81");
      nameValueCollection.Add("USDA_X81", str53);
      string str54 = JS.GetStr(loan, "USDA.X82");
      nameValueCollection.Add("USDA_X82", str54);
      string str55 = JS.GetStr(loan, "USDA.X83");
      nameValueCollection.Add("USDA_X83", str55);
      string str56 = JS.GetStr(loan, "USDA.X84");
      nameValueCollection.Add("USDA_X84", str56);
      string str57 = JS.GetStr(loan, "USDA.X85");
      nameValueCollection.Add("USDA_X85", str57);
      string str58 = JS.GetStr(loan, "USDA.X86");
      nameValueCollection.Add("USDA_X86", str58);
      string str59 = JS.GetStr(loan, "USDA.X87");
      nameValueCollection.Add("USDA_X87", str59);
      string str60 = JS.GetStr(loan, "USDA.X88");
      nameValueCollection.Add("USDA_X88", str60);
      string str61 = JS.GetStr(loan, "USDA.X89");
      nameValueCollection.Add("USDA_X89", str61);
      string str62 = JS.GetStr(loan, "USDA.X90");
      nameValueCollection.Add("USDA_X90", str62);
      string str63 = JS.GetStr(loan, "USDA.X91");
      nameValueCollection.Add("USDA_X91", str63);
      string str64 = JS.GetStr(loan, "USDA.X92");
      nameValueCollection.Add("USDA_X92", str64);
      string str65 = JS.GetStr(loan, "USDA.X93");
      nameValueCollection.Add("USDA_X93", str65);
      string str66 = JS.GetStr(loan, "USDA.X94");
      nameValueCollection.Add("USDA_X94", str66);
      string str67 = JS.GetStr(loan, "USDA.X95");
      nameValueCollection.Add("USDA_X95", str67);
      string str68 = JS.GetStr(loan, "USDA.X96");
      nameValueCollection.Add("USDA_X96", str68);
      string str69 = JS.GetStr(loan, "USDA.X97");
      nameValueCollection.Add("USDA_X97", str69);
      string str70 = JS.GetStr(loan, "USDA.X98");
      nameValueCollection.Add("USDA_X98", str70);
      string str71 = JS.GetStr(loan, "USDA.X99");
      nameValueCollection.Add("USDA_X99", str71);
      string str72 = JS.GetStr(loan, "USDA.X100") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X100"), "", false) != 0, ", ") + JS.GetStr(loan, "USDA.X101") + " " + JS.GetStr(loan, "USDA.X102");
      nameValueCollection.Add("USDA_X100_X101_X102", str72);
      string str73 = JS.GetStr(loan, "USDA.X103");
      nameValueCollection.Add("USDA_X103", str73);
      string str74 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X104"), "Y", false) == 0, "X");
      nameValueCollection.Add("USDA_X104_Y", str74);
      string str75 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X104"), "Y", false) != 0, "X");
      nameValueCollection.Add("USDA_X104_N", str75);
      string str76 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X105"), "Y", false) == 0, "X");
      nameValueCollection.Add("USDA_X105_Y", str76);
      string str77 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X105"), "Y", false) != 0, "X");
      nameValueCollection.Add("USDA_X105_N", str77);
      string str78 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X106"), "Y", false) == 0, "X");
      nameValueCollection.Add("USDA_X106_Y", str78);
      string str79 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X106"), "Y", false) != 0, "X");
      nameValueCollection.Add("USDA_X106_N", str79);
      string str80 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X107"), "Y", false) == 0, "X");
      nameValueCollection.Add("USDA_X107_Y", str80);
      string str81 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X107"), "Y", false) != 0, "X");
      nameValueCollection.Add("USDA_X107_N", str81);
      string str82 = JS.GetStr(loan, "USDA.X108");
      nameValueCollection.Add("USDA_X108", str82);
      string str83 = JS.GetStr(loan, "USDA.X109");
      nameValueCollection.Add("USDA_X109", str83);
      string str84 = JS.GetStr(loan, "USDA.X110") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X110"), "", false) != 0, ", ") + JS.GetStr(loan, "USDA.X111") + " " + JS.GetStr(loan, "USDA.X112");
      nameValueCollection.Add("USDA_X110_X111_X112", str84);
      string str85 = JS.GetStr(loan, "USDA.X113");
      nameValueCollection.Add("USDA_X113", str85);
      string str86 = JS.GetStr(loan, "USDA.X114");
      nameValueCollection.Add("USDA_X114", str86);
      string str87 = JS.GetStr(loan, "USDA.X115");
      nameValueCollection.Add("USDA_X115", str87);
      string str88 = JS.GetStr(loan, "USDA.X116") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "USDA.X116"), "", false) != 0, ", ") + JS.GetStr(loan, "USDA.X117") + " " + JS.GetStr(loan, "USDA.X118");
      nameValueCollection.Add("USDA_X116_X117_X118", str88);
      string str89 = JS.GetStr(loan, "USDA.X119");
      nameValueCollection.Add("USDA_X119", str89);
      return nameValueCollection;
    }
  }
}
