// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._REGZ_TIL_SUMMARYCLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _REGZ_TIL_SUMMARYCLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2626"), "Banked - Wholesale", false) == 0 & Operators.CompareString(JS.GetStr(loan, "1264"), "", false) != 0, JS.GetStr(loan, "1264"), JS.GetStr(loan, "315"));
      nameValueCollection.Add("315", str1);
      string str2 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str2);
      string str3 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str3);
      string str4 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69", str4);
      string str5 = JS.GetStr(loan, "11");
      nameValueCollection.Add("11", str5);
      string str6 = JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("12_14", str6);
      string str7 = JS.GetStr(loan, "3122");
      nameValueCollection.Add("3122", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "662"), "Initial", false) == 0, "X");
      nameValueCollection.Add("662_Initial", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "662"), "Final", false) == 0, "X");
      nameValueCollection.Add("662_Final", str9);
      string str10 = JS.GetStr(loan, "799");
      nameValueCollection.Add("779", str10);
      string str11 = JS.GetStr(loan, "1206");
      nameValueCollection.Add("1206", str11);
      string str12 = JS.GetStr(loan, "948");
      nameValueCollection.Add("948", str12);
      string str13 = JS.GetStr(loan, "1207");
      nameValueCollection.Add("1207", str13);
      string str14 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, "Biweekly", "Monthly");
      nameValueCollection.Add("DUETYPE", str14);
      string str15 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "FHA", false) == 0, "IF YOU PREPAY YOUR LOAN OTHER THAN ON THE REGULAR INSTALLMENT DATE YOU MAY BE ASSESSED INTEREST CHARGES UNTIL THE END OF THE MONTH AND YOU MAY BE ENTITLED TO A REFUND OF PART OF THE FINANCE CHARGE.");
      nameValueCollection.Add("FHA_Message", str15);
      string str16 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "663"), "Y", false) == 0, "X");
      nameValueCollection.Add("663", str16);
      string str17 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "664"), "Y", false) == 0, "X");
      nameValueCollection.Add("664", str17);
      string str18 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "665"), "Y", false) == 0, "X");
      nameValueCollection.Add("665", str18);
      string str19 = JS.GetStr(loan, "666");
      nameValueCollection.Add("666", str19);
      string str20 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "671"), "TheGoodsOrPropertyBeingPurchased", false) == 0, "X");
      nameValueCollection.Add("671_Thegoods", str20);
      string str21 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "671"), "RealPropertyYouAlreadyOwn", false) == 0, "X");
      nameValueCollection.Add("671_Realproperty", str21);
      string str22 = JS.GetStr(loan, "1603");
      nameValueCollection.Add("1603", str22);
      string str23 = JS.GetStr(loan, "1707");
      nameValueCollection.Add("390", str23);
      string str24 = JS.GetStr(loan, "672");
      nameValueCollection.Add("672", str24);
      string str25 = JS.GetStr(loan, "674");
      nameValueCollection.Add("674", str25);
      string str26 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1719"), "", false) != 0, JS.GetStr(loan, "1719") + ".");
      nameValueCollection.Add("1719", str26);
      string str27 = JS.GetStr(loan, "1854");
      nameValueCollection.Add("1854", str27);
      string str28 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "670"), "Y", false) == 0, "X");
      nameValueCollection.Add("670_May", str28);
      string str29 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "670"), "N", false) == 0, "X");
      nameValueCollection.Add("670_Willnot", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "675"), "Y", false) == 0, "X");
      nameValueCollection.Add("675_May", str30);
      string str31 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "675"), "N", false) == 0, "X");
      nameValueCollection.Add("675_Willnot", str31);
      string str32 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1242"), "Y", false) == 0, "X");
      nameValueCollection.Add("1242", str32);
      string str33 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "676"), "Y", false) == 0, "X");
      nameValueCollection.Add("676", str33);
      string str34 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1698"), "Y", false) == 0, "X");
      nameValueCollection.Add("1698", str34);
      string str35 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1697"), "Y", false) == 0, "X");
      nameValueCollection.Add("1697", str35);
      string str36 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "723"), "Y", false) == 0, "X");
      nameValueCollection.Add("723", str36);
      string str37 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "8"), "Y", false) == 0, "X");
      nameValueCollection.Add("8", str37);
      string str38 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "677"), "May", false) == 0, "X");
      nameValueCollection.Add("677_May", str38);
      string str39 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "677"), "May_SubjectToConditions", false) == 0, "X");
      nameValueCollection.Add("677_Maysubjectto", str39);
      string str40 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "677"), "May_not", false) == 0, "X");
      nameValueCollection.Add("677_Maynot", str40);
      string str41 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "679"), "Y", false) == 0, "X");
      nameValueCollection.Add("679", str41);
      string str42 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "680"), "Y", false) == 0, "E");
      nameValueCollection.Add("680", str42);
      string str43 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "680"), "Y", false) == 0, "E");
      nameValueCollection.Add("E1", str43);
      string str44 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "680"), "Y", false) == 0, "E");
      nameValueCollection.Add("E2", str44);
      string str45 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "680"), "Y", false) == 0, "E");
      nameValueCollection.Add("E3", str45);
      string str46 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "680"), "Y", false) == 0, "E");
      nameValueCollection.Add("E4", str46);
      string str47 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2026"), "", false) != 0, JS.GetStr(loan, "2026"), JS.GetStr(loan, "317"));
      nameValueCollection.Add("317", str47);
      string str48 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37_A", str48);
      string str49 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69_A", str49);
      string str50 = JS.GetStr(loan, "REGZ_DAY");
      nameValueCollection.Add("REGZ_DAY", str50);
      string str51 = JS.GetStr(loan, "REGZ_MONTH") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZ_MONTH"), "", false) != 0, ", ", "         ") + JS.GetStr(loan, "REGZ_YR");
      nameValueCollection.Add("REGZ_MONTH_YR", str51);
      string str52 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1708"), "Y", false) == 0, "X");
      nameValueCollection.Add("1708", str52);
      string str53 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1709"), "Property", false) == 0, "hazard", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1709"), "Flood", false) == 0, "flood", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1709"), "Property and Flood", false) == 0, "hazard and flood", "")));
      nameValueCollection.Add("1709", str53);
      string str54 = JS.GetStr(loan, "1710");
      nameValueCollection.Add("1710", str54);
      string str55 = JS.GetStr(loan, "1702");
      nameValueCollection.Add("1702", str55);
      string str56 = JS.GetStr(loan, "1703");
      nameValueCollection.Add("1703", str56);
      string str57 = JS.GetStr(loan, "1704");
      nameValueCollection.Add("1704", str57);
      string str58 = JS.GetStr(loan, "1705");
      nameValueCollection.Add("1705", str58);
      string str59 = JS.GetStr(loan, "3");
      nameValueCollection.Add("3", str59);
      string str60 = JS.GetStr(loan, "3");
      nameValueCollection.Add("3_a", str60);
      string str61 = JS.GetStr(loan, "3");
      nameValueCollection.Add("3_b", str61);
      string str62 = JS.GetStr(loan, "5");
      nameValueCollection.Add("5", str62);
      string str63 = JS.GetStr(loan, "696");
      nameValueCollection.Add("696", str63);
      string str64 = JS.GetStr(loan, "696");
      nameValueCollection.Add("696_a", str64);
      string str65 = JS.GetStr(loan, "2625");
      nameValueCollection.Add("2625", str65);
      string str66 = JS.GetStr(loan, "1176");
      nameValueCollection.Add("1176", str66);
      string str67 = JS.GetStr(loan, "1177");
      nameValueCollection.Add("1177", str67);
      string str68 = JS.GetStr(loan, "1677");
      nameValueCollection.Add("1677", str68);
      string str69 = JS.GetStr(loan, "1677");
      nameValueCollection.Add("1677_a", str69);
      string str70 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3264"), "Y", false) == 0, "X");
      nameValueCollection.Add("3264", str70);
      string str71 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3265"), "Y", false) == 0, "X");
      nameValueCollection.Add("3265", str71);
      string str72 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "3266"), "Y", false) == 0, "X");
      nameValueCollection.Add("3266", str72);
      string str73 = JS.GetStr(loan, "3267");
      nameValueCollection.Add("3267", str73);
      string str74 = JS.GetStr(loan, "3268");
      nameValueCollection.Add("3268", str74);
      string str75 = JS.GetStr(loan, "3269");
      nameValueCollection.Add("3269", str75);
      string str76 = JS.GetStr(loan, "3270");
      nameValueCollection.Add("3270", str76);
      string str77 = JS.GetStr(loan, "3271");
      nameValueCollection.Add("3271", str77);
      string str78 = JS.GetStr(loan, "3272");
      nameValueCollection.Add("3272", str78);
      string str79 = JS.GetStr(loan, "3273");
      nameValueCollection.Add("3273", str79);
      string str80 = JS.GetStr(loan, "3274");
      nameValueCollection.Add("3274", str80);
      string str81 = JS.GetStr(loan, "3275");
      nameValueCollection.Add("3275", str81);
      string str82 = JS.GetStr(loan, "3276");
      nameValueCollection.Add("3276", str82);
      string str83 = JS.GetStr(loan, "3277");
      nameValueCollection.Add("3277", str83);
      string str84 = JS.GetStr(loan, "3278");
      nameValueCollection.Add("3278", str84);
      string str85 = JS.GetStr(loan, "3279");
      nameValueCollection.Add("3279", str85);
      string str86 = JS.GetStr(loan, "3280");
      nameValueCollection.Add("3280", str86);
      string str87 = JS.GetStr(loan, "3281");
      nameValueCollection.Add("3281", str87);
      string str88 = JS.GetStr(loan, "3282");
      nameValueCollection.Add("3282", str88);
      string str89 = JS.GetStr(loan, "3283");
      nameValueCollection.Add("3283", str89);
      string str90 = JS.GetStr(loan, "3284");
      nameValueCollection.Add("3284", str90);
      string str91 = JS.GetStr(loan, "3285");
      nameValueCollection.Add("3285", str91);
      string str92 = JS.GetStr(loan, "3286");
      nameValueCollection.Add("3286", str92);
      string str93 = JS.GetStr(loan, "3287");
      nameValueCollection.Add("3287", str93);
      string str94 = JS.GetStr(loan, "3288");
      nameValueCollection.Add("3288", str94);
      string str95 = JS.GetStr(loan, "3289");
      nameValueCollection.Add("3289", str95);
      string str96 = JS.GetStr(loan, "1827");
      nameValueCollection.Add("1827", str96);
      string str97 = JS.GetStr(loan, "3296");
      nameValueCollection.Add("3296", str97);
      string str98 = JS.GetStr(loan, "3290");
      nameValueCollection.Add("3290", str98);
      string str99 = JS.GetStr(loan, "3291");
      nameValueCollection.Add("3291", str99);
      string str100 = JS.GetStr(loan, "3291");
      nameValueCollection.Add("3291_a", str100);
      string str101 = JS.GetStr(loan, "3294");
      nameValueCollection.Add("3294", str101);
      string str102 = JS.GetStr(loan, "3295");
      nameValueCollection.Add("3295", str102);
      string str103 = JS.GetStr(loan, "1613");
      nameValueCollection.Add("1613", str103);
      string str104 = JS.GetStr(loan, "1679");
      nameValueCollection.Add("1679", str104);
      return nameValueCollection;
    }
  }
}
