// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._REGZ___TILCLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _REGZ___TILCLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2626"), "Banked - Wholesale", false) == 0 & Operators.CompareString(JS.GetStr(loan, "1264"), "", false) != 0, JS.GetStr(loan, "1264"), JS.GetStr(loan, "315"));
      nameValueCollection.Add("315", str1);
      string str2 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str2);
      string str3 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str3);
      string str4 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69", str4);
      string str5 = JS.GetStr(loan, "11");
      nameValueCollection.Add("11", str5);
      string str6 = JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("12_14", str6);
      string str7 = JS.GetStr(loan, "3122");
      nameValueCollection.Add("3122", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "662"), "Initial", false) == 0, "X");
      nameValueCollection.Add("662_Initial", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "662"), "Final", false) == 0, "X");
      nameValueCollection.Add("662_Final", str9);
      string str10 = JS.GetStr(loan, "799");
      nameValueCollection.Add("779", str10);
      string str11 = JS.GetStr(loan, "1206");
      nameValueCollection.Add("1206", str11);
      string str12 = JS.GetStr(loan, "948");
      nameValueCollection.Add("948", str12);
      string str13 = JS.GetStr(loan, "1207");
      nameValueCollection.Add("1207", str13);
      string str14 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, "Biweekly", "Monthly");
      nameValueCollection.Add("DUETYPE", str14);
      string str15 = "";
      nameValueCollection.Add("SX1", str15);
      string str16 = "";
      nameValueCollection.Add("SX2", str16);
      string str17 = "";
      nameValueCollection.Add("SX3", str17);
      string str18 = "";
      nameValueCollection.Add("SX4", str18);
      string str19 = "";
      nameValueCollection.Add("SX5", str19);
      string str20 = "";
      nameValueCollection.Add("SX6", str20);
      string str21 = "";
      nameValueCollection.Add("SX7", str21);
      string str22 = "";
      nameValueCollection.Add("SX8", str22);
      string str23 = "";
      nameValueCollection.Add("SX9", str23);
      string str24 = "";
      nameValueCollection.Add("SX10", str24);
      string str25 = "";
      nameValueCollection.Add("SX11", str25);
      string str26 = "";
      nameValueCollection.Add("SX12", str26);
      string str27 = "";
      nameValueCollection.Add("SX13", str27);
      string str28 = "";
      nameValueCollection.Add("SX14", str28);
      string str29 = "";
      nameValueCollection.Add("SX15", str29);
      string str30 = "";
      nameValueCollection.Add("SX16", str30);
      string str31 = "";
      nameValueCollection.Add("SX17", str31);
      string str32 = "";
      nameValueCollection.Add("SX18", str32);
      string str33 = "";
      nameValueCollection.Add("SX19", str33);
      string str34 = "";
      nameValueCollection.Add("SX20", str34);
      string str35 = "";
      nameValueCollection.Add("SX21", str35);
      string str36 = "";
      nameValueCollection.Add("SX22", str36);
      string str37 = "";
      nameValueCollection.Add("SX23", str37);
      string str38 = "";
      nameValueCollection.Add("SX24", str38);
      string str39 = "";
      nameValueCollection.Add("SX25", str39);
      string str40 = "";
      nameValueCollection.Add("SX26", str40);
      string str41 = "";
      nameValueCollection.Add("SX27", str41);
      string str42 = "";
      nameValueCollection.Add("SX28", str42);
      string str43 = "";
      nameValueCollection.Add("SX29", str43);
      string str44 = "";
      nameValueCollection.Add("SX30", str44);
      string str45 = "";
      nameValueCollection.Add("SX31", str45);
      string str46 = "";
      nameValueCollection.Add("SX32", str46);
      string str47 = "";
      nameValueCollection.Add("SX33", str47);
      string str48 = "";
      nameValueCollection.Add("SX34", str48);
      string str49 = "";
      nameValueCollection.Add("SX35", str49);
      string str50 = "";
      nameValueCollection.Add("SX36", str50);
      string str51 = "";
      nameValueCollection.Add("SX37", str51);
      string str52 = "";
      nameValueCollection.Add("SX38", str52);
      string str53 = "";
      nameValueCollection.Add("SX39", str53);
      string str54 = "";
      nameValueCollection.Add("SX40", str54);
      string str55 = "";
      nameValueCollection.Add("SX41", str55);
      string str56 = "";
      nameValueCollection.Add("SX42", str56);
      string str57 = "";
      nameValueCollection.Add("SX43", str57);
      string str58 = "";
      nameValueCollection.Add("SX44", str58);
      string str59 = "";
      nameValueCollection.Add("SX45", str59);
      string str60 = "";
      nameValueCollection.Add("SX46", str60);
      string str61 = "";
      nameValueCollection.Add("SX47", str61);
      string str62 = "";
      nameValueCollection.Add("SX48", str62);
      string str63 = "";
      nameValueCollection.Add("SX49", str63);
      string str64 = "";
      nameValueCollection.Add("SX50", str64);
      string str65 = "";
      nameValueCollection.Add("SX51", str65);
      string str66 = "";
      nameValueCollection.Add("SX52", str66);
      string str67 = "";
      nameValueCollection.Add("SX53", str67);
      string str68 = "";
      nameValueCollection.Add("SX54", str68);
      string str69 = "";
      nameValueCollection.Add("SX55", str69);
      string str70 = "";
      nameValueCollection.Add("SX56", str70);
      string str71 = "";
      nameValueCollection.Add("SX57", str71);
      string str72 = "";
      nameValueCollection.Add("SX58", str72);
      string str73 = "";
      nameValueCollection.Add("SX59", str73);
      string str74 = "";
      nameValueCollection.Add("SX60", str74);
      string str75 = "";
      nameValueCollection.Add("SX61", str75);
      string str76 = "";
      nameValueCollection.Add("SX62", str76);
      string str77 = "";
      nameValueCollection.Add("SX63", str77);
      string str78 = "";
      nameValueCollection.Add("SX64", str78);
      string str79 = "";
      nameValueCollection.Add("SX65", str79);
      string str80 = "";
      nameValueCollection.Add("SX66", str80);
      string str81 = "";
      nameValueCollection.Add("SX67", str81);
      string str82 = "";
      nameValueCollection.Add("SX68", str82);
      string str83 = "";
      nameValueCollection.Add("SX69", str83);
      string str84 = "";
      nameValueCollection.Add("SX70", str84);
      string str85 = "";
      nameValueCollection.Add("SX71", str85);
      string str86 = "";
      nameValueCollection.Add("SX72", str86);
      string str87 = "";
      nameValueCollection.Add("SX73", str87);
      string str88 = "";
      nameValueCollection.Add("SX74", str88);
      string str89 = "";
      nameValueCollection.Add("SX75", str89);
      string str90 = "";
      nameValueCollection.Add("SX76", str90);
      string str91 = "";
      nameValueCollection.Add("SX77", str91);
      string str92 = "";
      nameValueCollection.Add("SX78", str92);
      string str93 = "";
      nameValueCollection.Add("SX79", str93);
      string str94 = "";
      nameValueCollection.Add("SX80", str94);
      string str95 = "";
      nameValueCollection.Add("SX81", str95);
      string str96 = "";
      nameValueCollection.Add("SX82", str96);
      string str97 = "";
      nameValueCollection.Add("SX83", str97);
      string str98 = "";
      nameValueCollection.Add("SX84", str98);
      string str99 = "";
      nameValueCollection.Add("SX85", str99);
      string str100 = "";
      nameValueCollection.Add("SX86", str100);
      string str101 = "";
      nameValueCollection.Add("SX87", str101);
      string str102 = "";
      nameValueCollection.Add("SX88", str102);
      string str103 = "";
      nameValueCollection.Add("SX89", str103);
      string str104 = "";
      nameValueCollection.Add("SX90", str104);
      string str105 = "";
      nameValueCollection.Add("SX91", str105);
      string str106 = "";
      nameValueCollection.Add("SX92", str106);
      string str107 = "";
      nameValueCollection.Add("SX93", str107);
      string str108 = "";
      nameValueCollection.Add("SX94", str108);
      string str109 = "";
      nameValueCollection.Add("SX95", str109);
      string str110 = "";
      nameValueCollection.Add("SX96", str110);
      string str111 = "";
      nameValueCollection.Add("SX97", str111);
      string str112 = "";
      nameValueCollection.Add("SX98", str112);
      string str113 = "";
      nameValueCollection.Add("SX99", str113);
      string str114 = "";
      nameValueCollection.Add("SX100", str114);
      string str115 = "";
      nameValueCollection.Add("SX101", str115);
      string str116 = "";
      nameValueCollection.Add("SX102", str116);
      string str117 = "";
      nameValueCollection.Add("SX103", str117);
      string str118 = "";
      nameValueCollection.Add("SX104", str118);
      string str119 = "";
      nameValueCollection.Add("SX105", str119);
      string str120 = "";
      nameValueCollection.Add("SX106", str120);
      string str121 = "";
      nameValueCollection.Add("SX107", str121);
      string str122 = "";
      nameValueCollection.Add("SX108", str122);
      string str123 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "FHA", false) == 0, "IF YOU PREPAY YOUR LOAN OTHER THAN ON THE REGULAR INSTALLMENT DATE YOU MAY BE ASSESSED INTEREST CHARGES UNTIL THE END OF THE MONTH AND YOU MAY BE ENTITLED TO A REFUND OF PART OF THE FINANCE CHARGE.");
      nameValueCollection.Add("FHA_Message", str123);
      string str124 = JS.GetStr(loan, "1404");
      nameValueCollection.Add("1404", str124);
      string str125 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "663"), "Y", false) == 0, "X");
      nameValueCollection.Add("663", str125);
      string str126 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "664"), "Y", false) == 0, "X");
      nameValueCollection.Add("664", str126);
      string str127 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "665"), "Y", false) == 0, "X");
      nameValueCollection.Add("665", str127);
      string str128 = JS.GetStr(loan, "666");
      nameValueCollection.Add("666", str128);
      string str129 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "671"), "TheGoodsOrPropertyBeingPurchased", false) == 0, "X");
      nameValueCollection.Add("671_Thegoods", str129);
      string str130 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "671"), "RealPropertyYouAlreadyOwn", false) == 0, "X");
      nameValueCollection.Add("671_Realproperty", str130);
      string str131 = JS.GetStr(loan, "1603");
      nameValueCollection.Add("1603", str131);
      string str132 = JS.GetStr(loan, "1707");
      nameValueCollection.Add("390", str132);
      string str133 = JS.GetStr(loan, "672");
      nameValueCollection.Add("672", str133);
      string str134 = JS.GetStr(loan, "674");
      nameValueCollection.Add("674", str134);
      string str135 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1719"), "", false) != 0, JS.GetStr(loan, "1719") + ".");
      nameValueCollection.Add("1719", str135);
      string str136 = JS.GetStr(loan, "1854");
      nameValueCollection.Add("1854", str136);
      string str137 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "670"), "Y", false) == 0, "X");
      nameValueCollection.Add("670_May", str137);
      string str138 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "670"), "N", false) == 0, "X");
      nameValueCollection.Add("670_Willnot", str138);
      string str139 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "675"), "Y", false) == 0, "X");
      nameValueCollection.Add("675_May", str139);
      string str140 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "675"), "N", false) == 0, "X");
      nameValueCollection.Add("675_Willnot", str140);
      string str141 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1242"), "Y", false) == 0, "X");
      nameValueCollection.Add("1242", str141);
      string str142 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "676"), "Y", false) == 0, "X");
      nameValueCollection.Add("676", str142);
      string str143 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1698"), "Y", false) == 0, "X");
      nameValueCollection.Add("1698", str143);
      string str144 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1697"), "Y", false) == 0, "X");
      nameValueCollection.Add("1697", str144);
      string str145 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "723"), "Y", false) == 0, "X");
      nameValueCollection.Add("723", str145);
      string str146 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "8"), "Y", false) == 0, "X");
      nameValueCollection.Add("8", str146);
      string str147 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "677"), "May", false) == 0, "X");
      nameValueCollection.Add("677_May", str147);
      string str148 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "677"), "May_SubjectToConditions", false) == 0, "X");
      nameValueCollection.Add("677_Maysubjectto", str148);
      string str149 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "677"), "May_not", false) == 0, "X");
      nameValueCollection.Add("677_Maynot", str149);
      string str150 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "679"), "Y", false) == 0, "X");
      nameValueCollection.Add("679", str150);
      string str151 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "680"), "Y", false) == 0, "E");
      nameValueCollection.Add("680", str151);
      string str152 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "680"), "Y", false) == 0, "E");
      nameValueCollection.Add("E1", str152);
      string str153 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "680"), "Y", false) == 0, "E");
      nameValueCollection.Add("E2", str153);
      string str154 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "680"), "Y", false) == 0, "E");
      nameValueCollection.Add("E3", str154);
      string str155 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "680"), "Y", false) == 0, "E");
      nameValueCollection.Add("E4", str155);
      string str156 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2026"), "", false) != 0, JS.GetStr(loan, "2026"), JS.GetStr(loan, "317"));
      nameValueCollection.Add("317", str156);
      string str157 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37_A", str157);
      string str158 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69_A", str158);
      string str159 = JS.GetStr(loan, "REGZ_DAY");
      nameValueCollection.Add("REGZ_DAY", str159);
      string str160 = JS.GetStr(loan, "REGZ_MONTH") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "REGZ_MONTH"), "", false) != 0, ", ", "         ") + JS.GetStr(loan, "REGZ_YR");
      nameValueCollection.Add("REGZ_MONTH_YR", str160);
      string str161 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1708"), "Y", false) == 0, "X");
      nameValueCollection.Add("1708", str161);
      string str162 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1709"), "Property", false) == 0, "hazard", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1709"), "Flood", false) == 0, "flood", Jed.BF(Operators.CompareString(JS.GetStr(loan, "1709"), "Property and Flood", false) == 0, "hazard and flood", "")));
      nameValueCollection.Add("1709", str162);
      string str163 = JS.GetStr(loan, "1710");
      nameValueCollection.Add("1710", str163);
      string str164 = JS.GetStr(loan, "1702");
      nameValueCollection.Add("1702", str164);
      string str165 = JS.GetStr(loan, "1703");
      nameValueCollection.Add("1703", str165);
      string str166 = JS.GetStr(loan, "1704");
      nameValueCollection.Add("1704", str166);
      string str167 = JS.GetStr(loan, "1705");
      nameValueCollection.Add("1705", str167);
      return nameValueCollection;
    }
  }
}
