// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._TRUST_ACCOUNTCLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _TRUST_ACCOUNTCLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str1);
      string str2 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "363"), "//", false) != 0, JS.GetStr(loan, "363"));
      nameValueCollection.Add("363", str2);
      string str3 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str3);
      string str4 = JS.GetStr(loan, "68") + " " + JS.GetStr(loan, "69");
      nameValueCollection.Add("68_69", str4);
      string str5 = JS.GetStr(loan, "11");
      nameValueCollection.Add("MAP3", str5);
      string str6 = JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("MAP4", str6);
      string str7 = JS.GetStr(loan, "317");
      nameValueCollection.Add("317", str7);
      string str8 = JS.GetStr(loan, "362");
      nameValueCollection.Add("362", str8);
      string str9 = JS.GetStr(loan, "TA01DS");
      nameValueCollection.Add("TA01DS", str9);
      string str10 = JS.GetStr(loan, "TA01PC");
      nameValueCollection.Add("TA01PC", str10);
      string str11 = JS.GetStr(loan, "TA01RC");
      nameValueCollection.Add("TA01RC", str11);
      string str12 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA01DT"), "//", false) != 0, JS.GetStr(loan, "TA01DT"));
      nameValueCollection.Add("TA01DT", str12);
      string str13 = JS.GetStr(loan, "TA01PA");
      nameValueCollection.Add("TA01PA", str13);
      string str14 = JS.GetStr(loan, "TA01RA");
      nameValueCollection.Add("TA01RA", str14);
      string str15 = JS.GetStr(loan, "TA01NO");
      nameValueCollection.Add("TA01NO", str15);
      string str16 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX81", str16);
      string str17 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA01RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA01PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA01RA")) - Jed.S2N(JS.GetStr(loan, "TA01PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX129", str17);
      string str18 = JS.GetStr(loan, "TA02DS");
      nameValueCollection.Add("TA02DS", str18);
      string str19 = JS.GetStr(loan, "TA02PC");
      nameValueCollection.Add("TA02PC", str19);
      string str20 = JS.GetStr(loan, "TA02RC");
      nameValueCollection.Add("TA02RC", str20);
      string str21 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA02DT"), "//", false) != 0, JS.GetStr(loan, "TA02DT"));
      nameValueCollection.Add("TA02DT", str21);
      string str22 = JS.GetStr(loan, "TA02PA");
      nameValueCollection.Add("TA02PA", str22);
      string str23 = JS.GetStr(loan, "TA02RA");
      nameValueCollection.Add("TA02RA", str23);
      string str24 = JS.GetStr(loan, "TA02NO");
      nameValueCollection.Add("TA02NO", str24);
      string str25 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX82", str25);
      string str26 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA02RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA02PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA02RA")) - Jed.S2N(JS.GetStr(loan, "TA02PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX130", str26);
      string str27 = JS.GetStr(loan, "TA03DS");
      nameValueCollection.Add("TA03DS", str27);
      string str28 = JS.GetStr(loan, "TA03PC");
      nameValueCollection.Add("TA03PC", str28);
      string str29 = JS.GetStr(loan, "TA03RC");
      nameValueCollection.Add("TA03RC", str29);
      string str30 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA03DT"), "//", false) != 0, JS.GetStr(loan, "TA03DT"));
      nameValueCollection.Add("TA03DT", str30);
      string str31 = JS.GetStr(loan, "TA03PA");
      nameValueCollection.Add("TA03PA", str31);
      string str32 = JS.GetStr(loan, "TA03RA");
      nameValueCollection.Add("TA03RA", str32);
      string str33 = JS.GetStr(loan, "TA03NO");
      nameValueCollection.Add("TA03NO", str33);
      string str34 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX83", str34);
      string str35 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA03RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA03PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA03RA")) - Jed.S2N(JS.GetStr(loan, "TA03PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX131", str35);
      string str36 = JS.GetStr(loan, "TA04DS");
      nameValueCollection.Add("TA04DS", str36);
      string str37 = JS.GetStr(loan, "TA04PC");
      nameValueCollection.Add("TA04PC", str37);
      string str38 = JS.GetStr(loan, "TA04RC");
      nameValueCollection.Add("TA04RC", str38);
      string str39 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA04DT"), "//", false) != 0, JS.GetStr(loan, "TA04DT"));
      nameValueCollection.Add("TA04DT", str39);
      string str40 = JS.GetStr(loan, "TA04PA");
      nameValueCollection.Add("TA04PA", str40);
      string str41 = JS.GetStr(loan, "TA04RA");
      nameValueCollection.Add("TA04RA", str41);
      string str42 = JS.GetStr(loan, "TA04NO");
      nameValueCollection.Add("TA04NO", str42);
      string str43 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX84", str43);
      string str44 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA04RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA04PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA04RA")) - Jed.S2N(JS.GetStr(loan, "TA04PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX132", str44);
      string str45 = JS.GetStr(loan, "TA05DS");
      nameValueCollection.Add("TA05DS", str45);
      string str46 = JS.GetStr(loan, "TA05PC");
      nameValueCollection.Add("TA05PC", str46);
      string str47 = JS.GetStr(loan, "TA05RC");
      nameValueCollection.Add("TA05RC", str47);
      string str48 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA05DT"), "//", false) != 0, JS.GetStr(loan, "TA05DT"));
      nameValueCollection.Add("TA05DT", str48);
      string str49 = JS.GetStr(loan, "TA05PA");
      nameValueCollection.Add("TA05PA", str49);
      string str50 = JS.GetStr(loan, "TA05RA");
      nameValueCollection.Add("TA05RA", str50);
      string str51 = JS.GetStr(loan, "TA05NO");
      nameValueCollection.Add("TA05NO", str51);
      string str52 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX85", str52);
      string str53 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA05RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA05PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA05RA")) - Jed.S2N(JS.GetStr(loan, "TA05PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX133", str53);
      string str54 = JS.GetStr(loan, "TA06DS");
      nameValueCollection.Add("TA06DS", str54);
      string str55 = JS.GetStr(loan, "TA06PC");
      nameValueCollection.Add("TA06PC", str55);
      string str56 = JS.GetStr(loan, "TA06RC");
      nameValueCollection.Add("TA06RC", str56);
      string str57 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA06DT"), "//", false) != 0, JS.GetStr(loan, "TA06DT"));
      nameValueCollection.Add("TA06DT", str57);
      string str58 = JS.GetStr(loan, "TA06PA");
      nameValueCollection.Add("TA06PA", str58);
      string str59 = JS.GetStr(loan, "TA06RA");
      nameValueCollection.Add("TA06RA", str59);
      string str60 = JS.GetStr(loan, "TA06NO");
      nameValueCollection.Add("TA06NO", str60);
      string str61 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX86", str61);
      string str62 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA06RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA06PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA06RA")) - Jed.S2N(JS.GetStr(loan, "TA06PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX134", str62);
      string str63 = JS.GetStr(loan, "TA07DS");
      nameValueCollection.Add("TA07DS", str63);
      string str64 = JS.GetStr(loan, "TA07PC") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA07RC"), "", false) != 0, " / ") + JS.GetStr(loan, "TA07RC");
      nameValueCollection.Add("FEETRKX55", str64);
      string str65 = JS.GetStr(loan, "TA07PC");
      nameValueCollection.Add("TA07PC", str65);
      string str66 = JS.GetStr(loan, "TA07RC");
      nameValueCollection.Add("TA07RC", str66);
      string str67 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA07DT"), "//", false) != 0, JS.GetStr(loan, "TA07DT"));
      nameValueCollection.Add("TA07DT", str67);
      string str68 = JS.GetStr(loan, "TA07PA");
      nameValueCollection.Add("TA07PA", str68);
      string str69 = JS.GetStr(loan, "TA07RA");
      nameValueCollection.Add("TA07RA", str69);
      string str70 = JS.GetStr(loan, "TA07NO");
      nameValueCollection.Add("TA07NO", str70);
      string str71 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX87", str71);
      string str72 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA07RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA07PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA07RA")) - Jed.S2N(JS.GetStr(loan, "TA07PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX135", str72);
      string str73 = JS.GetStr(loan, "TA08DS");
      nameValueCollection.Add("TA08DS", str73);
      string str74 = JS.GetStr(loan, "TA08PC");
      nameValueCollection.Add("TA08PC", str74);
      string str75 = JS.GetStr(loan, "TA08RC");
      nameValueCollection.Add("TA08RC", str75);
      string str76 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA08DT"), "//", false) != 0, JS.GetStr(loan, "TA08DT"));
      nameValueCollection.Add("TA08DT", str76);
      string str77 = JS.GetStr(loan, "TA08PA");
      nameValueCollection.Add("TA08PA", str77);
      string str78 = JS.GetStr(loan, "TA08RA");
      nameValueCollection.Add("TA08RA", str78);
      string str79 = JS.GetStr(loan, "TA08NO");
      nameValueCollection.Add("TA08NO", str79);
      string str80 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX88", str80);
      string str81 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA08RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA08PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA08RA")) - Jed.S2N(JS.GetStr(loan, "TA08PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX136", str81);
      string str82 = JS.GetStr(loan, "TA09DS");
      nameValueCollection.Add("TA09DS", str82);
      string str83 = JS.GetStr(loan, "TA09PC");
      nameValueCollection.Add("TA09PC", str83);
      string str84 = JS.GetStr(loan, "TA09RC");
      nameValueCollection.Add("TA09RC", str84);
      string str85 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA09DT"), "//", false) != 0, JS.GetStr(loan, "TA09DT"));
      nameValueCollection.Add("TA09DT", str85);
      string str86 = JS.GetStr(loan, "TA09PA");
      nameValueCollection.Add("TA09PA", str86);
      string str87 = JS.GetStr(loan, "TA09RA");
      nameValueCollection.Add("TA09RA", str87);
      string str88 = JS.GetStr(loan, "TA09NO");
      nameValueCollection.Add("TA09NO", str88);
      string str89 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX89", str89);
      string str90 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA09RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA09PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA09RA")) - Jed.S2N(JS.GetStr(loan, "TA09PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX137", str90);
      string str91 = JS.GetStr(loan, "TA10DS");
      nameValueCollection.Add("TA10DS", str91);
      string str92 = JS.GetStr(loan, "TA10PC");
      nameValueCollection.Add("TA10PC", str92);
      string str93 = JS.GetStr(loan, "TA10RC");
      nameValueCollection.Add("TA10RC", str93);
      string str94 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA10DT"), "//", false) != 0, JS.GetStr(loan, "TA10DT"));
      nameValueCollection.Add("TA10DT", str94);
      string str95 = JS.GetStr(loan, "TA10PA");
      nameValueCollection.Add("TA10PA", str95);
      string str96 = JS.GetStr(loan, "TA10RA");
      nameValueCollection.Add("TA10RA", str96);
      string str97 = JS.GetStr(loan, "TA10NO");
      nameValueCollection.Add("TA10NO", str97);
      string str98 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX90", str98);
      string str99 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA10RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA10PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA10RA")) - Jed.S2N(JS.GetStr(loan, "TA10PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX138", str99);
      string str100 = JS.GetStr(loan, "TA11DS");
      nameValueCollection.Add("TA11DS", str100);
      string str101 = JS.GetStr(loan, "TA11PC");
      nameValueCollection.Add("TA11PC", str101);
      string str102 = JS.GetStr(loan, "TA11RC");
      nameValueCollection.Add("TA11RC", str102);
      string str103 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA11DT"), "//", false) != 0, JS.GetStr(loan, "TA11DT"));
      nameValueCollection.Add("TA11DT", str103);
      string str104 = JS.GetStr(loan, "TA11PA");
      nameValueCollection.Add("TA11PA", str104);
      string str105 = JS.GetStr(loan, "TA11RA");
      nameValueCollection.Add("TA11RA", str105);
      string str106 = JS.GetStr(loan, "TA11NO");
      nameValueCollection.Add("TA11NO", str106);
      string str107 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX91", str107);
      string str108 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA11RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA11PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA11RA")) - Jed.S2N(JS.GetStr(loan, "TA11PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX139", str108);
      string str109 = JS.GetStr(loan, "TA12DS");
      nameValueCollection.Add("TA12DS", str109);
      string str110 = JS.GetStr(loan, "TA12PC");
      nameValueCollection.Add("TA12PC", str110);
      string str111 = JS.GetStr(loan, "TA12RC");
      nameValueCollection.Add("TA12RC", str111);
      string str112 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA12DT"), "//", false) != 0, JS.GetStr(loan, "TA12DT"));
      nameValueCollection.Add("TA12DT", str112);
      string str113 = JS.GetStr(loan, "TA12PA");
      nameValueCollection.Add("TA12PA", str113);
      string str114 = JS.GetStr(loan, "TA12RA");
      nameValueCollection.Add("TA12RA", str114);
      string str115 = JS.GetStr(loan, "TA12NO");
      nameValueCollection.Add("TA12NO", str115);
      string str116 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX92", str116);
      string str117 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA12RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA12PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA12RA")) - Jed.S2N(JS.GetStr(loan, "TA12PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX140", str117);
      string str118 = JS.GetStr(loan, "TA13DS");
      nameValueCollection.Add("TA13DS", str118);
      string str119 = JS.GetStr(loan, "TA13PC");
      nameValueCollection.Add("TA13PC", str119);
      string str120 = JS.GetStr(loan, "TA13RC");
      nameValueCollection.Add("TA13RC", str120);
      string str121 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA13DT"), "//", false) != 0, JS.GetStr(loan, "TA13DT"));
      nameValueCollection.Add("TA13DT", str121);
      string str122 = JS.GetStr(loan, "TA13PA");
      nameValueCollection.Add("TA13PA", str122);
      string str123 = JS.GetStr(loan, "TA13RA");
      nameValueCollection.Add("TA13RA", str123);
      string str124 = JS.GetStr(loan, "TA13NO");
      nameValueCollection.Add("TA13NO", str124);
      string str125 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX93", str125);
      string str126 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA13RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA13PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA13RA")) - Jed.S2N(JS.GetStr(loan, "TA13PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX141", str126);
      string str127 = JS.GetStr(loan, "TA14DS");
      nameValueCollection.Add("TA14DS", str127);
      string str128 = JS.GetStr(loan, "TA14PC");
      nameValueCollection.Add("TA14PC", str128);
      string str129 = JS.GetStr(loan, "TA14RC");
      nameValueCollection.Add("TA14RC", str129);
      string str130 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA14DT"), "//", false) != 0, JS.GetStr(loan, "TA14DT"));
      nameValueCollection.Add("TA14DT", str130);
      string str131 = JS.GetStr(loan, "TA14PA");
      nameValueCollection.Add("TA14PA", str131);
      string str132 = JS.GetStr(loan, "TA14RA");
      nameValueCollection.Add("TA14RA", str132);
      string str133 = JS.GetStr(loan, "TA14NO");
      nameValueCollection.Add("TA14NO", str133);
      string str134 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX94", str134);
      string str135 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA14RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA14PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA14RA")) - Jed.S2N(JS.GetStr(loan, "TA14PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX142", str135);
      string str136 = JS.GetStr(loan, "TA15DS");
      nameValueCollection.Add("TA15DS", str136);
      string str137 = JS.GetStr(loan, "TA15PC");
      nameValueCollection.Add("TA15PC", str137);
      string str138 = JS.GetStr(loan, "TA15RC");
      nameValueCollection.Add("TA15RC", str138);
      string str139 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA15DT"), "//", false) != 0, JS.GetStr(loan, "TA15DT"));
      nameValueCollection.Add("TA15DT", str139);
      string str140 = JS.GetStr(loan, "TA15PA");
      nameValueCollection.Add("TA15PA", str140);
      string str141 = JS.GetStr(loan, "TA15RA");
      nameValueCollection.Add("TA15RA", str141);
      string str142 = JS.GetStr(loan, "TA15NO");
      nameValueCollection.Add("TA15NO", str142);
      string str143 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX95", str143);
      string str144 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA15RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA15PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA15RA")) - Jed.S2N(JS.GetStr(loan, "TA15PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX143", str144);
      string str145 = JS.GetStr(loan, "TA16DS");
      nameValueCollection.Add("TA16DS", str145);
      string str146 = JS.GetStr(loan, "TA16PC");
      nameValueCollection.Add("TA16PC", str146);
      string str147 = JS.GetStr(loan, "TA16RC");
      nameValueCollection.Add("TA16RC", str147);
      string str148 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "TA16DT"), "//", false) != 0, JS.GetStr(loan, "TA16DT"));
      nameValueCollection.Add("TA16DT", str148);
      string str149 = JS.GetStr(loan, "TA16PA");
      nameValueCollection.Add("TA16PA", str149);
      string str150 = JS.GetStr(loan, "TA16RA");
      nameValueCollection.Add("TA16RA", str150);
      string str151 = JS.GetStr(loan, "TA16NO");
      nameValueCollection.Add("TA16NO", str151);
      string str152 = JS.GetStr(loan, "");
      nameValueCollection.Add("FEETRKX95", str152);
      string str153 = Jed.BF(Jed.S2N(JS.GetStr(loan, "TA16RA")) != 0.0 & Jed.S2N(JS.GetStr(loan, "TA16PA")) != 0.0, Jed.NF(Jed.S2N(JS.GetStr(loan, "TA16RA")) - Jed.S2N(JS.GetStr(loan, "TA16PA")), (byte) 18, 0), "");
      nameValueCollection.Add("FEETRKX144", str153);
      string str154 = JS.GetStr(loan, "TATOTAL1");
      nameValueCollection.Add("TATOTAL1", str154);
      string str155 = JS.GetStr(loan, "TATOTAL2");
      nameValueCollection.Add("TATOTAL2", str155);
      string str156 = JS.GetStr(loan, "TABALANCE");
      nameValueCollection.Add("TABALANCE", str156);
      return nameValueCollection;
    }
  }
}
