// Decompiled with JetBrains decompiler
// Type: JedScripts.EllieMae.EMLite.Script._UNDERWRITERSUMMARYP1CLASS
// Assembly: JedScripts, Version=19.3.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 0C1FAB5C-E085-4229-8A3F-9EA3E2E6B3AA
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.dll
// XML documentation location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\JedScripts.xml

using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.JedScript;
using Microsoft.VisualBasic.CompilerServices;
using System.Collections.Specialized;

#nullable disable
namespace JedScripts.EllieMae.EMLite.Script
{
  public class _UNDERWRITERSUMMARYP1CLASS
  {
    public NameValueCollection RunScript(LoanData loan)
    {
      NameValueCollection nameValueCollection = new NameValueCollection();
      string empty = string.Empty;
      string str1 = JS.GetStr(loan, "2981");
      nameValueCollection.Add("2981", str1);
      string str2 = JS.GetStr(loan, "364");
      nameValueCollection.Add("364", str2);
      string str3 = JS.GetStr(loan, "VEND.X263");
      nameValueCollection.Add("VEND_X263", str3);
      string str4 = JS.GetStr(loan, "352");
      nameValueCollection.Add("352", str4);
      string str5 = JS.GetStr(loan, "36") + " " + JS.GetStr(loan, "37");
      nameValueCollection.Add("36_37", str5);
      string str6 = JS.GetStr(loan, "11") + "  " + JS.GetStr(loan, "12") + Jed.BF(Operators.CompareString(JS.GetStr(loan, "14"), "", false) != 0, ", ") + JS.GetStr(loan, "14") + " " + JS.GetStr(loan, "15");
      nameValueCollection.Add("11_12_14_15", str6);
      string str7 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "1172"), "FarmersHomeAdministration", false) == 0, "USDA-RHS", JS.GetStr(loan, "1172"));
      nameValueCollection.Add("1172", str7);
      string str8 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "420"), "SecondLien", false) == 0, "Second Lien", Jed.BF(Operators.CompareString(JS.GetStr(loan, "420"), "FirstLien", false) == 0, "First Lien"));
      nameValueCollection.Add("420", str8);
      string str9 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "GraduatedPaymentMortgage", false) == 0, "Graduated Payment Mortgage", Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "AdjustableRate", false) == 0, "Adjustable Rate", Jed.BF(Operators.CompareString(JS.GetStr(loan, "608"), "OtherAmortizationType", false) == 0, "Other Amortization Type", JS.GetStr(loan, "608"))));
      nameValueCollection.Add("608", str9);
      string str10 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionToPermanent", false) == 0, "Construction To Permanent", Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "NoCash-Out Refinance", false) == 0, "No Cash-Out Refinance", Jed.BF(Operators.CompareString(JS.GetStr(loan, "19"), "ConstructionOnly", false) == 0, "Construction", JS.GetStr(loan, "19"))));
      nameValueCollection.Add("19", str10);
      string str11 = JS.GetStr(loan, "356");
      nameValueCollection.Add("356", str11);
      string str12 = JS.GetStr(loan, "136");
      nameValueCollection.Add("136", str12);
      string str13 = JS.GetStr(loan, "1109");
      nameValueCollection.Add("1109", str13);
      string str14 = JS.GetStr(loan, "3");
      nameValueCollection.Add("3", str14);
      string str15 = JS.GetStr(loan, "4");
      nameValueCollection.Add("4", str15);
      string str16 = JS.GetStr(loan, "5");
      nameValueCollection.Add("5", str16);
      string str17 = JS.GetStr(loan, "353");
      nameValueCollection.Add("353", str17);
      string str18 = JS.GetStr(loan, "976");
      nameValueCollection.Add("976", str18);
      string str19 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) == 0, "X");
      nameValueCollection.Add("423_Y", str19);
      string str20 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "423"), "Biweekly", false) != 0, "X");
      nameValueCollection.Add("423_N", str20);
      string str21 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2982"), "Y", false) == 0, "X");
      nameValueCollection.Add("2982_Y", str21);
      string str22 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2982"), "Y", false) != 0, "X");
      nameValueCollection.Add("2982_N", str22);
      string str23 = JS.GetStr(loan, "1177");
      nameValueCollection.Add("1177", str23);
      string str24 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "425"), "Y", false) == 0, "X");
      nameValueCollection.Add("425_Y", str24);
      string str25 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "425"), "Y", false) != 0, "X");
      nameValueCollection.Add("425_N", str25);
      string str26 = JS.GetStr(loan, "799");
      nameValueCollection.Add("799", str26);
      string str27 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2400"), "Y", false) == 0, "X");
      nameValueCollection.Add("2400_Y", str27);
      string str28 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2400"), "Y", false) != 0, "X");
      nameValueCollection.Add("2400_N", str28);
      string str29 = JS.GetStr(loan, "762");
      nameValueCollection.Add("762", str29);
      string str30 = JS.GetStr(loan, "737");
      nameValueCollection.Add("737", str30);
      string str31 = JS.GetStr(loan, "732");
      nameValueCollection.Add("732", str31);
      string str32 = JS.GetStr(loan, "733");
      nameValueCollection.Add("733", str32);
      string str33 = JS.GetStr(loan, "912");
      nameValueCollection.Add("912", str33);
      string str34 = JS.GetStr(loan, "101");
      nameValueCollection.Add("101", str34);
      string str35 = JS.GetStr(loan, "110");
      nameValueCollection.Add("110", str35);
      string str36 = JS.GetStr(loan, "1168");
      nameValueCollection.Add("1168", str36);
      string str37 = JS.GetStr(loan, "1389");
      nameValueCollection.Add("1389", str37);
      string str38 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2983"), "Y", false) == 0, "X");
      nameValueCollection.Add("2983_Y", str38);
      string str39 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2983"), "Y", false) != 0, "X");
      nameValueCollection.Add("2983_N", str39);
      string str40 = JS.GetStr(loan, "740");
      nameValueCollection.Add("740", str40);
      string str41 = JS.GetStr(loan, "742");
      nameValueCollection.Add("742", str41);
      string str42 = JS.GetStr(loan, "67");
      nameValueCollection.Add("67", str42);
      string str43 = JS.GetStr(loan, "1450");
      nameValueCollection.Add("1450", str43);
      string str44 = JS.GetStr(loan, "1414");
      nameValueCollection.Add("1414", str44);
      string str45 = JS.GetStr(loan, "VASUMM.X23");
      nameValueCollection.Add("VASUMM_X23", str45);
      string str46 = JS.GetStr(loan, "60");
      nameValueCollection.Add("60", str46);
      string str47 = JS.GetStr(loan, "1452");
      nameValueCollection.Add("1452", str47);
      string str48 = JS.GetStr(loan, "1415");
      nameValueCollection.Add("1415", str48);
      string str49 = JS.GetStr(loan, "1546");
      nameValueCollection.Add("1546", str49);
      string str50 = JS.GetStr(loan, "1547");
      nameValueCollection.Add("1547", str50);
      string str51 = JS.GetStr(loan, "191");
      nameValueCollection.Add("191", str51);
      string str52 = JS.GetStr(loan, "CASASRN.X78");
      nameValueCollection.Add("CASASRN_X78", str52);
      string str53 = JS.GetStr(loan, "1548");
      nameValueCollection.Add("1548", str53);
      string str54 = JS.GetStr(loan, "1549");
      nameValueCollection.Add("1549", str54);
      string str55 = JS.GetStr(loan, "220");
      nameValueCollection.Add("220", str55);
      string str56 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "MCAWPUR.X9"), "00", false) == 0, "N/A", Jed.BF(Operators.CompareString(JS.GetStr(loan, "MCAWPUR.X9"), "01", false) == 0, "01:Relative", Jed.BF(Operators.CompareString(JS.GetStr(loan, "MCAWPUR.X9"), "02", false) == 0, "02:Nonprofit/Religious/Community", Jed.BF(Operators.CompareString(JS.GetStr(loan, "MCAWPUR.X9"), "03", false) == 0, "03:Government Assistance", Jed.BF(Operators.CompareString(JS.GetStr(loan, "MCAWPUR.X9"), "06", false) == 0, "06:Employer", Jed.BF(Operators.CompareString(JS.GetStr(loan, "MCAWPUR.X9"), "15", false) == 0, "15:Nonprofit/Religious/Community - Non-Seller Funded ", JS.GetStr(loan, "MCAWPUR.X9")))))));
      nameValueCollection.Add("MCAWPUR_X9", str56);
      string str57 = JS.GetStr(loan, "1092");
      nameValueCollection.Add("1092", str57);
      string str58 = JS.GetStr(loan, "427");
      nameValueCollection.Add("427", str58);
      string str59 = JS.GetStr(loan, "428");
      nameValueCollection.Add("428", str59);
      string str60 = JS.GetStr(loan, "976");
      nameValueCollection.Add("976_a", str60);
      string str61 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "675"), "Y", false) == 0, "X");
      nameValueCollection.Add("675_Y", str61);
      string str62 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "675"), "Y", false) != 0, "X");
      nameValueCollection.Add("675_N", str62);
      string str63 = JS.GetStr(loan, "1946");
      nameValueCollection.Add("1946", str63);
      string str64 = JS.GetStr(loan, "1947");
      nameValueCollection.Add("1947", str64);
      string str65 = JS.GetStr(loan, "1948");
      nameValueCollection.Add("1948", str65);
      string str66 = JS.GetStr(loan, "2829");
      nameValueCollection.Add("2829", str66);
      string str67 = JS.GetStr(loan, "2830");
      nameValueCollection.Add("2830", str67);
      string str68 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2293"), "Not Waived", false) == 0, "X");
      nameValueCollection.Add("2293_Y", str68);
      string str69 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "2293"), "Not Waived", false) != 0, "X");
      nameValueCollection.Add("2293_N", str69);
      string str70 = JS.GetStr(loan, "230");
      nameValueCollection.Add("230", str70);
      string str71 = JS.GetStr(loan, "232");
      nameValueCollection.Add("232", str71);
      string str72 = JS.GetStr(loan, "L268");
      nameValueCollection.Add("L268", str72);
      string str73 = JS.GetStr(loan, "231");
      nameValueCollection.Add("231", str73);
      string str74 = JS.GetStr(loan, "235");
      nameValueCollection.Add("235", str74);
      string str75 = JS.GetStr(loan, "1628");
      nameValueCollection.Add("1628", str75);
      string str76 = JS.GetStr(loan, "1630");
      nameValueCollection.Add("1630", str76);
      string str77 = JS.GetStr(loan, "660");
      nameValueCollection.Add("660", str77);
      string str78 = JS.GetStr(loan, "253");
      nameValueCollection.Add("253", str78);
      string str79 = JS.GetStr(loan, "661");
      nameValueCollection.Add("661", str79);
      string str80 = JS.GetStr(loan, "254");
      nameValueCollection.Add("254", str80);
      string str81 = JS.GetStr(loan, "NEWHUD.X1707");
      nameValueCollection.Add("NEWHUD_X1707", str81);
      string str82 = JS.GetStr(loan, "HUD24");
      nameValueCollection.Add("HUD24", str82);
      string str83 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "S32DISC.X51"), "does", false) == 0, "X");
      nameValueCollection.Add("S32DISC_X51_Y", str83);
      string str84 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "S32DISC.X51"), "does not", false) == 0, "X");
      nameValueCollection.Add("S32DISC_X51_N", str84);
      string str85 = Jed.BF(Operators.CompareString(JS.GetStr(loan, "NEWHUD.X354"), "Y", false) == 0, JS.GetStr(loan, "NEWHUD.X277"), JS.GetStr(loan, "304"));
      nameValueCollection.Add("304", str85);
      string str86 = JS.GetStr(loan, "2984");
      nameValueCollection.Add("2984", str86);
      string str87 = JS.GetStr(loan, "2985");
      nameValueCollection.Add("2985", str87);
      string str88 = JS.GetStr(loan, "2986");
      nameValueCollection.Add("2986", str88);
      string str89 = JS.GetStr(loan, "2988");
      nameValueCollection.Add("2988", str89);
      string str90 = JS.GetStr(loan, "2301");
      nameValueCollection.Add("2301", str90);
      string str91 = JS.GetStr(loan, "2302");
      nameValueCollection.Add("2302", str91);
      string str92 = JS.GetStr(loan, "2303");
      nameValueCollection.Add("2303", str92);
      string str93 = JS.GetStr(loan, "2987");
      nameValueCollection.Add("2987", str93);
      string str94 = JS.GetStr(loan, "2988");
      nameValueCollection.Add("2988", str94);
      string str95 = JS.GetStr(loan, "2989");
      nameValueCollection.Add("2989", str95);
      string str96 = JS.GetStr(loan, "2990");
      nameValueCollection.Add("2990", str96);
      string str97 = JS.GetStr(loan, "2991");
      nameValueCollection.Add("2991", str97);
      string str98 = JS.GetStr(loan, "2992");
      nameValueCollection.Add("2992", str98);
      string str99 = JS.GetStr(loan, "2995");
      nameValueCollection.Add("2995", str99);
      string str100 = JS.GetStr(loan, "2993");
      nameValueCollection.Add("2993", str100);
      string str101 = JS.GetStr(loan, "2994");
      nameValueCollection.Add("2994", str101);
      return nameValueCollection;
    }
  }
}
