// Decompiled with JetBrains decompiler
// Type: EllieMae.EMLite.Trading.MbsPoolFannieMaeFieldsEditor
// Assembly: TradeManagement, Version=24.3.0.5, Culture=neutral, PublicKeyToken=null
// MVID: 30F9401A-5385-498E-9C5B-D147722AC94C
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\TradeManagement.dll

using EllieMae.EMLite.ClientServer;
using EllieMae.EMLite.Common;
using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.RemotingServices;
using EllieMae.EMLite.UI;
using System;
using System.Collections;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace EllieMae.EMLite.Trading
{
  public class MbsPoolFannieMaeFieldsEditor : MbsPoolFieldsEditorBase
  {
    private GroupContainer gpSetup;
    private Panel panel4;
    private TextBox txtSellerId;
    private Label label13;
    private TextBox txtGuaranteeFee;
    private Label label44;
    private TextBox txtGFeeAfterPayment;
    private BorderPanel borderPanel2;
    private BorderPanel borderPanel1;
    private TextBox txtRemittancePaymentDay;
    private Label label31;
    private TextBox txtStandLookback;
    private Label label1;
    private Label label39;
    private TextBox txtDocCustodianID;
    private TextBox txtFinancialInstNo;
    private Label label2;
    private Label label40;
    private TextBox txtServicerID;
    private TextBox txtNoteCustodian;
    private Label label4;
    private Label label41;
    private TextBox txtInvestorProdPlanID;
    private CheckBox ckboxMultifamily;
    private Label label3;
    private Label label38;
    private TextBox txtInvestorFeatureID;
    private Label label37;
    private Label label5;
    private DatePicker dpInterestOnlyEndDate;
    private TextBox txtDeliveryRegion;
    private Label label6;
    private Label label35;
    private TextBox txtBaseGuarantyFee;
    private TextBox txtContractType;
    private ComboBox cmbLoanLossParty;
    private Label label36;
    private ComboBox cmbREOMarketingParty;
    private TextBox txtForecloseRiskCode;
    private Label label7;
    private Label label33;
    private Label label8;
    private TextBox txtPassThruRate;
    private Label lblInvestorRemittanceDay;
    private Label label34;
    private TextBox txtInvestorRemittanceDay;
    private TextBox txtPlanNumber;
    private Label label12;
    private TextBox txtContactNo;
    private Label label43;
    private Label label11;
    private ComboBox cmbInvestorRemittanceType;
    private Label label10;
    private CheckBox ckboxGuarantyFeeAddOn;
    private TextBox txtOwnership;
    private Label label42;
    private DatePicker dtIssueDate;
    private TextBox txtSubmissionType;
    private Label label18;
    private Label label32;
    private TextBox txtMinimumAccrualRate;
    private TextBox txtCommitmentPeriod;
    private Label label17;
    private Label label29;
    private TextBox txtSecurityIssueRate;
    private TextBox txtPayeeCode;
    private ComboBox cmbStructureType;
    private Label label30;
    private ComboBox cmbAccrualRateType;
    private Label label28;
    private Label label16;
    private DatePicker dpSecurityTradeBookDate;
    private Label label15;
    private Label label27;
    private Label label14;
    private Label label26;
    private TextBox txtMaximumAccrualRate;
    private TextBox txtServiceFee;
    private Label label9;
    private Label label25;
    private TextBox txtMarginRate;
    private CheckBox ckboxBalloonIndicator;
    private TextBox txtRateRounding;
    private Label label24;
    private ComboBox cmbRateRoundingType;
    private CheckBox ckboxAssumabilityIndicator;
    private Label label19;
    private Label label23;
    private Label label20;
    private TextBox txtIndexLeadDays;
    private Label label21;
    private Label label22;
    private CheckBox ckboxInterestOnly;
    private TextBox txtMaxBU;
    private Label label46;
    private TextBox txtMinServicingFee;
    private Label label45;

    public MbsPoolFannieMaeFieldsEditor(
      PipelineInfo[] currentInTradeLoans,
      MbsPoolMortgageType type)
      : base(currentInTradeLoans)
    {
      this.InitializeComponent();
      TextBoxFormatter.Attach(this.txtServicerID, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtInvestorProdPlanID, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtInvestorFeatureID, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtBaseGuarantyFee, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtGFeeAfterPayment, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtGuaranteeFee, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtOwnership, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtSecurityIssueRate, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtMinimumAccrualRate, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtMaximumAccrualRate, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtMarginRate, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtRateRounding, TextBoxContentRule.NonNegativeDecimal, "##0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtIndexLeadDays, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtServiceFee, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtPassThruRate, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtSellerId, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtMinServicingFee, TextBoxContentRule.NonNegativeDecimal, "#0.00;;\"\"");
      TextBoxFormatter.Attach(this.txtMaxBU, TextBoxContentRule.NonNegativeDecimal, "#0.00;;\"\"");
      this.gpSetup.Text = "Fannie Mae";
      if (type == MbsPoolMortgageType.FannieMaePE)
        this.gpSetup.Text = "Fannie Mae PE";
      this.LoadConfigurableFieldOptions();
    }

    protected override void LoadConfigurableFieldOptions()
    {
      this.cmbLoanLossParty.Items.Clear();
      ArrayList secondaryFields1 = Session.ConfigurationManager.GetSecondaryFields(SecondaryFieldTypes.LoanDefaultLossParty);
      if (secondaryFields1 != null)
        this.cmbLoanLossParty.Items.AddRange(secondaryFields1.ToArray());
      this.cmbREOMarketingParty.Items.Clear();
      ArrayList secondaryFields2 = Session.ConfigurationManager.GetSecondaryFields(SecondaryFieldTypes.REOMarketingParty);
      if (secondaryFields2 != null)
        this.cmbREOMarketingParty.Items.AddRange(secondaryFields2.ToArray());
      this.cmbStructureType.Items.Clear();
      ArrayList secondaryFields3 = Session.ConfigurationManager.GetSecondaryFields(SecondaryFieldTypes.StructureType);
      if (secondaryFields3 != null)
        this.cmbStructureType.Items.AddRange(secondaryFields3.ToArray());
      this.cmbAccrualRateType.Items.Clear();
      ArrayList secondaryFields4 = Session.ConfigurationManager.GetSecondaryFields(SecondaryFieldTypes.AccrualRateStructureType);
      if (secondaryFields4 != null)
        this.cmbAccrualRateType.Items.AddRange(secondaryFields4.ToArray());
      this.cmbRateRoundingType.Items.Clear();
      ArrayList secondaryFields5 = Session.ConfigurationManager.GetSecondaryFields(SecondaryFieldTypes.IntRateRoundingType);
      if (secondaryFields5 != null)
        this.cmbRateRoundingType.Items.AddRange(secondaryFields5.ToArray());
      this.cmbInvestorRemittanceType.Items.Clear();
      ArrayList secondaryFields6 = Session.ConfigurationManager.GetSecondaryFields(SecondaryFieldTypes.InvestorRemittanceType);
      if (secondaryFields6 == null)
        return;
      this.cmbInvestorRemittanceType.Items.AddRange(secondaryFields6.ToArray());
    }

    protected override void loadTradeData()
    {
      this.txtDocCustodianID.Text = this.PoolTrade.DocCustodianID;
      this.txtServicerID.Text = this.PoolTrade.ServicerID;
      this.txtInvestorProdPlanID.Text = this.PoolTrade.InvestorProductPlanID;
      this.txtInvestorFeatureID.Text = this.PoolTrade.InvestorFeatureID;
      this.cmbLoanLossParty.Text = this.PoolTrade.LoanDefaultLossParty;
      this.cmbREOMarketingParty.Text = this.PoolTrade.ReoMarketingParty;
      this.txtBaseGuarantyFee.Text = this.PoolTrade.BaseGuarantyFee.ToString("#0.0000;;\"\"");
      this.txtGFeeAfterPayment.Text = this.PoolTrade.GFeeAfterAltPaymentMethod.ToString("#0.0000;;\"\"");
      this.txtGuaranteeFee.Text = this.PoolTrade.GuaranteeFee.ToString("#0.0000;;\"\"");
      string str1 = this.PoolTrade.InvestorRemittanceDay.ToString("00;;\"\"");
      if (str1.Length > 0)
        str1 = "---" + str1;
      this.txtInvestorRemittanceDay.Text = str1;
      this.txtContactNo.Text = this.PoolTrade.ContractNum;
      this.dtIssueDate.Value = this.PoolTrade.IssueDate;
      this.txtOwnership.Text = this.PoolTrade.OwnershipPercent.ToString("##0;;\"\"");
      this.cmbStructureType.Text = this.PoolTrade.StructureType;
      this.cmbAccrualRateType.Text = this.PoolTrade.AccrualRateStructureType;
      this.txtSecurityIssueRate.Text = this.PoolTrade.SecurityIssueDateIntRate.ToString("#0.0000;;\"\"");
      this.txtMinimumAccrualRate.Text = this.PoolTrade.MinAccuralRate.ToString("#0.0000;;\"\"");
      this.txtMaximumAccrualRate.Text = this.PoolTrade.MaxAccuralRate.ToString("#0.0000;;\"\"");
      this.txtMarginRate.Text = this.PoolTrade.MarginRate.ToString("#0.0000;;\"\"");
      this.cmbRateRoundingType.Text = this.PoolTrade.IntRateRoundingType;
      this.txtRateRounding.Text = this.PoolTrade.IntRateRoundingPercent.ToString("##0.0000;;\"\"");
      this.ckboxInterestOnly.Checked = this.PoolTrade.IsInterestOnly;
      this.txtIndexLeadDays.Text = this.PoolTrade.IntPaymentAdjIndexLeadDays.ToString("##0;;\"\"");
      this.ckboxAssumabilityIndicator.Checked = this.PoolTrade.IsAssumability;
      this.ckboxBalloonIndicator.Checked = this.PoolTrade.IsBalloon;
      this.txtServiceFee.Text = this.PoolTrade.FixedServicingFeePercent.ToString("#0.0000;;\"\"");
      string str2 = this.PoolTrade.ScheduledRemittancePaymentDay.ToString("00;;\"\"");
      if (str2.Length > 0)
        str2 = "---" + str2;
      this.txtRemittancePaymentDay.Text = str2;
      this.dpSecurityTradeBookDate.Value = this.PoolTrade.SecurityTradeBookEntryDate;
      this.txtPayeeCode.Text = this.PoolTrade.PayeeCode;
      this.txtCommitmentPeriod.Text = this.PoolTrade.CommitmentPeriod;
      this.txtSubmissionType.Text = this.PoolTrade.SubmissionType;
      this.txtPlanNumber.Text = this.PoolTrade.PlanNum;
      this.txtPassThruRate.Text = this.PoolTrade.PassThruRate.ToString("#0.0000;;\"\"");
      this.txtForecloseRiskCode.Text = this.PoolTrade.ForecloseRiskCode;
      this.txtContractType.Text = this.PoolTrade.ContractType;
      this.txtDeliveryRegion.Text = this.PoolTrade.DeliveryRegion;
      this.dpInterestOnlyEndDate.Value = this.PoolTrade.InterestOnlyEndDate;
      this.ckboxMultifamily.Checked = this.PoolTrade.IsMultiFamily;
      this.txtNoteCustodian.Text = this.PoolTrade.NoteCustodian;
      this.txtFinancialInstNo.Text = this.PoolTrade.FinancialInstNum;
      this.txtStandLookback.Text = this.PoolTrade.StandardLookback;
      this.ckboxGuarantyFeeAddOn.Checked = this.PoolTrade.IsGuarantyFeeAddOn;
      this.cmbInvestorRemittanceType.Text = this.PoolTrade.InvestorRemittanceType;
      this.txtSellerId.Text = this.PoolTrade.SellerId;
      this.txtMinServicingFee.Text = this.PoolTrade.MinServicingFee.ToString("#0.00;;\"\"");
      this.txtMaxBU.Text = this.PoolTrade.MaxBU.ToString("#0.00;;\"\"");
    }

    protected override void setReadOnly()
    {
      this.txtDocCustodianID.ReadOnly = this.readOnly;
      this.txtDocCustodianID.ReadOnly = this.readOnly;
      this.txtServicerID.ReadOnly = this.readOnly;
      this.txtInvestorProdPlanID.ReadOnly = this.readOnly;
      this.txtInvestorFeatureID.ReadOnly = this.readOnly;
      this.cmbLoanLossParty.Enabled = !this.readOnly;
      this.cmbREOMarketingParty.Enabled = !this.readOnly;
      this.txtBaseGuarantyFee.ReadOnly = this.readOnly;
      this.txtGFeeAfterPayment.ReadOnly = this.readOnly;
      this.txtGuaranteeFee.ReadOnly = this.readOnly;
      this.txtInvestorRemittanceDay.ReadOnly = this.readOnly;
      this.txtContactNo.ReadOnly = this.readOnly;
      this.dtIssueDate.ReadOnly = this.readOnly;
      this.txtOwnership.ReadOnly = this.readOnly;
      this.cmbStructureType.Enabled = !this.readOnly;
      this.cmbAccrualRateType.Enabled = !this.readOnly;
      this.txtSecurityIssueRate.ReadOnly = this.readOnly;
      this.txtMinimumAccrualRate.ReadOnly = this.readOnly;
      this.txtMaximumAccrualRate.ReadOnly = this.readOnly;
      this.txtMarginRate.ReadOnly = this.readOnly;
      this.cmbRateRoundingType.Enabled = !this.readOnly;
      this.txtRateRounding.ReadOnly = this.readOnly;
      this.ckboxInterestOnly.Enabled = !this.readOnly;
      this.txtIndexLeadDays.ReadOnly = this.readOnly;
      this.ckboxAssumabilityIndicator.Enabled = !this.readOnly;
      this.ckboxBalloonIndicator.Enabled = !this.readOnly;
      this.txtServiceFee.ReadOnly = this.readOnly;
      this.txtRemittancePaymentDay.ReadOnly = this.readOnly;
      this.dpSecurityTradeBookDate.ReadOnly = this.readOnly;
      this.txtPayeeCode.ReadOnly = this.readOnly;
      this.txtCommitmentPeriod.ReadOnly = this.readOnly;
      this.txtSubmissionType.ReadOnly = this.readOnly;
      this.txtPlanNumber.ReadOnly = this.readOnly;
      this.txtPassThruRate.ReadOnly = this.readOnly;
      this.txtForecloseRiskCode.ReadOnly = this.readOnly;
      this.txtContractType.ReadOnly = this.readOnly;
      this.txtDeliveryRegion.ReadOnly = this.readOnly;
      this.dpInterestOnlyEndDate.ReadOnly = this.readOnly;
      this.ckboxMultifamily.Enabled = !this.readOnly;
      this.txtNoteCustodian.ReadOnly = this.readOnly;
      this.txtFinancialInstNo.ReadOnly = this.readOnly;
      this.txtStandLookback.ReadOnly = this.readOnly;
      this.ckboxGuarantyFeeAddOn.Enabled = !this.readOnly;
      this.cmbInvestorRemittanceType.Enabled = !this.readOnly;
      this.txtSellerId.Enabled = !this.readOnly;
      this.txtMinServicingFee.Enabled = !this.readOnly;
      this.txtMaxBU.Enabled = !this.readOnly;
    }

    protected override bool queryCommitChanges(bool popupMsg)
    {
      return popupMsg ? this.ValidateEditor((object) this.txtInvestorRemittanceDay, ValidateMode.Day, "Valid entry for \"Investor Remittance Day\" is a number 1-31.", false) && this.ValidateEditor((object) this.txtRemittancePaymentDay, ValidateMode.Day, "Valid entry for \"Scheduled Remittance Payment Day\" is a number 1-31.", false) && this.ValidateEditor((object) this.txtBaseGuarantyFee, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtGFeeAfterPayment, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtGuaranteeFee, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtSecurityIssueRate, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtMinimumAccrualRate, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtMaximumAccrualRate, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtMarginRate, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtRateRounding, ValidateMode.Percent34, "Valid enter is a decimal less than 1000", false) && this.ValidateEditor((object) this.txtServiceFee, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtPassThruRate, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtMinServicingFee, ValidateMode.Percent34, "Valid enter is a decimal less than 1000", false) && this.ValidateEditor((object) this.txtMaxBU, ValidateMode.Percent34, "Valid enter is a decimal less than 1000", false) : this.ValidateEditor((object) this.txtInvestorRemittanceDay, ValidateMode.Day, "Valid entry for \"Investor Remittance Day\" is a number 1-31.", false) && this.ValidateEditor((object) this.txtRemittancePaymentDay, ValidateMode.Day, string.Empty, false) && this.ValidateEditor((object) this.txtBaseGuarantyFee, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtGFeeAfterPayment, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtGuaranteeFee, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtSecurityIssueRate, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtMinimumAccrualRate, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtMaximumAccrualRate, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtMarginRate, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtRateRounding, ValidateMode.Percent34, string.Empty, false) && this.ValidateEditor((object) this.txtServiceFee, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtPassThruRate, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtMinServicingFee, ValidateMode.Percent34, "Valid enter is a decimal less than 1000", false) && this.ValidateEditor((object) this.txtMaxBU, ValidateMode.Percent34, "Valid enter is a decimal less than 1000", false);
    }

    protected override void commitChanges()
    {
      this.PoolTrade.DocCustodianID = this.txtDocCustodianID.Text;
      this.PoolTrade.ServicerID = this.txtServicerID.Text;
      this.PoolTrade.InvestorProductPlanID = this.txtInvestorProdPlanID.Text;
      this.PoolTrade.InvestorFeatureID = this.txtInvestorFeatureID.Text;
      this.PoolTrade.LoanDefaultLossParty = this.cmbLoanLossParty.SelectedItem != null ? this.cmbLoanLossParty.SelectedItem.ToString() : string.Empty;
      this.PoolTrade.ReoMarketingParty = this.cmbREOMarketingParty.SelectedItem != null ? this.cmbREOMarketingParty.SelectedItem.ToString() : string.Empty;
      this.PoolTrade.BaseGuarantyFee = Utils.ParseDecimal((object) this.txtBaseGuarantyFee.Text);
      this.PoolTrade.GFeeAfterAltPaymentMethod = Utils.ParseDecimal((object) this.txtGFeeAfterPayment.Text);
      this.PoolTrade.GuaranteeFee = Utils.ParseDecimal((object) this.txtGuaranteeFee.Text);
      this.PoolTrade.InvestorRemittanceDay = Utils.ParseInt((object) this.txtInvestorRemittanceDay.Text.Replace("---", ""), 0);
      this.PoolTrade.ContractNum = this.txtContactNo.Text;
      this.PoolTrade.IssueDate = this.dtIssueDate.Value;
      this.PoolTrade.OwnershipPercent = (Decimal) Utils.ParseInt((object) this.txtOwnership.Text, 0);
      this.PoolTrade.StructureType = this.cmbStructureType.SelectedItem != null ? this.cmbStructureType.SelectedItem.ToString() : string.Empty;
      this.PoolTrade.AccrualRateStructureType = this.cmbAccrualRateType.SelectedItem != null ? this.cmbAccrualRateType.SelectedItem.ToString() : string.Empty;
      this.PoolTrade.SecurityIssueDateIntRate = Utils.ParseDecimal((object) this.txtSecurityIssueRate.Text);
      this.PoolTrade.MinAccuralRate = Utils.ParseDecimal((object) this.txtMinimumAccrualRate.Text);
      this.PoolTrade.MaxAccuralRate = Utils.ParseDecimal((object) this.txtMaximumAccrualRate.Text);
      this.PoolTrade.MarginRate = Utils.ParseDecimal((object) this.txtMarginRate.Text);
      this.PoolTrade.IntRateRoundingType = this.cmbRateRoundingType.SelectedItem != null ? this.cmbRateRoundingType.SelectedItem.ToString() : string.Empty;
      this.PoolTrade.IntRateRoundingPercent = Utils.ParseDecimal((object) this.txtRateRounding.Text);
      this.PoolTrade.IsInterestOnly = this.ckboxInterestOnly.Checked;
      this.PoolTrade.IntPaymentAdjIndexLeadDays = Utils.ParseInt((object) this.txtIndexLeadDays.Text, 0);
      this.PoolTrade.IsAssumability = this.ckboxAssumabilityIndicator.Checked;
      this.PoolTrade.IsBalloon = this.ckboxBalloonIndicator.Checked;
      this.PoolTrade.FixedServicingFeePercent = Utils.ParseDecimal((object) this.txtServiceFee.Text);
      this.PoolTrade.ScheduledRemittancePaymentDay = Utils.ParseInt((object) this.txtRemittancePaymentDay.Text.Replace("---", ""), 0);
      this.PoolTrade.SecurityTradeBookEntryDate = Utils.ParseDate((object) this.dpSecurityTradeBookDate.Text);
      this.PoolTrade.PayeeCode = this.txtPayeeCode.Text;
      this.PoolTrade.CommitmentPeriod = this.txtCommitmentPeriod.Text;
      this.PoolTrade.SubmissionType = this.txtSubmissionType.Text;
      this.PoolTrade.PlanNum = this.txtPlanNumber.Text;
      this.PoolTrade.PassThruRate = Utils.ParseDecimal((object) this.txtPassThruRate.Text);
      this.PoolTrade.ForecloseRiskCode = this.txtForecloseRiskCode.Text;
      this.PoolTrade.ContractType = this.txtContractType.Text;
      this.PoolTrade.DeliveryRegion = this.txtDeliveryRegion.Text;
      this.PoolTrade.InterestOnlyEndDate = Utils.ParseDate((object) this.dpInterestOnlyEndDate.Text);
      this.PoolTrade.IsMultiFamily = this.ckboxMultifamily.Checked;
      this.PoolTrade.NoteCustodian = this.txtNoteCustodian.Text;
      this.PoolTrade.FinancialInstNum = this.txtFinancialInstNo.Text;
      this.PoolTrade.StandardLookback = this.txtStandLookback.Text;
      this.PoolTrade.IsGuarantyFeeAddOn = this.ckboxGuarantyFeeAddOn.Checked;
      this.PoolTrade.InvestorRemittanceType = this.cmbInvestorRemittanceType.SelectedItem != null ? this.cmbInvestorRemittanceType.SelectedItem.ToString() : string.Empty;
      this.PoolTrade.SellerId = this.txtSellerId.Text;
      this.PoolTrade.MinServicingFee = Utils.ParseDecimal((object) this.txtMinServicingFee.Text);
      this.PoolTrade.MaxBU = Utils.ParseDecimal((object) this.txtMaxBU.Text);
    }

    private new void OnFieldValueChanged(object sender, EventArgs e)
    {
      base.OnFieldValueChanged(sender, e);
    }

    private new void OnLoanUpdatableFieldValueChanged(object sender, EventArgs e)
    {
      base.OnLoanUpdatableFieldValueChanged(sender, e);
    }

    private void txtInvestorRemittanceDay_Leave(object sender, EventArgs e)
    {
      if (!this.modified)
        return;
      this.ValidateEditor((object) (TextBox) sender, ValidateMode.Day, "Valid entry for \"Investor Remittance Day\" is a number 1-31.");
    }

    private void txtRemittancePaymentDay_Leave(object sender, EventArgs e)
    {
      if (!this.modified)
        return;
      this.ValidateEditor((object) (TextBox) sender, ValidateMode.Day, "Valid entry for \"Scheduled Remittance Payment Day\" is a number 1-31.");
    }

    private void txt_Percent24_Leave(object sender, EventArgs e)
    {
      if (!this.modified)
        return;
      this.ValidateEditor((object) (TextBox) sender, ValidateMode.Percent24, "Valid enter is a decimal less than 100");
    }

    private void txt_Percent34_Leave(object sender, EventArgs e)
    {
      if (!this.modified)
        return;
      this.ValidateEditor((object) (TextBox) sender, ValidateMode.Percent34, "Valid enter is a decimal less than 1000");
    }

    private void InitializeComponent()
    {
      this.gpSetup = new GroupContainer();
      this.panel4 = new Panel();
      this.txtMaxBU = new TextBox();
      this.label46 = new Label();
      this.txtMinServicingFee = new TextBox();
      this.label45 = new Label();
      this.txtSellerId = new TextBox();
      this.label13 = new Label();
      this.txtGuaranteeFee = new TextBox();
      this.label44 = new Label();
      this.txtGFeeAfterPayment = new TextBox();
      this.borderPanel2 = new BorderPanel();
      this.borderPanel1 = new BorderPanel();
      this.txtRemittancePaymentDay = new TextBox();
      this.label31 = new Label();
      this.txtStandLookback = new TextBox();
      this.label1 = new Label();
      this.label39 = new Label();
      this.txtDocCustodianID = new TextBox();
      this.txtFinancialInstNo = new TextBox();
      this.label2 = new Label();
      this.label40 = new Label();
      this.txtServicerID = new TextBox();
      this.txtNoteCustodian = new TextBox();
      this.label4 = new Label();
      this.label41 = new Label();
      this.txtInvestorProdPlanID = new TextBox();
      this.ckboxMultifamily = new CheckBox();
      this.label3 = new Label();
      this.label38 = new Label();
      this.txtInvestorFeatureID = new TextBox();
      this.label37 = new Label();
      this.label5 = new Label();
      this.dpInterestOnlyEndDate = new DatePicker();
      this.txtDeliveryRegion = new TextBox();
      this.label6 = new Label();
      this.label35 = new Label();
      this.txtBaseGuarantyFee = new TextBox();
      this.txtContractType = new TextBox();
      this.cmbLoanLossParty = new ComboBox();
      this.label36 = new Label();
      this.cmbREOMarketingParty = new ComboBox();
      this.txtForecloseRiskCode = new TextBox();
      this.label7 = new Label();
      this.label33 = new Label();
      this.label8 = new Label();
      this.txtPassThruRate = new TextBox();
      this.lblInvestorRemittanceDay = new Label();
      this.label34 = new Label();
      this.txtInvestorRemittanceDay = new TextBox();
      this.txtPlanNumber = new TextBox();
      this.label12 = new Label();
      this.txtContactNo = new TextBox();
      this.label43 = new Label();
      this.label11 = new Label();
      this.cmbInvestorRemittanceType = new ComboBox();
      this.label10 = new Label();
      this.ckboxGuarantyFeeAddOn = new CheckBox();
      this.txtOwnership = new TextBox();
      this.label42 = new Label();
      this.dtIssueDate = new DatePicker();
      this.txtSubmissionType = new TextBox();
      this.label18 = new Label();
      this.label32 = new Label();
      this.txtMinimumAccrualRate = new TextBox();
      this.txtCommitmentPeriod = new TextBox();
      this.label17 = new Label();
      this.label29 = new Label();
      this.txtSecurityIssueRate = new TextBox();
      this.txtPayeeCode = new TextBox();
      this.cmbStructureType = new ComboBox();
      this.label30 = new Label();
      this.cmbAccrualRateType = new ComboBox();
      this.label28 = new Label();
      this.label16 = new Label();
      this.dpSecurityTradeBookDate = new DatePicker();
      this.label15 = new Label();
      this.label27 = new Label();
      this.label14 = new Label();
      this.label26 = new Label();
      this.txtMaximumAccrualRate = new TextBox();
      this.txtServiceFee = new TextBox();
      this.label9 = new Label();
      this.label25 = new Label();
      this.txtMarginRate = new TextBox();
      this.ckboxBalloonIndicator = new CheckBox();
      this.txtRateRounding = new TextBox();
      this.label24 = new Label();
      this.cmbRateRoundingType = new ComboBox();
      this.ckboxAssumabilityIndicator = new CheckBox();
      this.label19 = new Label();
      this.label23 = new Label();
      this.label20 = new Label();
      this.txtIndexLeadDays = new TextBox();
      this.label21 = new Label();
      this.label22 = new Label();
      this.ckboxInterestOnly = new CheckBox();
      this.gpSetup.SuspendLayout();
      this.panel4.SuspendLayout();
      this.SuspendLayout();
      this.gpSetup.AutoScroll = true;
      this.gpSetup.Controls.Add((Control) this.panel4);
      this.gpSetup.Font = new Font("Arial Narrow", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.gpSetup.HeaderForeColor = SystemColors.ControlText;
      this.gpSetup.Location = new Point(0, 0);
      this.gpSetup.Name = "gpSetup";
      this.gpSetup.Size = new Size(983, 408);
      this.gpSetup.TabIndex = 0;
      this.panel4.AutoScroll = true;
      this.panel4.BackColor = Color.WhiteSmoke;
      this.panel4.Controls.Add((Control) this.txtMaxBU);
      this.panel4.Controls.Add((Control) this.label46);
      this.panel4.Controls.Add((Control) this.txtMinServicingFee);
      this.panel4.Controls.Add((Control) this.label45);
      this.panel4.Controls.Add((Control) this.txtSellerId);
      this.panel4.Controls.Add((Control) this.label13);
      this.panel4.Controls.Add((Control) this.txtGuaranteeFee);
      this.panel4.Controls.Add((Control) this.label44);
      this.panel4.Controls.Add((Control) this.txtGFeeAfterPayment);
      this.panel4.Controls.Add((Control) this.borderPanel2);
      this.panel4.Controls.Add((Control) this.borderPanel1);
      this.panel4.Controls.Add((Control) this.txtRemittancePaymentDay);
      this.panel4.Controls.Add((Control) this.label31);
      this.panel4.Controls.Add((Control) this.txtStandLookback);
      this.panel4.Controls.Add((Control) this.label1);
      this.panel4.Controls.Add((Control) this.label39);
      this.panel4.Controls.Add((Control) this.txtDocCustodianID);
      this.panel4.Controls.Add((Control) this.txtFinancialInstNo);
      this.panel4.Controls.Add((Control) this.label2);
      this.panel4.Controls.Add((Control) this.label40);
      this.panel4.Controls.Add((Control) this.txtServicerID);
      this.panel4.Controls.Add((Control) this.txtNoteCustodian);
      this.panel4.Controls.Add((Control) this.label4);
      this.panel4.Controls.Add((Control) this.label41);
      this.panel4.Controls.Add((Control) this.txtInvestorProdPlanID);
      this.panel4.Controls.Add((Control) this.ckboxMultifamily);
      this.panel4.Controls.Add((Control) this.label3);
      this.panel4.Controls.Add((Control) this.label38);
      this.panel4.Controls.Add((Control) this.txtInvestorFeatureID);
      this.panel4.Controls.Add((Control) this.label37);
      this.panel4.Controls.Add((Control) this.label5);
      this.panel4.Controls.Add((Control) this.dpInterestOnlyEndDate);
      this.panel4.Controls.Add((Control) this.txtDeliveryRegion);
      this.panel4.Controls.Add((Control) this.label6);
      this.panel4.Controls.Add((Control) this.label35);
      this.panel4.Controls.Add((Control) this.txtBaseGuarantyFee);
      this.panel4.Controls.Add((Control) this.txtContractType);
      this.panel4.Controls.Add((Control) this.cmbLoanLossParty);
      this.panel4.Controls.Add((Control) this.label36);
      this.panel4.Controls.Add((Control) this.cmbREOMarketingParty);
      this.panel4.Controls.Add((Control) this.txtForecloseRiskCode);
      this.panel4.Controls.Add((Control) this.label7);
      this.panel4.Controls.Add((Control) this.label33);
      this.panel4.Controls.Add((Control) this.label8);
      this.panel4.Controls.Add((Control) this.txtPassThruRate);
      this.panel4.Controls.Add((Control) this.lblInvestorRemittanceDay);
      this.panel4.Controls.Add((Control) this.label34);
      this.panel4.Controls.Add((Control) this.txtInvestorRemittanceDay);
      this.panel4.Controls.Add((Control) this.txtPlanNumber);
      this.panel4.Controls.Add((Control) this.label12);
      this.panel4.Controls.Add((Control) this.txtContactNo);
      this.panel4.Controls.Add((Control) this.label43);
      this.panel4.Controls.Add((Control) this.label11);
      this.panel4.Controls.Add((Control) this.cmbInvestorRemittanceType);
      this.panel4.Controls.Add((Control) this.label10);
      this.panel4.Controls.Add((Control) this.ckboxGuarantyFeeAddOn);
      this.panel4.Controls.Add((Control) this.txtOwnership);
      this.panel4.Controls.Add((Control) this.label42);
      this.panel4.Controls.Add((Control) this.dtIssueDate);
      this.panel4.Controls.Add((Control) this.txtSubmissionType);
      this.panel4.Controls.Add((Control) this.label18);
      this.panel4.Controls.Add((Control) this.label32);
      this.panel4.Controls.Add((Control) this.txtMinimumAccrualRate);
      this.panel4.Controls.Add((Control) this.txtCommitmentPeriod);
      this.panel4.Controls.Add((Control) this.label17);
      this.panel4.Controls.Add((Control) this.label29);
      this.panel4.Controls.Add((Control) this.txtSecurityIssueRate);
      this.panel4.Controls.Add((Control) this.txtPayeeCode);
      this.panel4.Controls.Add((Control) this.cmbStructureType);
      this.panel4.Controls.Add((Control) this.label30);
      this.panel4.Controls.Add((Control) this.cmbAccrualRateType);
      this.panel4.Controls.Add((Control) this.label28);
      this.panel4.Controls.Add((Control) this.label16);
      this.panel4.Controls.Add((Control) this.dpSecurityTradeBookDate);
      this.panel4.Controls.Add((Control) this.label15);
      this.panel4.Controls.Add((Control) this.label27);
      this.panel4.Controls.Add((Control) this.label14);
      this.panel4.Controls.Add((Control) this.label26);
      this.panel4.Controls.Add((Control) this.txtMaximumAccrualRate);
      this.panel4.Controls.Add((Control) this.txtServiceFee);
      this.panel4.Controls.Add((Control) this.label9);
      this.panel4.Controls.Add((Control) this.label25);
      this.panel4.Controls.Add((Control) this.txtMarginRate);
      this.panel4.Controls.Add((Control) this.ckboxBalloonIndicator);
      this.panel4.Controls.Add((Control) this.txtRateRounding);
      this.panel4.Controls.Add((Control) this.label24);
      this.panel4.Controls.Add((Control) this.cmbRateRoundingType);
      this.panel4.Controls.Add((Control) this.ckboxAssumabilityIndicator);
      this.panel4.Controls.Add((Control) this.label19);
      this.panel4.Controls.Add((Control) this.label23);
      this.panel4.Controls.Add((Control) this.label20);
      this.panel4.Controls.Add((Control) this.txtIndexLeadDays);
      this.panel4.Controls.Add((Control) this.label21);
      this.panel4.Controls.Add((Control) this.label22);
      this.panel4.Controls.Add((Control) this.ckboxInterestOnly);
      this.panel4.Location = new Point(1, 26);
      this.panel4.Name = "panel4";
      this.panel4.Size = new Size(980, 381);
      this.panel4.TabIndex = 25;
      this.txtMaxBU.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtMaxBU.Location = new Point(825, 329);
      this.txtMaxBU.MaxLength = 6;
      this.txtMaxBU.Name = "txtMaxBU";
      this.txtMaxBU.Size = new Size(138, 20);
      this.txtMaxBU.TabIndex = 394;
      this.txtMaxBU.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtMaxBU.Leave += new EventHandler(this.txt_Percent34_Leave);
      this.label46.AutoSize = true;
      this.label46.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label46.Location = new Point(677, 332);
      this.label46.Name = "label46";
      this.label46.Size = new Size(65, 14);
      this.label46.TabIndex = 393;
      this.label46.Text = "Max Buy Up";
      this.txtMinServicingFee.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtMinServicingFee.Location = new Point(825, 308);
      this.txtMinServicingFee.MaxLength = 6;
      this.txtMinServicingFee.Name = "txtMinServicingFee";
      this.txtMinServicingFee.Size = new Size(138, 20);
      this.txtMinServicingFee.TabIndex = 392;
      this.txtMinServicingFee.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtMinServicingFee.Leave += new EventHandler(this.txt_Percent34_Leave);
      this.label45.AutoSize = true;
      this.label45.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label45.Location = new Point(677, 310);
      this.label45.Name = "label45";
      this.label45.Size = new Size(92, 14);
      this.label45.TabIndex = 391;
      this.label45.Text = "Min Servicing Fee";
      this.txtSellerId.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtSellerId.Location = new Point(825, 352);
      this.txtSellerId.MaxLength = 9;
      this.txtSellerId.Name = "txtSellerId";
      this.txtSellerId.Size = new Size(138, 20);
      this.txtSellerId.TabIndex = 396;
      this.label13.AutoSize = true;
      this.label13.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label13.Location = new Point(677, 355);
      this.label13.Name = "label13";
      this.label13.Size = new Size(46, 14);
      this.label13.TabIndex = 381;
      this.label13.Text = "Seller ID";
      this.txtGuaranteeFee.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtGuaranteeFee.Location = new Point(170, 191);
      this.txtGuaranteeFee.MaxLength = 7;
      this.txtGuaranteeFee.Name = "txtGuaranteeFee";
      this.txtGuaranteeFee.Size = new Size(138, 20);
      this.txtGuaranteeFee.TabIndex = 310;
      this.txtGuaranteeFee.TextAlign = HorizontalAlignment.Right;
      this.txtGuaranteeFee.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtGuaranteeFee.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.label44.AutoSize = true;
      this.label44.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label44.Location = new Point(6, 197);
      this.label44.Name = "label44";
      this.label44.Size = new Size(73, 14);
      this.label44.TabIndex = 380;
      this.label44.Text = "Guaranty Fee";
      this.txtGFeeAfterPayment.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtGFeeAfterPayment.Location = new Point(170, 169);
      this.txtGFeeAfterPayment.MaxLength = 7;
      this.txtGFeeAfterPayment.Name = "txtGFeeAfterPayment";
      this.txtGFeeAfterPayment.Size = new Size(138, 20);
      this.txtGFeeAfterPayment.TabIndex = 309;
      this.txtGFeeAfterPayment.TextAlign = HorizontalAlignment.Right;
      this.txtGFeeAfterPayment.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtGFeeAfterPayment.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.borderPanel2.AutoSizeMode = AutoSizeMode.GrowAndShrink;
      this.borderPanel2.Location = new Point(666, 0);
      this.borderPanel2.Name = "borderPanel2";
      this.borderPanel2.Size = new Size(1, 380);
      this.borderPanel2.TabIndex = 377;
      this.borderPanel1.AutoSizeMode = AutoSizeMode.GrowAndShrink;
      this.borderPanel1.Location = new Point(325, -1);
      this.borderPanel1.Name = "borderPanel1";
      this.borderPanel1.Size = new Size(1, 380);
      this.borderPanel1.TabIndex = 376;
      this.txtRemittancePaymentDay.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtRemittancePaymentDay.Location = new Point(513, 261);
      this.txtRemittancePaymentDay.MaxLength = 5;
      this.txtRemittancePaymentDay.Name = "txtRemittancePaymentDay";
      this.txtRemittancePaymentDay.Size = new Size(138, 20);
      this.txtRemittancePaymentDay.TabIndex = 334;
      this.txtRemittancePaymentDay.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtRemittancePaymentDay.Leave += new EventHandler(this.txtRemittancePaymentDay_Leave);
      this.label31.AutoSize = true;
      this.label31.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label31.Location = new Point(677, 35);
      this.label31.Name = "label31";
      this.label31.Size = new Size(67, 14);
      this.label31.TabIndex = 359;
      this.label31.Text = "Plan Number";
      this.txtStandLookback.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtStandLookback.Location = new Point(825, 236);
      this.txtStandLookback.MaxLength = 8;
      this.txtStandLookback.Name = "txtStandLookback";
      this.txtStandLookback.Size = new Size(138, 20);
      this.txtStandLookback.TabIndex = 373;
      this.txtStandLookback.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.label1.AutoSize = true;
      this.label1.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label1.Location = new Point(6, 12);
      this.label1.Name = "label1";
      this.label1.Size = new Size(118, 14);
      this.label1.TabIndex = 291;
      this.label1.Text = "Document Custodian ID";
      this.label39.AutoSize = true;
      this.label39.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label39.Location = new Point(677, 239);
      this.label39.Name = "label39";
      this.label39.Size = new Size(100, 14);
      this.label39.TabIndex = 372;
      this.label39.Text = "Standard Lookback";
      this.txtDocCustodianID.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtDocCustodianID.Location = new Point(170, 10);
      this.txtDocCustodianID.MaxLength = 11;
      this.txtDocCustodianID.Name = "txtDocCustodianID";
      this.txtDocCustodianID.Size = new Size(138, 20);
      this.txtDocCustodianID.TabIndex = 292;
      this.txtDocCustodianID.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtFinancialInstNo.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtFinancialInstNo.Location = new Point(825, 213);
      this.txtFinancialInstNo.MaxLength = 15;
      this.txtFinancialInstNo.Name = "txtFinancialInstNo";
      this.txtFinancialInstNo.Size = new Size(138, 20);
      this.txtFinancialInstNo.TabIndex = 371;
      this.txtFinancialInstNo.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.label2.AutoSize = true;
      this.label2.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label2.Location = new Point(6, 33);
      this.label2.Name = "label2";
      this.label2.Size = new Size(60, 14);
      this.label2.TabIndex = 293;
      this.label2.Text = "Servicer ID";
      this.label40.AutoSize = true;
      this.label40.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label40.Location = new Point(677, 217);
      this.label40.Name = "label40";
      this.label40.Size = new Size(91, 14);
      this.label40.TabIndex = 370;
      this.label40.Text = "Financial Inst. No.";
      this.txtServicerID.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtServicerID.Location = new Point(170, 31);
      this.txtServicerID.MaxLength = 9;
      this.txtServicerID.Name = "txtServicerID";
      this.txtServicerID.Size = new Size(138, 20);
      this.txtServicerID.TabIndex = 294;
      this.txtServicerID.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtNoteCustodian.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtNoteCustodian.Location = new Point(825, 190);
      this.txtNoteCustodian.MaxLength = 15;
      this.txtNoteCustodian.Name = "txtNoteCustodian";
      this.txtNoteCustodian.Size = new Size(138, 20);
      this.txtNoteCustodian.TabIndex = 367;
      this.txtNoteCustodian.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.label4.AutoSize = true;
      this.label4.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label4.Location = new Point(6, 56);
      this.label4.Name = "label4";
      this.label4.Size = new Size(121, 14);
      this.label4.TabIndex = 295;
      this.label4.Text = "Investor Product Plan ID";
      this.label41.AutoSize = true;
      this.label41.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label41.Location = new Point(677, 194);
      this.label41.Name = "label41";
      this.label41.Size = new Size(80, 14);
      this.label41.TabIndex = 369;
      this.label41.Text = "Note Custodian";
      this.txtInvestorProdPlanID.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtInvestorProdPlanID.Location = new Point(170, 53);
      this.txtInvestorProdPlanID.MaxLength = 5;
      this.txtInvestorProdPlanID.Name = "txtInvestorProdPlanID";
      this.txtInvestorProdPlanID.Size = new Size(138, 20);
      this.txtInvestorProdPlanID.TabIndex = 297;
      this.txtInvestorProdPlanID.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.ckboxMultifamily.AutoSize = true;
      this.ckboxMultifamily.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.ckboxMultifamily.Location = new Point(825, 170);
      this.ckboxMultifamily.Name = "ckboxMultifamily";
      this.ckboxMultifamily.Size = new Size(15, 14);
      this.ckboxMultifamily.TabIndex = 364;
      this.ckboxMultifamily.UseVisualStyleBackColor = true;
      this.ckboxMultifamily.CheckedChanged += new EventHandler(this.OnFieldValueChanged);
      this.label3.AutoSize = true;
      this.label3.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label3.Location = new Point(6, 81);
      this.label3.Name = "label3";
      this.label3.Size = new Size(98, 14);
      this.label3.TabIndex = 296;
      this.label3.Text = "Investor Feature ID";
      this.label38.AutoSize = true;
      this.label38.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label38.Location = new Point(677, 170);
      this.label38.Name = "label38";
      this.label38.Size = new Size(85, 14);
      this.label38.TabIndex = 368;
      this.label38.Text = "Multifamily (Y/N)";
      this.txtInvestorFeatureID.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtInvestorFeatureID.Location = new Point(170, 75);
      this.txtInvestorFeatureID.MaxLength = 3;
      this.txtInvestorFeatureID.Name = "txtInvestorFeatureID";
      this.txtInvestorFeatureID.Size = new Size(138, 20);
      this.txtInvestorFeatureID.TabIndex = 300;
      this.txtInvestorFeatureID.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label37.AutoSize = true;
      this.label37.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label37.Location = new Point(677, 147);
      this.label37.Name = "label37";
      this.label37.Size = new Size(114, 14);
      this.label37.TabIndex = 366;
      this.label37.Text = "Interest Only End Date";
      this.label5.AutoSize = true;
      this.label5.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label5.Location = new Point(6, 175);
      this.label5.Name = "label5";
      this.label5.Size = new Size(164, 14);
      this.label5.TabIndex = 298;
      this.label5.Text = "G-Fee After Alt. Payment Method";
      this.dpInterestOnlyEndDate.BackColor = SystemColors.Window;
      this.dpInterestOnlyEndDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dpInterestOnlyEndDate.Location = new Point(825, 142);
      this.dpInterestOnlyEndDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dpInterestOnlyEndDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dpInterestOnlyEndDate.Name = "dpInterestOnlyEndDate";
      this.dpInterestOnlyEndDate.Size = new Size(138, 22);
      this.dpInterestOnlyEndDate.TabIndex = 360;
      this.dpInterestOnlyEndDate.ToolTip = "";
      this.dpInterestOnlyEndDate.Value = new DateTime(0L);
      this.dpInterestOnlyEndDate.ValueChanged += new EventHandler(this.OnFieldValueChanged);
      this.txtDeliveryRegion.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtDeliveryRegion.Location = new Point(825, 120);
      this.txtDeliveryRegion.MaxLength = 15;
      this.txtDeliveryRegion.Name = "txtDeliveryRegion";
      this.txtDeliveryRegion.Size = new Size(138, 20);
      this.txtDeliveryRegion.TabIndex = 356;
      this.txtDeliveryRegion.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.label6.AutoSize = true;
      this.label6.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label6.Location = new Point(6, 152);
      this.label6.Name = "label6";
      this.label6.Size = new Size(101, 14);
      this.label6.TabIndex = 299;
      this.label6.Text = "Base Guaranty Fee";
      this.label35.AutoSize = true;
      this.label35.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label35.Location = new Point(677, 124);
      this.label35.Name = "label35";
      this.label35.Size = new Size(82, 14);
      this.label35.TabIndex = 365;
      this.label35.Text = "Delivery Region";
      this.txtBaseGuarantyFee.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtBaseGuarantyFee.Location = new Point(170, 147);
      this.txtBaseGuarantyFee.MaxLength = 7;
      this.txtBaseGuarantyFee.Name = "txtBaseGuarantyFee";
      this.txtBaseGuarantyFee.Size = new Size(138, 20);
      this.txtBaseGuarantyFee.TabIndex = 308;
      this.txtBaseGuarantyFee.TextAlign = HorizontalAlignment.Right;
      this.txtBaseGuarantyFee.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtBaseGuarantyFee.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.txtContractType.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtContractType.Location = new Point(825, 98);
      this.txtContractType.MaxLength = 3;
      this.txtContractType.Name = "txtContractType";
      this.txtContractType.Size = new Size(138, 20);
      this.txtContractType.TabIndex = 355;
      this.txtContractType.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.cmbLoanLossParty.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbLoanLossParty.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.cmbLoanLossParty.FormattingEnabled = true;
      this.cmbLoanLossParty.Location = new Point(170, 97);
      this.cmbLoanLossParty.Name = "cmbLoanLossParty";
      this.cmbLoanLossParty.Size = new Size(138, 22);
      this.cmbLoanLossParty.TabIndex = 304;
      this.cmbLoanLossParty.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label36.AutoSize = true;
      this.label36.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label36.Location = new Point(677, 101);
      this.label36.Name = "label36";
      this.label36.Size = new Size(74, 14);
      this.label36.TabIndex = 363;
      this.label36.Text = "Contract Type";
      this.cmbREOMarketingParty.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbREOMarketingParty.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.cmbREOMarketingParty.FormattingEnabled = true;
      this.cmbREOMarketingParty.Location = new Point(170, 122);
      this.cmbREOMarketingParty.Name = "cmbREOMarketingParty";
      this.cmbREOMarketingParty.Size = new Size(138, 22);
      this.cmbREOMarketingParty.TabIndex = 307;
      this.cmbREOMarketingParty.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtForecloseRiskCode.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtForecloseRiskCode.Location = new Point(825, 76);
      this.txtForecloseRiskCode.MaxLength = 3;
      this.txtForecloseRiskCode.Name = "txtForecloseRiskCode";
      this.txtForecloseRiskCode.Size = new Size(138, 20);
      this.txtForecloseRiskCode.TabIndex = 354;
      this.txtForecloseRiskCode.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.label7.AutoSize = true;
      this.label7.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label7.Location = new Point(6, 102);
      this.label7.Name = "label7";
      this.label7.Size = new Size(123, 14);
      this.label7.TabIndex = 301;
      this.label7.Text = "Loan Default Loss Party";
      this.label33.AutoSize = true;
      this.label33.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label33.Location = new Point(677, 79);
      this.label33.Name = "label33";
      this.label33.Size = new Size(106, 14);
      this.label33.TabIndex = 362;
      this.label33.Text = "Foreclose Risk Code";
      this.label8.AutoSize = true;
      this.label8.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label8.Location = new Point(6, 128);
      this.label8.Name = "label8";
      this.label8.Size = new Size(105, 14);
      this.label8.TabIndex = 302;
      this.label8.Text = "REO Marketing Party";
      this.txtPassThruRate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPassThruRate.Location = new Point(825, 54);
      this.txtPassThruRate.MaxLength = 7;
      this.txtPassThruRate.Name = "txtPassThruRate";
      this.txtPassThruRate.Size = new Size(138, 20);
      this.txtPassThruRate.TabIndex = 353;
      this.txtPassThruRate.TextAlign = HorizontalAlignment.Right;
      this.txtPassThruRate.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.txtPassThruRate.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.lblInvestorRemittanceDay.AutoSize = true;
      this.lblInvestorRemittanceDay.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.lblInvestorRemittanceDay.Location = new Point(6, 218);
      this.lblInvestorRemittanceDay.Name = "lblInvestorRemittanceDay";
      this.lblInvestorRemittanceDay.Size = new Size(124, 14);
      this.lblInvestorRemittanceDay.TabIndex = 303;
      this.lblInvestorRemittanceDay.Text = "Investor Remittance Day";
      this.label34.AutoSize = true;
      this.label34.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label34.Location = new Point(677, 57);
      this.label34.Name = "label34";
      this.label34.Size = new Size(81, 14);
      this.label34.TabIndex = 361;
      this.label34.Text = "Pass Thru Rate";
      this.txtInvestorRemittanceDay.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtInvestorRemittanceDay.Location = new Point(170, 213);
      this.txtInvestorRemittanceDay.MaxLength = 5;
      this.txtInvestorRemittanceDay.Name = "txtInvestorRemittanceDay";
      this.txtInvestorRemittanceDay.Size = new Size(138, 20);
      this.txtInvestorRemittanceDay.TabIndex = 311;
      this.txtInvestorRemittanceDay.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.txtInvestorRemittanceDay.Leave += new EventHandler(this.txtInvestorRemittanceDay_Leave);
      this.txtPlanNumber.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPlanNumber.Location = new Point(825, 32);
      this.txtPlanNumber.MaxLength = 10;
      this.txtPlanNumber.Name = "txtPlanNumber";
      this.txtPlanNumber.Size = new Size(138, 20);
      this.txtPlanNumber.TabIndex = 352;
      this.txtPlanNumber.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.label12.AutoSize = true;
      this.label12.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label12.Location = new Point(6, 241);
      this.label12.Name = "label12";
      this.label12.Size = new Size(57, 14);
      this.label12.TabIndex = 305;
      this.label12.Text = "Contract #";
      this.txtContactNo.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtContactNo.Location = new Point(170, 235);
      this.txtContactNo.MaxLength = 6;
      this.txtContactNo.Name = "txtContactNo";
      this.txtContactNo.Size = new Size(138, 20);
      this.txtContactNo.TabIndex = 312;
      this.txtContactNo.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label43.AutoSize = true;
      this.label43.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label43.Location = new Point(677, 286);
      this.label43.Name = "label43";
      this.label43.Size = new Size(128, 14);
      this.label43.TabIndex = 358;
      this.label43.Text = "Investor Remittance Type";
      this.label11.AutoSize = true;
      this.label11.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label11.Location = new Point(5, 265);
      this.label11.Name = "label11";
      this.label11.Size = new Size(58, 14);
      this.label11.TabIndex = 306;
      this.label11.Text = "Issue Date";
      this.cmbInvestorRemittanceType.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbInvestorRemittanceType.DropDownWidth = 200;
      this.cmbInvestorRemittanceType.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.cmbInvestorRemittanceType.FormattingEnabled = true;
      this.cmbInvestorRemittanceType.Items.AddRange(new object[2]
      {
        (object) "None",
        (object) "TBD"
      });
      this.cmbInvestorRemittanceType.Location = new Point(825, 281);
      this.cmbInvestorRemittanceType.Name = "cmbInvestorRemittanceType";
      this.cmbInvestorRemittanceType.Size = new Size(138, 22);
      this.cmbInvestorRemittanceType.TabIndex = 375;
      this.cmbInvestorRemittanceType.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.label10.AutoSize = true;
      this.label10.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label10.Location = new Point(6, 289);
      this.label10.Name = "label10";
      this.label10.Size = new Size(61, 14);
      this.label10.TabIndex = 307;
      this.label10.Text = "Ownership";
      this.ckboxGuarantyFeeAddOn.AutoSize = true;
      this.ckboxGuarantyFeeAddOn.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.ckboxGuarantyFeeAddOn.Location = new Point(825, 261);
      this.ckboxGuarantyFeeAddOn.Name = "ckboxGuarantyFeeAddOn";
      this.ckboxGuarantyFeeAddOn.Size = new Size(15, 14);
      this.ckboxGuarantyFeeAddOn.TabIndex = 374;
      this.ckboxGuarantyFeeAddOn.UseVisualStyleBackColor = true;
      this.ckboxGuarantyFeeAddOn.CheckedChanged += new EventHandler(this.OnFieldValueChanged);
      this.txtOwnership.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtOwnership.Location = new Point(170, 281);
      this.txtOwnership.MaxLength = 3;
      this.txtOwnership.Name = "txtOwnership";
      this.txtOwnership.Size = new Size(138, 20);
      this.txtOwnership.TabIndex = 314;
      this.txtOwnership.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label42.AutoSize = true;
      this.label42.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label42.Location = new Point(677, 262);
      this.label42.Name = "label42";
      this.label42.Size = new Size(112, 14);
      this.label42.TabIndex = 357;
      this.label42.Text = "Guaranty Fee Add On";
      this.dtIssueDate.BackColor = SystemColors.Window;
      this.dtIssueDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dtIssueDate.Location = new Point(170, 257);
      this.dtIssueDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dtIssueDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dtIssueDate.Name = "dtIssueDate";
      this.dtIssueDate.Size = new Size(138, 22);
      this.dtIssueDate.TabIndex = 313;
      this.dtIssueDate.ToolTip = "";
      this.dtIssueDate.Value = new DateTime(0L);
      this.dtIssueDate.ValueChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtSubmissionType.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtSubmissionType.Location = new Point(825, 9);
      this.txtSubmissionType.MaxLength = 20;
      this.txtSubmissionType.Name = "txtSubmissionType";
      this.txtSubmissionType.Size = new Size(138, 20);
      this.txtSubmissionType.TabIndex = 349;
      this.txtSubmissionType.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.label18.AutoSize = true;
      this.label18.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label18.Location = new Point(336, 36);
      this.label18.Name = "label18";
      this.label18.Size = new Size(109, 14);
      this.label18.TabIndex = 326;
      this.label18.Text = "Minimum Accrual rate";
      this.label32.AutoSize = true;
      this.label32.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label32.Location = new Point(677, 12);
      this.label32.Name = "label32";
      this.label32.Size = new Size(88, 14);
      this.label32.TabIndex = 351;
      this.label32.Text = "Submission Type";
      this.txtMinimumAccrualRate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtMinimumAccrualRate.Location = new Point(513, 33);
      this.txtMinimumAccrualRate.MaxLength = 7;
      this.txtMinimumAccrualRate.Name = "txtMinimumAccrualRate";
      this.txtMinimumAccrualRate.Size = new Size(138, 20);
      this.txtMinimumAccrualRate.TabIndex = 318;
      this.txtMinimumAccrualRate.TextAlign = HorizontalAlignment.Right;
      this.txtMinimumAccrualRate.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtMinimumAccrualRate.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.txtCommitmentPeriod.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtCommitmentPeriod.Location = new Point(513, 330);
      this.txtCommitmentPeriod.MaxLength = 3;
      this.txtCommitmentPeriod.Name = "txtCommitmentPeriod";
      this.txtCommitmentPeriod.Size = new Size(138, 20);
      this.txtCommitmentPeriod.TabIndex = 345;
      this.txtCommitmentPeriod.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.label17.AutoSize = true;
      this.label17.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label17.Location = new Point(336, 12);
      this.label17.Name = "label17";
      this.label17.Size = new Size(143, 14);
      this.label17.TabIndex = 327;
      this.label17.Text = "Security Issue Date Int. Rate";
      this.label29.AutoSize = true;
      this.label29.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label29.Location = new Point(336, 334);
      this.label29.Name = "label29";
      this.label29.Size = new Size(97, 14);
      this.label29.TabIndex = 350;
      this.label29.Text = "Commitment Period";
      this.txtSecurityIssueRate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtSecurityIssueRate.Location = new Point(513, 11);
      this.txtSecurityIssueRate.MaxLength = 7;
      this.txtSecurityIssueRate.Name = "txtSecurityIssueRate";
      this.txtSecurityIssueRate.Size = new Size(138, 20);
      this.txtSecurityIssueRate.TabIndex = 317;
      this.txtSecurityIssueRate.TextAlign = HorizontalAlignment.Right;
      this.txtSecurityIssueRate.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtSecurityIssueRate.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.txtPayeeCode.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPayeeCode.Location = new Point(513, 308);
      this.txtPayeeCode.MaxLength = 9;
      this.txtPayeeCode.Name = "txtPayeeCode";
      this.txtPayeeCode.Size = new Size(138, 20);
      this.txtPayeeCode.TabIndex = 342;
      this.txtPayeeCode.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.cmbStructureType.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbStructureType.DropDownWidth = 170;
      this.cmbStructureType.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.cmbStructureType.FormattingEnabled = true;
      this.cmbStructureType.Location = new Point(170, 304);
      this.cmbStructureType.Name = "cmbStructureType";
      this.cmbStructureType.Size = new Size(138, 22);
      this.cmbStructureType.TabIndex = 315;
      this.cmbStructureType.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label30.AutoSize = true;
      this.label30.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label30.Location = new Point(336, 310);
      this.label30.Name = "label30";
      this.label30.Size = new Size(65, 14);
      this.label30.TabIndex = 348;
      this.label30.Text = "Payee Code";
      this.cmbAccrualRateType.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbAccrualRateType.DropDownWidth = 170;
      this.cmbAccrualRateType.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.cmbAccrualRateType.FormattingEnabled = true;
      this.cmbAccrualRateType.Location = new Point(170, 329);
      this.cmbAccrualRateType.Name = "cmbAccrualRateType";
      this.cmbAccrualRateType.Size = new Size(138, 22);
      this.cmbAccrualRateType.TabIndex = 316;
      this.cmbAccrualRateType.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label28.AutoSize = true;
      this.label28.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label28.Location = new Point(336, 286);
      this.label28.Name = "label28";
      this.label28.Size = new Size(158, 14);
      this.label28.TabIndex = 347;
      this.label28.Text = "Security Trade Book Entry Date";
      this.label16.AutoSize = true;
      this.label16.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label16.Location = new Point(6, 312);
      this.label16.Name = "label16";
      this.label16.Size = new Size(78, 14);
      this.label16.TabIndex = 329;
      this.label16.Text = "Structure Type";
      this.dpSecurityTradeBookDate.BackColor = SystemColors.Window;
      this.dpSecurityTradeBookDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dpSecurityTradeBookDate.Location = new Point(513, 283);
      this.dpSecurityTradeBookDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dpSecurityTradeBookDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dpSecurityTradeBookDate.Name = "dpSecurityTradeBookDate";
      this.dpSecurityTradeBookDate.Size = new Size(138, 22);
      this.dpSecurityTradeBookDate.TabIndex = 338;
      this.dpSecurityTradeBookDate.ToolTip = "";
      this.dpSecurityTradeBookDate.Value = new DateTime(0L);
      this.dpSecurityTradeBookDate.ValueChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label15.AutoSize = true;
      this.label15.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label15.Location = new Point(6, 335);
      this.label15.Name = "label15";
      this.label15.Size = new Size(128, 14);
      this.label15.TabIndex = 330;
      this.label15.Text = "Accrual Rate Struc. Type";
      this.label27.AutoSize = true;
      this.label27.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label27.Location = new Point(349, 157);
      this.label27.Name = "label27";
      this.label27.Size = new Size(0, 14);
      this.label27.TabIndex = 346;
      this.label14.AutoSize = true;
      this.label14.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label14.Location = new Point(336, 58);
      this.label14.Name = "label14";
      this.label14.Size = new Size(116, 14);
      this.label14.TabIndex = 331;
      this.label14.Text = "Maximum Accrual Rate";
      this.label26.AutoSize = true;
      this.label26.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label26.Location = new Point(336, 262);
      this.label26.Name = "label26";
      this.label26.Size = new Size(180, 14);
      this.label26.TabIndex = 344;
      this.label26.Text = "Scheduled Remittance Payment Day";
      this.txtMaximumAccrualRate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtMaximumAccrualRate.Location = new Point(513, 55);
      this.txtMaximumAccrualRate.MaxLength = 7;
      this.txtMaximumAccrualRate.Name = "txtMaximumAccrualRate";
      this.txtMaximumAccrualRate.Size = new Size(138, 20);
      this.txtMaximumAccrualRate.TabIndex = 319;
      this.txtMaximumAccrualRate.TextAlign = HorizontalAlignment.Right;
      this.txtMaximumAccrualRate.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtMaximumAccrualRate.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.txtServiceFee.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtServiceFee.Location = new Point(513, 239);
      this.txtServiceFee.MaxLength = 7;
      this.txtServiceFee.Name = "txtServiceFee";
      this.txtServiceFee.Size = new Size(138, 20);
      this.txtServiceFee.TabIndex = 332;
      this.txtServiceFee.TextAlign = HorizontalAlignment.Right;
      this.txtServiceFee.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtServiceFee.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.label9.AutoSize = true;
      this.label9.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label9.Location = new Point(336, 80);
      this.label9.Name = "label9";
      this.label9.Size = new Size(64, 14);
      this.label9.TabIndex = 333;
      this.label9.Text = "Margin Rate";
      this.label25.AutoSize = true;
      this.label25.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label25.Location = new Point(336, 240);
      this.label25.Name = "label25";
      this.label25.Size = new Size(142, 14);
      this.label25.TabIndex = 343;
      this.label25.Text = "Fixed Servicing Fee Percent";
      this.txtMarginRate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtMarginRate.Location = new Point(513, 77);
      this.txtMarginRate.MaxLength = 7;
      this.txtMarginRate.Name = "txtMarginRate";
      this.txtMarginRate.Size = new Size(138, 20);
      this.txtMarginRate.TabIndex = 320;
      this.txtMarginRate.TextAlign = HorizontalAlignment.Right;
      this.txtMarginRate.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtMarginRate.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.ckboxBalloonIndicator.AutoSize = true;
      this.ckboxBalloonIndicator.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.ckboxBalloonIndicator.Location = new Point(513, 197);
      this.ckboxBalloonIndicator.Name = "ckboxBalloonIndicator";
      this.ckboxBalloonIndicator.Size = new Size(15, 14);
      this.ckboxBalloonIndicator.TabIndex = 325;
      this.ckboxBalloonIndicator.UseVisualStyleBackColor = true;
      this.ckboxBalloonIndicator.CheckedChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtRateRounding.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtRateRounding.Location = new Point(513, 123);
      this.txtRateRounding.MaxLength = 8;
      this.txtRateRounding.Name = "txtRateRounding";
      this.txtRateRounding.Size = new Size(138, 20);
      this.txtRateRounding.TabIndex = 322;
      this.txtRateRounding.TextAlign = HorizontalAlignment.Right;
      this.txtRateRounding.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtRateRounding.Leave += new EventHandler(this.txt_Percent34_Leave);
      this.label24.AutoSize = true;
      this.label24.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label24.Location = new Point(336, 196);
      this.label24.Name = "label24";
      this.label24.Size = new Size(86, 14);
      this.label24.TabIndex = 341;
      this.label24.Text = "Balloon Indicator";
      this.cmbRateRoundingType.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbRateRoundingType.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.cmbRateRoundingType.FormattingEnabled = true;
      this.cmbRateRoundingType.Location = new Point(513, 99);
      this.cmbRateRoundingType.Name = "cmbRateRoundingType";
      this.cmbRateRoundingType.Size = new Size(138, 22);
      this.cmbRateRoundingType.TabIndex = 321;
      this.cmbRateRoundingType.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.ckboxAssumabilityIndicator.AutoSize = true;
      this.ckboxAssumabilityIndicator.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.ckboxAssumabilityIndicator.Location = new Point(513, 174);
      this.ckboxAssumabilityIndicator.Name = "ckboxAssumabilityIndicator";
      this.ckboxAssumabilityIndicator.Size = new Size(15, 14);
      this.ckboxAssumabilityIndicator.TabIndex = 324;
      this.ckboxAssumabilityIndicator.UseVisualStyleBackColor = true;
      this.ckboxAssumabilityIndicator.CheckedChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label19.AutoSize = true;
      this.label19.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label19.Location = new Point(336, 102);
      this.label19.Name = "label19";
      this.label19.Size = new Size(120, 14);
      this.label19.TabIndex = 335;
      this.label19.Text = "Int. Rate Rounding Type";
      this.label23.AutoSize = true;
      this.label23.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label23.Location = new Point(336, 173);
      this.label23.Name = "label23";
      this.label23.Size = new Size(112, 14);
      this.label23.TabIndex = 340;
      this.label23.Text = "Assumability Indicator";
      this.label20.AutoSize = true;
      this.label20.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label20.Location = new Point(336, 126);
      this.label20.Name = "label20";
      this.label20.Size = new Size(107, 14);
      this.label20.TabIndex = 336;
      this.label20.Text = "Int. Rate Rounding %";
      this.txtIndexLeadDays.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtIndexLeadDays.Location = new Point(513, 217);
      this.txtIndexLeadDays.MaxLength = 3;
      this.txtIndexLeadDays.Name = "txtIndexLeadDays";
      this.txtIndexLeadDays.Size = new Size(138, 20);
      this.txtIndexLeadDays.TabIndex = 328;
      this.txtIndexLeadDays.TextAlign = HorizontalAlignment.Right;
      this.txtIndexLeadDays.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label21.AutoSize = true;
      this.label21.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label21.Location = new Point(336, 151);
      this.label21.Name = "label21";
      this.label21.Size = new Size(68, 14);
      this.label21.TabIndex = 337;
      this.label21.Text = "Interest Only";
      this.label22.AutoSize = true;
      this.label22.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label22.Location = new Point(336, 218);
      this.label22.Name = "label22";
      this.label22.Size = new Size(180, 14);
      this.label22.TabIndex = 339;
      this.label22.Text = "Int. && Payment Adj. Index Lead Days";
      this.ckboxInterestOnly.AutoSize = true;
      this.ckboxInterestOnly.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.ckboxInterestOnly.Location = new Point(513, 151);
      this.ckboxInterestOnly.Name = "ckboxInterestOnly";
      this.ckboxInterestOnly.Size = new Size(15, 14);
      this.ckboxInterestOnly.TabIndex = 323;
      this.ckboxInterestOnly.UseVisualStyleBackColor = true;
      this.ckboxInterestOnly.CheckedChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.Controls.Add((Control) this.gpSetup);
      this.Name = nameof (MbsPoolFannieMaeFieldsEditor);
      this.Size = new Size(981, 408);
      this.gpSetup.ResumeLayout(false);
      this.panel4.ResumeLayout(false);
      this.panel4.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
