// Decompiled with JetBrains decompiler
// Type: EllieMae.EMLite.Trading.MBSPoolGinnieMaeFieldsEditor
// Assembly: TradeManagement, Version=24.3.0.5, Culture=neutral, PublicKeyToken=null
// MVID: 30F9401A-5385-498E-9C5B-D147722AC94C
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\TradeManagement.dll

using EllieMae.EMLite.ClientServer;
using EllieMae.EMLite.Common;
using EllieMae.EMLite.DataEngine;
using EllieMae.EMLite.RemotingServices;
using EllieMae.EMLite.UI;
using System;
using System.Collections;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace EllieMae.EMLite.Trading
{
  public class MBSPoolGinnieMaeFieldsEditor : MbsPoolFieldsEditorBase
  {
    private IContainer components;
    private GroupContainer gpSetup;
    private Panel panel4;
    private Label label27;
    private GroupContainer gcCustodialBondInfo;
    private Label label3;
    private TextBox txtCertAgreement;
    private CheckBox ckboxIsDocRequired;
    private Label label45;
    private CheckBox ckboxIsDocSubmission;
    private Label label44;
    private CheckBox ckboxIsSent1711ToCustodian;
    private Label label9;
    private TextBox txtPnICustodialAcctNum;
    private Label label14;
    private TextBox txtPnICustodialABA;
    private TextBox txtNoteCustodian;
    private Label label7;
    private Label label8;
    private GroupContainer gcBondInfo;
    private TextBox txtBondFinanceProgramName;
    private Label label47;
    private Label label46;
    private CheckBox ckboxIsBondFinancePool;
    private Label label17;
    private GroupContainer gcPoolDetailsBankInfo;
    private Label label10;
    private TextBox txtPoolTaxId;
    private ComboBox cmbGinniePoolType;
    private Label label22;
    private GroupContainer gcBankInfo;
    private TextBox txtMasterTnIAcctNum;
    private Label label18;
    private TextBox txtSubscriberRecordAcctNum;
    private Label label20;
    private TextBox txtSubscriberRecordABA;
    private Label label19;
    private Label label5;
    private TextBox txtSubscriberRecordFrbActDesc;
    private Label label6;
    private TextBox txtSubscriberRecordFrbPosDesc;
    private Label label13;
    private TextBox txtMasterTnIABA;
    private Label label48;
    private TextBox txtSecurityOriginalSubscriptionAmount;
    private Label label49;
    private TextBox txtPoolMaturityPeriodCount;
    private Label label50;
    private TextBox txtPoolCurrentPrincipalBalAmt;
    private Label label51;
    private TextBox txtPoolCurrentLoanCount;
    private Label label52;
    private CheckBox ckboxIsPoolConcurrentTransfer;
    private Label label43;
    private Label label42;
    private TextBox txtACHBankAccountDescription;
    private Label label39;
    private TextBox txtACHReveiverSubaccountName;
    private Label label40;
    private Label label41;
    private TextBox txtACHInsititTelegraphicName;
    private Label label35;
    private TextBox txtABARTId;
    private Label label38;
    private TextBox txtACHABARTNum;
    private Label label37;
    private GroupContainer gcIssueDetailsMilestoneDates;
    private GroupContainer gcPoolMilestoneDates;
    private DatePicker dpInterestAdjEffectiveDate;
    private Label label34;
    private DatePicker dpCertificatePaymentDate;
    private Label label33;
    private DatePicker dpLastPaidInstallmentDate;
    private Label label26;
    private DatePicker dpUnpaidBalanceDate;
    private Label label25;
    private DatePicker dpMaturityDate;
    private Label label11;
    private DatePicker dpInitialDate;
    private Label label24;
    private DatePicker dpIssueDate;
    private Label label23;
    private DatePicker dpChangeDate;
    private Label label15;
    private TextBox txtMbsMargin;
    private Label label16;
    private Label label31;
    private Label label28;
    private TextBox txtGuaranteeFee;
    private Label label29;
    private TextBox txtServiceFee;
    private Label label4;
    private TextBox txtArmIndex;
    private TextBox txtSubservicerIssuerNum;
    private Label label21;
    private TextBox txtNewTransferIssuerNum;
    private Label label12;
    private TextBox txtPoolIssuerTransferee;
    private Label label30;
    private Label label2;
    private TextBox txtIssueType;
    private Label label1;
    private TextBox txtIssueNum;
    private ComboBox cmbBondFinanceProgramType;
    private ComboBox cmbPoolingMethodType;
    private ComboBox cmbACHBankAccPurposeType;
    private ComboBox cmbPoolIndexType;
    private ComboBox cmbPoolClassType;

    public MBSPoolGinnieMaeFieldsEditor(PipelineInfo[] currentInTradeLoans)
      : base(currentInTradeLoans)
    {
      this.InitializeComponent();
      TextBoxFormatter.Attach(this.txtPnICustodialABA, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtSubscriberRecordABA, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtMasterTnIABA, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtNewTransferIssuerNum, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtArmIndex, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtMbsMargin, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtGuaranteeFee, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtServiceFee, TextBoxContentRule.NonNegativeDecimal, "#0.0000;;\"\"");
      TextBoxFormatter.Attach(this.txtPnICustodialABA, TextBoxContentRule.NonNegativeInteger);
      TextBoxFormatter.Attach(this.txtPoolCurrentLoanCount, TextBoxContentRule.NonNegativeInteger, "#0;;\"\"");
      TextBoxFormatter.Attach(this.txtPoolMaturityPeriodCount, TextBoxContentRule.NonNegativeInteger, "#0;;\"\"");
      TextBoxFormatter.Attach(this.txtPoolCurrentPrincipalBalAmt, TextBoxContentRule.Decimal, "#,##0;;\"\"");
      TextBoxFormatter.Attach(this.txtSecurityOriginalSubscriptionAmount, TextBoxContentRule.Decimal, "#,##0;;\"\"");
      this.gpSetup.Text = "Ginnie Mae";
      this.LoadConfigurableFieldOptions();
    }

    protected override void LoadConfigurableFieldOptions()
    {
      this.cmbGinniePoolType.Items.Clear();
      ArrayList secondaryFields = Session.ConfigurationManager.GetSecondaryFields(SecondaryFieldTypes.GinniePoolType);
      if (secondaryFields != null)
        this.cmbGinniePoolType.Items.AddRange(secondaryFields.ToArray());
      this.cmbPoolIndexType.Items.AddRange((object[]) EnumUtil.GetEnumDescriptions(typeof (PoolIndexType)));
      this.cmbACHBankAccPurposeType.Items.AddRange((object[]) EnumUtil.GetEnumDescriptions(typeof (ACHBankAccountPurposeType)));
      this.cmbPoolingMethodType.Items.AddRange((object[]) EnumUtil.GetEnumDescriptions(typeof (PoolingMethodType)));
      this.cmbPoolClassType.Items.AddRange((object[]) EnumUtil.GetEnumDescriptions(typeof (PoolClassType)));
      this.cmbBondFinanceProgramType.Items.AddRange((object[]) EnumUtil.GetEnumDescriptions(typeof (BondFinanceProgramType)));
    }

    protected override void loadTradeData()
    {
      this.txtIssueNum.Text = this.PoolTrade.IssuerNum;
      this.txtIssueType.Text = this.PoolTrade.IssueType;
      this.txtArmIndex.Text = this.PoolTrade.ARMIndex.ToString("#0.0000;;\"\"");
      this.txtCertAgreement.Text = this.PoolTrade.CertAgreement;
      this.txtNoteCustodian.Text = this.PoolTrade.NoteCustodian;
      this.txtPnICustodialABA.Text = this.PoolTrade.PnICustodialABA;
      this.txtSubscriberRecordABA.Text = this.PoolTrade.SubscriberRecordABA;
      this.txtSubscriberRecordFrbPosDesc.Text = this.PoolTrade.SubscriberRecordFRBPosDesc;
      this.txtSubscriberRecordFrbActDesc.Text = this.PoolTrade.SubscriberRecordFRBAcctDesc;
      this.txtMasterTnIABA.Text = this.PoolTrade.MasterTnIABA;
      this.txtNewTransferIssuerNum.Text = this.PoolTrade.NewTransferIssuerNum;
      this.dpMaturityDate.Value = this.PoolTrade.MaturityDate;
      this.txtPoolTaxId.Text = this.PoolTrade.PoolTaxID;
      this.txtMbsMargin.Text = this.PoolTrade.MbsMargin.ToString("#0.0000;;\"\"");
      this.dpChangeDate.Value = this.PoolTrade.ChangeDate;
      this.ckboxIsBondFinancePool.Checked = this.PoolTrade.IsBondFinancePool;
      this.ckboxIsSent1711ToCustodian.Checked = this.PoolTrade.IsSent1711ToCustodian;
      this.txtPnICustodialAcctNum.Text = this.PoolTrade.PnICustodialAcctNum;
      this.txtSubscriberRecordAcctNum.Text = this.PoolTrade.SubscriberRecordAcctNum;
      this.txtMasterTnIAcctNum.Text = this.PoolTrade.MasterTnIAcctNum;
      this.txtSubservicerIssuerNum.Text = this.PoolTrade.SubservicerIssuerNum;
      this.cmbGinniePoolType.Text = this.PoolTrade.GinniePoolType;
      this.txtGuaranteeFee.Text = this.PoolTrade.GuaranteeFee.ToString("#0.0000;;\"\"");
      this.txtServiceFee.Text = this.PoolTrade.FixedServicingFeePercent.ToString("#0.0000;;\"\"");
      this.dpIssueDate.Value = this.PoolTrade.IssueDate;
      this.dpInitialDate.Value = this.PoolTrade.InitialDate;
      this.dpLastPaidInstallmentDate.Value = this.PoolTrade.LastPaidInstallmentDate;
      this.dpUnpaidBalanceDate.Value = this.PoolTrade.UnpaidBalanceDate;
      this.cmbACHBankAccPurposeType.Text = this.PoolTrade.ACHBankAccountPurposeType;
      this.txtACHABARTNum.Text = this.PoolTrade.ACHABARoutingAndTransitNum;
      this.txtABARTId.Text = this.PoolTrade.ACHABARoutingAndTransitId;
      this.txtACHInsititTelegraphicName.Text = this.PoolTrade.ACHInsitutionTelegraphicName;
      this.txtACHReveiverSubaccountName.Text = this.PoolTrade.ACHReceiverSubaccountName;
      this.txtACHBankAccountDescription.Text = this.PoolTrade.ACHBankAccountDescription;
      this.cmbPoolIndexType.Text = this.PoolTrade.GinniePoolIndexType;
      this.txtPoolIssuerTransferee.Text = this.PoolTrade.PoolIssuerTransferee;
      this.dpCertificatePaymentDate.Value = this.PoolTrade.PoolCertificatePaymentDate;
      this.txtBondFinanceProgramName.Text = this.PoolTrade.BondFinanceProgramName;
      this.cmbBondFinanceProgramType.Text = this.PoolTrade.BondFinanceProgramType;
      this.cmbPoolClassType.Text = this.PoolTrade.GinniePoolClassType;
      this.ckboxIsPoolConcurrentTransfer.Checked = this.PoolTrade.GinniePoolConcurrentTransferIndicator;
      this.txtPoolCurrentLoanCount.Text = (this.CurrentInTradeLoans != null ? this.CurrentInTradeLoans.Length : 0).ToString("0;;\"\"");
      TextBox currentPrincipalBalAmt = this.txtPoolCurrentPrincipalBalAmt;
      long num = this.PoolTrade.PoolCurrentPrincipalBalAmt;
      string str1 = num.ToString("#,##0;;\"\"");
      currentPrincipalBalAmt.Text = str1;
      this.cmbPoolingMethodType.Text = this.PoolTrade.PoolingMethodType;
      this.dpInterestAdjEffectiveDate.Value = this.PoolTrade.PoolInterestAdjustmentEffectiveDate;
      this.txtPoolMaturityPeriodCount.Text = this.PoolTrade.PoolMaturityPeriodCount.ToString("0;;\"\"");
      this.ckboxIsDocSubmission.Checked = this.PoolTrade.DocSubmissionIndicator;
      this.ckboxIsDocRequired.Checked = this.PoolTrade.DocReqIndicator;
      TextBox subscriptionAmount = this.txtSecurityOriginalSubscriptionAmount;
      num = this.PoolTrade.SecurityOrigSubscriptionAmt;
      string str2 = num.ToString("#,##0;;\"\"");
      subscriptionAmount.Text = str2;
    }

    protected override void setReadOnly()
    {
      this.txtIssueNum.ReadOnly = this.readOnly;
      this.txtIssueType.ReadOnly = this.readOnly;
      this.txtArmIndex.ReadOnly = this.readOnly;
      this.txtCertAgreement.ReadOnly = this.readOnly;
      this.txtNoteCustodian.ReadOnly = this.readOnly;
      this.txtPnICustodialABA.ReadOnly = this.readOnly;
      this.txtSubscriberRecordABA.ReadOnly = this.readOnly;
      this.txtSubscriberRecordFrbPosDesc.ReadOnly = this.readOnly;
      this.txtSubscriberRecordFrbActDesc.ReadOnly = this.readOnly;
      this.txtMasterTnIABA.ReadOnly = this.readOnly;
      this.txtNewTransferIssuerNum.ReadOnly = this.readOnly;
      this.dpMaturityDate.Enabled = !this.readOnly;
      this.txtPoolTaxId.ReadOnly = this.readOnly;
      this.txtMbsMargin.ReadOnly = this.readOnly;
      this.dpChangeDate.Enabled = !this.readOnly;
      this.ckboxIsBondFinancePool.Enabled = !this.readOnly;
      this.ckboxIsSent1711ToCustodian.Enabled = !this.readOnly;
      this.txtPnICustodialAcctNum.ReadOnly = this.readOnly;
      this.txtSubscriberRecordAcctNum.ReadOnly = this.readOnly;
      this.txtMasterTnIAcctNum.ReadOnly = this.readOnly;
      this.txtSubservicerIssuerNum.ReadOnly = this.readOnly;
      this.cmbGinniePoolType.Enabled = !this.readOnly;
      this.txtGuaranteeFee.ReadOnly = this.readOnly;
      this.txtServiceFee.ReadOnly = this.readOnly;
      this.dpIssueDate.Enabled = !this.readOnly;
      this.dpInitialDate.Enabled = !this.readOnly;
      this.dpLastPaidInstallmentDate.Enabled = !this.readOnly;
      this.dpUnpaidBalanceDate.Enabled = !this.readOnly;
      this.cmbACHBankAccPurposeType.Enabled = !this.readOnly;
      this.txtACHABARTNum.Enabled = !this.readOnly;
      this.txtABARTId.Enabled = !this.readOnly;
      this.txtACHInsititTelegraphicName.Enabled = !this.readOnly;
      this.txtACHReveiverSubaccountName.Enabled = !this.readOnly;
      this.txtACHBankAccountDescription.Enabled = !this.readOnly;
      this.cmbPoolIndexType.Enabled = !this.readOnly;
      this.txtPoolIssuerTransferee.Enabled = !this.readOnly;
      this.dpCertificatePaymentDate.Enabled = !this.readOnly;
      this.txtBondFinanceProgramName.Enabled = !this.readOnly;
      this.cmbBondFinanceProgramType.Enabled = !this.readOnly;
      this.cmbPoolClassType.Enabled = !this.readOnly;
      this.ckboxIsPoolConcurrentTransfer.Enabled = !this.readOnly;
      this.txtPoolCurrentLoanCount.Enabled = false;
      this.txtPoolCurrentPrincipalBalAmt.Enabled = !this.readOnly;
      this.cmbPoolingMethodType.Enabled = !this.readOnly;
      this.dpInterestAdjEffectiveDate.Enabled = !this.readOnly;
      this.txtPoolMaturityPeriodCount.Enabled = !this.readOnly;
      this.ckboxIsDocSubmission.Enabled = !this.readOnly;
      this.ckboxIsDocRequired.Enabled = !this.readOnly;
      this.txtSecurityOriginalSubscriptionAmount.Enabled = !this.readOnly;
    }

    protected override bool queryCommitChanges(bool popupMsg)
    {
      return popupMsg ? this.ValidateEditor((object) this.txtGuaranteeFee, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtServiceFee, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtMbsMargin, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) && this.ValidateEditor((object) this.txtArmIndex, ValidateMode.Percent24, "Valid enter is a decimal less than 100", false) : this.ValidateEditor((object) this.txtGuaranteeFee, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtServiceFee, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtMbsMargin, ValidateMode.Percent24, string.Empty, false) && this.ValidateEditor((object) this.txtArmIndex, ValidateMode.Percent24, string.Empty, false);
    }

    protected override void commitChanges()
    {
      this.PoolTrade.IssuerNum = this.txtIssueNum.Text;
      this.PoolTrade.IssueType = this.txtIssueType.Text;
      this.PoolTrade.ARMIndex = Utils.ParseDecimal((object) this.txtArmIndex.Text);
      this.PoolTrade.CertAgreement = this.txtCertAgreement.Text;
      this.PoolTrade.NoteCustodian = this.txtNoteCustodian.Text;
      this.PoolTrade.PnICustodialABA = this.txtPnICustodialABA.Text;
      this.PoolTrade.SubscriberRecordABA = this.txtSubscriberRecordABA.Text;
      this.PoolTrade.SubscriberRecordFRBPosDesc = this.txtSubscriberRecordFrbPosDesc.Text;
      this.PoolTrade.SubscriberRecordFRBAcctDesc = this.txtSubscriberRecordFrbActDesc.Text;
      this.PoolTrade.MasterTnIABA = this.txtMasterTnIABA.Text;
      this.PoolTrade.NewTransferIssuerNum = this.txtNewTransferIssuerNum.Text;
      this.PoolTrade.MaturityDate = Utils.ParseDate((object) this.dpMaturityDate.Value);
      this.PoolTrade.PoolTaxID = this.txtPoolTaxId.Text;
      this.PoolTrade.MbsMargin = Utils.ParseDecimal((object) this.txtMbsMargin.Text);
      this.PoolTrade.ChangeDate = Utils.ParseDate((object) this.dpChangeDate.Value);
      this.PoolTrade.IsBondFinancePool = this.ckboxIsBondFinancePool.Checked;
      this.PoolTrade.IsSent1711ToCustodian = this.ckboxIsSent1711ToCustodian.Checked;
      this.PoolTrade.PnICustodialAcctNum = this.txtPnICustodialAcctNum.Text;
      this.PoolTrade.SubscriberRecordAcctNum = this.txtSubscriberRecordAcctNum.Text;
      this.PoolTrade.MasterTnIAcctNum = this.txtMasterTnIAcctNum.Text;
      this.PoolTrade.SubservicerIssuerNum = this.txtSubservicerIssuerNum.Text;
      this.PoolTrade.GinniePoolType = this.cmbGinniePoolType.Text;
      this.PoolTrade.GuaranteeFee = Utils.ParseDecimal((object) this.txtGuaranteeFee.Text);
      this.PoolTrade.FixedServicingFeePercent = Utils.ParseDecimal((object) this.txtServiceFee.Text);
      this.PoolTrade.IssueDate = Utils.ParseDate((object) this.dpIssueDate.Value);
      this.PoolTrade.InitialDate = Utils.ParseDate((object) this.dpInitialDate.Value);
      this.PoolTrade.LastPaidInstallmentDate = Utils.ParseDate((object) this.dpLastPaidInstallmentDate.Value);
      this.PoolTrade.UnpaidBalanceDate = Utils.ParseDate((object) this.dpUnpaidBalanceDate.Value);
      this.PoolTrade.ACHBankAccountPurposeType = this.cmbACHBankAccPurposeType.Text;
      this.PoolTrade.ACHABARoutingAndTransitNum = this.txtACHABARTNum.Text;
      this.PoolTrade.ACHABARoutingAndTransitId = this.txtABARTId.Text;
      this.PoolTrade.ACHInsitutionTelegraphicName = this.txtACHInsititTelegraphicName.Text;
      this.PoolTrade.ACHReceiverSubaccountName = this.txtACHReveiverSubaccountName.Text;
      this.PoolTrade.ACHBankAccountDescription = this.txtACHBankAccountDescription.Text;
      this.PoolTrade.GinniePoolIndexType = this.cmbPoolIndexType.Text;
      this.PoolTrade.PoolIssuerTransferee = this.txtPoolIssuerTransferee.Text;
      this.PoolTrade.PoolCertificatePaymentDate = Utils.ParseDate((object) this.dpCertificatePaymentDate.Value);
      this.PoolTrade.BondFinanceProgramName = this.txtBondFinanceProgramName.Text;
      this.PoolTrade.BondFinanceProgramType = this.cmbBondFinanceProgramType.Text;
      this.PoolTrade.GinniePoolClassType = this.cmbPoolClassType.Text;
      this.PoolTrade.GinniePoolConcurrentTransferIndicator = this.ckboxIsPoolConcurrentTransfer.Checked;
      this.PoolTrade.PoolCurrentLoanCount = this.CurrentInTradeLoans != null ? this.CurrentInTradeLoans.Length : 0;
      this.PoolTrade.PoolCurrentPrincipalBalAmt = Utils.ParseLong((object) this.txtPoolCurrentPrincipalBalAmt.Text, 0L);
      this.PoolTrade.PoolingMethodType = this.cmbPoolingMethodType.Text;
      this.PoolTrade.PoolInterestAdjustmentEffectiveDate = Utils.ParseDate((object) this.dpInterestAdjEffectiveDate.Value);
      this.PoolTrade.PoolMaturityPeriodCount = Utils.ParseInt((object) this.txtPoolMaturityPeriodCount.Text, 0);
      this.PoolTrade.DocSubmissionIndicator = this.ckboxIsDocSubmission.Checked;
      this.PoolTrade.DocReqIndicator = this.ckboxIsDocRequired.Checked;
      this.PoolTrade.SecurityOrigSubscriptionAmt = Utils.ParseLong((object) this.txtSecurityOriginalSubscriptionAmount.Text, 0L);
    }

    private new void OnFieldValueChanged(object sender, EventArgs e)
    {
      base.OnFieldValueChanged(sender, e);
    }

    private new void OnLoanUpdatableFieldValueChanged(object sender, EventArgs e)
    {
      base.OnLoanUpdatableFieldValueChanged(sender, e);
    }

    private void txt_Percent24_Leave(object sender, EventArgs e)
    {
      if (!this.modified)
        return;
      this.ValidateEditor((object) (TextBox) sender, ValidateMode.Percent24, "Valid enter is a decimal less than 100");
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.gpSetup = new GroupContainer();
      this.panel4 = new Panel();
      this.gcCustodialBondInfo = new GroupContainer();
      this.label3 = new Label();
      this.txtCertAgreement = new TextBox();
      this.ckboxIsDocRequired = new CheckBox();
      this.label45 = new Label();
      this.ckboxIsDocSubmission = new CheckBox();
      this.label44 = new Label();
      this.ckboxIsSent1711ToCustodian = new CheckBox();
      this.label9 = new Label();
      this.txtPnICustodialAcctNum = new TextBox();
      this.label14 = new Label();
      this.txtPnICustodialABA = new TextBox();
      this.txtNoteCustodian = new TextBox();
      this.label7 = new Label();
      this.label8 = new Label();
      this.gcBondInfo = new GroupContainer();
      this.cmbBondFinanceProgramType = new ComboBox();
      this.txtBondFinanceProgramName = new TextBox();
      this.label47 = new Label();
      this.label46 = new Label();
      this.ckboxIsBondFinancePool = new CheckBox();
      this.label17 = new Label();
      this.gcPoolDetailsBankInfo = new GroupContainer();
      this.cmbPoolClassType = new ComboBox();
      this.cmbPoolingMethodType = new ComboBox();
      this.label48 = new Label();
      this.txtSecurityOriginalSubscriptionAmount = new TextBox();
      this.label49 = new Label();
      this.txtPoolMaturityPeriodCount = new TextBox();
      this.label50 = new Label();
      this.txtPoolCurrentPrincipalBalAmt = new TextBox();
      this.label51 = new Label();
      this.txtPoolCurrentLoanCount = new TextBox();
      this.label52 = new Label();
      this.ckboxIsPoolConcurrentTransfer = new CheckBox();
      this.label43 = new Label();
      this.label42 = new Label();
      this.label10 = new Label();
      this.txtPoolTaxId = new TextBox();
      this.cmbGinniePoolType = new ComboBox();
      this.label22 = new Label();
      this.gcBankInfo = new GroupContainer();
      this.cmbACHBankAccPurposeType = new ComboBox();
      this.txtACHBankAccountDescription = new TextBox();
      this.label39 = new Label();
      this.txtACHReveiverSubaccountName = new TextBox();
      this.label40 = new Label();
      this.label41 = new Label();
      this.txtACHInsititTelegraphicName = new TextBox();
      this.label35 = new Label();
      this.txtABARTId = new TextBox();
      this.label38 = new Label();
      this.txtACHABARTNum = new TextBox();
      this.label37 = new Label();
      this.txtMasterTnIAcctNum = new TextBox();
      this.label18 = new Label();
      this.txtSubscriberRecordAcctNum = new TextBox();
      this.label20 = new Label();
      this.txtSubscriberRecordABA = new TextBox();
      this.label19 = new Label();
      this.label5 = new Label();
      this.txtSubscriberRecordFrbActDesc = new TextBox();
      this.label6 = new Label();
      this.txtSubscriberRecordFrbPosDesc = new TextBox();
      this.label13 = new Label();
      this.txtMasterTnIABA = new TextBox();
      this.gcIssueDetailsMilestoneDates = new GroupContainer();
      this.cmbPoolIndexType = new ComboBox();
      this.gcPoolMilestoneDates = new GroupContainer();
      this.dpInterestAdjEffectiveDate = new DatePicker();
      this.label34 = new Label();
      this.dpCertificatePaymentDate = new DatePicker();
      this.label33 = new Label();
      this.dpLastPaidInstallmentDate = new DatePicker();
      this.label26 = new Label();
      this.dpUnpaidBalanceDate = new DatePicker();
      this.label25 = new Label();
      this.dpMaturityDate = new DatePicker();
      this.label11 = new Label();
      this.dpInitialDate = new DatePicker();
      this.label24 = new Label();
      this.dpIssueDate = new DatePicker();
      this.label23 = new Label();
      this.dpChangeDate = new DatePicker();
      this.label15 = new Label();
      this.txtMbsMargin = new TextBox();
      this.label16 = new Label();
      this.label31 = new Label();
      this.label28 = new Label();
      this.txtGuaranteeFee = new TextBox();
      this.label29 = new Label();
      this.txtServiceFee = new TextBox();
      this.label4 = new Label();
      this.txtArmIndex = new TextBox();
      this.txtSubservicerIssuerNum = new TextBox();
      this.label21 = new Label();
      this.txtNewTransferIssuerNum = new TextBox();
      this.label12 = new Label();
      this.txtPoolIssuerTransferee = new TextBox();
      this.label30 = new Label();
      this.label2 = new Label();
      this.txtIssueType = new TextBox();
      this.label1 = new Label();
      this.txtIssueNum = new TextBox();
      this.label27 = new Label();
      this.gpSetup.SuspendLayout();
      this.panel4.SuspendLayout();
      this.gcCustodialBondInfo.SuspendLayout();
      this.gcBondInfo.SuspendLayout();
      this.gcPoolDetailsBankInfo.SuspendLayout();
      this.gcBankInfo.SuspendLayout();
      this.gcIssueDetailsMilestoneDates.SuspendLayout();
      this.gcPoolMilestoneDates.SuspendLayout();
      this.SuspendLayout();
      this.gpSetup.Controls.Add((Control) this.panel4);
      this.gpSetup.Dock = DockStyle.Fill;
      this.gpSetup.Font = new Font("Arial Narrow", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.gpSetup.HeaderForeColor = SystemColors.ControlText;
      this.gpSetup.Location = new Point(0, 0);
      this.gpSetup.Name = "gpSetup";
      this.gpSetup.Size = new Size(1203, 612);
      this.gpSetup.TabIndex = 2;
      this.panel4.AutoScroll = true;
      this.panel4.Controls.Add((Control) this.gcCustodialBondInfo);
      this.panel4.Controls.Add((Control) this.gcPoolDetailsBankInfo);
      this.panel4.Controls.Add((Control) this.gcIssueDetailsMilestoneDates);
      this.panel4.Controls.Add((Control) this.label27);
      this.panel4.Dock = DockStyle.Fill;
      this.panel4.Location = new Point(1, 26);
      this.panel4.Name = "panel4";
      this.panel4.Size = new Size(1201, 585);
      this.panel4.TabIndex = 25;
      this.gcCustodialBondInfo.Controls.Add((Control) this.label3);
      this.gcCustodialBondInfo.Controls.Add((Control) this.txtCertAgreement);
      this.gcCustodialBondInfo.Controls.Add((Control) this.ckboxIsDocRequired);
      this.gcCustodialBondInfo.Controls.Add((Control) this.label45);
      this.gcCustodialBondInfo.Controls.Add((Control) this.ckboxIsDocSubmission);
      this.gcCustodialBondInfo.Controls.Add((Control) this.label44);
      this.gcCustodialBondInfo.Controls.Add((Control) this.ckboxIsSent1711ToCustodian);
      this.gcCustodialBondInfo.Controls.Add((Control) this.label9);
      this.gcCustodialBondInfo.Controls.Add((Control) this.txtPnICustodialAcctNum);
      this.gcCustodialBondInfo.Controls.Add((Control) this.label14);
      this.gcCustodialBondInfo.Controls.Add((Control) this.txtPnICustodialABA);
      this.gcCustodialBondInfo.Controls.Add((Control) this.txtNoteCustodian);
      this.gcCustodialBondInfo.Controls.Add((Control) this.label7);
      this.gcCustodialBondInfo.Controls.Add((Control) this.label8);
      this.gcCustodialBondInfo.Controls.Add((Control) this.gcBondInfo);
      this.gcCustodialBondInfo.Font = new Font("Arial Narrow", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.gcCustodialBondInfo.HeaderForeColor = SystemColors.ControlText;
      this.gcCustodialBondInfo.Location = new Point(801, -2);
      this.gcCustodialBondInfo.Name = "gcCustodialBondInfo";
      this.gcCustodialBondInfo.Size = new Size(399, 582);
      this.gcCustodialBondInfo.TabIndex = 401;
      this.gcCustodialBondInfo.Text = "Custodial Info";
      this.label3.AutoSize = true;
      this.label3.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label3.Location = new Point(10, 167);
      this.label3.Name = "label3";
      this.label3.Size = new Size(129, 14);
      this.label3.TabIndex = 420;
      this.label3.Text = "Certification && Agreement";
      this.txtCertAgreement.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtCertAgreement.Location = new Point(245, 161);
      this.txtCertAgreement.MaxLength = 20;
      this.txtCertAgreement.Name = "txtCertAgreement";
      this.txtCertAgreement.Size = new Size(138, 20);
      this.txtCertAgreement.TabIndex = 470;
      this.ckboxIsDocRequired.AutoSize = true;
      this.ckboxIsDocRequired.Location = new Point(245, 145);
      this.ckboxIsDocRequired.Name = "ckboxIsDocRequired";
      this.ckboxIsDocRequired.Size = new Size(15, 14);
      this.ckboxIsDocRequired.TabIndex = 460;
      this.ckboxIsDocRequired.UseVisualStyleBackColor = true;
      this.ckboxIsDocRequired.CheckedChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label45.AutoSize = true;
      this.label45.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label45.Location = new Point(10, 145);
      this.label45.Name = "label45";
      this.label45.Size = new Size(145, 14);
      this.label45.TabIndex = 418;
      this.label45.Text = "Document Required Indicator";
      this.ckboxIsDocSubmission.AutoSize = true;
      this.ckboxIsDocSubmission.Location = new Point(245, 123);
      this.ckboxIsDocSubmission.Name = "ckboxIsDocSubmission";
      this.ckboxIsDocSubmission.Size = new Size(15, 14);
      this.ckboxIsDocSubmission.TabIndex = 450;
      this.ckboxIsDocSubmission.UseVisualStyleBackColor = true;
      this.ckboxIsDocSubmission.CheckedChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label44.AutoSize = true;
      this.label44.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label44.Location = new Point(10, 123);
      this.label44.Name = "label44";
      this.label44.Size = new Size(157, 14);
      this.label44.TabIndex = 416;
      this.label44.Text = "Document Submission Indicator";
      this.ckboxIsSent1711ToCustodian.AutoSize = true;
      this.ckboxIsSent1711ToCustodian.Location = new Point(245, 101);
      this.ckboxIsSent1711ToCustodian.Name = "ckboxIsSent1711ToCustodian";
      this.ckboxIsSent1711ToCustodian.Size = new Size(15, 14);
      this.ckboxIsSent1711ToCustodian.TabIndex = 440;
      this.ckboxIsSent1711ToCustodian.UseVisualStyleBackColor = true;
      this.label9.AutoSize = true;
      this.label9.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label9.Location = new Point(10, 101);
      this.label9.Name = "label9";
      this.label9.Size = new Size(147, 14);
      this.label9.TabIndex = 414;
      this.label9.Text = "Sent 1711 to Custodian (Y/N)";
      this.txtPnICustodialAcctNum.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPnICustodialAcctNum.Location = new Point(245, 73);
      this.txtPnICustodialAcctNum.MaxLength = 15;
      this.txtPnICustodialAcctNum.Name = "txtPnICustodialAcctNum";
      this.txtPnICustodialAcctNum.Size = new Size(138, 20);
      this.txtPnICustodialAcctNum.TabIndex = 430;
      this.label14.AutoSize = true;
      this.label14.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label14.Location = new Point(10, 79);
      this.label14.Name = "label14";
      this.label14.Size = new Size((int) sbyte.MaxValue, 14);
      this.label14.TabIndex = 412;
      this.label14.Text = "P && I Custodial Account #";
      this.txtPnICustodialABA.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPnICustodialABA.Location = new Point(245, 51);
      this.txtPnICustodialABA.MaxLength = 12;
      this.txtPnICustodialABA.Name = "txtPnICustodialABA";
      this.txtPnICustodialABA.Size = new Size(138, 20);
      this.txtPnICustodialABA.TabIndex = 420;
      this.txtNoteCustodian.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtNoteCustodian.Location = new Point(245, 29);
      this.txtNoteCustodian.MaxLength = 15;
      this.txtNoteCustodian.Name = "txtNoteCustodian";
      this.txtNoteCustodian.Size = new Size(138, 20);
      this.txtNoteCustodian.TabIndex = 410;
      this.label7.AutoSize = true;
      this.label7.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label7.Location = new Point(10, 35);
      this.label7.Name = "label7";
      this.label7.Size = new Size(80, 14);
      this.label7.TabIndex = 409;
      this.label7.Text = "Note Custodian";
      this.label8.AutoSize = true;
      this.label8.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label8.Location = new Point(10, 57);
      this.label8.Name = "label8";
      this.label8.Size = new Size(108, 14);
      this.label8.TabIndex = 410;
      this.label8.Text = "P && I Custodial ABA #";
      this.gcBondInfo.Controls.Add((Control) this.cmbBondFinanceProgramType);
      this.gcBondInfo.Controls.Add((Control) this.txtBondFinanceProgramName);
      this.gcBondInfo.Controls.Add((Control) this.label47);
      this.gcBondInfo.Controls.Add((Control) this.label46);
      this.gcBondInfo.Controls.Add((Control) this.ckboxIsBondFinancePool);
      this.gcBondInfo.Controls.Add((Control) this.label17);
      this.gcBondInfo.Dock = DockStyle.Bottom;
      this.gcBondInfo.Font = new Font("Arial Narrow", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.gcBondInfo.HeaderForeColor = SystemColors.ControlText;
      this.gcBondInfo.Location = new Point(1, 279);
      this.gcBondInfo.Name = "gcBondInfo";
      this.gcBondInfo.Size = new Size(397, 302);
      this.gcBondInfo.TabIndex = 471;
      this.gcBondInfo.Text = "Bond Info";
      this.cmbBondFinanceProgramType.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbBondFinanceProgramType.Font = new Font("Arial", 8.25f);
      this.cmbBondFinanceProgramType.FormattingEnabled = true;
      this.cmbBondFinanceProgramType.Location = new Point(244, 49);
      this.cmbBondFinanceProgramType.Name = "cmbBondFinanceProgramType";
      this.cmbBondFinanceProgramType.Size = new Size(138, 22);
      this.cmbBondFinanceProgramType.TabIndex = 490;
      this.cmbBondFinanceProgramType.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtBondFinanceProgramName.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtBondFinanceProgramName.Location = new Point(244, 73);
      this.txtBondFinanceProgramName.MaxLength = 144;
      this.txtBondFinanceProgramName.Name = "txtBondFinanceProgramName";
      this.txtBondFinanceProgramName.Size = new Size(138, 20);
      this.txtBondFinanceProgramName.TabIndex = 500;
      this.label47.AutoSize = true;
      this.label47.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label47.Location = new Point(10, 79);
      this.label47.Name = "label47";
      this.label47.Size = new Size(146, 14);
      this.label47.TabIndex = 416;
      this.label47.Text = "Bond Finance Program Name";
      this.label46.AutoSize = true;
      this.label46.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label46.Location = new Point(10, 57);
      this.label46.Name = "label46";
      this.label46.Size = new Size(142, 14);
      this.label46.TabIndex = 414;
      this.label46.Text = "Bond Finance Program Type";
      this.ckboxIsBondFinancePool.AutoSize = true;
      this.ckboxIsBondFinancePool.Location = new Point(244, 35);
      this.ckboxIsBondFinancePool.Name = "ckboxIsBondFinancePool";
      this.ckboxIsBondFinancePool.Size = new Size(15, 14);
      this.ckboxIsBondFinancePool.TabIndex = 480;
      this.ckboxIsBondFinancePool.UseVisualStyleBackColor = true;
      this.ckboxIsBondFinancePool.CheckedChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label17.AutoSize = true;
      this.label17.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label17.Location = new Point(10, 35);
      this.label17.Name = "label17";
      this.label17.Size = new Size(125, 14);
      this.label17.TabIndex = 374;
      this.label17.Text = "Bond Finance Pool (Y/N)";
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.cmbPoolClassType);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.cmbPoolingMethodType);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.label48);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.txtSecurityOriginalSubscriptionAmount);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.label49);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.txtPoolMaturityPeriodCount);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.label50);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.txtPoolCurrentPrincipalBalAmt);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.label51);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.txtPoolCurrentLoanCount);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.label52);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.ckboxIsPoolConcurrentTransfer);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.label43);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.label42);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.label10);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.txtPoolTaxId);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.cmbGinniePoolType);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.label22);
      this.gcPoolDetailsBankInfo.Controls.Add((Control) this.gcBankInfo);
      this.gcPoolDetailsBankInfo.Font = new Font("Arial Narrow", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.gcPoolDetailsBankInfo.HeaderForeColor = SystemColors.ControlText;
      this.gcPoolDetailsBankInfo.Location = new Point(400, 0);
      this.gcPoolDetailsBankInfo.Name = "gcPoolDetailsBankInfo";
      this.gcPoolDetailsBankInfo.Size = new Size(399, 581);
      this.gcPoolDetailsBankInfo.TabIndex = 181;
      this.gcPoolDetailsBankInfo.Text = "Pool Details";
      this.cmbPoolClassType.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbPoolClassType.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.cmbPoolClassType.FormattingEnabled = true;
      this.cmbPoolClassType.Location = new Point(245, 73);
      this.cmbPoolClassType.Name = "cmbPoolClassType";
      this.cmbPoolClassType.Size = new Size(138, 22);
      this.cmbPoolClassType.TabIndex = 210;
      this.cmbPoolClassType.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.cmbPoolingMethodType.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbPoolingMethodType.Font = new Font("Arial", 8.25f);
      this.cmbPoolingMethodType.FormattingEnabled = true;
      this.cmbPoolingMethodType.Location = new Point(246, 161);
      this.cmbPoolingMethodType.Name = "cmbPoolingMethodType";
      this.cmbPoolingMethodType.Size = new Size(138, 22);
      this.cmbPoolingMethodType.TabIndex = 250;
      this.cmbPoolingMethodType.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label48.AutoSize = true;
      this.label48.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label48.Location = new Point(10, 211);
      this.label48.Name = "label48";
      this.label48.Size = new Size(188, 14);
      this.label48.TabIndex = 443;
      this.label48.Text = "Security Original Subscription Amount";
      this.txtSecurityOriginalSubscriptionAmount.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtSecurityOriginalSubscriptionAmount.Location = new Point(245, 207);
      this.txtSecurityOriginalSubscriptionAmount.MaxLength = 13;
      this.txtSecurityOriginalSubscriptionAmount.Name = "txtSecurityOriginalSubscriptionAmount";
      this.txtSecurityOriginalSubscriptionAmount.Size = new Size(138, 20);
      this.txtSecurityOriginalSubscriptionAmount.TabIndex = 270;
      this.txtSecurityOriginalSubscriptionAmount.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label49.AutoSize = true;
      this.label49.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label49.Location = new Point(10, 189);
      this.label49.Name = "label49";
      this.label49.Size = new Size(132, 14);
      this.label49.TabIndex = 441;
      this.label49.Text = "Pool Maturity Period Count";
      this.txtPoolMaturityPeriodCount.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPoolMaturityPeriodCount.Location = new Point(245, 186);
      this.txtPoolMaturityPeriodCount.MaxLength = 3;
      this.txtPoolMaturityPeriodCount.Name = "txtPoolMaturityPeriodCount";
      this.txtPoolMaturityPeriodCount.Size = new Size(138, 20);
      this.txtPoolMaturityPeriodCount.TabIndex = 260;
      this.txtPoolMaturityPeriodCount.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label50.AutoSize = true;
      this.label50.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label50.Location = new Point(10, 167);
      this.label50.Name = "label50";
      this.label50.Size = new Size(105, 14);
      this.label50.TabIndex = 439;
      this.label50.Text = "Pooling Method Type";
      this.txtPoolCurrentPrincipalBalAmt.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPoolCurrentPrincipalBalAmt.Location = new Point(245, 139);
      this.txtPoolCurrentPrincipalBalAmt.MaxLength = 15;
      this.txtPoolCurrentPrincipalBalAmt.Name = "txtPoolCurrentPrincipalBalAmt";
      this.txtPoolCurrentPrincipalBalAmt.Size = new Size(138, 20);
      this.txtPoolCurrentPrincipalBalAmt.TabIndex = 240;
      this.txtPoolCurrentPrincipalBalAmt.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label51.AutoSize = true;
      this.label51.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label51.Location = new Point(10, 123);
      this.label51.Name = "label51";
      this.label51.Size = new Size(124, 14);
      this.label51.TabIndex = 436;
      this.label51.Text = "Pool Current Loan Count";
      this.txtPoolCurrentLoanCount.Enabled = false;
      this.txtPoolCurrentLoanCount.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPoolCurrentLoanCount.Location = new Point(245, 117);
      this.txtPoolCurrentLoanCount.MaxLength = 5;
      this.txtPoolCurrentLoanCount.Name = "txtPoolCurrentLoanCount";
      this.txtPoolCurrentLoanCount.Size = new Size(138, 20);
      this.txtPoolCurrentLoanCount.TabIndex = 230;
      this.txtPoolCurrentLoanCount.TextAlign = HorizontalAlignment.Right;
      this.label52.AutoSize = true;
      this.label52.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label52.Location = new Point(10, 145);
      this.label52.Name = "label52";
      this.label52.Size = new Size(190, 14);
      this.label52.TabIndex = 437;
      this.label52.Text = "Pool Current Principal Balance Amount";
      this.ckboxIsPoolConcurrentTransfer.AutoSize = true;
      this.ckboxIsPoolConcurrentTransfer.Location = new Point(245, 101);
      this.ckboxIsPoolConcurrentTransfer.Name = "ckboxIsPoolConcurrentTransfer";
      this.ckboxIsPoolConcurrentTransfer.Size = new Size(15, 14);
      this.ckboxIsPoolConcurrentTransfer.TabIndex = 220;
      this.ckboxIsPoolConcurrentTransfer.UseVisualStyleBackColor = true;
      this.ckboxIsPoolConcurrentTransfer.CheckedChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label43.AutoSize = true;
      this.label43.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label43.Location = new Point(10, 101);
      this.label43.Name = "label43";
      this.label43.Size = new Size(173, 14);
      this.label43.TabIndex = 418;
      this.label43.Text = "Pool Concurrent Transfer Indicator";
      this.label42.AutoSize = true;
      this.label42.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label42.Location = new Point(10, 79);
      this.label42.Name = "label42";
      this.label42.Size = new Size(83, 14);
      this.label42.TabIndex = 416;
      this.label42.Text = "Pool Class Type";
      this.label10.AutoSize = true;
      this.label10.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label10.Location = new Point(10, 57);
      this.label10.Name = "label10";
      this.label10.Size = new Size(59, 14);
      this.label10.TabIndex = 410;
      this.label10.Text = "Pool Tax ID";
      this.txtPoolTaxId.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPoolTaxId.Location = new Point(245, 51);
      this.txtPoolTaxId.MaxLength = 15;
      this.txtPoolTaxId.Name = "txtPoolTaxId";
      this.txtPoolTaxId.Size = new Size(138, 20);
      this.txtPoolTaxId.TabIndex = 200;
      this.cmbGinniePoolType.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.cmbGinniePoolType.FormattingEnabled = true;
      this.cmbGinniePoolType.Location = new Point(245, 29);
      this.cmbGinniePoolType.Name = "cmbGinniePoolType";
      this.cmbGinniePoolType.Size = new Size(138, 22);
      this.cmbGinniePoolType.TabIndex = 190;
      this.cmbGinniePoolType.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label22.AutoSize = true;
      this.label22.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label22.Location = new Point(10, 35);
      this.label22.Name = "label22";
      this.label22.Size = new Size(53, 14);
      this.label22.TabIndex = 408;
      this.label22.Text = "Pool Type";
      this.gcBankInfo.Controls.Add((Control) this.cmbACHBankAccPurposeType);
      this.gcBankInfo.Controls.Add((Control) this.txtACHBankAccountDescription);
      this.gcBankInfo.Controls.Add((Control) this.label39);
      this.gcBankInfo.Controls.Add((Control) this.txtACHReveiverSubaccountName);
      this.gcBankInfo.Controls.Add((Control) this.label40);
      this.gcBankInfo.Controls.Add((Control) this.label41);
      this.gcBankInfo.Controls.Add((Control) this.txtACHInsititTelegraphicName);
      this.gcBankInfo.Controls.Add((Control) this.label35);
      this.gcBankInfo.Controls.Add((Control) this.txtABARTId);
      this.gcBankInfo.Controls.Add((Control) this.label38);
      this.gcBankInfo.Controls.Add((Control) this.txtACHABARTNum);
      this.gcBankInfo.Controls.Add((Control) this.label37);
      this.gcBankInfo.Controls.Add((Control) this.txtMasterTnIAcctNum);
      this.gcBankInfo.Controls.Add((Control) this.label18);
      this.gcBankInfo.Controls.Add((Control) this.txtSubscriberRecordAcctNum);
      this.gcBankInfo.Controls.Add((Control) this.label20);
      this.gcBankInfo.Controls.Add((Control) this.txtSubscriberRecordABA);
      this.gcBankInfo.Controls.Add((Control) this.label19);
      this.gcBankInfo.Controls.Add((Control) this.label5);
      this.gcBankInfo.Controls.Add((Control) this.txtSubscriberRecordFrbActDesc);
      this.gcBankInfo.Controls.Add((Control) this.label6);
      this.gcBankInfo.Controls.Add((Control) this.txtSubscriberRecordFrbPosDesc);
      this.gcBankInfo.Controls.Add((Control) this.label13);
      this.gcBankInfo.Controls.Add((Control) this.txtMasterTnIABA);
      this.gcBankInfo.Dock = DockStyle.Bottom;
      this.gcBankInfo.Font = new Font("Arial Narrow", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.gcBankInfo.HeaderForeColor = SystemColors.ControlText;
      this.gcBankInfo.Location = new Point(1, 277);
      this.gcBankInfo.Name = "gcBankInfo";
      this.gcBankInfo.Size = new Size(397, 303);
      this.gcBankInfo.TabIndex = 271;
      this.gcBankInfo.Text = "Bank Info";
      this.cmbACHBankAccPurposeType.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbACHBankAccPurposeType.Font = new Font("Arial", 8.25f);
      this.cmbACHBankAccPurposeType.FormattingEnabled = true;
      this.cmbACHBankAccPurposeType.Location = new Point(244, 159);
      this.cmbACHBankAccPurposeType.Name = "cmbACHBankAccPurposeType";
      this.cmbACHBankAccPurposeType.Size = new Size(138, 22);
      this.cmbACHBankAccPurposeType.TabIndex = 340;
      this.cmbACHBankAccPurposeType.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtACHBankAccountDescription.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtACHBankAccountDescription.Location = new Point(244, 271);
      this.txtACHBankAccountDescription.MaxLength = 12;
      this.txtACHBankAccountDescription.Name = "txtACHBankAccountDescription";
      this.txtACHBankAccountDescription.Size = new Size(138, 20);
      this.txtACHBankAccountDescription.TabIndex = 400;
      this.txtACHBankAccountDescription.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label39.AutoSize = true;
      this.label39.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label39.Location = new Point(10, (int) byte.MaxValue);
      this.label39.Name = "label39";
      this.label39.Size = new Size(166, 14);
      this.label39.TabIndex = 439;
      this.label39.Text = "ACH Receiver Subaccount Name";
      this.txtACHReveiverSubaccountName.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtACHReveiverSubaccountName.Location = new Point(244, 249);
      this.txtACHReveiverSubaccountName.MaxLength = 10;
      this.txtACHReveiverSubaccountName.Name = "txtACHReveiverSubaccountName";
      this.txtACHReveiverSubaccountName.Size = new Size(138, 20);
      this.txtACHReveiverSubaccountName.TabIndex = 390;
      this.txtACHReveiverSubaccountName.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label40.AutoSize = true;
      this.label40.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label40.Location = new Point(10, 277);
      this.label40.Name = "label40";
      this.label40.Size = new Size(156, 14);
      this.label40.TabIndex = 440;
      this.label40.Text = "ACH Bank Account Description";
      this.label41.AutoSize = true;
      this.label41.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label41.Location = new Point(10, 233);
      this.label41.Name = "label41";
      this.label41.Size = new Size(165, 14);
      this.label41.TabIndex = 436;
      this.label41.Text = "ACH Institution Telegraphic Name";
      this.txtACHInsititTelegraphicName.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtACHInsititTelegraphicName.Location = new Point(244, 227);
      this.txtACHInsititTelegraphicName.MaxLength = 20;
      this.txtACHInsititTelegraphicName.Name = "txtACHInsititTelegraphicName";
      this.txtACHInsititTelegraphicName.Size = new Size(138, 20);
      this.txtACHInsititTelegraphicName.TabIndex = 380;
      this.txtACHInsititTelegraphicName.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label35.AutoSize = true;
      this.label35.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label35.Location = new Point(10, 211);
      this.label35.Name = "label35";
      this.label35.Size = new Size(194, 14);
      this.label35.TabIndex = 433;
      this.label35.Text = "ACH ABA Routing And Transit Identifier";
      this.txtABARTId.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtABARTId.Location = new Point(244, 205);
      this.txtABARTId.MaxLength = 9;
      this.txtABARTId.Name = "txtABARTId";
      this.txtABARTId.Size = new Size(138, 20);
      this.txtABARTId.TabIndex = 360;
      this.label38.AutoSize = true;
      this.label38.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label38.Location = new Point(10, 189);
      this.label38.Name = "label38";
      this.label38.Size = new Size(159, 14);
      this.label38.TabIndex = 430;
      this.label38.Text = "ACH ABA Routing And Transit #";
      this.txtACHABARTNum.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtACHABARTNum.Location = new Point(244, 183);
      this.txtACHABARTNum.MaxLength = 9;
      this.txtACHABARTNum.Name = "txtACHABARTNum";
      this.txtACHABARTNum.Size = new Size(138, 20);
      this.txtACHABARTNum.TabIndex = 350;
      this.txtACHABARTNum.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label37.AutoSize = true;
      this.label37.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label37.Location = new Point(10, 167);
      this.label37.Name = "label37";
      this.label37.Size = new Size(168, 14);
      this.label37.TabIndex = 428;
      this.label37.Text = "ACH Bank Account Purpose Type";
      this.txtMasterTnIAcctNum.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtMasterTnIAcctNum.Location = new Point(244, 139);
      this.txtMasterTnIAcctNum.MaxLength = 15;
      this.txtMasterTnIAcctNum.Name = "txtMasterTnIAcctNum";
      this.txtMasterTnIAcctNum.Size = new Size(138, 20);
      this.txtMasterTnIAcctNum.TabIndex = 330;
      this.txtMasterTnIAcctNum.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label18.AutoSize = true;
      this.label18.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label18.Location = new Point(10, 123);
      this.label18.Name = "label18";
      this.label18.Size = new Size(150, 14);
      this.label18.TabIndex = 425;
      this.label18.Text = "Subscriber Record Account #";
      this.txtSubscriberRecordAcctNum.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtSubscriberRecordAcctNum.Location = new Point(244, 117);
      this.txtSubscriberRecordAcctNum.MaxLength = 15;
      this.txtSubscriberRecordAcctNum.Name = "txtSubscriberRecordAcctNum";
      this.txtSubscriberRecordAcctNum.Size = new Size(138, 20);
      this.txtSubscriberRecordAcctNum.TabIndex = 320;
      this.label20.AutoSize = true;
      this.label20.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label20.Location = new Point(10, 145);
      this.label20.Name = "label20";
      this.label20.Size = new Size(119, 14);
      this.label20.TabIndex = 426;
      this.label20.Text = "Master T && I  Account #";
      this.txtSubscriberRecordABA.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtSubscriberRecordABA.Location = new Point(245, 29);
      this.txtSubscriberRecordABA.MaxLength = 12;
      this.txtSubscriberRecordABA.Name = "txtSubscriberRecordABA";
      this.txtSubscriberRecordABA.Size = new Size(138, 20);
      this.txtSubscriberRecordABA.TabIndex = 280;
      this.label19.AutoSize = true;
      this.label19.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label19.Location = new Point(10, 35);
      this.label19.Name = "label19";
      this.label19.Size = new Size(131, 14);
      this.label19.TabIndex = 422;
      this.label19.Text = "Subscriber Record ABA #";
      this.label5.AutoSize = true;
      this.label5.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label5.Location = new Point(10, 79);
      this.label5.Name = "label5";
      this.label5.Size = new Size(203, 14);
      this.label5.TabIndex = 419;
      this.label5.Text = "Subscriber Record FRB Acct Description";
      this.txtSubscriberRecordFrbActDesc.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtSubscriberRecordFrbActDesc.Location = new Point(245, 73);
      this.txtSubscriberRecordFrbActDesc.MaxLength = 15;
      this.txtSubscriberRecordFrbActDesc.Name = "txtSubscriberRecordFrbActDesc";
      this.txtSubscriberRecordFrbActDesc.Size = new Size(138, 20);
      this.txtSubscriberRecordFrbActDesc.TabIndex = 300;
      this.label6.AutoSize = true;
      this.label6.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label6.Location = new Point(10, 57);
      this.label6.Name = "label6";
      this.label6.Size = new Size(218, 14);
      this.label6.TabIndex = 420;
      this.label6.Text = "Subscriber Record FRB Position Description";
      this.txtSubscriberRecordFrbPosDesc.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtSubscriberRecordFrbPosDesc.Location = new Point(245, 51);
      this.txtSubscriberRecordFrbPosDesc.MaxLength = 12;
      this.txtSubscriberRecordFrbPosDesc.Name = "txtSubscriberRecordFrbPosDesc";
      this.txtSubscriberRecordFrbPosDesc.Size = new Size(138, 20);
      this.txtSubscriberRecordFrbPosDesc.TabIndex = 290;
      this.label13.AutoSize = true;
      this.label13.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label13.Location = new Point(10, 101);
      this.label13.Name = "label13";
      this.label13.Size = new Size(100, 14);
      this.label13.TabIndex = 421;
      this.label13.Text = "Master T && I  ABA #";
      this.txtMasterTnIABA.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtMasterTnIABA.Location = new Point(244, 95);
      this.txtMasterTnIABA.MaxLength = 12;
      this.txtMasterTnIABA.Name = "txtMasterTnIABA";
      this.txtMasterTnIABA.Size = new Size(138, 20);
      this.txtMasterTnIABA.TabIndex = 310;
      this.txtMasterTnIABA.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.cmbPoolIndexType);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.gcPoolMilestoneDates);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.txtMbsMargin);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.label16);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.label31);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.label28);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.txtGuaranteeFee);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.label29);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.txtServiceFee);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.label4);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.txtArmIndex);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.txtSubservicerIssuerNum);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.label21);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.txtNewTransferIssuerNum);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.label12);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.txtPoolIssuerTransferee);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.label30);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.label2);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.txtIssueType);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.label1);
      this.gcIssueDetailsMilestoneDates.Controls.Add((Control) this.txtIssueNum);
      this.gcIssueDetailsMilestoneDates.Font = new Font("Arial Narrow", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.gcIssueDetailsMilestoneDates.HeaderForeColor = SystemColors.ControlText;
      this.gcIssueDetailsMilestoneDates.Location = new Point(0, 0);
      this.gcIssueDetailsMilestoneDates.Name = "gcIssueDetailsMilestoneDates";
      this.gcIssueDetailsMilestoneDates.Size = new Size(399, 582);
      this.gcIssueDetailsMilestoneDates.TabIndex = 1;
      this.gcIssueDetailsMilestoneDates.Text = "Pool Issuer Details";
      this.cmbPoolIndexType.DropDownStyle = ComboBoxStyle.DropDownList;
      this.cmbPoolIndexType.Font = new Font("Arial", 8.25f);
      this.cmbPoolIndexType.FormattingEnabled = true;
      this.cmbPoolIndexType.Location = new Point(245, 203);
      this.cmbPoolIndexType.Name = "cmbPoolIndexType";
      this.cmbPoolIndexType.Size = new Size(138, 22);
      this.cmbPoolIndexType.TabIndex = 90;
      this.cmbPoolIndexType.SelectedIndexChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.dpInterestAdjEffectiveDate);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.label34);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.dpCertificatePaymentDate);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.label33);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.dpLastPaidInstallmentDate);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.label26);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.dpUnpaidBalanceDate);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.label25);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.dpMaturityDate);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.label11);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.dpInitialDate);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.label24);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.dpIssueDate);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.label23);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.dpChangeDate);
      this.gcPoolMilestoneDates.Controls.Add((Control) this.label15);
      this.gcPoolMilestoneDates.Dock = DockStyle.Bottom;
      this.gcPoolMilestoneDates.Font = new Font("Arial Narrow", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.gcPoolMilestoneDates.HeaderForeColor = SystemColors.ControlText;
      this.gcPoolMilestoneDates.Location = new Point(1, 277);
      this.gcPoolMilestoneDates.Name = "gcPoolMilestoneDates";
      this.gcPoolMilestoneDates.Size = new Size(397, 304);
      this.gcPoolMilestoneDates.TabIndex = 101;
      this.gcPoolMilestoneDates.Text = "Pool Milestone Dates";
      this.dpInterestAdjEffectiveDate.BackColor = SystemColors.Window;
      this.dpInterestAdjEffectiveDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dpInterestAdjEffectiveDate.Location = new Point(245, 183);
      this.dpInterestAdjEffectiveDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dpInterestAdjEffectiveDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dpInterestAdjEffectiveDate.Name = "dpInterestAdjEffectiveDate";
      this.dpInterestAdjEffectiveDate.Size = new Size(138, 22);
      this.dpInterestAdjEffectiveDate.TabIndex = 180;
      this.dpInterestAdjEffectiveDate.ToolTip = "";
      this.dpInterestAdjEffectiveDate.Value = new DateTime(0L);
      this.dpInterestAdjEffectiveDate.ValueChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label34.AutoSize = true;
      this.label34.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label34.Location = new Point(10, 189);
      this.label34.Name = "label34";
      this.label34.Size = new Size(193, 14);
      this.label34.TabIndex = 414;
      this.label34.Text = "Pool Interest Adjustment Effective Date";
      this.dpCertificatePaymentDate.BackColor = SystemColors.Window;
      this.dpCertificatePaymentDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dpCertificatePaymentDate.Location = new Point(245, 161);
      this.dpCertificatePaymentDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dpCertificatePaymentDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dpCertificatePaymentDate.Name = "dpCertificatePaymentDate";
      this.dpCertificatePaymentDate.Size = new Size(138, 22);
      this.dpCertificatePaymentDate.TabIndex = 170;
      this.dpCertificatePaymentDate.ToolTip = "";
      this.dpCertificatePaymentDate.Value = new DateTime(0L);
      this.dpCertificatePaymentDate.ValueChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label33.AutoSize = true;
      this.label33.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label33.Location = new Point(10, 167);
      this.label33.Name = "label33";
      this.label33.Size = new Size(148, 14);
      this.label33.TabIndex = 411;
      this.label33.Text = "Pool Certificate Payment Date";
      this.dpLastPaidInstallmentDate.BackColor = SystemColors.Window;
      this.dpLastPaidInstallmentDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dpLastPaidInstallmentDate.Location = new Point(245, 139);
      this.dpLastPaidInstallmentDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dpLastPaidInstallmentDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dpLastPaidInstallmentDate.Name = "dpLastPaidInstallmentDate";
      this.dpLastPaidInstallmentDate.Size = new Size(138, 22);
      this.dpLastPaidInstallmentDate.TabIndex = 160;
      this.dpLastPaidInstallmentDate.ToolTip = "";
      this.dpLastPaidInstallmentDate.Value = new DateTime(0L);
      this.label26.AutoSize = true;
      this.label26.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label26.Location = new Point(10, 145);
      this.label26.Name = "label26";
      this.label26.Size = new Size(129, 14);
      this.label26.TabIndex = 408;
      this.label26.Text = "Last Paid Installment Date";
      this.dpUnpaidBalanceDate.BackColor = SystemColors.Window;
      this.dpUnpaidBalanceDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dpUnpaidBalanceDate.Location = new Point(245, 117);
      this.dpUnpaidBalanceDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dpUnpaidBalanceDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dpUnpaidBalanceDate.Name = "dpUnpaidBalanceDate";
      this.dpUnpaidBalanceDate.Size = new Size(138, 22);
      this.dpUnpaidBalanceDate.TabIndex = 150;
      this.dpUnpaidBalanceDate.ToolTip = "";
      this.dpUnpaidBalanceDate.Value = new DateTime(0L);
      this.label25.AutoSize = true;
      this.label25.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label25.Location = new Point(10, 123);
      this.label25.Name = "label25";
      this.label25.Size = new Size(107, 14);
      this.label25.TabIndex = 407;
      this.label25.Text = "Unpaid Balance Date";
      this.dpMaturityDate.BackColor = SystemColors.Window;
      this.dpMaturityDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dpMaturityDate.Location = new Point(245, 95);
      this.dpMaturityDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dpMaturityDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dpMaturityDate.Name = "dpMaturityDate";
      this.dpMaturityDate.Size = new Size(138, 22);
      this.dpMaturityDate.TabIndex = 140;
      this.dpMaturityDate.ToolTip = "";
      this.dpMaturityDate.Value = new DateTime(0L);
      this.dpMaturityDate.ValueChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label11.AutoSize = true;
      this.label11.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label11.Location = new Point(10, 101);
      this.label11.Name = "label11";
      this.label11.Size = new Size(70, 14);
      this.label11.TabIndex = 404;
      this.label11.Text = "Maturity Date";
      this.dpInitialDate.BackColor = SystemColors.Window;
      this.dpInitialDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dpInitialDate.Location = new Point(245, 73);
      this.dpInitialDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dpInitialDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dpInitialDate.Name = "dpInitialDate";
      this.dpInitialDate.Size = new Size(138, 22);
      this.dpInitialDate.TabIndex = 130;
      this.dpInitialDate.ToolTip = "";
      this.dpInitialDate.Value = new DateTime(0L);
      this.label24.AutoSize = true;
      this.label24.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label24.Location = new Point(10, 79);
      this.label24.Name = "label24";
      this.label24.Size = new Size(76, 14);
      this.label24.TabIndex = 402;
      this.label24.Text = "Initial Pay Date";
      this.dpIssueDate.BackColor = SystemColors.Window;
      this.dpIssueDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dpIssueDate.Location = new Point(245, 29);
      this.dpIssueDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dpIssueDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dpIssueDate.Name = "dpIssueDate";
      this.dpIssueDate.Size = new Size(138, 22);
      this.dpIssueDate.TabIndex = 110;
      this.dpIssueDate.ToolTip = "";
      this.dpIssueDate.Value = new DateTime(0L);
      this.dpIssueDate.ValueChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label23.AutoSize = true;
      this.label23.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label23.Location = new Point(10, 35);
      this.label23.Name = "label23";
      this.label23.Size = new Size(58, 14);
      this.label23.TabIndex = 401;
      this.label23.Text = "Issue Date";
      this.dpChangeDate.BackColor = SystemColors.Window;
      this.dpChangeDate.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dpChangeDate.Location = new Point(245, 51);
      this.dpChangeDate.MaxValue = new DateTime(2100, 1, 1, 0, 0, 0, 0);
      this.dpChangeDate.MinValue = new DateTime(1900, 1, 1, 0, 0, 0, 0);
      this.dpChangeDate.Name = "dpChangeDate";
      this.dpChangeDate.Size = new Size(138, 22);
      this.dpChangeDate.TabIndex = 120;
      this.dpChangeDate.ToolTip = "";
      this.dpChangeDate.Value = new DateTime(0L);
      this.label15.AutoSize = true;
      this.label15.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label15.Location = new Point(10, 57);
      this.label15.Name = "label15";
      this.label15.Size = new Size(69, 14);
      this.label15.TabIndex = 400;
      this.label15.Text = "Change Date";
      this.txtMbsMargin.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtMbsMargin.Location = new Point(245, 227);
      this.txtMbsMargin.MaxLength = 7;
      this.txtMbsMargin.Name = "txtMbsMargin";
      this.txtMbsMargin.Size = new Size(138, 20);
      this.txtMbsMargin.TabIndex = 100;
      this.txtMbsMargin.TextAlign = HorizontalAlignment.Right;
      this.txtMbsMargin.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtMbsMargin.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.label16.AutoSize = true;
      this.label16.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label16.Location = new Point(10, 233);
      this.label16.Name = "label16";
      this.label16.Size = new Size(64, 14);
      this.label16.TabIndex = 414;
      this.label16.Text = "MBS Margin";
      this.label31.AutoSize = true;
      this.label31.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label31.Location = new Point(10, 211);
      this.label31.Name = "label31";
      this.label31.Size = new Size(59, 14);
      this.label31.TabIndex = 412;
      this.label31.Text = "Index Type";
      this.label28.AutoSize = true;
      this.label28.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label28.Location = new Point(10, 145);
      this.label28.Name = "label28";
      this.label28.Size = new Size(73, 14);
      this.label28.TabIndex = 409;
      this.label28.Text = "Guaranty Fee";
      this.txtGuaranteeFee.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtGuaranteeFee.Location = new Point(245, 139);
      this.txtGuaranteeFee.MaxLength = 7;
      this.txtGuaranteeFee.Name = "txtGuaranteeFee";
      this.txtGuaranteeFee.Size = new Size(138, 20);
      this.txtGuaranteeFee.TabIndex = 60;
      this.txtGuaranteeFee.TextAlign = HorizontalAlignment.Right;
      this.txtGuaranteeFee.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.txtGuaranteeFee.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.label29.AutoSize = true;
      this.label29.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label29.Location = new Point(10, 167);
      this.label29.Name = "label29";
      this.label29.Size = new Size(65, 14);
      this.label29.TabIndex = 410;
      this.label29.Text = "Service Fee";
      this.txtServiceFee.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtServiceFee.Location = new Point(245, 161);
      this.txtServiceFee.MaxLength = 7;
      this.txtServiceFee.Name = "txtServiceFee";
      this.txtServiceFee.Size = new Size(138, 20);
      this.txtServiceFee.TabIndex = 70;
      this.txtServiceFee.TextAlign = HorizontalAlignment.Right;
      this.txtServiceFee.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.txtServiceFee.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.label4.AutoSize = true;
      this.label4.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label4.Location = new Point(10, 189);
      this.label4.Name = "label4";
      this.label4.Size = new Size(59, 14);
      this.label4.TabIndex = 408;
      this.label4.Text = "ARM Index";
      this.txtArmIndex.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtArmIndex.Location = new Point(245, 183);
      this.txtArmIndex.MaxLength = 7;
      this.txtArmIndex.Name = "txtArmIndex";
      this.txtArmIndex.Size = new Size(138, 20);
      this.txtArmIndex.TabIndex = 80;
      this.txtArmIndex.TextAlign = HorizontalAlignment.Right;
      this.txtArmIndex.TextChanged += new EventHandler(this.OnFieldValueChanged);
      this.txtArmIndex.Leave += new EventHandler(this.txt_Percent24_Leave);
      this.txtSubservicerIssuerNum.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtSubservicerIssuerNum.Location = new Point(245, 117);
      this.txtSubservicerIssuerNum.MaxLength = 15;
      this.txtSubservicerIssuerNum.Name = "txtSubservicerIssuerNum";
      this.txtSubservicerIssuerNum.Size = new Size(138, 20);
      this.txtSubservicerIssuerNum.TabIndex = 50;
      this.label21.AutoSize = true;
      this.label21.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label21.Location = new Point(10, 123);
      this.label21.Name = "label21";
      this.label21.Size = new Size(139, 14);
      this.label21.TabIndex = 388;
      this.label21.Text = "Subservicer Issuer Number";
      this.txtNewTransferIssuerNum.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtNewTransferIssuerNum.Location = new Point(245, 95);
      this.txtNewTransferIssuerNum.MaxLength = 12;
      this.txtNewTransferIssuerNum.Name = "txtNewTransferIssuerNum";
      this.txtNewTransferIssuerNum.Size = new Size(138, 20);
      this.txtNewTransferIssuerNum.TabIndex = 40;
      this.txtNewTransferIssuerNum.Tag = (object) "";
      this.label12.AutoSize = true;
      this.label12.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label12.Location = new Point(10, 101);
      this.label12.Name = "label12";
      this.label12.Size = new Size(148, 14);
      this.label12.TabIndex = 361;
      this.label12.Text = "New Transfer Issuer Number";
      this.txtPoolIssuerTransferee.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtPoolIssuerTransferee.Location = new Point(245, 73);
      this.txtPoolIssuerTransferee.MaxLength = 20;
      this.txtPoolIssuerTransferee.Name = "txtPoolIssuerTransferee";
      this.txtPoolIssuerTransferee.Size = new Size(138, 20);
      this.txtPoolIssuerTransferee.TabIndex = 30;
      this.txtPoolIssuerTransferee.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label30.AutoSize = true;
      this.label30.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label30.Location = new Point(10, 79);
      this.label30.Name = "label30";
      this.label30.Size = new Size(117, 14);
      this.label30.TabIndex = 352;
      this.label30.Text = "Pool Issuer Transferee";
      this.label2.AutoSize = true;
      this.label2.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label2.Location = new Point(10, 57);
      this.label2.Name = "label2";
      this.label2.Size = new Size(59, 14);
      this.label2.TabIndex = 351;
      this.label2.Text = "Issue Type";
      this.txtIssueType.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtIssueType.Location = new Point(245, 51);
      this.txtIssueType.MaxLength = 25;
      this.txtIssueType.Name = "txtIssueType";
      this.txtIssueType.Size = new Size(138, 20);
      this.txtIssueType.TabIndex = 20;
      this.label1.AutoSize = true;
      this.label1.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label1.Location = new Point(10, 35);
      this.label1.Name = "label1";
      this.label1.Size = new Size(77, 14);
      this.label1.TabIndex = 350;
      this.label1.Text = "Issuer Number";
      this.txtIssueNum.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.txtIssueNum.Location = new Point(245, 29);
      this.txtIssueNum.MaxLength = 11;
      this.txtIssueNum.Name = "txtIssueNum";
      this.txtIssueNum.Size = new Size(138, 20);
      this.txtIssueNum.TabIndex = 10;
      this.txtIssueNum.TextChanged += new EventHandler(this.OnLoanUpdatableFieldValueChanged);
      this.label27.AutoSize = true;
      this.label27.Location = new Point(198, 253);
      this.label27.Name = "label27";
      this.label27.Size = new Size(0, 15);
      this.label27.TabIndex = 346;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.Controls.Add((Control) this.gpSetup);
      this.Name = nameof (MBSPoolGinnieMaeFieldsEditor);
      this.Size = new Size(1203, 612);
      this.gpSetup.ResumeLayout(false);
      this.panel4.ResumeLayout(false);
      this.panel4.PerformLayout();
      this.gcCustodialBondInfo.ResumeLayout(false);
      this.gcCustodialBondInfo.PerformLayout();
      this.gcBondInfo.ResumeLayout(false);
      this.gcBondInfo.PerformLayout();
      this.gcPoolDetailsBankInfo.ResumeLayout(false);
      this.gcPoolDetailsBankInfo.PerformLayout();
      this.gcBankInfo.ResumeLayout(false);
      this.gcBankInfo.PerformLayout();
      this.gcIssueDetailsMilestoneDates.ResumeLayout(false);
      this.gcIssueDetailsMilestoneDates.PerformLayout();
      this.gcPoolMilestoneDates.ResumeLayout(false);
      this.gcPoolMilestoneDates.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
