// Decompiled with JetBrains decompiler
// Type: EllieMae.EMLite.ClientServer.SystemAuditTrail.ActionType
// Assembly: ClientServer, Version=1.5.1.0, Culture=neutral, PublicKeyToken=d11ef57bba4acf91
// MVID: 301E11EA-0960-40C7-AC1B-26929E024B20
// Assembly location: C:\SmartClientCache\Apps\UAC\Ellie Mae\xIHR5EqGa7zPnRG0YpD5z4TPAB0=\Encompass360\ClientServer.dll

#nullable disable
namespace EllieMae.EMLite.ClientServer.SystemAuditTrail
{
  public enum ActionType
  {
    None,
    LoanCreated,
    LoanImported,
    LoanModified,
    LoanDeleted,
    LoanPermanentDeleted,
    LoanRestored,
    UserCreated,
    UserModified,
    UserDeleted,
    UserPasswordChangeForced,
    UserPasswordChanged,
    UserLogin,
    UserLogout,
    TemplateCreated,
    TemplateModified,
    TemplateDeleted,
    PersonaCreated,
    PersonaModified,
    PersonaDeleted,
    UserGroupCreated,
    UserGroupModified,
    UserGroupDeleted,
    BusinessContactGroupCreated,
    BusinessContactGroupModified,
    BusinessContactGroupDeleted,
    BusinessRuleCreated,
    BusinessRuleModified,
    BusinessRuleDeleted,
    BusinessRuleActivated,
    BusinessRuleDeactivated,
    FailedLoginUserNotFound,
    FailedLoginPasswordMismatch,
    FailedLoginUserDisabled,
    FailedLoginLoginDisabled,
    FailedLoginUserLocked,
    FailedLoginPersonaNotFound,
    IPBlocked,
    LoanMoved,
    FailedLoginServerBusy,
    FeeRuleCreated,
    FeeRuleModified,
    FeeRuleDeleted,
    FeeRuleActivated,
    FeeRuleDeactivated,
    FieldRuleCreated,
    FieldRuleModified,
    FieldRuleDeleted,
    FieldRuleActivated,
    FieldRuleDeactivated,
    FeeScenarioCreated,
    FeeScenarioModified,
    FeeScenarioDeleted,
    FeeScenarioActivated,
    FeeScenarioDeactivated,
    FieldScenarioCreated,
    FieldScenarioModified,
    FieldScenarioDeleted,
    FieldScenarioActivated,
    FieldScenarioDeactivated,
    DataTableCreated,
    DataTableModified,
    DataTableDeleted,
    DataPopulationTimingModified,
    HMDACreated,
    HMDAModified,
    HMDADeleted,
    SSOUserLogin,
    SSOFailedUserLogin,
    ServerSettingsChanged,
    AttachmentMigrated,
    LoanExternalFieldsDeleted,
  }
}
